import { readFileSync } from "node:fs"
import { describe, expect, it } from "vitest"

const clientSource = readFileSync(new URL("./desktop-knowledge-client.ts", import.meta.url), "utf8")
const knowledgePageSource = readFileSync(new URL("../pages/knowledge.tsx", import.meta.url), "utf8")

describe("desktop knowledge renderer client", () => {
  it("centralizes desktop knowledge IPC channels behind shared knowledge types", () => {
    expect(clientSource).toContain("KnowledgeNote")
    expect(clientSource).toContain("KnowledgeNotesOverview")
    expect(clientSource).toContain("tipcClient.getKnowledgeNotesOverview(filter)")
    expect(clientSource).toContain("tipcClient.getKnowledgeNotesByGroup(filter)")
    expect(clientSource).toContain("tipcClient.getAllKnowledgeNotes(filter)")
    expect(clientSource).toContain("tipcClient.searchKnowledgeNotes(request)")
    expect(clientSource).toContain("tipcClient.updateKnowledgeNote(request)")
    expect(clientSource).toContain("tipcClient.deleteKnowledgeNote({ id })")
    expect(clientSource).toContain("tipcClient.deleteMultipleKnowledgeNotes({ ids })")
    expect(clientSource).toContain("tipcClient.deleteAllKnowledgeNotes()")
    expect(clientSource).toContain("tipcClient.getAgentsFolders()")
    expect(clientSource).toContain("tipcClient.openKnowledgeFolder()")
    expect(clientSource).toContain("tipcClient.openWorkspaceKnowledgeFolder()")
    expect(clientSource).not.toContain("window.electron.ipcRenderer")
  })

  it("keeps knowledge UI off direct knowledge IPC channels", () => {
    expect(knowledgePageSource).toContain("desktopKnowledgeClient.getOverview(")
    expect(knowledgePageSource).toContain("desktopKnowledgeClient.getNotesByGroup(")
    expect(knowledgePageSource).toContain("desktopKnowledgeClient.getAllNotes(")
    expect(knowledgePageSource).toContain("desktopKnowledgeClient.searchNotes(")
    expect(knowledgePageSource).toContain("desktopKnowledgeClient.updateNote(")
    expect(knowledgePageSource).toContain("desktopKnowledgeClient.deleteNote(id)")
    expect(knowledgePageSource).toContain("desktopKnowledgeClient.deleteMultipleNotes(ids)")
    expect(knowledgePageSource).toContain("desktopKnowledgeClient.deleteAllNotes()")
    expect(knowledgePageSource).toContain("desktopKnowledgeClient.getAgentsFolders()")
    expect(knowledgePageSource).toContain("desktopKnowledgeClient.openKnowledgeFolder()")
    expect(knowledgePageSource).toContain("desktopKnowledgeClient.openWorkspaceKnowledgeFolder()")
    expect(knowledgePageSource).not.toContain("tipcClient.getKnowledgeNotesOverview(")
    expect(knowledgePageSource).not.toContain("tipcClient.getKnowledgeNotesByGroup(")
    expect(knowledgePageSource).not.toContain("tipcClient.getAllKnowledgeNotes(")
    expect(knowledgePageSource).not.toContain("tipcClient.searchKnowledgeNotes(")
    expect(knowledgePageSource).not.toContain("tipcClient.updateKnowledgeNote(")
    expect(knowledgePageSource).not.toContain("tipcClient.deleteKnowledgeNote(")
    expect(knowledgePageSource).not.toContain("tipcClient.deleteMultipleKnowledgeNotes(")
    expect(knowledgePageSource).not.toContain("tipcClient.deleteAllKnowledgeNotes(")
    expect(knowledgePageSource).not.toContain("tipcClient.getAgentsFolders(")
    expect(knowledgePageSource).not.toContain("tipcClient.openKnowledgeFolder(")
    expect(knowledgePageSource).not.toContain("tipcClient.openWorkspaceKnowledgeFolder(")
  })
})
