import { readFileSync } from "node:fs"
import { describe, expect, it } from "vitest"

const clientSource = readFileSync(new URL("./desktop-mcp-server-client.ts", import.meta.url), "utf8")
const queriesSource = readFileSync(new URL("./queries.ts", import.meta.url), "utf8")
const mcpConfigManagerSource = readFileSync(new URL("../components/mcp-config-manager.tsx", import.meta.url), "utf8")
const onboardingPageSource = readFileSync(new URL("../pages/onboarding.tsx", import.meta.url), "utf8")

describe("desktop MCP server renderer client", () => {
  it("centralizes MCP server runtime and config IPC", () => {
    expect(clientSource).toContain("tipcClient.getMcpServerStatus()")
    expect(clientSource).toContain("tipcClient.getMcpInitializationStatus()")
    expect(clientSource).toContain("tipcClient.testMcpServerConnection({")
    expect(clientSource).toContain("tipcClient.setMcpServerRuntimeEnabled({")
    expect(clientSource).toContain("tipcClient.restartMcpServer({ serverName })")
    expect(clientSource).toContain("tipcClient.stopMcpServer({ serverName })")
    expect(clientSource).toContain("tipcClient.getMcpServerLogs({ serverName })")
    expect(clientSource).toContain("tipcClient.clearMcpServerLogs({ serverName })")
    expect(clientSource).toContain("tipcClient.loadMcpConfigFile()")
    expect(clientSource).toContain("tipcClient.saveMcpConfigFile({ config })")
    expect(clientSource).toContain("tipcClient.validateMcpConfigText({ text })")
    expect(clientSource).not.toContain("window.electron.ipcRenderer")
  })

  it("keeps MCP config surfaces off direct MCP server IPC", () => {
    const combinedSource = [queriesSource, mcpConfigManagerSource, onboardingPageSource].join("\n")

    expect(queriesSource).toContain("desktopMcpServerClient.getServerStatus()")
    expect(queriesSource).toContain("desktopMcpServerClient.getInitializationStatus()")
    expect(queriesSource).toContain("desktopMcpServerClient.loadConfigFile()")
    expect(queriesSource).toContain("desktopMcpServerClient.saveConfigFile(config)")
    expect(mcpConfigManagerSource).toContain("desktopMcpServerClient.testConnection(")
    expect(mcpConfigManagerSource).toContain("desktopMcpServerClient.getServerLogs(serverName)")
    expect(mcpConfigManagerSource).toContain("desktopMcpServerClient.getServerStatus()")
    expect(mcpConfigManagerSource).toContain("desktopMcpServerClient.getInitializationStatus()")
    expect(mcpConfigManagerSource).toContain("desktopMcpServerClient.setRuntimeEnabled(")
    expect(mcpConfigManagerSource).toContain("desktopMcpServerClient.restartServer(")
    expect(mcpConfigManagerSource).toContain("desktopMcpServerClient.stopServer(")
    expect(mcpConfigManagerSource).toContain("desktopMcpServerClient.loadConfigFile()")
    expect(mcpConfigManagerSource).toContain("desktopMcpServerClient.saveConfigFile(config)")
    expect(mcpConfigManagerSource).toContain("desktopMcpServerClient.validateConfigText(formattedJson)")
    expect(mcpConfigManagerSource).toContain("desktopMcpServerClient.clearServerLogs(serverName)")
    expect(onboardingPageSource).toContain("desktopMcpServerClient.setRuntimeEnabled(")
    expect(onboardingPageSource).toContain("desktopMcpServerClient.restartServer(\"exa\")")
    expect(combinedSource).not.toContain("tipcClient.getMcpServerStatus(")
    expect(combinedSource).not.toContain("tipcClient.getMcpInitializationStatus(")
    expect(combinedSource).not.toContain("tipcClient.testMcpServerConnection(")
    expect(combinedSource).not.toContain("tipcClient.setMcpServerRuntimeEnabled(")
    expect(combinedSource).not.toContain("tipcClient.restartMcpServer(")
    expect(combinedSource).not.toContain("tipcClient.stopMcpServer(")
    expect(combinedSource).not.toContain("tipcClient.getMcpServerLogs(")
    expect(combinedSource).not.toContain("tipcClient.clearMcpServerLogs(")
    expect(combinedSource).not.toContain("tipcClient.loadMcpConfigFile(")
    expect(combinedSource).not.toContain("tipcClient.saveMcpConfigFile(")
    expect(combinedSource).not.toContain("tipcClient.validateMcpConfigText(")
  })

  it("uses shared MCP server draft parsing for desktop save and test config assembly", () => {
    expect(mcpConfigManagerSource).toContain("buildMcpServerConfigFromDraft(buildCurrentServerDraft(), SERVER_DIALOG_DRAFT_OPTIONS)")
    expect(mcpConfigManagerSource).toContain('commandDraftMode: "shell-command"')
    expect(mcpConfigManagerSource).toContain("includeRemoteEnv: true")
    expect(mcpConfigManagerSource).toContain("oauthConfig,")
    expect(mcpConfigManagerSource).not.toContain("parseMcpKeyValueDraft(")
    expect(mcpConfigManagerSource).not.toContain("parseShellCommand(")
  })
})
