import { readFileSync } from "node:fs"
import {
  formatChatRuntimeModelPickerTitle,
  formatChatRuntimeThinkingPickerTitle,
  formatChatRuntimeVerbosityPickerTitle,
  getChatRuntimeDelegationStatusDesktopClassNames,
  getChatRuntimeCopyState,
  getChatRuntimeDesktopSurfaceState,
} from "@dotagents/shared/session-presentation"
import { describe, expect, it } from "vitest"

const agentProgressSource = readFileSync(new URL("./agent-progress.tsx", import.meta.url), "utf8")
const acpSessionBadgeSource = readFileSync(new URL("./acp-session-badge.tsx", import.meta.url), "utf8")
const messageQueuePanelSource = readFileSync(new URL("./message-queue-panel.tsx", import.meta.url), "utf8")
const audioPlayerSource = readFileSync(new URL("./audio-player.tsx", import.meta.url), "utf8")
const desktopRuntimeCopy = getChatRuntimeCopyState()
const desktopRuntimeSurface = getChatRuntimeDesktopSurfaceState()
const desktopDelegationBubbleSurface = desktopRuntimeSurface.delegationBubble

describe("agent progress tile layout", () => {
  it("wraps the tile header chrome for narrow session widths and zoomed text", () => {
    expect(agentProgressSource).toContain(
      '"flex flex-wrap items-center gap-1.5 border-b bg-muted/30 flex-shrink-0 app-drag-region"'
    )
    expect(agentProgressSource).toContain('canCollapseTile && "cursor-pointer"')
    expect(agentProgressSource).toContain('isCollapsed ? "px-2.5 py-1.5" : "px-3 py-2"')
    expect(agentProgressSource).toContain('className="flex min-w-0 flex-1 items-center gap-1.5"')
    expect(agentProgressSource).toContain('className="ml-auto flex max-w-full flex-wrap items-center justify-end gap-1 app-no-drag-region"')
    expect(agentProgressSource).toContain('const tileTitle = getTitle()')
    expect(agentProgressSource).toContain("desktopRuntimeCopy.header.renameConversationTitleLabel")
    expect(agentProgressSource).toContain('desktopConversationsClient.renameConversationTitle(conversationId, nextTitle)')
    expect(agentProgressSource).toContain('"truncate font-medium min-w-0 cursor-text"')
    expect(agentProgressSource).toContain('"app-no-drag-region h-6 min-w-0 flex-1 rounded border border-input bg-background px-1.5 font-medium text-foreground shadow-sm outline-none ring-0 focus-visible:border-ring"')
    expect(agentProgressSource).toContain('getChatRuntimePinAccessibilityLabel')
    expect(agentProgressSource).toContain('title={getChatRuntimePinAccessibilityLabel(isPinned)}')
    expect(agentProgressSource).toContain('aria-label={getChatRuntimePinAccessibilityLabel(isPinned)}')
    expect(agentProgressSource).not.toContain('title={isPinned ? "Unpin session" : "Pin session"}')
  })

  it("wraps the tile footer metadata row and preserves trailing status visibility", () => {
    expect(agentProgressSource).toContain('className="flex items-center justify-between gap-2"')
    expect(agentProgressSource).toContain('className="flex min-w-0 flex-1 items-center gap-x-2"')
    expect(agentProgressSource).toContain('<SessionModelPicker modelInfo={modelInfo} compact />')
    expect(agentProgressSource).toContain('<SessionThinkingPicker compact />')
    expect(agentProgressSource).toContain('<SessionVerbosityPicker compact />')
    expect(agentProgressSource).toContain('className="shrink-0 whitespace-nowrap">Step')
  })

  it("lets the tile chat-summary switcher and delegation preview adapt to narrow widths", () => {
    expect(agentProgressSource).toContain(
      'className="flex flex-wrap items-center gap-1 border-b border-border/30 bg-muted/5 px-2.5 py-1.5"'
    )
    expect(agentProgressSource).toContain(
      '"inline-flex min-w-0 max-w-full items-center gap-1 rounded-md px-2 py-1 text-xs font-medium transition-colors"'
    )
    expect(agentProgressSource).toContain('<span className="truncate">Summary</span>')
    expect(agentProgressSource).toContain('desktopDelegationConversationPanelSurface.headerBaseClassName')
    expect(agentProgressSource).toContain('desktopDelegationConversationPanelSurface.headerStaticClassName')
    expect(agentProgressSource).toContain('desktopDelegationConversationPanelSurface.headerInteractiveClassName')
    expect(agentProgressSource).toContain('desktopDelegationConversationPanelSurface.headerTitleRowClassName')
    expect(agentProgressSource).toContain('desktopDelegationConversationPanelSurface.headerTitleClassName')
  })

  it("surfaces latest delegated activity and a richer live details dialog from the tile chat area", () => {
    expect(agentProgressSource).toContain('desktopRuntimeCopy.delegation.summaryTitle')
    expect(agentProgressSource).toContain('desktopRuntimeCopy.delegation.detailActionLabel')
    expect(agentProgressSource).toContain('formatChatRuntimeDelegationMessageCount')
    expect(agentProgressSource).toContain('getAgentDelegationSummaryEntries')
    expect(agentProgressSource).toContain('return getAgentDelegationSummaryEntries(progress.steps, { maxSubtitleLength: 140 })')
    expect(agentProgressSource).toContain('<DelegationSummaryStrip')
    expect(agentProgressSource).toContain('isCollapsed={isDelegationSummaryCollapsed}')
    expect(agentProgressSource).toContain('onToggleCollapsed={handleToggleDelegationSummaryCollapsed}')
    expect(agentProgressSource).toContain('desktopRuntimeCopy.delegation.expandSummaryLabel')
    expect(agentProgressSource).toContain('desktopRuntimeCopy.delegation.collapseSummaryLabel')
    expect(agentProgressSource).toContain('<DelegationDetailsDialog')
    expect(agentProgressSource).toContain('alwaysOpen')
    expect(agentProgressSource).toContain('defaultShowAll')
  })

  it("reuses compact delegated info rows for task/update/result/error sections", () => {
    expect(agentProgressSource).toContain('const DelegationInfoRow: React.FC<{')
    expect(agentProgressSource).toContain('"flex items-start gap-2 rounded-md border px-2 py-1.5"')
    expect(agentProgressSource).toContain('"w-12 shrink-0 pt-0.5 text-[9px] font-semibold uppercase tracking-wide"')
    expect(agentProgressSource).toContain('<DelegationInfoRow')
    expect(agentProgressSource).toContain('label={desktopRuntimeCopy.delegation.taskRoleLabel}')
    expect(agentProgressSource).toContain('label={desktopRuntimeCopy.delegation.updateRoleLabel}')
    expect(agentProgressSource).toContain('label={desktopRuntimeCopy.delegation.resultRoleLabel}')
    expect(agentProgressSource).toContain('label={desktopRuntimeCopy.delegation.errorRoleLabel}')
    expect(agentProgressSource).not.toContain('label="Update"')
    expect(agentProgressSource).not.toContain('label="Result"')
    expect(agentProgressSource).not.toContain('label="Error"')
  })

  it("tightens delegated headers, action buttons, and details dialog spacing", () => {
    expect(agentProgressSource).toContain('getChatRuntimeDelegationStatusDesktopClassNames')
    expect(agentProgressSource).toContain('const statusClasses = getChatRuntimeDelegationStatusDesktopClassNames(delegation.status)')
    expect(agentProgressSource).toContain('statusClasses.containerClassName')
    expect(agentProgressSource).toContain('statusClasses.headerClassName')
    expect(agentProgressSource).toContain('statusClasses.textClassName')
    expect(agentProgressSource).toContain('statusClasses.iconClassName')
    expect(agentProgressSource).toContain('statusClasses.mutedTextClassName')
    expect(agentProgressSource).toContain('desktopDelegationBubbleSurface.containerBaseClassName')
    expect(agentProgressSource).toContain('desktopDelegationBubbleSurface.headerBaseClassName')
    expect(agentProgressSource).toContain('desktopDelegationBubbleSurface.headerExpandedClassName')
    expect(agentProgressSource).toContain('desktopDelegationBubbleSurface.agentNameClassName')
    expect(agentProgressSource).toContain('desktopDelegationBubbleSurface.statusIconClassName')
    expect(agentProgressSource).toContain('desktopDelegationBubbleSurface.statusSpinnerClassName')
    expect(agentProgressSource).toContain('desktopDelegationBubbleSurface.statusMetaClassName')
    expect(agentProgressSource).toContain('desktopDelegationBubbleSurface.subtitleClassName')
    expect(agentProgressSource).toContain('desktopDelegationBubbleSurface.messageCountClassName')
    expect(agentProgressSource).toContain('formatChatRuntimeDelegationMessageCount(messageCount)')
    expect(agentProgressSource).toContain('desktopDelegationBubbleSurface.toggleIconClassName')
    expect(agentProgressSource).toContain('desktopDelegationBubbleSurface.contentClassName')
    expect(agentProgressSource).toContain('desktopDelegationBubbleSurface.footerClassName')
    expect(agentProgressSource).toContain('desktopDelegationBubbleSurface.footerCompactClassName')
    expect(agentProgressSource).toContain('desktopDelegationBubbleSurface.footerMetaClassName')
    expect(agentProgressSource).toContain('desktopDelegationBubbleSurface.footerActionsClassName')
    expect(agentProgressSource).toContain('desktopDelegationBubbleSurface.footerActionsCompactClassName')
    expect(agentProgressSource).toContain('desktopDelegationBubbleSurface.transcriptButtonClassName')
    expect(agentProgressSource).toContain('desktopDelegationBubbleSurface.detailsButtonClassName')
    expect(desktopDelegationBubbleSurface.headerBaseClassName).toContain("hover:opacity-90")
    expect(desktopDelegationBubbleSurface.transcriptButtonClassName).toContain("text-purple-700")
    expect(desktopDelegationBubbleSurface.detailsButtonClassName).toContain("border-border")
    expect(getChatRuntimeDelegationStatusDesktopClassNames("running")).toBe(
      desktopDelegationBubbleSurface.statusClassNames.active,
    )
    expect(getChatRuntimeDelegationStatusDesktopClassNames("completed")).toBe(
      desktopDelegationBubbleSurface.statusClassNames.completed,
    )
    expect(getChatRuntimeDelegationStatusDesktopClassNames("failed")).toBe(
      desktopDelegationBubbleSurface.statusClassNames.failed,
    )
    expect(getChatRuntimeDelegationStatusDesktopClassNames("cancelled")).toBe(
      desktopDelegationBubbleSurface.statusClassNames.cancelled,
    )
    expect(agentProgressSource).not.toContain('const statusColor =')
    expect(agentProgressSource).not.toContain('const headerColor =')
    expect(agentProgressSource).not.toContain('const textColor =')
    expect(agentProgressSource).not.toContain('const iconColor =')
    expect(agentProgressSource).not.toContain('const mutedTextColor =')
    expect(agentProgressSource).not.toContain('"border-green-300 dark:border-green-700 bg-green-50/50 dark:bg-green-950/30"')
    expect(agentProgressSource).not.toContain('"flex min-w-0 items-center gap-1.5 px-2 py-1 cursor-pointer hover:opacity-90 transition-opacity"')
    expect(agentProgressSource).not.toContain('className="inline-flex h-7 items-center justify-center rounded-md border border-purple-200/80 px-2 text-[10px] font-medium text-purple-700 transition-colors hover:bg-purple-50 dark:border-purple-800/70 dark:text-purple-300 dark:hover:bg-purple-950/30"')
    expect(agentProgressSource).not.toContain('className="inline-flex h-7 items-center justify-center rounded-md border border-border px-2 text-[10px] font-medium text-foreground transition-colors hover:bg-muted"')
    expect(agentProgressSource).toContain('className="max-h-[76vh] overflow-hidden p-3 sm:max-w-xl"')
    expect(agentProgressSource).toContain('className="flex flex-wrap items-center gap-1 text-[13px]"')
  })

  it("compresses sub-agent conversation cards and activity panel padding", () => {
    expect(agentProgressSource).toContain('desktopDelegationConversationMessageSurface.containerBaseClassName')
    expect(agentProgressSource).toContain('desktopDelegationConversationMessageSurface.rowClassName')
    expect(agentProgressSource).toContain('desktopDelegationConversationMessageSurface.iconShellBaseClassName')
    expect(agentProgressSource).toContain('desktopDelegationConversationMessageSurface.badgeBaseClassName')
    expect(agentProgressSource).toContain('getAgentDelegationConversationMessageDisplayState')
    expect(agentProgressSource).toContain('const messageDisplayState = getAgentDelegationConversationMessageDisplayState(message, agentName)')
    expect(agentProgressSource).toContain('const { role: roleState, timestampLabel } = messageDisplayState')
    expect(agentProgressSource).toContain('const roleTone: DelegationConversationMessageTone = roleState.tone')
    expect(agentProgressSource).toContain('formatAgentDelegationConversationTranscript')
    expect(agentProgressSource).toContain('const fullConversation = formatAgentDelegationConversationTranscript(conversation, agentName)')
    expect(agentProgressSource).toContain('desktopRuntimeCopy.delegation.taskRoleLabel')
    expect(agentProgressSource).toContain('desktopRuntimeCopy.delegation.activityLabel')
    expect(agentProgressSource).toContain('desktopRuntimeCopy.delegation.copyConversationLabel')
    expect(agentProgressSource).toContain('desktopRuntimeCopy.delegation.toolInputLabel')
    expect(agentProgressSource).toContain('desktopRuntimeCopy.delegation.rawPayloadLabel')
    expect(agentProgressSource).toContain('const desktopDelegationBubbleSurface = desktopRuntimeSurface.delegationBubble')
    expect(agentProgressSource).toContain('desktopDelegationBubbleSurface.compactSubtitleMaxLength')
    expect(agentProgressSource).toContain('desktopDelegationBubbleSurface.defaultSubtitleMaxLength')
    expect(agentProgressSource).toContain('const desktopDelegationConversationPanelSurface = desktopRuntimeSurface.delegationConversationPanel')
    expect(agentProgressSource).toContain('desktopDelegationConversationPanelSurface.recentMessagesLimit')
    expect(agentProgressSource).toContain('desktopDelegationConversationPanelSurface.compactPreviewMaxLength')
    expect(agentProgressSource).toContain('desktopDelegationConversationPanelSurface.defaultPreviewMaxLength')
    expect(agentProgressSource).toContain('desktopDelegationConversationPanelSurface.headerBaseClassName')
    expect(agentProgressSource).toContain('desktopDelegationConversationPanelSurface.headerInteractiveClassName')
    expect(agentProgressSource).toContain('desktopDelegationConversationPanelSurface.copyButtonClassName')
    expect(agentProgressSource).toContain('desktopDelegationConversationPanelSurface.showEarlierButtonClassName')
    expect(agentProgressSource).toContain('desktopDelegationConversationPanelSurface.scrollContainerClassName')
    expect(agentProgressSource).toContain('desktopDelegationConversationPanelSurface.compactScrollMaxHeight')
    expect(agentProgressSource).toContain('desktopDelegationConversationPanelSurface.defaultScrollMaxHeight')
    expect(agentProgressSource).toContain('formatChatRuntimeDelegationMessagesLabel(messageCount)')
    expect(agentProgressSource).toContain('formatChatRuntimeEarlierDelegationMessagesLabel(hiddenCount)')
    expect(agentProgressSource).toContain('messageDisplayState.serializedToolInput')
    expect(agentProgressSource).toContain('messageDisplayState.shouldShowRawToolPayload')
    expect(agentProgressSource).toContain('messageDisplayState.shouldShowToggle')
    expect(agentProgressSource).toContain('chatMessageActionCopy.copy.messageLabel')
    expect(agentProgressSource).toContain('getChatMessageExpansionLabel(isExpanded)')
    expect(agentProgressSource).not.toContain('const RECENT_MESSAGES_LIMIT = 3')
    expect(agentProgressSource).not.toContain('isCompact ? 72 : 120')
    expect(agentProgressSource).not.toContain('className="overflow-y-auto p-1 space-y-1"')
    expect(agentProgressSource).not.toContain('style={{ maxHeight: isCompact ? "min(32vh, 220px)" : "min(36vh, 280px)" }}')
    expect(agentProgressSource).not.toContain('title={isCopied ? "Copied!" : "Copy message"}')
    expect(agentProgressSource).not.toContain('title="Copy conversation"')
    expect(agentProgressSource).not.toContain('panelOpen ? "Activity" : conversationPreview')
    expect(agentProgressSource).not.toContain('const role = msg.role ===')
    expect(agentProgressSource).not.toContain('const isLongContent = message.content.length > 300')
    expect(agentProgressSource).not.toContain('JSON.stringify(message.toolInput, null, 2)')
    expect(agentProgressSource).not.toContain('extractSubAgentToolDisplayContent(message.content ?? "")')
    expect(agentProgressSource).not.toContain('formatChatRuntimeDelegationMessagesLabel(delegation.conversation!.length)')
    expect(agentProgressSource).not.toContain('{delegation.conversation!.length}m')
    expect(agentProgressSource).not.toContain('{delegation.conversation!.length} messages')
    expect(agentProgressSource).not.toContain('new Date(message.timestamp).toLocaleTimeString')
  })

  it("caps ACP session badges to the available tile width and truncates long labels", () => {
    expect(acpSessionBadgeSource).toContain(
      '"inline-flex max-w-full min-w-0 flex-wrap items-center gap-1.5 cursor-help"'
    )
    expect(acpSessionBadgeSource).toContain("function getConfigOptionLabel")
    expect(acpSessionBadgeSource).toContain("Array.isArray(option.options)")
    expect(acpSessionBadgeSource).toContain(
      'className="max-w-full min-w-0 text-[10px] px-1.5 py-0 font-medium"'
    )
    expect(acpSessionBadgeSource).toContain(
      'className="max-w-full min-w-0 text-[10px] px-1.5 py-0 font-mono"'
    )
    expect(acpSessionBadgeSource).toContain('className="truncate"')
  })

  it("keeps tile message-stream tool execution rows readable at narrow widths and zoom", () => {
    expect(agentProgressSource).toContain('desktopToolExecutionCompactSurface.previewButtonClassName')
    expect(agentProgressSource).toContain(
      'rowClassName = desktopToolExecutionCompactSurface.tileRowClassName'
    )
    expect(agentProgressSource).toContain('type="button"')
    expect(agentProgressSource).toContain('aria-expanded={detailsExpanded}')
    expect(agentProgressSource).toContain('createExpandCollapseAccessibilityLabel')
    expect(agentProgressSource).toContain('formatToolExecutionDetailsAccessibilityName(toolPreview)')
    expect(agentProgressSource).toContain('rowClassName={desktopToolExecutionCompactSurface.rowClassName}')
    expect(agentProgressSource).toContain('rowClassName={desktopToolExecutionCompactSurface.tileRowClassName}')
    expect(agentProgressSource).toContain('className={desktopToolExecutionCompactSurface.previewNameClassName}')
    expect(agentProgressSource).toContain('desktopToolExecutionDetailSurface.resultHeaderClassName')
    expect(agentProgressSource).toContain('desktopToolExecutionDetailSurface.resultMetaClassName')
    expect(agentProgressSource).toContain('desktopToolExecutionCompactSurface.detailCharacterCountClassName')
    expect(agentProgressSource).toContain('() => getAgentDelegationConversationRenderItems(conversation, delegationStatus)')
    expect(agentProgressSource).toContain('<ToolExecutionBubble')
  })

  it("renders collapsed tool previews inline as the single-line summary", () => {
    expect(agentProgressSource).toContain('formatToolExecutionHeading("tool_call", message.toolCalls.length)')
    expect(agentProgressSource).toContain('formatIndexedToolExecutionLabel("tool", index)')
    expect(agentProgressSource).toContain('formatToolExecutionSectionLabel(toolExecutionDetailCopy.inputLabel)')
    expect(agentProgressSource).toContain('formatToolExecutionSectionLabel(toolExecutionDetailCopy.outputLabel)')
    expect(agentProgressSource).toContain('formatToolExecutionSectionLabel(toolExecutionDetailCopy.errorDetailsLabel)')
    expect(agentProgressSource).toContain('formatToolExecutionSectionLabel(toolExecutionStatusCopy.error.label)')
    expect(agentProgressSource).toContain('formatToolExecutionCompactAccessibilityLabel')
    expect(agentProgressSource).not.toContain('toolExecutionDetailCopy.inputLabel}:')
    expect(agentProgressSource).not.toContain('toolExecutionDetailCopy.outputLabel}:')
    expect(agentProgressSource).not.toContain('toolExecutionDetailCopy.errorDetailsLabel}:')
    expect(agentProgressSource).not.toContain('>{toolExecutionDetailCopy.inputLabel}</span>')
    expect(agentProgressSource).not.toContain('? toolExecutionDetailCopy.outputLabel')
    expect(agentProgressSource).not.toContain(': toolExecutionStatusCopy.error.label')
    expect(agentProgressSource).toContain('getToolExecutionDetailArgumentsState')
    expect(agentProgressSource).toContain('const toolArgumentsDetail = getToolExecutionDetailArgumentsState(toolCall.arguments)')
    expect(agentProgressSource).toContain('const toolArgumentsDetail = getToolExecutionDetailArgumentsState(call.arguments)')
    expect(agentProgressSource).toContain('toolArgumentsDetail.hasArguments')
    expect(agentProgressSource).toContain('payload={toolArgumentsDetail.content}')
    expect(agentProgressSource).toContain('handleCopy(e, toolArgumentsDetail.content)')
    expect(agentProgressSource).toContain('getToolExecutionDetailResultState')
    expect(agentProgressSource).toContain('const resultDetail = getToolExecutionDetailResultState(')
    expect(agentProgressSource).toContain('const resultState = resultDetail.state')
    expect(agentProgressSource).toContain('const resultStatusTextClass = getToolExecutionStatusDesktopClassName(resultState)')
    expect(agentProgressSource).toContain('getToolExecutionCompactDesktopSurfaceState')
    expect(agentProgressSource).toContain('getToolExecutionDetailDesktopSurfaceState')
    expect(agentProgressSource).toContain('getToolExecutionDetailCopyState')
    expect(agentProgressSource).toContain('getToolExecutionStatusCopyState')
    expect(agentProgressSource).toContain('const desktopToolExecutionCompactSurface = getToolExecutionCompactDesktopSurfaceState()')
    expect(agentProgressSource).toContain('const desktopToolExecutionDetailSurface = getToolExecutionDetailDesktopSurfaceState()')
    expect(agentProgressSource).toContain('const toolExecutionDetailCopy = getToolExecutionDetailCopyState()')
    expect(agentProgressSource).toContain('const toolExecutionStatusCopy = getToolExecutionStatusCopyState()')
    expect(agentProgressSource).toContain('desktopToolExecutionCompactSurface.previewListClassName')
    expect(agentProgressSource).toContain('desktopToolExecutionCompactSurface.previewStatusIconContainerClassName')
    expect(agentProgressSource).toContain('desktopToolExecutionCompactSurface.previewPendingIconClassName')
    expect(agentProgressSource).toContain('desktopToolExecutionCompactSurface.previewStatusIconClassName')
    expect(agentProgressSource).toContain('desktopToolExecutionCompactSurface.previewToggleIconClassName')
    expect(agentProgressSource).toContain('desktopToolExecutionCompactSurface.tileRowClassName')
    expect(agentProgressSource).toContain('desktopToolExecutionCompactSurface.detailItemClassName')
    expect(agentProgressSource).toContain('desktopToolExecutionCompactSurface.detailSectionLabelClassName')
    expect(agentProgressSource).toContain('desktopToolExecutionCompactSurface.detailResultStatusClassName')
    expect(agentProgressSource).toContain('desktopToolExecutionCompactSurface.detailCharacterCountClassName')
    expect(agentProgressSource).toContain('desktopToolExecutionCompactSurface.pendingResponseClassName')
    expect(agentProgressSource).toContain('desktopToolExecutionCompactSurface.pendingResponseIconClassName')
    expect(agentProgressSource).toContain('desktopToolExecutionDetailSurface.resultOutputBlockClassName')
    expect(agentProgressSource).toContain('desktopToolExecutionDetailSurface.resultErrorBlockClassName')
    expect(agentProgressSource).toContain('desktopToolExecutionDetailSurface.toolCallPayloadMaxHeightClassName')
    expect(agentProgressSource).toContain('desktopToolExecutionDetailSurface.messageExtrasContainerClassName')
    expect(agentProgressSource).toContain('desktopToolExecutionDetailSurface.messageExtrasSectionClassName')
    expect(agentProgressSource).toContain('desktopToolExecutionDetailSurface.messageExtrasHeadingClassName')
    expect(agentProgressSource).toContain('desktopToolExecutionDetailSurface.messageExtrasSectionLabelClassName')
    expect(agentProgressSource).toContain('desktopToolExecutionDetailSurface.messageExtrasErrorLabelClassName')
    expect(agentProgressSource).toContain('desktopToolExecutionDetailSurface.toolCallCardClassName')
    expect(agentProgressSource).toContain('desktopToolExecutionDetailSurface.toolCallHeaderClassName')
    expect(agentProgressSource).toContain('desktopToolExecutionDetailSurface.toolCallNameClassName')
    expect(agentProgressSource).toContain('desktopToolExecutionDetailSurface.compactBadgeClassName')
    expect(agentProgressSource).toContain('desktopToolExecutionDetailSurface.resultHeaderClassName')
    expect(agentProgressSource).toContain('desktopToolExecutionDetailSurface.resultStatusClassName')
    expect(agentProgressSource).toContain('desktopToolExecutionDetailSurface.resultStatusIconClassName')
    expect(agentProgressSource).toContain('desktopToolExecutionDetailSurface.resultMetaClassName')
    expect(agentProgressSource).toContain('desktopToolExecutionDetailSurface.resultCharacterCountClassName')
    expect(agentProgressSource).toContain('desktopToolExecutionDetailSurface.resultBodyClassName')
    expect(agentProgressSource).toContain('desktopToolExecutionDetailSurface.resultCardBaseClassName')
    expect(agentProgressSource).toContain('desktopToolExecutionDetailSurface.resultCardStatusClassNames[resultState]')
    expect(agentProgressSource).toContain('const resultState = resultDetail.hasResult ? resultDetail.state : null')
    expect(agentProgressSource).toContain('const resultStatusTextClass = resultState ? getToolExecutionStatusDesktopClassName(resultState) : ""')
    expect(agentProgressSource).toContain('const resultPresentation = toolExecutionStatusCopy[resultState]')
    expect(agentProgressSource).toContain('{resultPresentation.label}')
    expect(agentProgressSource).not.toContain('toolExecutionStatusCopy.success.label')
    expect(agentProgressSource).not.toContain('border-green-200/50 bg-green-50/30 text-green-800')
    expect(agentProgressSource).not.toContain('border-red-200/50 bg-red-50/30 text-red-800')
    expect(agentProgressSource).not.toContain('className="mt-2 space-y-2 text-left"')
    expect(agentProgressSource).not.toContain('className="rounded-lg border border-border/30 bg-muted/20 p-2 text-xs"')
    expect(agentProgressSource).not.toContain('className="min-w-0 flex-1 truncate font-mono font-semibold text-primary"')
    expect(agentProgressSource).not.toContain('className="whitespace-nowrap font-mono text-[10px] opacity-60"')
    expect(agentProgressSource).not.toContain('className="rounded bg-muted/30 p-2 text-xs whitespace-pre-wrap break-words overflow-x-auto overflow-y-auto max-w-full max-h-80 scrollbar-thin"')
    expect(agentProgressSource).not.toContain('className="rounded bg-destructive/10 p-2 text-xs whitespace-pre-wrap break-words overflow-x-auto overflow-y-auto max-w-full max-h-60 scrollbar-thin"')
    expect(agentProgressSource).not.toContain('maxHeightClassName="max-h-80"')
    expect(agentProgressSource).toContain('resultDetail.characterCountLabel')
    expect(agentProgressSource).toContain('{resultDetail.content}')
    expect(agentProgressSource).toContain('payload={resultDetail.content}')
    expect(agentProgressSource).toContain('resultDetail.error')
    expect(agentProgressSource).not.toContain('formatToolExecutionCharacterCount')
    expect(agentProgressSource).not.toContain('getResolvedToolExecutionDisplayState')
    expect(agentProgressSource).not.toContain('const formattedArguments = formatToolArguments(call.arguments)')
    expect(agentProgressSource).toContain('getToolExecutionCallDisplayState')
    expect(agentProgressSource).toContain('getToolExecutionDisplayState')
    expect(agentProgressSource).toContain('const callState = getToolExecutionCallDisplayState(result)')
    expect(agentProgressSource).toContain('const callPresentation = toolExecutionStatusCopy[callState]')
    expect(agentProgressSource).toContain('const callStatusTextClass = getToolExecutionStatusDesktopClassName(callState)')
    expect(agentProgressSource).toContain('resultStatusTextClass')
    expect(agentProgressSource).toContain('const callAccessibilityLabel = formatToolExecutionCompactAccessibilityLabel(')
    expect(agentProgressSource).toContain('formatToolExecutionDetailsAccessibilityName(toolPreview)')
    expect(agentProgressSource).toContain('aria-label={createExpandCollapseAccessibilityLabel(')
    expect(agentProgressSource).toContain('callAccessibilityLabel,')
    expect(agentProgressSource).toContain('getToolExecutionCopyAccessibilityLabel("input", call.name)')
    expect(agentProgressSource).toContain('desktopToolExecutionDetailSurface.compactPayloadMaxHeightClassName')
    expect(agentProgressSource).toContain('desktopToolExecutionDetailSurface.copyButtonClassName')
    expect(agentProgressSource).toContain('desktopToolExecutionDetailSurface.copyIconClassName')
    expect(agentProgressSource).not.toContain('maxHeightClassName="max-h-52"')
    expect(agentProgressSource).not.toContain('className="h-5 shrink-0 px-1.5 text-[10px]"')
    expect(agentProgressSource).not.toContain('className="h-2 w-2 mr-0.5"')
    expect(agentProgressSource).not.toContain('const callSuccess = result?.success')
    expect(agentProgressSource).not.toContain('const callState = getToolExecutionDisplayState([result])')
    expect(agentProgressSource).not.toContain('className="space-y-0.5 text-xs"')
    expect(agentProgressSource).not.toContain('className="min-w-0 flex-1 truncate whitespace-nowrap font-mono font-medium"')
    expect(agentProgressSource).not.toContain('className="shrink-0 text-[10px] opacity-60"')
    expect(agentProgressSource).not.toContain('className="text-[10px] space-y-1"')
    expect(agentProgressSource).not.toContain('className="min-w-0 font-medium opacity-70"')
    expect(agentProgressSource).not.toContain('className="min-w-0 flex-1 font-medium"')
    expect(agentProgressSource).not.toContain('className="shrink-0 whitespace-nowrap opacity-50 text-[10px]"')
    expect(agentProgressSource).not.toContain('className="text-[10px] opacity-60 italic py-1 flex items-center gap-1"')
    expect(agentProgressSource).toContain('const toolExecutionState = getToolExecutionDisplayState(toolCallEntries.map(({ result }) => result))')
    expect(agentProgressSource).toContain('getToolExecutionStatusDesktopClassName')
    expect(agentProgressSource).toContain('desktopToolExecutionCompactSurface')
    expect(agentProgressSource).toContain('desktopToolExecutionDetailSurface')
    expect(agentProgressSource).toContain('getToolActivityGroupSummaryState')
    expect(agentProgressSource).toContain('const groupSummary = getToolActivityGroupSummaryState({')
    expect(agentProgressSource).toContain('activityCount: group.items.length')
    expect(agentProgressSource).toContain('previewLines: group.previewLines')
    expect(agentProgressSource).toContain('getToolActivityToolCallPreview')
    expect(agentProgressSource).toContain('getToolActivityGroupCopyState')
    expect(agentProgressSource).toContain('getToolActivityGroupDesktopSurfaceState')
    expect(agentProgressSource).toContain('const desktopToolActivityGroupSurface = getToolActivityGroupDesktopSurfaceState()')
    expect(agentProgressSource).not.toContain('group.previewLines.join')
    expect(agentProgressSource).not.toContain('collapsedPreviewLine || toolActivityGroupCopy.collapsedFallbackLabel')
    expect(agentProgressSource).not.toContain('getExecuteCommandResultPreview')
    expect(agentProgressSource).not.toContain('getToolCallPreview')
    expect(agentProgressSource).toContain('desktopToolActivityGroupSurface.headerClassName')
    expect(agentProgressSource).toContain('desktopToolActivityGroupSurface.previewClassName')
    expect(agentProgressSource).toContain('groupSummary.shouldShowToolCallCount')
    expect(agentProgressSource).toContain('aria-label={groupSummary.toolCallCountLabel}')
    expect(agentProgressSource).toContain('{groupSummary.previewText}')
    expect(agentProgressSource).toContain('const collapsedToolPreviewLine = data.calls')
    expect(agentProgressSource).toContain('const toolExecutionPresentation = toolExecutionStatusCopy[toolExecutionState]')
    expect(agentProgressSource).toContain('const collapsedToolAccessibilityLabel = formatToolExecutionCompactAccessibilityLabel(')
    expect(agentProgressSource).toContain('aria-label={createExpandCollapseAccessibilityLabel(collapsedToolAccessibilityLabel, showToolDetails)}')
    expect(agentProgressSource).toContain('const toolStatusTextClass = getToolExecutionStatusDesktopClassName(toolExecutionState)')
    expect(agentProgressSource).toContain('className={cn(desktopToolExecutionCompactSurface.previewButtonClassName, toolStatusTextClass)}')
    expect(agentProgressSource).toContain('className={desktopToolExecutionCompactSurface.previewNameClassName}')
    expect(agentProgressSource).toContain('rowClassName={desktopToolExecutionCompactSurface.rowClassName}')
    expect(agentProgressSource).toContain('detailsClassName={desktopToolExecutionCompactSurface.detailListClassName}')
    expect(agentProgressSource).toContain('getChatMessageDisplayState')
    expect(agentProgressSource).toContain('const messageDisplayState = getChatMessageDisplayState(')
    expect(agentProgressSource).toContain('{ includeResultOnlyFallback: false },')
    expect(agentProgressSource).toContain('const visibleToolEntries = messageDisplayState.visibleToolEntries')
    expect(agentProgressSource).toContain('calls: visibleToolEntries.map(({ toolCall }) => toolCall)')
    expect(agentProgressSource).toContain('results: visibleToolEntries.map(({ result }) => result)')
    expect(agentProgressSource).not.toContain('getVisibleChatMessageToolEntries')
    expect(agentProgressSource).not.toContain('const visibleToolCalls = message.toolCalls')
    expect(agentProgressSource).not.toContain('TOOL_EXECUTION_COMPACT_PRESENTATION')
    expect(agentProgressSource).not.toContain('TOOL_EXECUTION_DETAIL_PRESENTATION')
    expect(agentProgressSource).not.toContain('TOOL_EXECUTION_STATUS_PRESENTATION')
    expect(agentProgressSource).not.toContain('TOOL_EXECUTION_DETAIL_SURFACE_PRESENTATION')
    expect(agentProgressSource).not.toContain('TOOL_ACTIVITY_GROUP_SURFACE_PRESENTATION')
    expect(agentProgressSource).not.toContain('toolCountLabel')
    expect(agentProgressSource).not.toContain('.toLocaleString()} chars')
  })

  it("uses shared thought markdown normalization for assistant tool bubbles", () => {
    expect(agentProgressSource).toContain('normalizeMarkdownThoughtContent')
    expect(agentProgressSource).toContain('const thoughtContent = hasThought ? normalizeMarkdownThoughtContent(data.thought.trim()) : ""')
    expect(agentProgressSource).not.toContain('function normalizeThoughtNewlines')
  })

  it("uses shared chat message presentation for compact message tone and collapse behavior", () => {
    expect(agentProgressSource).toContain('getChatMessageActionCopyState')
    expect(agentProgressSource).toContain('getChatMessageActionAvailabilityRenderState')
    expect(agentProgressSource).toContain('chatMessageActionCopy')
    expect(agentProgressSource).toContain('getChatMessageActionDesktopSurfaceState')
    expect(agentProgressSource).toContain('createChatMessageActionSlotRenderState')
    expect(agentProgressSource).toContain('getChatMessageDesktopSurfaceState')
    expect(agentProgressSource).toContain('const desktopChatMessageActionSurface = getChatMessageActionDesktopSurfaceState()')
    expect(agentProgressSource).toContain('const desktopChatMessageSurface = getChatMessageDesktopSurfaceState()')
    expect(agentProgressSource).toContain('getChatMessageContentRenderState')
    expect(agentProgressSource).toContain('getChatMessageDisplayTone')
    expect(agentProgressSource).toContain('findLastChatMessageConversationContentIndex')
    expect(agentProgressSource).toContain('getChatMessageCopyActionState')
    expect(agentProgressSource).toContain('getChatMessageExpansionActionState')
    expect(agentProgressSource).toContain('getChatMessageExpansionLabel')
    expect(agentProgressSource).toContain('getChatMessageSpeechActionState')
    expect(agentProgressSource).toContain('getChatMessageToneDesktopClassName')
    expect(agentProgressSource).toContain('getChatMessageDisplayState')
    expect(agentProgressSource).toContain('const messageDisplayState = getChatMessageDisplayState(message, {')
    expect(agentProgressSource).toContain('collapseAssistantWithToolMetadata: true,')
    expect(agentProgressSource).not.toContain('displayContent: message.responseEvent?.text')
    expect(agentProgressSource).toContain('const effectiveContent = messageDisplayState.visibleContent')
    expect(agentProgressSource).toContain('getChatRuntimeTurnDurationBadgeState')
    expect(agentProgressSource).toContain('const messageTurnDurationBadgeState = getChatRuntimeTurnDurationBadgeState({')
    expect(agentProgressSource).toContain('scope: "message",')
    expect(agentProgressSource).toContain('const totalTurnDurationBadgeState = useMemo(')
    expect(agentProgressSource).toContain('scope: "total",')
    expect(agentProgressSource).toContain('{totalTurnDurationBadgeState.canShow && (')
    expect(agentProgressSource).toContain('title={totalTurnDurationBadgeState.title ?? undefined}')
    expect(agentProgressSource).toContain('{totalTurnDurationBadgeState.label}')
    expect(agentProgressSource).toContain('desktopRuntimeSurface.turnDurationBadge.compactClassName')
    expect(agentProgressSource).toContain('desktopRuntimeSurface.turnDurationBadge.fullClassName')
    expect(agentProgressSource).toContain('desktopRuntimeSurface.turnDurationBadge.liveClassName')
    expect(agentProgressSource).toContain('desktopRuntimeSurface.turnDurationBadge.compactIconClassName')
    expect(agentProgressSource).toContain('desktopRuntimeSurface.turnDurationBadge.fullIconClassName')
    expect(agentProgressSource).not.toContain('"shrink-0 inline-flex items-center gap-0.5 whitespace-nowrap tabular-nums"')
    expect(agentProgressSource).not.toContain('"text-xs shrink-0 inline-flex items-center gap-0.5 tabular-nums text-muted-foreground"')
    expect(agentProgressSource).not.toContain('getChatRuntimeTurnDurationTitle("total", turnDurations.hasLive)')
    expect(agentProgressSource).not.toContain('formatTurnDuration(turnDurations.totalMs)')
    expect(agentProgressSource).not.toContain('getChatMessageEffectiveCollapseState')
    expect(agentProgressSource).toContain('const shouldCollapse = messageDisplayState.shouldCollapse')
    expect(agentProgressSource).toContain('{hasExtras && isExpanded && (')
    expect(agentProgressSource).toContain('const messageExpansionAction = getChatMessageExpansionActionState({')
    expect(agentProgressSource).toContain('shouldCollapse,')
    expect(agentProgressSource).toContain('isExpanded,')
    expect(agentProgressSource).toContain('return getChatMessageToneDesktopClassName(tone)')
    expect(agentProgressSource).toContain('desktopChatMessageSurface.containerClassName')
    expect(agentProgressSource).toContain('desktopChatMessageSurface.contentRowClassName')
    expect(agentProgressSource).toContain('desktopChatMessageSurface.collapsedMarkdownClassName')
    expect(agentProgressSource).toContain('const messageContentRenderState = getChatMessageContentRenderState({')
    expect(agentProgressSource).toContain('const lastAssistantDisplayIndex = useMemo(() => {')
    expect(agentProgressSource).toContain('return findLastChatMessageConversationContentIndex<DisplayItem>(')
    expect(agentProgressSource).toContain('shouldToggleFromContentClick = messageContentRenderState.isCollapsed')
    expect(agentProgressSource).toContain('collapsed={messageContentRenderState.isCollapsed}')
    expect(agentProgressSource).toContain('const messageActionRenderState = createChatMessageActionSlotRenderState<React.ReactNode>({')
    expect(agentProgressSource).toContain('const messageActionAvailabilityRenderState = getChatMessageActionAvailabilityRenderState({')
    expect(agentProgressSource).toContain('availability: messageActionAvailabilityRenderState,')
    expect(agentProgressSource).toContain('renderState: messageContentRenderState,')
    expect(agentProgressSource).toContain('renderers: {')
    expect(agentProgressSource).toContain('const shouldRenderMessageActionSlots = messageActionRenderState.shouldRenderActionSlots')
    expect(agentProgressSource).toContain('const visibleMessageActionEntries = messageActionRenderState.entries')
    expect(agentProgressSource).toContain('{shouldRenderMessageActionSlots && (')
    expect(agentProgressSource).toContain('visibleMessageActionEntries.map(({ slot, item }) => (')
    expect(agentProgressSource).toContain('<React.Fragment key={slot}>')
    expect(agentProgressSource).toContain('{item}')
    expect(agentProgressSource).toContain('desktopChatMessageActionSurface.buttonClassName')
    expect(agentProgressSource).toContain('desktopChatMessageActionSurface.activeButtonClassName')
    expect(agentProgressSource).toContain('desktopChatMessageActionSurface.actionRowClassName')
    expect(agentProgressSource).toContain('desktopChatMessageActionSurface.turnDurationBadgeClassName')
    expect(agentProgressSource).toContain('desktopChatMessageActionSurface.turnDurationLiveClassName')
    expect(agentProgressSource).toContain('desktopChatMessageActionSurface.turnDurationIconClassName')
    expect(agentProgressSource).toContain('desktopChatMessageActionSurface.generatingAudioIconClassName')
    expect(agentProgressSource).toContain('desktopChatMessageActionSurface.playingAudioIconClassName')
    expect(agentProgressSource).toContain('desktopChatMessageActionSurface.branchIconClassName')
    expect(agentProgressSource).toContain('desktopChatMessageActionSurface.copiedIconClassName')
    expect(agentProgressSource).toContain('desktopChatMessageActionSurface.copyIconClassName')
    expect(agentProgressSource).toContain('desktopChatMessageActionSurface.toggleIconClassName')
    expect(agentProgressSource).not.toContain('CHAT_MESSAGE_ACTION_SURFACE_PRESENTATION')
    expect(agentProgressSource).not.toContain('CHAT_MESSAGE_SURFACE_PRESENTATION')
    expect(agentProgressSource).toContain('getChatMessageCopyActionAccessibilityLabel')
    expect(agentProgressSource).toContain('getChatMessageCopyActionTitle')
    expect(agentProgressSource).toContain('const messageCopyAction = getChatMessageCopyActionState({')
    expect(agentProgressSource).toContain('content: effectiveContent,')
    expect(agentProgressSource).toContain('isAssistantComplete: isComplete,')
    expect(agentProgressSource).toContain('isCopied,')
    expect(agentProgressSource).toContain('const messageCopyAccessibilityLabel = getChatMessageCopyActionAccessibilityLabel(messageCopyAction)')
    expect(agentProgressSource).toContain('const messageCopyTitle = getChatMessageCopyActionTitle(messageCopyAction)')
    expect(agentProgressSource).toContain('copy: () => (')
    expect(agentProgressSource).toContain('title={messageCopyTitle}')
    expect(agentProgressSource).toContain('aria-label={messageCopyAccessibilityLabel}')
    expect(agentProgressSource).toContain('const messageSpeechAction = getChatMessageSpeechActionState({')
    expect(agentProgressSource).toContain('content: ttsSource,')
    expect(agentProgressSource).toContain('isAssistantEligible: canUseTTSForAssistantMessage,')
    expect(agentProgressSource).toContain('const shouldShowTTSButton = messageSpeechAction.canSpeak')
    expect(agentProgressSource).toContain('speech: () => (')
    expect(agentProgressSource).toContain('getChatMessageExpansionActionAccessibilityLabel')
    expect(agentProgressSource).toContain('getChatMessageExpansionActionTitle')
    expect(agentProgressSource).toContain('const messageExpansionAccessibilityLabel = getChatMessageExpansionActionAccessibilityLabel(messageExpansionAction)')
    expect(agentProgressSource).toContain('const messageExpansionTitle = getChatMessageExpansionActionTitle(messageExpansionAction)')
    expect(agentProgressSource).toContain('expansion: () => (')
    expect(agentProgressSource).toContain('title={messageExpansionTitle}')
    expect(agentProgressSource).toContain('aria-label={messageExpansionAccessibilityLabel}')
    expect(agentProgressSource).toContain('aria-expanded={messageExpansionAction.isExpanded}')
    expect(agentProgressSource).toContain('chatMessageActionCopy.copy.feedbackResetDelayMs')
    expect(agentProgressSource).toContain('chatMessageActionCopy.speech.pauseLabel')
    expect(agentProgressSource).not.toContain('CHAT_MESSAGE_ACTION_PRESENTATION')
    expect(agentProgressSource).toContain('turnDuration: () => (')
    expect(agentProgressSource).toContain('title={messageTurnDurationBadgeState.title ?? undefined}')
    expect(agentProgressSource).toContain('{messageTurnDurationBadgeState.label}')
    expect(agentProgressSource).toContain('getChatRuntimeBranchActionAccessibilityLabel')
    expect(agentProgressSource).toContain('getChatRuntimeBranchActionState')
    expect(agentProgressSource).toContain('getChatRuntimeBranchActionTitle')
    expect(agentProgressSource).toContain('const messageBranchAction = getChatRuntimeBranchActionState({')
    expect(agentProgressSource).toContain('branchMessageIndex,')
    expect(agentProgressSource).toContain('const messageBranchAccessibilityLabel = getChatRuntimeBranchActionAccessibilityLabel(messageBranchAction)')
    expect(agentProgressSource).toContain('const messageBranchTitle = getChatRuntimeBranchActionTitle()')
    expect(agentProgressSource).toContain('branch: () => (')
    expect(agentProgressSource).toContain('title={messageBranchTitle}')
    expect(agentProgressSource).toContain('aria-label={messageBranchAccessibilityLabel}')
    expect(agentProgressSource).not.toContain('setIsCopied(false), 2000')
    expect(agentProgressSource).not.toContain('className="p-1 rounded hover:bg-muted/30 transition-colors"')
    expect(agentProgressSource).not.toContain('"flex items-center gap-1 flex-shrink-0"')
    expect(agentProgressSource).not.toContain('"inline-flex items-center gap-0.5 px-1 text-[10px] tabular-nums text-muted-foreground/80"')
    expect(agentProgressSource).not.toContain('className="h-3 w-3 animate-spin text-blue-500"')
    expect(agentProgressSource).not.toContain('className="h-3 w-3 text-blue-500"')
    expect(agentProgressSource).not.toContain('className="h-3 w-3 opacity-60 hover:opacity-100"')
    expect(agentProgressSource).not.toContain('className="h-3 w-3 text-green-500"')
    expect(agentProgressSource).not.toContain('const collapseLengthLimit = hasMarkdownMediaPayload(effectiveContent) ? 500 : 100')
    expect(agentProgressSource).not.toContain('shouldCollapseChatMessageContent(effectiveContent, hasExtras)')
    expect(agentProgressSource).not.toContain('message.role === "user" || message.role === "assistant"')
    expect(agentProgressSource).not.toContain('title={messageCopyAction.label ?? chatMessageActionCopy.copy.messageLabel}')
    expect(agentProgressSource).not.toContain('aria-label={messageCopyAction.label ?? chatMessageActionCopy.copy.messageLabel}')
    expect(agentProgressSource).not.toContain('title={messageExpansionAction.label ?? chatMessageActionCopy.expansion.messageName}')
    expect(agentProgressSource).not.toContain('messageExpansionAction.accessibilityLabel ?? messageExpansionAction.label ?? chatMessageActionCopy.expansion.messageName')
    expect(agentProgressSource).not.toContain('messageBranchAction.accessibilityLabel ?? desktopRuntimeCopy.branch.buttonAccessibilityLabel')
    expect(agentProgressSource).not.toContain('title={desktopRuntimeCopy.branch.buttonTitle}')
    expect(agentProgressSource).not.toContain('aria-label={desktopRuntimeCopy.branch.buttonAccessibilityLabel}')
  })

  it("uses shared runtime activity copy for live thinking and loading states", () => {
    expect(agentProgressSource).toContain("getChatRuntimeDesktopSurfaceState")
    expect(agentProgressSource).toContain("const desktopRuntimeSurface = getChatRuntimeDesktopSurfaceState()")
    expect(agentProgressSource).toContain('formatChatRuntimeActivityContent')
    expect(agentProgressSource).toContain("formatChatRuntimeVisibleUpdatesSummary")
    expect(agentProgressSource).toContain("formatChatRuntimeConversationHistorySummary")
    expect(agentProgressSource).toContain("formatChatRuntimeLoadEarlierLabel")
    expect(agentProgressSource).toContain('content: formatChatRuntimeActivityContent(currentThinkingStep)')
    expect(agentProgressSource).toContain('content: formatChatRuntimeActivityContent(step)')
    expect(agentProgressSource).toContain('const text = formatChatRuntimeActivityContent(activeStep)')
    expect(agentProgressSource).toContain("desktopRuntimeSurface.visibleUpdatesSummaryClassName")
    expect(agentProgressSource).toContain("desktopRuntimeSurface.conversationHistoryBanner.containerClassName")
    expect(agentProgressSource).toContain("desktopRuntimeSurface.conversationHistoryBanner.loadButtonClassName")
    expect(agentProgressSource).toContain("desktopRuntimeSurface.conversationHistoryBanner.pageSize")
    expect(agentProgressSource).not.toContain("CHAT_RUNTIME_SURFACE_PRESENTATION")
    expect(agentProgressSource).toContain("formatChatRuntimeConversationHistorySummary(loadedConversationHistoryCount, conversationHistoryTotalCount)")
    expect(agentProgressSource).toContain('desktopRuntimeCopy.activity.loadingAgentActivityAccessibilityLabel')
    expect(agentProgressSource).not.toContain('"Agent is thinking..."')
    expect(agentProgressSource).not.toContain('"Running tool..."')
    expect(agentProgressSource).not.toContain('"Thinking..."')
    expect(agentProgressSource).not.toContain('>Loading agent activity</span>')
    expect(agentProgressSource).not.toContain("Showing latest {visibleDisplayItems.length} updates")
    expect(agentProgressSource).not.toContain("Showing latest {loadedConversationHistoryCount} of {conversationHistoryTotalCount} messages")
    expect(agentProgressSource).not.toContain("const CONVERSATION_HISTORY_PAGE_SIZE = 120")
    expect(agentProgressSource).not.toContain("Loading…")
  })

  it("uses shared runtime retry presentation for retry status banners", () => {
    expect(agentProgressSource).toContain("const desktopRetryStatusSurface = desktopRuntimeSurface.retryStatus")
    expect(agentProgressSource).toContain("formatChatRuntimeRetryAttemptLabel(retryInfo)")
    expect(agentProgressSource).toContain("formatChatRuntimeRetryCountdownLabel(countdown)")
    expect(agentProgressSource).toContain("desktopRuntimeCopy.retryStatus.autoRetryDescription")
    expect(agentProgressSource).toContain("className={desktopRetryStatusSurface.containerClassName}")
    expect(agentProgressSource).toContain('data: AgentRetryInfo')
    expect(agentProgressSource).not.toContain("Retrying in {countdown}s")
    expect(agentProgressSource).not.toContain("The agent will automatically retry when the API is available.")
  })

  it("renders a bottom collapse control for expanded tool groups", () => {
    expect(agentProgressSource).toContain('toolActivityGroupCopy.collapseFromBottomAccessibilityLabel')
    expect(agentProgressSource).toContain('toolActivityGroupCopy.collapseFromBottomLabel')
    expect(agentProgressSource).toContain('toolActivityGroupCopy.collapseFromBottomTitle')
    expect(agentProgressSource).toContain('desktopToolActivityGroupSurface.expandedContentClassName')
    expect(agentProgressSource).toContain('desktopToolActivityGroupSurface.footerClassName')
    expect(agentProgressSource).toContain('desktopToolActivityGroupSurface.footerButtonClassName')
    expect(agentProgressSource).not.toContain('TOOL_ACTIVITY_GROUP_PRESENTATION')
  })

  it("keeps tool group expansion state separate from child rows", () => {
    expect(agentProgressSource).toContain('getToolActivityGroupStateKey')
    expect(agentProgressSource).toContain('const groupId = getToolActivityGroupStateKey(runItems[0]?.id ?? runStart)')
    expect(agentProgressSource).toContain('getToolActivityGroupExpanded')
    expect(agentProgressSource).toContain('getChatDisplayGroupedExpansionState')
    expect(agentProgressSource).toContain('applyChatDisplayGroupedExpansionInheritance')
    expect(agentProgressSource).toContain('groupKey: item.id')
    expect(agentProgressSource).toContain('inheritedKey: item.data.items[0]?.id ?? null')
  })

  it("stops delegated tool rows from showing a loading spinner after terminal completion", () => {
    expect(agentProgressSource).toContain('isAgentDelegationActiveStatus')
    expect(agentProgressSource).toContain('getAgentDelegationConversationRenderItems')
    expect(agentProgressSource).toContain('() => getAgentDelegationConversationRenderItems(conversation, delegationStatus)')
    expect(agentProgressSource).not.toContain('function buildSubAgentConversationItems(')
    expect(agentProgressSource).not.toContain('function isStructuredToolInvocationMessage(')
    expect(agentProgressSource).not.toContain('function normalizeStructuredToolResultContent(')
    expect(agentProgressSource).not.toContain('content: result.content || "Tool completed"')
  })

  it("uses shared runtime presentation for delegated conversation message cards", () => {
    expect(agentProgressSource).toContain('const desktopDelegationConversationMessageSurface = desktopRuntimeSurface.delegationConversationMessage')
    expect(agentProgressSource).toContain('type DelegationConversationMessageTone = keyof typeof desktopDelegationConversationMessageSurface.roleClassNames')
    expect(agentProgressSource).toContain('desktopDelegationConversationMessageSurface.containerBaseClassName')
    expect(agentProgressSource).toContain('desktopDelegationConversationMessageSurface.roleClassNames[roleTone]')
    expect(agentProgressSource).toContain('desktopDelegationConversationMessageSurface.rowClassName')
    expect(agentProgressSource).toContain('desktopDelegationConversationMessageSurface.iconShellBaseClassName')
    expect(agentProgressSource).toContain('desktopDelegationConversationMessageSurface.iconClassNames[roleTone]')
    expect(agentProgressSource).toContain('desktopDelegationConversationMessageSurface.headerCompactClassName')
    expect(agentProgressSource).toContain('desktopDelegationConversationMessageSurface.badgeRoleClassNames[roleTone]')
    expect(agentProgressSource).toContain('desktopDelegationConversationMessageSurface.toolInputCodeClassName')
    expect(agentProgressSource).toContain('desktopDelegationConversationMessageSurface.rawPayloadCodeClassName')
    expect(agentProgressSource).toContain('desktopDelegationConversationMessageSurface.copyButtonClassName')
    expect(agentProgressSource).not.toContain('"border-purple-200/80 bg-purple-50/70 dark:border-purple-800/60 dark:bg-purple-950/30"')
    expect(agentProgressSource).not.toContain('"inline-flex items-center rounded-full px-1.5 py-0.5 text-[10px] font-medium"')
    expect(agentProgressSource).not.toContain('"max-h-28 overflow-auto whitespace-pre-wrap break-words rounded bg-amber-50/80 p-1.5 text-[10px] text-amber-900 dark:bg-amber-950/30 dark:text-amber-100"')
  })

  it("keeps respond_to_user assistant tool calls outside collapsed tool activity groups", () => {
    expect(agentProgressSource).toContain('return !item.data.calls.some((call) => isCompletionControlTool(call.name))')
    expect(agentProgressSource).toContain('isCompletionControlTool,')
    expect(agentProgressSource).toContain('hasVisibleChatMessageContent,')
    expect(agentProgressSource).toContain('isChatMessageConversationContent,')
    expect(agentProgressSource).toContain('findLastChatMessageConversationContentIndex,')
    expect(agentProgressSource).toContain('isChatMessageConversationContent(m) &&')
    expect(agentProgressSource).toContain('(item) => item.kind === "message" ? item.data : null')
    expect(agentProgressSource).toContain('hasVisibleChatMessageContent(message)')
    expect(agentProgressSource).toContain('hasVisibleChatMessageContent(m),')
    expect(agentProgressSource).toContain('hasVisibleChatMessageContent(item.data),')
    expect(agentProgressSource).toContain('messageDisplayState.shouldRenderSurface')
    expect(agentProgressSource).not.toContain('displayContent: message.responseEvent?.text,')
    expect(agentProgressSource).not.toContain('shouldRenderChatMessageSurface,')
    expect(agentProgressSource).not.toContain('function isCompletionControlTool(toolName: string): boolean {')
    expect(agentProgressSource).not.toContain('MARK_WORK_COMPLETE_TOOL')
    expect(agentProgressSource).not.toContain('m.role === "assistant" &&\n        !m.toolCalls?.length')
  })

  it("wraps expanded tool detail chrome and caps tool output blocks inside narrow tiles", () => {
    expect(agentProgressSource).toContain(
      'detailsClassName={desktopToolExecutionDetailSurface.tileDetailListClassName}'
    )
    expect(agentProgressSource).toContain(
      'className={desktopToolExecutionDetailSurface.detailHeaderClassName}'
    )
    expect(agentProgressSource).toContain(
      'detailsClassName = desktopToolExecutionDetailSurface.detailListClassName'
    )
    expect(agentProgressSource).toContain(
      'className={desktopToolExecutionDetailSurface.errorBlockClassName}'
    )
    expect(agentProgressSource).toContain('payload={resultDetail.content}')
    expect(agentProgressSource).toContain('toolExecutionDetailCopy.copyLabel')
    expect(agentProgressSource).toContain('toolExecutionDetailCopy.pendingResponseAccessibilityLabel')
    expect(agentProgressSource).not.toContain('>Parameters</span>')
    expect(agentProgressSource).not.toContain('> Copy')
    expect(agentProgressSource).not.toContain('? "Result" : "Error"')
    expect(agentProgressSource).not.toContain('aria-label="Waiting for response"')
  })

  it("keeps structured tool payloads compact and collapses payloads over two lines", () => {
    expect(agentProgressSource).toContain('formatToolExecutionStructuredPayloadValue')
    expect(agentProgressSource).toContain('getToolExecutionPayloadValueType')
    expect(agentProgressSource).toContain('className={desktopToolExecutionDetailSurface.structuredPayloadDetailsClassName}')
    expect(agentProgressSource).toContain('const StructuredPayloadTree: React.FC')
    expect(agentProgressSource).toContain('getToolExecutionStructuredPayloadChildEntries(value.value)')
    expect(agentProgressSource).toContain('title={value.compactText}>{value.compactText}</span>')
    expect(agentProgressSource).toContain('desktopToolExecutionDetailSurface.structuredPayloadTreeEmptyClassName')
    expect(agentProgressSource).toContain('desktopToolExecutionDetailSurface.structuredPayloadTreeContainerClassName')
    expect(agentProgressSource).toContain('desktopToolExecutionDetailSurface.structuredPayloadTreeListClassName')
    expect(agentProgressSource).toContain('desktopToolExecutionDetailSurface.structuredPayloadTreeEntryClassName')
    expect(agentProgressSource).toContain('desktopToolExecutionDetailSurface.structuredPayloadTreeEntryLabelClassName')
    expect(agentProgressSource).toContain('desktopToolExecutionDetailSurface.structuredPayloadTreeEntryValueClassName')
    expect(agentProgressSource).toContain('desktopToolExecutionDetailSurface.structuredPayloadSummaryClassName')
    expect(agentProgressSource).toContain('desktopToolExecutionDetailSurface.structuredPayloadNestedSpacingClassName')
    expect(agentProgressSource).toContain('desktopToolExecutionDetailSurface.structuredPayloadDefaultSpacingClassName')
    expect(agentProgressSource).toContain('desktopToolExecutionDetailSurface.structuredPayloadToggleIconClassName')
    expect(agentProgressSource).toContain('desktopToolExecutionDetailSurface.structuredPayloadSummaryTextClassName')
    expect(agentProgressSource).toContain('desktopToolExecutionDetailSurface.structuredPayloadLineCountClassName')
    expect(agentProgressSource).toContain('desktopToolExecutionDetailSurface.structuredPayloadExpandedBlockClassName')
    expect(agentProgressSource).toContain('desktopToolExecutionDetailSurface.structuredPayloadInlineClassName')
    expect(agentProgressSource).toContain('desktopToolExecutionDetailSurface.structuredPayloadBlockClassName')
    expect(agentProgressSource).toContain('desktopToolExecutionDetailSurface.structuredPayloadBlockDefaultSpacingClassName')
    expect(agentProgressSource).toContain('desktopToolExecutionDetailSurface.structuredPayloadFallbackBaseClassName')
    expect(agentProgressSource).toContain('desktopToolExecutionDetailSurface.structuredPayloadFallbackToneClassNames[payloadTone]')
    expect(agentProgressSource).toContain('desktopToolExecutionDetailSurface.structuredPayloadEntryListClassName')
    expect(agentProgressSource).toContain('desktopToolExecutionDetailSurface.structuredPayloadEntryBaseClassName')
    expect(agentProgressSource).toContain('desktopToolExecutionDetailSurface.structuredPayloadEntryToneClassNames[payloadTone]')
    expect(agentProgressSource).toContain('desktopToolExecutionDetailSurface.structuredPayloadEntryHeaderClassName')
    expect(agentProgressSource).toContain('desktopToolExecutionDetailSurface.structuredPayloadEntryHeaderBorderClassNames[payloadTone]')
    expect(agentProgressSource).toContain('desktopToolExecutionDetailSurface.structuredPayloadEntryTextClassNames[payloadTone]')
    expect(agentProgressSource).toContain('desktopToolExecutionDetailSurface.structuredPayloadEntryKeyClassName')
    expect(agentProgressSource).toContain('desktopToolExecutionDetailSurface.structuredPayloadEntryTypeClassName')
    expect(agentProgressSource).not.toContain('const COLLAPSIBLE_PAYLOAD_LINE_THRESHOLD = 2')
    expect(agentProgressSource).not.toContain('{value.expandedText}\n        </pre>')
    expect(agentProgressSource).not.toContain('className="space-y-1"')
    expect(agentProgressSource).not.toContain('className="min-w-0 truncate font-mono text-[10px] font-semibold"')
    expect(agentProgressSource).not.toContain('className="shrink-0 text-[9px] uppercase tracking-wide opacity-50"')
    expect(agentProgressSource).not.toContain('"bg-amber-100/70 text-amber-900 dark:bg-amber-900/40 dark:text-amber-100"')
    expect(agentProgressSource).not.toContain('"border-border/40 bg-background/40 dark:bg-muted/20"')
  })

  it("keeps the session model visible and clickable as a picker", () => {
    expect(agentProgressSource).toContain('const SessionModelPicker: React.FC')
    expect(desktopRuntimeCopy.modelControls.model.changeAccessibilityLabel).toBe("Change agent model")
    expect(desktopRuntimeCopy.modelControls.model.updatedToast).toBe("Agent model updated")
    expect(desktopRuntimeCopy.modelControls.model.updateFailedToast).toBe("Failed to update model")
    expect(desktopRuntimeCopy.modelControls.model.loadingLabel).toBe("Loading models...")
    expect(desktopRuntimeCopy.modelControls.model.emptyLabel).toBe("No models available")
    expect(formatChatRuntimeModelPickerTitle("OpenAI", "gpt-5.2")).toBe("Change agent model (OpenAI/gpt-5.2)")
    expect(desktopRuntimeCopy.modelControls.thinking.changeAccessibilityLabel).toBe("Change thinking level")
    expect(desktopRuntimeCopy.modelControls.thinking.updatedToast).toBe("Thinking level updated")
    expect(desktopRuntimeCopy.modelControls.thinking.updateFailedToast).toBe("Failed to update thinking level")
    expect(formatChatRuntimeThinkingPickerTitle("High")).toBe("Thinking level (High)")
    expect(desktopRuntimeCopy.modelControls.verbosity.changeAccessibilityLabel).toBe("Change verbosity")
    expect(desktopRuntimeCopy.modelControls.verbosity.updatedToast).toBe("Verbosity updated")
    expect(desktopRuntimeCopy.modelControls.verbosity.updateFailedToast).toBe("Failed to update verbosity")
    expect(formatChatRuntimeVerbosityPickerTitle("Detailed")).toBe("Verbosity (Detailed)")
    expect(agentProgressSource).toContain("desktopRuntimeCopy.modelControls.model.changeAccessibilityLabel")
    expect(agentProgressSource).toContain("desktopRuntimeCopy.modelControls.model.updatedToast")
    expect(agentProgressSource).toContain("desktopRuntimeCopy.modelControls.model.updateFailedToast")
    expect(agentProgressSource).toContain("desktopRuntimeCopy.modelControls.model.loadingLabel")
    expect(agentProgressSource).toContain("desktopRuntimeCopy.modelControls.model.emptyLabel")
    expect(agentProgressSource).toContain("formatChatRuntimeModelPickerTitle(providerLabel, currentValue)")
    expect(agentProgressSource).toContain("desktopRuntimeCopy.modelControls.thinking.changeAccessibilityLabel")
    expect(agentProgressSource).toContain("desktopRuntimeCopy.modelControls.thinking.updatedToast")
    expect(agentProgressSource).toContain("desktopRuntimeCopy.modelControls.thinking.updateFailedToast")
    expect(agentProgressSource).toContain("formatChatRuntimeThinkingPickerTitle(currentLabel)")
    expect(agentProgressSource).toContain("desktopRuntimeCopy.modelControls.verbosity.changeAccessibilityLabel")
    expect(agentProgressSource).toContain("desktopRuntimeCopy.modelControls.verbosity.updatedToast")
    expect(agentProgressSource).toContain("desktopRuntimeCopy.modelControls.verbosity.updateFailedToast")
    expect(agentProgressSource).toContain("formatChatRuntimeVerbosityPickerTitle(currentLabel)")
    expect(agentProgressSource).toContain('buildAgentModelConfigUpdates(config as AgentModelConfigLike, providerId, modelId)')
    expect(agentProgressSource).toContain('Model/provider controls stay available even before live session metadata arrives')
    expect(agentProgressSource).toContain('<SessionModelPicker modelInfo={modelInfo} />')
    // Tile footer renders unconditionally so the model/thinking/verbosity controls
    // stay reachable for inactive (completed) sessions too.
    expect(agentProgressSource).toContain('always render so model picker, thinking,')
    expect(agentProgressSource).not.toContain('aria-label="Change agent model"')
    expect(agentProgressSource).not.toContain('toast.success("Agent model updated")')
    expect(agentProgressSource).not.toContain('toast.error("Failed to update model")')
    expect(agentProgressSource).not.toContain('aria-label="Change thinking level"')
    expect(agentProgressSource).not.toContain('toast.success("Thinking level updated")')
    expect(agentProgressSource).not.toContain('aria-label="Change verbosity"')
    expect(agentProgressSource).not.toContain('toast.success("Verbosity updated")')
  })

  it("keeps inline tool approval cards readable in narrow tiles and under zoom", () => {
    expect(agentProgressSource).toContain('getChatRuntimeToolApprovalDesktopSurfaceState')
    expect(agentProgressSource).toContain('getChatRuntimeToolApprovalArgumentsAccessibilityLabel')
    expect(agentProgressSource).toContain('const approvalCopy = desktopRuntimeCopy.approval')
    expect(agentProgressSource).toContain('const approvalSurface = getChatRuntimeToolApprovalDesktopSurfaceState()')
    expect(agentProgressSource).toContain('const approvalArgumentsDetail = getToolExecutionDetailArgumentsState(approval.arguments)')
    expect(agentProgressSource).toContain('const argsPreview = approvalArgumentsDetail.preview')
    expect(agentProgressSource).toContain('className={approvalSurface.containerClassName}')
    expect(agentProgressSource).toContain('className={approvalSurface.headerClassName}')
    expect(agentProgressSource).toContain('className={approvalSurface.toolRowClassName}')
    expect(agentProgressSource).toContain('className={approvalSurface.toolNameClassName}')
    expect(agentProgressSource).toContain('className={approvalSurface.argumentsPreviewClassName}')
    expect(agentProgressSource).toContain('payload={approvalArgumentsDetail.content}')
    expect(agentProgressSource).not.toContain('formatArgumentsPreview')
    expect(agentProgressSource).toContain('aria-expanded={showArgs}')
    expect(agentProgressSource).toContain('aria-label={getChatRuntimeToolApprovalArgumentsAccessibilityLabel(')
    expect(agentProgressSource).toContain('approval.toolName,')
    expect(agentProgressSource).toContain('showArgs,')
    expect(agentProgressSource).toContain('className={approvalSurface.actionStackClassName}')
    expect(agentProgressSource).toContain('className={approvalSurface.hotkeysRowClassName}')
    expect(agentProgressSource).not.toContain('TOOL_APPROVAL_SURFACE_PRESENTATION')
  })

  it("keeps the session-tile scroll-to-bottom affordance scoped inside the chat area", () => {
    expect(agentProgressSource).toContain("desktopScrollToBottomSurface")
    expect(agentProgressSource).toContain("className={desktopScrollToBottomSurface.buttonClassName}")
    expect(agentProgressSource).toContain("className={desktopScrollToBottomSurface.compactButtonClassName}")
    expect(agentProgressSource).toContain("title={desktopRuntimeCopy.scrollToBottom.accessibilityLabel}")
    expect(agentProgressSource).toContain("aria-label={desktopRuntimeCopy.scrollToBottom.accessibilityLabel}")
    expect(agentProgressSource).toContain("desktopRuntimeCopy.scrollToBottom.latestLabel")
    expect(agentProgressSource).toContain('scrollToBottom("smooth")')
    expect(agentProgressSource).not.toContain('title="Scroll to bottom"')
    expect(agentProgressSource).not.toContain('aria-label="Scroll to bottom"')
    expect(agentProgressSource).not.toContain(">Latest</button>")
  })

  it("uses shared runtime presentation for desktop stop-session dialogs and header controls", () => {
    expect(agentProgressSource).toContain("const desktopRuntimeCopy = getChatRuntimeCopyState()")
    expect(agentProgressSource).toContain("const desktopKillSwitchDialogSurface = desktopRuntimeSurface.killSwitchDialog")
    expect(agentProgressSource).toContain("desktopRuntimeCopy.killSwitch.sessionTitle")
    expect(agentProgressSource).toContain("desktopRuntimeCopy.killSwitch.sessionMessage")
    expect(agentProgressSource).toContain("desktopRuntimeCopy.killSwitch.sessionMessageWithOtherSessions")
    expect(agentProgressSource).toContain("desktopRuntimeCopy.killSwitch.sessionActionLabel")
    expect(agentProgressSource).toContain("desktopRuntimeCopy.killSwitch.sessionPendingActionLabel")
    expect(agentProgressSource).toContain("desktopRuntimeCopy.common.cancel")
    expect(agentProgressSource).toContain("desktopRuntimeCopy.killSwitch.sessionButtonTitle")
    expect(agentProgressSource).toContain("desktopRuntimeCopy.killSwitch.sessionExecutionButtonTitle")
    expect(agentProgressSource).toContain("desktopRuntimeCopy.killSwitch.dismissButtonTitle")
    expect(agentProgressSource).toContain("desktopRuntimeCopy.killSwitch.closeButtonTitle")
    expect(agentProgressSource).not.toContain("CHAT_RUNTIME_PRESENTATION")
    expect(agentProgressSource).not.toContain(">Stop Agent Execution</h3>")
    expect(agentProgressSource).not.toContain("Are you sure you want to stop this session?")
    expect(agentProgressSource).not.toContain("title=\"Stop agent execution\"")
  })

  it("uses a lightweight plain-text path for active streaming bubbles before final markdown rendering", () => {
    expect(agentProgressSource).toContain('const contentNode = streamingContent.isStreaming')
    expect(agentProgressSource).toContain('const desktopStreamingContentSurface = desktopRuntimeSurface.streamingContent')
    expect(agentProgressSource).toContain('className={desktopStreamingContentSurface.liveTextClassName}')
    expect(agentProgressSource).toContain('getChatRuntimeStreamingContentTitle(streamingContent.isStreaming)')
    expect(agentProgressSource).toContain('className={desktopStreamingContentSurface.containerClassName}')
    expect(agentProgressSource).toContain('className={desktopStreamingContentSurface.caretClassName}')
    expect(agentProgressSource).toContain(': <MarkdownRenderer content={streamingContent.text} />')
    expect(agentProgressSource).not.toContain('streamingContent.isStreaming ? "Generating response..." : "Response"')
  })

  it("wraps retry banners and queue chrome safely in narrow tile footers", () => {
    expect(agentProgressSource).toContain(
      'className={approvalSurface.containerClassName}'
    )
    expect(agentProgressSource).toContain(
      'className={approvalSurface.headerClassName}'
    )
    expect(agentProgressSource).toContain('className={cn(approvalSurface.contentClassName, isResponding && "opacity-60")}')
    expect(agentProgressSource).toContain('className={desktopRetryStatusSurface.metaRowClassName}')
    expect(messageQueuePanelSource).toContain('desktopMessageQueueCompactSurface.containerBaseClassName')
    expect(messageQueuePanelSource).toContain('desktopMessageQueueCompactSurface.labelBaseClassName')
    expect(messageQueuePanelSource).toContain('desktopMessageQueueCompactSurface.actionsClassName')
    expect(messageQueuePanelSource).toContain('desktopMessageQueueChromeSurface.headerBaseClassName')
    expect(messageQueuePanelSource).toContain('desktopMessageQueueChromeSurface.titleGroupClassName')
    expect(messageQueuePanelSource).toContain('desktopMessageQueueChromeSurface.actionsClassName')
    expect(messageQueuePanelSource).toContain('desktopMessageQueueChromeSurface.pausedNoticeClassName')
    expect(messageQueuePanelSource).toContain('desktopMessageQueueItemSurface.rowClassName')
    expect(messageQueuePanelSource).toContain('desktopMessageQueueItemSurface.bodyClassName')
    expect(messageQueuePanelSource).toContain('desktopMessageQueueItemSurface.actionRailClassName')
    expect(messageQueuePanelSource).not.toContain(
      '"flex flex-wrap items-center gap-2 rounded-md px-2 py-1.5 text-xs"'
    )
    expect(messageQueuePanelSource).not.toContain(
      '"flex flex-wrap items-center justify-between gap-1.5 px-2.5 py-1.5"'
    )
    expect(messageQueuePanelSource).not.toContain(
      'className="border-b border-orange-200 bg-orange-100/30 px-2.5 py-1 text-[10px] text-orange-700 break-words dark:border-orange-800 dark:bg-orange-900/20 dark:text-orange-300"'
    )
    expect(messageQueuePanelSource).not.toContain(
      '"ml-auto flex shrink-0 flex-wrap items-center gap-1 self-start transition-opacity"'
    )
  })

  it("keeps shared audio player and compact TTS errors readable under width pressure", () => {
    expect(audioPlayerSource).toContain('const compactStatusText = hasAudio')
    expect(audioPlayerSource).toContain(
      '"inline-flex items-center"'
    )
    expect(audioPlayerSource).toContain('className="h-10 w-10 shrink-0 p-0"')
    expect(audioPlayerSource).toContain(
      'className={cn("min-w-0 max-w-full space-y-2 rounded-lg bg-muted/50 p-3", className)}'
    )
    expect(audioPlayerSource).toContain('className="flex flex-wrap items-center gap-3"')
    expect(audioPlayerSource).toContain('className="min-w-0 flex-1 space-y-1"')
    expect(audioPlayerSource).toContain('className="ml-auto flex min-w-0 max-w-full items-center gap-2"')
    expect(audioPlayerSource).toContain('aria-label="Audio position"')
    expect(audioPlayerSource).toContain('aria-label="Audio volume"')
    expect(agentProgressSource).toContain(
      'className="mt-2 rounded-md bg-red-50 p-2 text-xs text-red-700 break-words [overflow-wrap:anywhere] dark:bg-red-900/20 dark:text-red-300"'
    )
  })

  it("allows tile auto-play without requiring tile focus", () => {
    expect(agentProgressSource).toContain('function shouldAutoPlayTTSForVariant')
    expect(agentProgressSource).toContain('focus no\n  // longer decides whether a tile may request auto-play')
    expect(agentProgressSource).toContain('return !isSnoozed')
    expect(agentProgressSource).toContain('consumeSessionForcedAutoPlay(sessionId)')
    expect(agentProgressSource).toContain('hasTTSPlayed(key)')
  })

  it("uses shared conversation-state normalization across agent progress surfaces", () => {
    expect(agentProgressSource).toContain('getSessionPresentation')
    expect(agentProgressSource).toContain('const sessionPresentation = getSessionPresentation({')
    expect(agentProgressSource).toContain('conversationState === "needs_input"')
    expect(agentProgressSource).toContain('conversationState === "blocked"')
    expect(agentProgressSource).toContain('const conversationStateBadgeClass = sessionPresentation.badgeClassName')
  })
})
