import { readFileSync } from "node:fs"
import { describe, expect, it } from "vitest"

const source = readFileSync(new URL("./message-queue-panel.tsx", import.meta.url), "utf8")

describe("desktop message queue panel presentation", () => {
  it("uses shared queue presentation helpers for visible copy and labels", () => {
    expect(source).toContain("getMessageQueuePanelDesktopRenderState")
    expect(source).toContain("getQueuedMessageItemDesktopRenderState")
    expect(source).toContain("const desktopQueueItemRenderState = getQueuedMessageItemDesktopRenderState({")
    expect(source).toContain("const desktopMessageQueueItemSurface = desktopQueueItemRenderState.surface")
    expect(source).toContain("const desktopMessageQueuePanelCopy = desktopQueueItemRenderState.copy")
    expect(source).toContain("const queuePanelRenderState = getMessageQueuePanelDesktopRenderState({")
    expect(source).toContain("const queuePanelState = queuePanelRenderState.panel")
    expect(source).toContain("const desktopMessageQueueCompactSurface = queuePanelRenderState.surface.compact")
    expect(source).toContain("const desktopMessageQueueChromeSurface = queuePanelRenderState.surface.panel")
    expect(source).toContain("const desktopMessageQueuePanelCopy = queuePanelRenderState.copy")
    expect(source).toContain("!queuePanelRenderState.shouldRender")
    expect(source).toContain("queuePanelState.compactLabel")
    expect(source).toContain("queuePanelState.title")
    expect(source).toContain("queuePanelState.listToggleLabel")
    expect(source).toContain("queuePanelState.items.map")
    expect(source).toContain("queuePanelState.clearActionState.isDisabled")
    expect(source).toContain("queuePanelState.pauseActionState.isDisabled")
    expect(source).toContain("getQueuedMessageEditDraftState(editText, message.text)")
    expect(source).toContain("editDraftState.submitState")
    expect(source).toContain("editDraftState.saveActionState.isDisabled")
    expect(source).toContain("messagePresentation")
    expect(source).toContain("desktopMessageQueuePanelCopy.actions.retryAccessibilityLabel")
    expect(source).toContain("desktopMessageQueuePanelCopy.pausedNotice")
    expect(source).not.toContain("formatMessageQueueCompactLabel(messages.length, isPaused)")
    expect(source).not.toContain("formatMessageQueuePanelTitle(messages.length, isPaused)")
    expect(source).not.toContain("getMessageQueueListToggleLabel(isListCollapsed)")
    expect(source).not.toContain("getMessageQueuePanelCopyState")
    expect(source).not.toContain("getMessageQueuePanelDesktopSurfaceState")
    expect(source).not.toContain("getMessageQueuePanelState")
    expect(source).not.toContain("getQueuedMessageItemPresentation")
    expect(source).not.toContain("const trimmed = editText.trim()")
    expect(source).not.toContain("getQueuedMessageEditSaveActionState(editText)")
    expect(source).not.toContain("getQueuedMessageEditSubmitState(editText, message.text)")
    expect(source).not.toContain("messages.length === 0")
    expect(source).not.toContain("!queuePanelState.canClear")
    expect(source).not.toContain("!queuePanelState.canPause")
    expect(source).not.toContain("!editText.trim()")
    expect(source).not.toContain("hasProcessingQueuedMessage(messages)")
    expect(source).not.toContain("MESSAGE_QUEUE_PANEL_PRESENTATION")
    expect(source).not.toContain("MESSAGE_QUEUE_PANEL_SURFACE_PRESENTATION")
    expect(source).not.toContain('{isPaused ? "Paused" : "Queued"} ({messages.length})')
    expect(source).not.toContain("Paused. Click Resume to continue.</div>")
    expect(source).not.toContain('"rounded-md border overflow-hidden"')
    expect(source).not.toContain('"divide-y max-h-60 overflow-y-auto"')
  })
})
