import { readFileSync } from "node:fs"
import { describe, expect, it } from "vitest"

const source = readFileSync(new URL("./message-queue-panel.tsx", import.meta.url), "utf8")

describe("desktop message queue panel presentation", () => {
  it("uses shared queue presentation helpers for visible copy and labels", () => {
    expect(source).toContain("getMessageQueuePanelCopyState")
    expect(source).toContain("getMessageQueuePanelDesktopSurfaceState")
    expect(source).toContain("const desktopMessageQueuePanelCopy = getMessageQueuePanelCopyState()")
    expect(source).toContain("const desktopMessageQueuePanelSurface = getMessageQueuePanelDesktopSurfaceState()")
    expect(source).toContain("const desktopMessageQueueItemSurface = desktopMessageQueuePanelSurface.item")
    expect(source).toContain("const desktopMessageQueueCompactSurface = desktopMessageQueuePanelSurface.compact")
    expect(source).toContain("const desktopMessageQueueChromeSurface = desktopMessageQueuePanelSurface.panel")
    expect(source).toContain("getMessageQueuePanelState")
    expect(source).toContain("const queuePanelState = getMessageQueuePanelState(messages, {")
    expect(source).toContain("queuePanelState.compactLabel")
    expect(source).toContain("queuePanelState.title")
    expect(source).toContain("queuePanelState.listToggleLabel")
    expect(source).toContain("queuePanelState.items.map")
    expect(source).toContain("queuePanelState.clearActionState.isDisabled")
    expect(source).toContain("queuePanelState.pauseActionState.isDisabled")
    expect(source).toContain("getQueuedMessageItemPresentation(message, isExpanded)")
    expect(source).toContain("getQueuedMessageEditSaveActionState(editText)")
    expect(source).toContain("getQueuedMessageEditSubmitState(editText, message.text)")
    expect(source).toContain("editSaveActionState.isDisabled")
    expect(source).toContain("messagePresentation")
    expect(source).toContain("desktopMessageQueuePanelCopy.actions.retryAccessibilityLabel")
    expect(source).toContain("desktopMessageQueuePanelCopy.pausedNotice")
    expect(source).not.toContain("formatMessageQueueCompactLabel(messages.length, isPaused)")
    expect(source).not.toContain("formatMessageQueuePanelTitle(messages.length, isPaused)")
    expect(source).not.toContain("getMessageQueueListToggleLabel(isListCollapsed)")
    expect(source).not.toContain("const trimmed = editText.trim()")
    expect(source).not.toContain("!queuePanelState.canClear")
    expect(source).not.toContain("!queuePanelState.canPause")
    expect(source).not.toContain("!editText.trim()")
    expect(source).not.toContain("hasProcessingQueuedMessage(messages)")
    expect(source).not.toContain("MESSAGE_QUEUE_PANEL_PRESENTATION")
    expect(source).not.toContain("MESSAGE_QUEUE_PANEL_SURFACE_PRESENTATION")
    expect(source).not.toContain('{isPaused ? "Paused" : "Queued"} ({messages.length})')
    expect(source).not.toContain("Paused. Click Resume to continue.</div>")
    expect(source).not.toContain('"rounded-md border overflow-hidden"')
    expect(source).not.toContain('"divide-y max-h-60 overflow-y-auto"')
  })
})
