import { readFileSync } from "node:fs"
import { describe, expect, it } from "vitest"

const panelResizeWrapperSource = readFileSync(
  new URL("./panel-resize-wrapper.tsx", import.meta.url),
  "utf8",
)
const resizeHandleSource = readFileSync(new URL("./resize-handle.tsx", import.meta.url), "utf8")

const compactPanelResizeWrapperSource = panelResizeWrapperSource.replace(/\s+/g, "")
const compactResizeHandleSource = resizeHandleSource.replace(/\s+/g, "")

function expectCompactSourceToContain(source: string, fragment: string) {
  expect(source).toContain(fragment.replace(/\s+/g, ""))
}

describe("floating panel resize impact feedback", () => {
  it("warns when resize width enters a range likely to crowd compare or grid layouts", () => {
    expectCompactSourceToContain(compactPanelResizeWrapperSource, 'disableTopEdgeResize?: boolean')
    expectCompactSourceToContain(compactPanelResizeWrapperSource, 'disableTopEdgeResize = false')
    expectCompactSourceToContain(compactResizeHandleSource, "onResizeStart?: (position: ResizeHandlePosition) => void")
    expectCompactSourceToContain(compactResizeHandleSource, "onResizeStart?.(position)")
    expectCompactSourceToContain(compactResizeHandleSource, "export interface ResizeHandleCommitMeta")
    expectCompactSourceToContain(compactResizeHandleSource, "source:'pointer'|'keyboard'")
    expectCompactSourceToContain(compactResizeHandleSource, "startingSize?:{width:number;height:number}")
    expectCompactSourceToContain(compactResizeHandleSource, "onResetSize?: (meta?: ResizeHandleCommitMeta) => void | Promise<void>")
    expectCompactSourceToContain(compactResizeHandleSource, "onResizeEnd?:(size:{width:number;height:number},meta?:ResizeHandleCommitMeta)=>void|Promise<void>")
    expectCompactSourceToContain(compactResizeHandleSource, "onDoubleClick={onResetSize ? handleDoubleClick : undefined}")
    expectCompactSourceToContain(compactResizeHandleSource, "await onResetSize?.({source:'keyboard',position,startingSize})")
    expectCompactSourceToContain(compactResizeHandleSource, "await onResizeEnd({")
    expectCompactSourceToContain(compactResizeHandleSource, "source:'keyboard',position,startingSize")
    expectCompactSourceToContain(compactPanelResizeWrapperSource, 'const PANEL_TILING_HINT_DEADBAND_PX = 12')
    expectCompactSourceToContain(compactPanelResizeWrapperSource, 'const PANEL_POINTER_TILING_HINT_TIMEOUT_MS = 1200')
    expectCompactSourceToContain(compactPanelResizeWrapperSource, 'const PANEL_KEYBOARD_TILING_HINT_TIMEOUT_MS = 1800')
    expectCompactSourceToContain(compactPanelResizeWrapperSource, 'const AGENT_PANEL_DEFAULT_WIDTH = 600')
    expectCompactSourceToContain(compactPanelResizeWrapperSource, 'const PANEL_TILE_PRESSURE_WIDTH = AGENT_PANEL_DEFAULT_WIDTH + 64')
    expectCompactSourceToContain(compactPanelResizeWrapperSource, 'const isWidthAffectingResizeHandle = (position: ResizeHandlePosition | null) =>')
    expectCompactSourceToContain(compactPanelResizeWrapperSource, 'function getPanelTilePressureWidth(panelWidth: number): number {')
    expectCompactSourceToContain(compactPanelResizeWrapperSource, 'function getPanelTilePressureDetail(panelWidth: number): string | null {')
    expectCompactSourceToContain(compactPanelResizeWrapperSource, 'function getPanelTilePressureBadgeLabel(')
    expectCompactSourceToContain(compactPanelResizeWrapperSource, 'function getPanelTilePressureWidthDeltaBadgeLabel(pressureWidth: number): string | null {')
    expectCompactSourceToContain(compactPanelResizeWrapperSource, 'return `Need ~${pressureWidth}px narrower`')
    expectCompactSourceToContain(compactPanelResizeWrapperSource, 'function getPanelTileComfortHeadroomBadgeLabel(remainingComfortWidth: number): string | null {')
    expectCompactSourceToContain(compactPanelResizeWrapperSource, 'return `~${remainingComfortWidth}px left`')
    expectCompactSourceToContain(compactPanelResizeWrapperSource, 'function getPanelTilingWidthDeltaDetail(panelWidth: number): string {')
    expectCompactSourceToContain(compactPanelResizeWrapperSource, 'function getPanelWidthBadgeLabel(panelWidth: number): string {')
    expectCompactSourceToContain(compactPanelResizeWrapperSource, 'function getPanelTilingMetricBadge(')
    expectCompactSourceToContain(compactPanelResizeWrapperSource, 'function getPanelTileComfortWidthLabel(): string {')
    expectCompactSourceToContain(compactPanelResizeWrapperSource, 'return `${PANEL_TILE_PRESSURE_WIDTH}px`')
    expectCompactSourceToContain(compactPanelResizeWrapperSource, 'const panelTilePressureWidth = getPanelTilePressureWidth(panelWidth)')
    expectCompactSourceToContain(compactPanelResizeWrapperSource, '`${panelTilePressureWidth}px past tile comfort`')
    expectCompactSourceToContain(compactPanelResizeWrapperSource, 'return options?.compact ? `+${pressureWidth}px` : `${pressureWidth}px over`')
    expectCompactSourceToContain(compactPanelResizeWrapperSource, 'return `${Math.round(panelWidth)}px wide`')
    expectCompactSourceToContain(compactPanelResizeWrapperSource, 'label: getPanelTilePressureWidthDeltaBadgeLabel(panelTilePressureWidth) ?? "At tile comfort limit"')
    expectCompactSourceToContain(compactPanelResizeWrapperSource, 'label: "At tile comfort limit"')
    expectCompactSourceToContain(compactPanelResizeWrapperSource, 'label: getPanelTileComfortHeadroomBadgeLabel(remainingComfortWidth) ?? "At tile comfort limit"')
    expectCompactSourceToContain(compactPanelResizeWrapperSource, 'return `Need ~${panelTilePressureWidth}px narrower for Compare/Grid comfort`')
    expectCompactSourceToContain(compactPanelResizeWrapperSource, 'return `At the ${panelTileComfortWidthLabel} Compare/Grid comfort limit`')
    expectCompactSourceToContain(compactPanelResizeWrapperSource, 'return `~${remainingComfortWidth}px left before Compare/Grid gets tight`')
    expectCompactSourceToContain(compactPanelResizeWrapperSource, 'function getPanelTilingHint({')
    expectCompactSourceToContain(compactPanelResizeWrapperSource, 'const isPanelLikelyCrowdingTiles = panelWidth >= PANEL_TILE_PRESSURE_WIDTH')
    expectCompactSourceToContain(compactPanelResizeWrapperSource, 'const panelTilingWidthDeltaDetail = getPanelTilingWidthDeltaDetail(panelWidth)')
    expectCompactSourceToContain(compactPanelResizeWrapperSource, 'const showPanelTilingHint = enableResize && isWidthAffectingResizeHandle(activeResizePosition)')
    expectCompactSourceToContain(compactPanelResizeWrapperSource, 'const [isResizeGestureActive, setIsResizeGestureActive] = useState(false)')
    expectCompactSourceToContain(compactPanelResizeWrapperSource, 'setIsResizeGestureActive(true)')
    expectCompactSourceToContain(compactPanelResizeWrapperSource, 'setIsResizeGestureActive(false)')
    expectCompactSourceToContain(compactPanelResizeWrapperSource, 'const showPersistentPanelRecovery = enableResize && !isResizeGestureActive && currentSize.width >= PANEL_TILE_PRESSURE_WIDTH')
    expectCompactSourceToContain(compactPanelResizeWrapperSource, 'const panelTilingHint = getPanelTilingHint({')
    expectCompactSourceToContain(compactPanelResizeWrapperSource, 'const panelTilingHintResetInstruction =')
    expectCompactSourceToContain(compactPanelResizeWrapperSource, 'const panelTileComfortWidthLabel = getPanelTileComfortWidthLabel()')
    expectCompactSourceToContain(compactPanelResizeWrapperSource, 'const panelTilePressureDetail = getPanelTilePressureDetail(currentSize.width)')
    expectCompactSourceToContain(compactPanelResizeWrapperSource, 'const panelWidthBadgeLabel = getPanelWidthBadgeLabel(currentSize.width)')
    expectCompactSourceToContain(compactPanelResizeWrapperSource, 'const panelTilingMetricBadge = getPanelTilingMetricBadge(currentSize.width)')
    expectCompactSourceToContain(compactPanelResizeWrapperSource, 'const panelTilePressureWidth = getPanelTilePressureWidth(currentSize.width)')
    expectCompactSourceToContain(compactPanelResizeWrapperSource, 'const persistentPanelRecoveryPressureLabel = getPanelTilePressureBadgeLabel(')
    expectCompactSourceToContain(compactPanelResizeWrapperSource, 'panelTilePressureWidth')
    expectCompactSourceToContain(compactPanelResizeWrapperSource, 'compact: true')
    expectCompactSourceToContain(compactPanelResizeWrapperSource, 'const [activePanelRecoveryAction, setActivePanelRecoveryAction] = useState<"reset" | "hide" | null>(null)')
    expectCompactSourceToContain(compactPanelResizeWrapperSource, 'if (!enableResize || activePanelRecoveryAction) return')
    expectCompactSourceToContain(compactPanelResizeWrapperSource, 'setActivePanelRecoveryAction("reset")')
    expectCompactSourceToContain(compactPanelResizeWrapperSource, 'setActivePanelRecoveryAction(null)')
    expectCompactSourceToContain(compactPanelResizeWrapperSource, 'const showPersistentPanelHideRecovery = showPersistentPanelRecovery && panelTilePressureWidth >= PANEL_TILING_HINT_DEADBAND_PX')
    expectCompactSourceToContain(compactPanelResizeWrapperSource, 'const persistentPanelRecoveryTitle = !panelTilePressureDetail')
    expectCompactSourceToContain(compactPanelResizeWrapperSource, '`Panel is at the tiled-session comfort threshold (${panelTileComfortWidthLabel}). Reset to the default size for the current mode to recover room for tiled sessions.`')
    expectCompactSourceToContain(compactPanelResizeWrapperSource, '`Panel is currently ${panelTilePressureDetail}. Aim for about ${panelTileComfortWidthLabel} wide or narrower, or reset to the default size for the current mode to recover room for tiled sessions.`')
    expectCompactSourceToContain(compactPanelResizeWrapperSource, 'const persistentPanelHideTitle = !panelTilePressureDetail')
    expectCompactSourceToContain(compactPanelResizeWrapperSource, '"Hide the floating panel to immediately give tiled sessions their room back. Sessions continue in the background and you can reopen the panel later."')
    expectCompactSourceToContain(compactPanelResizeWrapperSource, '`Hide the floating panel to immediately recover the ${panelTilePressureDetail} currently being taken from tiled sessions. Sessions continue in the background and you can reopen the panel later.`')
    expectCompactSourceToContain(compactPanelResizeWrapperSource, 'const tilingHintTimeoutRef = useRef<ReturnType<typeof window.setTimeout> | null>(null)')
    expectCompactSourceToContain(compactPanelResizeWrapperSource, 'const clearPendingTilingHint = useCallback(() => {')
    expectCompactSourceToContain(compactPanelResizeWrapperSource, 'function getPanelTilingHint({')
    expectCompactSourceToContain(compactPanelResizeWrapperSource, 'const settlePanelTilingHint = useCallback((meta?: ResizeHandleCommitMeta) => {')
    expectCompactSourceToContain(compactPanelResizeWrapperSource, 'const shouldKeepPanelTilingHintVisible =')
    expectCompactSourceToContain(compactPanelResizeWrapperSource, 'isWidthAffectingResizeHandle(meta.position)')
    expectCompactSourceToContain(compactPanelResizeWrapperSource, 'meta.source === "keyboard"')
    expectCompactSourceToContain(compactPanelResizeWrapperSource, ': PANEL_POINTER_TILING_HINT_TIMEOUT_MS')
    expectCompactSourceToContain(compactPanelResizeWrapperSource, 'tilingHintTimeoutRef.current = window.setTimeout(() => {')
    expectCompactSourceToContain(compactPanelResizeWrapperSource, '}, hintTimeoutMs)')
    expectCompactSourceToContain(compactPanelResizeWrapperSource, 'settlePanelTilingHint(meta)')
    expectCompactSourceToContain(compactPanelResizeWrapperSource, 'const settledHintMeta =')
    expectCompactSourceToContain(compactPanelResizeWrapperSource, 'meta && !meta.startingSize && isWidthAffectingResizeHandle(meta.position)')
    expectCompactSourceToContain(compactPanelResizeWrapperSource, 'startingSize: currentSize')
    expectCompactSourceToContain(compactPanelResizeWrapperSource, 'settlePanelTilingHint(settledHintMeta)')
    expectCompactSourceToContain(compactPanelResizeWrapperSource, 'Wide panel is crowding Compare/Grid')
    expectCompactSourceToContain(compactPanelResizeWrapperSource, 'Compare/Grid still tight')
    expectCompactSourceToContain(compactPanelResizeWrapperSource, 'Less room for tiled sessions')
    expectCompactSourceToContain(compactPanelResizeWrapperSource, 'More room for tiled sessions')
    expectCompactSourceToContain(compactPanelResizeWrapperSource, 'past tile comfort')
    expectCompactSourceToContain(compactPanelResizeWrapperSource, 'Panel width affects tiled session space')
    expectCompactSourceToContain(compactPanelResizeWrapperSource, 'detail: `${panelTilingWidthDeltaDetail} · ${roundedPanelWidth}px wide`')
    expectCompactSourceToContain(compactPanelResizeWrapperSource, 'const handleResetPanelSize = useCallback(async (meta?: ResizeHandleCommitMeta) => {')
    expectCompactSourceToContain(compactPanelResizeWrapperSource, 'const resetSize = await tipcClient.resetPanelSizeForCurrentMode({})')
    expectCompactSourceToContain(compactPanelResizeWrapperSource, 'const handleHidePanel = useCallback(async () => {')
    expectCompactSourceToContain(compactPanelResizeWrapperSource, 'await tipcClient.hidePanelWindow({})')
    expectCompactSourceToContain(compactPanelResizeWrapperSource, 'Failed to hide panel while recovering tiled-session space:')
    expectCompactSourceToContain(compactPanelResizeWrapperSource, '{panelTilingHintResetInstruction}')
    expectCompactSourceToContain(compactPanelResizeWrapperSource, 'Enter / double-click resets to default size')
    expectCompactSourceToContain(compactPanelResizeWrapperSource, 'Still tight? Reset panel or Enter / double-click')
    expectCompactSourceToContain(compactPanelResizeWrapperSource, 'Still tight? Reset panel, hide panel, or Enter / double-click')
    expectCompactSourceToContain(compactPanelResizeWrapperSource, 'onResetSize={handleResetPanelSize}')
    expectCompactSourceToContain(compactPanelResizeWrapperSource, 'data-panel-resize-impact-hint')
    expectCompactSourceToContain(compactPanelResizeWrapperSource, 'data-panel-resize-impact-metrics')
    expectCompactSourceToContain(compactPanelResizeWrapperSource, 'data-panel-recovery-actions')
    expectCompactSourceToContain(compactPanelResizeWrapperSource, 'data-panel-hide-recovery')
    expectCompactSourceToContain(compactPanelResizeWrapperSource, 'data-panel-size-recovery')
    expectCompactSourceToContain(compactPanelResizeWrapperSource, 'data-panel-size-recovery-badge')
    expectCompactSourceToContain(compactPanelResizeWrapperSource, 'activePanelRecoveryAction === "hide" ? "Hiding..." : "Hide panel"')
    expectCompactSourceToContain(compactPanelResizeWrapperSource, 'activePanelRecoveryAction === "reset" ? "Resetting..." : "Reset panel"')
    expectCompactSourceToContain(compactPanelResizeWrapperSource, 'Reset panel')
    expectCompactSourceToContain(compactPanelResizeWrapperSource, 'showPanelTilingHint ? "top-14" : "top-1"')
    expectCompactSourceToContain(compactPanelResizeWrapperSource, '{persistentPanelRecoveryPressureLabel ? (')
    expectCompactSourceToContain(compactPanelResizeWrapperSource, '{persistentPanelRecoveryPressureLabel}')
    expectCompactSourceToContain(compactPanelResizeWrapperSource, 'rounded-full border border-current/15 bg-background/80 px-1.5 py-0.5 text-[10px] font-medium leading-none whitespace-nowrap')
    expectCompactSourceToContain(compactPanelResizeWrapperSource, 'style={{ WebkitAppRegion: "no-drag" } as React.CSSProperties}')
    expectCompactSourceToContain(compactPanelResizeWrapperSource, '{panelTilingHint.label}')
    expectCompactSourceToContain(compactPanelResizeWrapperSource, '{panelTilingHint.detail}')
    expectCompactSourceToContain(compactPanelResizeWrapperSource, '{panelWidthBadgeLabel}')
    expectCompactSourceToContain(compactPanelResizeWrapperSource, '{panelTilingMetricBadge.label}')
    expectCompactSourceToContain(compactPanelResizeWrapperSource, 'panelTilingMetricBadge.tone === "crowded"')
    expectCompactSourceToContain(compactPanelResizeWrapperSource, 'panelTilingMetricBadge.tone === "relief"')
    expectCompactSourceToContain(compactPanelResizeWrapperSource, '{!disableTopEdgeResize ? (')
    expectCompactSourceToContain(compactPanelResizeWrapperSource, 'position="top"')
    expectCompactSourceToContain(compactPanelResizeWrapperSource, 'className={cn("relative", className)}')
  })
})