import { readFileSync } from "node:fs"
import { describe, expect, it } from "vitest"

const panelResizeWrapperSource = readFileSync(new URL("./panel-resize-wrapper.tsx", import.meta.url), "utf8")
const resizeHandleSource = readFileSync(new URL("./resize-handle.tsx", import.meta.url), "utf8")

describe("panel resize affordances", () => {
  it("adds visible panel-edge and corner cues so resizing is discoverable before drag begins", () => {
    expect(panelResizeWrapperSource).toContain('className={cn("group/panel-resize relative", className)}')
    expect(panelResizeWrapperSource).toContain('const panelResizeRailClassName = ({')
    expect(panelResizeWrapperSource).toContain('const highlightLeftRail = isLeftResizeHandle(highlightedResizeHandle)')
    expect(panelResizeWrapperSource).toContain('"left-0 top-6 bottom-8 w-1"')
    expect(panelResizeWrapperSource).toContain('group-hover/panel-resize:bg-blue-500/35')
    expect(panelResizeWrapperSource).toContain('const panelResizeCornerClassName = cn(')
    expect(panelResizeWrapperSource).toContain('getPanelResizeHintPositionClassName(highlightedResizeHandle)')
    expect(panelResizeWrapperSource).toContain('getPanelResizeHintLabel(highlightedResizeHandle)')
    expect(panelResizeWrapperSource).toContain('currentSize.width')
    expect(panelResizeWrapperSource).toContain('currentSize.height')
  })

  it("shows live width and height delta badges while the panel is actively being resized", () => {
    expect(panelResizeWrapperSource).toContain('const COMPACT_ACTIVE_PANEL_RESIZE_HINT_WIDTH = 360')
    expect(panelResizeWrapperSource).toContain('function formatPanelResizeDelta(delta: number): string {')
    expect(panelResizeWrapperSource).toContain('return `${delta > 0 ? "+" : ""}${delta}px`')
    expect(panelResizeWrapperSource).toContain('function getPanelResizeAxisDeltaLabel({')
    expect(panelResizeWrapperSource).toContain('axis: "Width" | "Height"')
    expect(panelResizeWrapperSource).toContain('compact = false')
    expect(panelResizeWrapperSource).toContain('const axisLabel = compact ? axis.charAt(0) : axis')
    expect(panelResizeWrapperSource).toContain('return `${axisLabel} ${formatPanelResizeDelta(delta)}`')
    expect(panelResizeWrapperSource).toContain('const useCompactActiveResizeHintCopy =')
    expect(panelResizeWrapperSource).toContain('isResizeActive && currentSize.width < COMPACT_ACTIVE_PANEL_RESIZE_HINT_WIDTH')
    expect(panelResizeWrapperSource).toContain('const activeResizeStartSize = isResizeActive ? resizeStartSizeRef.current : null')
    expect(panelResizeWrapperSource).toContain('const activePanelWidthDeltaLabel =')
    expect(panelResizeWrapperSource).toContain('isWidthResizeHandle(activeResizeHandle)')
    expect(panelResizeWrapperSource).toContain('delta: Math.round(currentSize.width - activeResizeStartSize.width)')
    expect(panelResizeWrapperSource).toContain('compact: useCompactActiveResizeHintCopy')
    expect(panelResizeWrapperSource).toContain('const activePanelHeightDeltaLabel =')
    expect(panelResizeWrapperSource).toContain('isHeightResizeHandle(activeResizeHandle)')
    expect(panelResizeWrapperSource).toContain('delta: Math.round(currentSize.height - activeResizeStartSize.height)')
    expect(panelResizeWrapperSource).toContain('{activePanelWidthDeltaLabel && (')
    expect(panelResizeWrapperSource).toContain('{activePanelHeightDeltaLabel && (')
    expect(panelResizeWrapperSource).toContain('useCompactActiveResizeHintCopy')
    expect(panelResizeWrapperSource).toContain('? `${currentSize.width}×${currentSize.height}`')
    expect(panelResizeWrapperSource).toContain(': `${currentSize.width} × ${currentSize.height}`')
    expect(panelResizeWrapperSource).toContain('{activePanelWidthDeltaLabel}')
    expect(panelResizeWrapperSource).toContain('{activePanelHeightDeltaLabel}')
  })

  it("keeps the content-facing panel edge visibly recoverable after the panel has been widened", () => {
    expect(panelResizeWrapperSource).toContain('const PANEL_WIDTH_RECOVERY_REMINDER_THRESHOLD = 56')
    expect(panelResizeWrapperSource).toContain('const PANEL_WIDTH_RECOVERY_BADGE_CLASS_NAME =')
    expect(panelResizeWrapperSource).toContain('const restingWidthRecoveryAmount = Math.max(')
    expect(panelResizeWrapperSource).toContain('const showRestingWidthRecoveryHint =')
    expect(panelResizeWrapperSource).toContain('currentSize.width > minWidth + PANEL_WIDTH_RECOVERY_REMINDER_THRESHOLD')
    expect(panelResizeWrapperSource).toContain('const restingWidthRecoveryAmountLabel =')
    expect(panelResizeWrapperSource).toContain('showRestingWidthRecoveryHint && restingWidthRecoveryAmount > 0')
    expect(panelResizeWrapperSource).toContain('`-${restingWidthRecoveryAmount}px`')
    expect(panelResizeWrapperSource).toContain('showRecoveryReminder: showRestingWidthRecoveryHint')
    expect(panelResizeWrapperSource).toContain('"bg-blue-500/45 opacity-90"')
    expect(panelResizeWrapperSource).toContain('absolute -left-1 top-1/2 z-[960] flex -translate-y-1/2 cursor-ew-resize items-center gap-1 rounded-r-full border border-l-0 border-blue-500/25')
    expect(panelResizeWrapperSource).toContain('<ChevronsLeft className="h-3 w-3 shrink-0" />')
    expect(panelResizeWrapperSource).toContain('<span className="whitespace-nowrap">Shrink width</span>')
    expect(panelResizeWrapperSource).toContain('{restingWidthRecoveryAmountLabel && (')
    expect(panelResizeWrapperSource).toContain('className={PANEL_WIDTH_RECOVERY_BADGE_CLASS_NAME}')
    expect(panelResizeWrapperSource).toContain('{restingWidthRecoveryAmountLabel}')
  })

  it("makes the resting width-recovery tab act like a normal single-click control instead of a visual-only hint", () => {
    expect(panelResizeWrapperSource).toContain('const RESTING_WIDTH_RECOVERY_HINT_DRAG_THRESHOLD = 4')
    expect(panelResizeWrapperSource).toContain('const RESTING_WIDTH_RECOVERY_HINT_TITLE =')
    expect(panelResizeWrapperSource).toContain('"Click to shrink width. Drag this tab to resize panel width."')
    expect(panelResizeWrapperSource).toContain('const restingWidthRecoveryHintTitle =')
    expect(panelResizeWrapperSource).toContain('`Click to shrink width by about ${restingWidthRecoveryAmount}px. Drag this tab to resize panel width.`')
    expect(panelResizeWrapperSource).toContain(': RESTING_WIDTH_RECOVERY_HINT_TITLE')
    expect(panelResizeWrapperSource).toContain('const handleRestingWidthRecoveryHintAction = useCallback(async () => {')
    expect(panelResizeWrapperSource).toContain('const handleRestingWidthRecoveryHintPointerDown = useCallback((event: React.MouseEvent<HTMLButtonElement>) => {')
    expect(panelResizeWrapperSource).toContain('const restingWidthRecoveryGestureRef = useRef<{')
    expect(panelResizeWrapperSource).toContain('const restingWidthRecoveryDragConsumedClickRef = useRef(false)')
    expect(panelResizeWrapperSource).toContain('restingWidthRecoveryGestureRef.current = {')
    expect(panelResizeWrapperSource).toContain('handleResizeStart("left", gesture.startSize)')
    expect(panelResizeWrapperSource).toContain('handleResize({ width: -deltaX, height: 0 })')
    expect(panelResizeWrapperSource).toContain('void handleResizeEnd({')
    expect(panelResizeWrapperSource).toContain('window.setTimeout(() => {')
    expect(panelResizeWrapperSource).toContain('await handleCompactResize("left")')
    expect(panelResizeWrapperSource).toContain('type="button"')
    expect(panelResizeWrapperSource).toContain('title={restingWidthRecoveryHintTitle}')
    expect(panelResizeWrapperSource).toContain('aria-label="Shrink panel width"')
    expect(panelResizeWrapperSource).toContain('className="absolute -left-1 top-1/2 z-[960] flex -translate-y-1/2 cursor-ew-resize')
    expect(panelResizeWrapperSource).toContain('onMouseDown={handleRestingWidthRecoveryHintPointerDown}')
    expect(panelResizeWrapperSource).toContain('onClick={handleRestingWidthRecoveryHintClick}')
    expect(panelResizeWrapperSource).toContain('onMouseEnter={() => setHoveredResizeHandle("left")}')
    expect(panelResizeWrapperSource).toContain('onMouseLeave={() => setHoveredResizeHandle(null)}')
    expect(panelResizeWrapperSource).toContain('onFocus={() => setHoveredResizeHandle("left")}')
    expect(panelResizeWrapperSource).toContain('onBlur={() => setHoveredResizeHandle(null)}')
    expect(panelResizeWrapperSource).toContain('void handleRestingWidthRecoveryHintAction()')
    expect(panelResizeWrapperSource).toContain('onKeyDown={(event) => {')
    expect(panelResizeWrapperSource).toContain('if (event.key !== "Enter" && event.key !== " ") return')
  })

  it("explains when resize gestures are being clamped by the panel minimum size", () => {
    expect(panelResizeWrapperSource).toContain('function getPanelResizeConstraintLabel({')
    expect(panelResizeWrapperSource).toContain('compact = false')
    expect(panelResizeWrapperSource).toContain('const isWidthResizeConstrained =')
    expect(panelResizeWrapperSource).toContain('const isHeightResizeConstrained =')
    expect(panelResizeWrapperSource).toContain('currentSize.width <= minWidth + 0.5')
    expect(panelResizeWrapperSource).toContain('currentSize.height <= minHeight + 0.5')
    expect(panelResizeWrapperSource).toContain('return compact ? "Min width" : "Minimum width reached"')
    expect(panelResizeWrapperSource).toContain('return compact ? "Min height" : "Minimum height reached"')
    expect(panelResizeWrapperSource).toContain('return compact ? "Min size" : "Minimum size reached"')
    expect(panelResizeWrapperSource).toContain('compact: useCompactActiveResizeHintCopy')
    expect(panelResizeWrapperSource).toContain('rounded-full bg-amber-500/10 px-1.5 py-0.5 text-[9px] font-semibold uppercase tracking-[0.08em] text-amber-700 dark:text-amber-300')
    expect(panelResizeWrapperSource).toContain('{panelResizeConstraintLabel}')
  })

  it("lets the same resize handles quickly compact the panel back toward its minimum footprint", () => {
    expect(panelResizeWrapperSource).toContain('function getPanelResizeCompactHintLabel(position: ResizeHandlePosition | null): string | null {')
    expect(panelResizeWrapperSource).toContain('return "Double-click to shrink width"')
    expect(panelResizeWrapperSource).toContain('return "Double-click to shrink height"')
    expect(panelResizeWrapperSource).toContain('return "Double-click to shrink panel"')
    expect(panelResizeWrapperSource).toContain('function getPanelResizeCompactSize({')
    expect(panelResizeWrapperSource).toContain('width: isWidthResizeHandle(position) ? minWidth : currentSize.width')
    expect(panelResizeWrapperSource).toContain('height: isHeightResizeHandle(position) ? minHeight : currentSize.height')
    expect(panelResizeWrapperSource).toContain('const handleCompactResize = useCallback(async (position: ResizeHandlePosition) => {')
    expect(panelResizeWrapperSource).toContain('const panelResizeCompactHintLabel =')
    expect(panelResizeWrapperSource).toContain('{panelResizeCompactHintLabel}')
    expect(panelResizeWrapperSource).toContain('onDoubleClick={handleCompactResize}')
    expect(resizeHandleSource).toContain('onDoubleClick?: (position: ResizeHandlePosition) => void')
    expect(resizeHandleSource).toContain('onDoubleClick={(e) => {')
    expect(resizeHandleSource).toContain('onDoubleClick?.(position)')
  })

  it("echoes the shrink-to-min width delta in ordinary left and right handle hover hints", () => {
    expect(panelResizeWrapperSource).toContain('const showPanelWidthCompactAmountLabel =')
    expect(panelResizeWrapperSource).toContain('(highlightedResizeHandle === "left" || highlightedResizeHandle === "right") &&')
    expect(panelResizeWrapperSource).toContain('restingWidthRecoveryAmount > 0')
    expect(panelResizeWrapperSource).toContain('const panelWidthCompactAmountLabel = showPanelWidthCompactAmountLabel')
    expect(panelResizeWrapperSource).toContain('? `-${restingWidthRecoveryAmount}px`')
    expect(panelResizeWrapperSource).toContain('{panelWidthCompactAmountLabel && (')
    expect(panelResizeWrapperSource).toContain('className={PANEL_WIDTH_RECOVERY_BADGE_CLASS_NAME}')
    expect(panelResizeWrapperSource).toContain('{panelWidthCompactAmountLabel}')
  })

  it("passes the active resize edge through to the main process so manual panel resizing preserves the content-facing anchor", () => {
    expect(panelResizeWrapperSource).toContain('const activeResizeHandleRef = useRef<ResizeHandlePosition | null>(null)')
    expect(panelResizeWrapperSource).toContain('activeResizeHandleRef.current = position')
    expect(panelResizeWrapperSource).toContain('resizeAnchor: activeResizeHandleRef.current')
    expect(panelResizeWrapperSource).toContain('const resizeAnchor = activeResizeHandleRef.current')
    expect(panelResizeWrapperSource).toContain('await persistPanelSize(requestedFinalSize, resizeAnchor)')
    expect(panelResizeWrapperSource).toContain('await persistPanelSize(compactSize, position)')
  })

  it("anchors the width-recovery reminder to the sessions-facing edge instead of covering panel content", () => {
    expect(panelResizeWrapperSource).toContain('const showRestingWidthRecoveryHint =')
    expect(panelResizeWrapperSource).toContain('!isResizeActive &&')
    expect(panelResizeWrapperSource).toContain('(!highlightedResizeHandle || highlightedResizeHandle === "left") &&')
    expect(panelResizeWrapperSource).toContain('showRecoveryReminder: showRestingWidthRecoveryHint')
    expect(panelResizeWrapperSource).toContain('{showRestingWidthRecoveryHint && (')
    expect(panelResizeWrapperSource).toContain('absolute -left-1 top-1/2 z-[960] flex -translate-y-1/2 cursor-ew-resize items-center gap-1 rounded-r-full border border-l-0 border-blue-500/25 bg-background/95 pl-2 pr-2 py-1 text-[10px] font-medium text-blue-700 shadow-sm backdrop-blur-sm transition-colors duration-200 hover:bg-background focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-blue-500/40 dark:text-blue-300')
    expect(panelResizeWrapperSource).toContain('<ChevronsLeft className="h-3 w-3 shrink-0" />')
    expect(panelResizeWrapperSource).toContain('<span className="whitespace-nowrap">Shrink width</span>')
  })

  it("keeps the width-recovery tab visible while its own left edge is highlighted", () => {
    expect(panelResizeWrapperSource).toContain('const highlightedResizeHandle = activeResizeHandle ?? hoveredResizeHandle')
    expect(panelResizeWrapperSource).toContain('const highlightLeftRail = isLeftResizeHandle(highlightedResizeHandle)')
    expect(panelResizeWrapperSource).toContain('(!highlightedResizeHandle || highlightedResizeHandle === "left") &&')
    expect(panelResizeWrapperSource).toContain('onMouseEnter={() => setHoveredResizeHandle("left")}')
    expect(panelResizeWrapperSource).toContain('onFocus={() => setHoveredResizeHandle("left")}')
  })

  it("keeps explicit panel resize labels on the live hit targets", () => {
    expect(panelResizeWrapperSource).toContain('function getPanelResizeHandleTitle(')
    expect(panelResizeWrapperSource).toContain('widthRecoveryAmount = 0')
    expect(panelResizeWrapperSource).toContain('widthRecoveryAmount > 0')
    expect(panelResizeWrapperSource).toContain('`Drag to resize panel width. Double-click to shrink width by about ${widthRecoveryAmount}px.`')
    expect(panelResizeWrapperSource).toContain('return "Drag to resize panel width and height. Double-click to shrink panel."')
    expect(panelResizeWrapperSource).toContain(': "Drag to resize panel width. Double-click to shrink width."')
    expect(panelResizeWrapperSource).toContain('return "Drag to resize panel height. Double-click to shrink height."')
    expect(panelResizeWrapperSource).toContain('title={getPanelResizeHandleTitle("bottom-right")}')
    expect(panelResizeWrapperSource).toContain('ariaLabel="Resize panel width and height"')
    expect(panelResizeWrapperSource).toContain('title={getPanelResizeHandleTitle("right", restingWidthRecoveryAmount)}')
    expect(panelResizeWrapperSource).toContain('ariaLabel="Resize panel width"')
    expect(panelResizeWrapperSource).toContain('title={getPanelResizeHandleTitle("left", restingWidthRecoveryAmount)}')
    expect(panelResizeWrapperSource).toContain('title={getPanelResizeHandleTitle("bottom")}')
    expect(panelResizeWrapperSource).toContain('ariaLabel="Resize panel height"')
    expect(panelResizeWrapperSource).toContain('onHoverChange={setHoveredResizeHandle}')
    expect(resizeHandleSource).toContain('export type ResizeHandlePosition =')
    expect(resizeHandleSource).toContain('title?: string')
    expect(resizeHandleSource).toContain('ariaLabel?: string')
    expect(resizeHandleSource).toContain('onHoverChange?: (position: ResizeHandlePosition | null) => void')
    expect(resizeHandleSource).toContain('onDoubleClick?: (position: ResizeHandlePosition) => void')
    expect(resizeHandleSource).toContain('onResizeStart?: (position: ResizeHandlePosition) => void')
    expect(resizeHandleSource).toContain('title={title}')
    expect(resizeHandleSource).toContain('aria-label={ariaLabel}')
    expect(resizeHandleSource).toContain('return "w-full h-3"')
    expect(resizeHandleSource).toContain('return "w-3 h-full"')
  })
})

