import { readFileSync } from "node:fs"
import { describe, expect, it } from "vitest"

const sessionGridSource = readFileSync(new URL("./session-grid.tsx", import.meta.url), "utf8")

describe("session grid responsive reflow", () => {
  it("preserves user-adjusted width on ordinary width changes while still clamping out-of-bounds widths and only retargeting height when a width breakpoint catches a layout-driven tile", () => {
    expect(sessionGridSource).toContain("Responsive width reflow")
    expect(sessionGridSource).toContain('export function getResponsiveTileWidthOnContainerWidthChange(')
    expect(sessionGridSource).toContain('export function shouldRetargetTileHeightOnContainerWidthChange(')
    expect(sessionGridSource).toContain('const prevTargetWidth = calculateTileWidth(prevWidth, gap, layoutMode, sessionCount)')
    expect(sessionGridSource).toContain('const prevTargetHeight = calculateTileHeight(')
    expect(sessionGridSource).toContain('const nextResponsiveWidth = getResponsiveTileWidthOnContainerWidthChange(')
    expect(sessionGridSource).toContain('width,')
    expect(sessionGridSource).toContain('prevTargetWidth,')
    expect(sessionGridSource).toContain('targetTileWidth,')
    expect(sessionGridSource).toContain('minWidth,')
    expect(sessionGridSource).toContain('maxWidth,')
    expect(sessionGridSource).toContain('const shouldRetargetHeight =')
    expect(sessionGridSource).toContain('shouldRetargetTileHeightOnContainerWidthChange(')
    expect(sessionGridSource).toContain('height,')
    expect(sessionGridSource).toContain('if (nextResponsiveWidth === null && !shouldRetargetHeight) {')
    expect(sessionGridSource).toContain('...(nextResponsiveWidth !== null')
    expect(sessionGridSource).toContain('? { width: nextResponsiveWidth }')
    expect(sessionGridSource).toContain('? { height: targetTileHeight }')
  })

  it("retargets lone-visible fallback width immediately while only retargeting height when the tile still follows the prior layout-driven height", () => {
    expect(sessionGridSource).toContain('const isSingleVisibleTileFallback = shouldUseSingleVisibleTileFallback(sessionCount)')
    expect(sessionGridSource).toContain('const lastSingleVisibleTileFallbackRef = useRef(isSingleVisibleTileFallback)')
    expect(sessionGridSource).toContain('const lastTargetTileHeightRef = useRef(targetTileHeight)')
    expect(sessionGridSource).toContain('if (lastSingleVisibleTileFallbackRef.current === isSingleVisibleTileFallback || containerWidth <= 0 || isResizing) {')
    expect(sessionGridSource).toContain('const previousTargetHeight = lastTargetTileHeightRef.current')
    expect(sessionGridSource).toContain('lastSingleVisibleTileFallbackRef.current = isSingleVisibleTileFallback')
    expect(sessionGridSource).toContain('export function shouldRetargetTileHeightOnSessionCountChange(')
    expect(sessionGridSource).toContain('const shouldRetargetHeight = shouldRetargetTileHeightOnSessionCountChange(')
    expect(sessionGridSource).toContain('width: targetTileWidth,')
    expect(sessionGridSource).toContain('...(shouldRetargetHeight ? { height: targetTileHeight } : {})')
  })

  it("retargets sparse wide-grid height only while the tile still follows the prior layout-driven height", () => {
    expect(sessionGridSource).toContain('function shouldUseSparseWideGridHeight(')
    expect(sessionGridSource).toContain('const isSparseWideGridLayout = shouldUseSparseWideGridHeight(')
    expect(sessionGridSource).toContain('const lastSparseWideGridLayoutRef = useRef(isSparseWideGridLayout)')
    expect(sessionGridSource).toContain('if (\n      lastSparseWideGridLayoutRef.current === isSparseWideGridLayout ||')
    expect(sessionGridSource).toContain('const previousTargetHeight = lastTargetTileHeightRef.current')
    expect(sessionGridSource).toContain('lastSparseWideGridLayoutRef.current = isSparseWideGridLayout')
    expect(sessionGridSource).toContain('const shouldRetargetHeight = shouldRetargetTileHeightOnSessionCountChange(')
    expect(sessionGridSource).toContain('if (shouldRetargetHeight) {')
    expect(sessionGridSource).toContain('setSize({ height: targetTileHeight })')
  })

  it("retargets layout-driven tile height when the container gets taller or shorter without clobbering manual height overrides", () => {
    expect(sessionGridSource).toContain('export function shouldRetargetTileHeightOnContainerHeightChange(')
    expect(sessionGridSource).toContain('const lastContainerHeightRef = useRef(containerHeight)')
    expect(sessionGridSource).toContain('const prevContainerHeight = lastContainerHeightRef.current')
    expect(sessionGridSource).toContain('Math.abs(containerHeight - prevContainerHeight) > 20')
    expect(sessionGridSource).toContain('const prevTargetHeight = calculateTileHeight(')
    expect(sessionGridSource).toContain('shouldRetargetTileHeightOnContainerHeightChange(')
    expect(sessionGridSource).toContain('height,')
    expect(sessionGridSource).toContain('prevTargetHeight,')
    expect(sessionGridSource).toContain('targetTileHeight,')
    expect(sessionGridSource).toContain('setSize({ height: targetTileHeight })')
  })

  it("preserves manual width and height when switching between compare and grid without changing the effective tile footprint", () => {
    expect(sessionGridSource).toContain('export function shouldPreserveTileWidthOnLayoutChange(')
    expect(sessionGridSource).toContain('export function shouldPreserveTileHeightOnLayoutChange(')
    expect(sessionGridSource).toContain('const shouldPreserveWidth = shouldPreserveTileWidthOnLayoutChange(')
    expect(sessionGridSource).toContain('const shouldPreserveHeight = shouldPreserveTileHeightOnLayoutChange(')
    expect(sessionGridSource).toContain(': shouldPreserveWidth')
    expect(sessionGridSource).toContain('? {}')
    expect(sessionGridSource).toContain(': { width: targetTileWidth })')
    expect(sessionGridSource).toContain('...(restoredHeightFromSingleView !== null')
    expect(sessionGridSource).toContain(': shouldPreserveHeight')
    expect(sessionGridSource).toContain(': { height: targetTileHeight })')
  })

  it("restores the previous multi-tile width when leaving Single view for a side-by-side layout", () => {
    expect(sessionGridSource).toContain('layoutRestoreWidth: number | null')
    expect(sessionGridSource).toContain('layoutRestoreHeight: number | null')
    expect(sessionGridSource).toContain('export function getSingleViewLayoutRestoreWidth(')
    expect(sessionGridSource).toContain('export function getSingleViewLayoutRestoreHeight(')
    expect(sessionGridSource).toContain('const restoredWidthFromSingleView =')
    expect(sessionGridSource).toContain('const restoredHeightFromSingleView =')
    expect(sessionGridSource).toContain('previousLayoutMode === "1x1"')
    expect(sessionGridSource).toContain('? getSingleViewLayoutRestoreWidth(')
    expect(sessionGridSource).toContain('targetTileHeight,')
    expect(sessionGridSource).toContain('? getSingleViewLayoutRestoreHeight(')
    expect(sessionGridSource).toContain('layoutRestoreHeight,')
    expect(sessionGridSource).toContain('targetTileHeight,')
    expect(sessionGridSource).toContain('targetTileWidth,')
    expect(sessionGridSource).toContain('maxWidth,')
    expect(sessionGridSource).toContain('isWidthResizeLocked,')
    expect(sessionGridSource).toContain('...(restoredWidthFromSingleView !== null')
    expect(sessionGridSource).toContain('{ width: restoredWidthFromSingleView }')
    expect(sessionGridSource).toContain('...(restoredHeightFromSingleView !== null')
    expect(sessionGridSource).toContain('{ height: restoredHeightFromSingleView }')
  })

  it("lets resize handles snap a tile back to the current layout size without a broader layout reset", () => {
    expect(sessionGridSource).toContain('export function getIdleTileResizeHintLabel(')
    expect(sessionGridSource).toContain('export function getTileResizeHandleTitle(')
    expect(sessionGridSource).toContain('const handleRestoreLayoutWidth = useCallback((e: React.MouseEvent) => {')
    expect(sessionGridSource).toContain('setSize({ width: targetTileWidth })')
    expect(sessionGridSource).toContain('const handleRestoreLayoutHeight = useCallback((e: React.MouseEvent) => {')
    expect(sessionGridSource).toContain('setSize({ height: targetTileHeight })')
    expect(sessionGridSource).toContain('const handleRestoreLayoutSize = useCallback((e: React.MouseEvent) => {')
    expect(sessionGridSource).toContain('setSize({ width: targetTileWidth, height: targetTileHeight })')
    expect(sessionGridSource).toContain('onDoubleClick={handleRestoreLayoutWidth}')
    expect(sessionGridSource).toContain('onDoubleClick={handleRestoreLayoutHeight}')
    expect(sessionGridSource).toContain('onDoubleClick={handleRestoreLayoutSize}')
    expect(sessionGridSource).toContain('title={getTileResizeHandleTitle("width", false)}')
    expect(sessionGridSource).toContain('title={getTileResizeHandleTitle("height", isWidthResizeLocked)}')
    expect(sessionGridSource).toContain('title={getTileResizeHandleTitle("corner", false)}')
  })

  it("briefly confirms height-only fit resets when width remains layout-locked", () => {
    expect(sessionGridSource).toContain('const RECENT_LOCKED_WIDTH_HEIGHT_RESTORE_CUE_DURATION_MS = 1_800')
    expect(sessionGridSource).toContain('export function getLockedWidthHeightRestoreCue(): {')
    expect(sessionGridSource).toContain('const [hasRecentLockedWidthHeightRestoreCue, setHasRecentLockedWidthHeightRestoreCue] = useState(false)')
    expect(sessionGridSource).toContain('const clearRecentLockedWidthHeightRestoreCue = useCallback(() => {')
    expect(sessionGridSource).toContain('const showRecentLockedWidthHeightRestoreCue = useCallback(() => {')
    expect(sessionGridSource).toContain('isWidthResizeLocked && Math.abs(height - targetTileHeight) > 0.5')
    expect(sessionGridSource).toContain('showRecentLockedWidthHeightRestoreCue()')
    expect(sessionGridSource).toContain('title={recentLockedWidthHeightRestoreCue.title}')
    expect(sessionGridSource).toContain('{recentLockedWidthHeightRestoreCue.badgeLabel}')
    expect(sessionGridSource).toContain('pointer-events-none absolute inset-x-3 bottom-6 z-20 flex justify-center')
  })

  it("promotes the tile reorder handle when stacked layouts no longer keep a separate header hint visible", () => {
    expect(sessionGridSource).toContain('export function shouldPromoteTileReorderHandle(')
    expect(sessionGridSource).toContain('const shouldPromoteReorderHandle = shouldPromoteTileReorderHandle(')
    expect(sessionGridSource).toContain('? "opacity-100 border-blue-500/25 bg-blue-500/5 text-blue-700 shadow-sm dark:text-blue-200"')
    expect(sessionGridSource).toContain('? "ml-0.5 max-w-12 opacity-100"')
    expect(sessionGridSource).toContain('? "Move"')
    expect(sessionGridSource).toContain('? "text-blue-600 dark:text-blue-300"')
  })
})