import { readFileSync } from "node:fs"
import { describe, expect, it } from "vitest"

const sessionGridSource = readFileSync(new URL("./session-grid.tsx", import.meta.url), "utf8")
const sessionsSource = readFileSync(new URL("../pages/sessions.tsx", import.meta.url), "utf8")

describe("session grid drag affordances", () => {
  it("keeps reorder discoverability visible when more than one session can be rearranged", () => {
    expect(sessionsSource).toContain('const showReorderHint =')
    expect(sessionsSource).toContain('canReorderTiles &&')
    expect(sessionsSource).toContain('const reorderHintLabel = isVeryCompactSessionHeader')
    expect(sessionsSource).toContain('const reorderHintTitle =')
    expect(sessionsSource).toContain('"Drag a session tile\'s reorder handle onto another tile to place it before that session, drag below the last tile to move it to the end, or focus a handle and use arrow keys to move it earlier or later"')
    expect(sessionsSource).toContain('? "Move"')
    expect(sessionsSource).toContain(': "Drag or use arrows"')
    expect(sessionsSource).toContain('title={reorderHintTitle}')
    expect(sessionsSource).toContain('{reorderHintLabel ? (')
    expect(sessionsSource).toContain('<span className="whitespace-nowrap">')
    expect(sessionsSource).toContain('{reorderHintLabel}')
  })

  it("shows a persistent per-tile reorder affordance, uses it as the drag source, supports arrow-key reordering, and marks the leading insertion edge of the drop target", () => {
    expect(sessionGridSource).toContain('overlay?: React.ReactNode')
    expect(sessionGridSource).toContain('tileLabel?: string')
    expect(sessionGridSource).toContain('draggedTileLabel?: string | null')
    expect(sessionGridSource).toContain('group/session-tile relative flex-shrink-0 transition-all duration-200')
    expect(sessionGridSource).toContain('"relative flex flex-wrap gap-4 p-4 content-start min-h-full w-full"')
    expect(sessionGridSource).toContain('{overlay}')
    expect(sessionGridSource).not.toContain('draggable={isDraggable && !isResizing}')
    expect(sessionGridSource).toContain('draggable={!isResizing}')
    expect(sessionGridSource).toContain('const handleReorderKeyDown = (e: React.KeyboardEvent<HTMLButtonElement>) => {')
    expect(sessionGridSource).toContain('const isMoveEarlierKey = e.key === "ArrowLeft" || e.key === "ArrowUp"')
    expect(sessionGridSource).toContain('const isMoveLaterKey = e.key === "ArrowRight" || e.key === "ArrowDown"')
    expect(sessionGridSource).toContain('e.preventDefault()')
    expect(sessionGridSource).toContain('e.stopPropagation()')
    expect(sessionGridSource).toContain('onKeyboardReorder?.("earlier")')
    expect(sessionGridSource).toContain('onKeyboardReorder?.("later")')
    expect(sessionGridSource).toContain('const handleDrop = (e: React.DragEvent) => {')
    expect(sessionGridSource).toContain('e.preventDefault()')
    expect(sessionGridSource).toContain('onDrop?.(index)')
    expect(sessionGridSource).toContain('const handleDragLeave = (e: React.DragEvent) => {')
    expect(sessionGridSource).toContain('const relatedTarget = e.relatedTarget')
    expect(sessionGridSource).toContain('if (relatedTarget instanceof Node && e.currentTarget.contains(relatedTarget)) {')
    expect(sessionGridSource).toContain('onDragLeave?.(index)')
    expect(sessionGridSource).toContain('onDragLeave={handleDragLeave}')
    expect(sessionGridSource).toContain('onDrop={handleDrop}')
    expect(sessionGridSource).toContain('absolute -left-2 top-4 z-20 flex appearance-none select-none items-center gap-1 overflow-hidden rounded-r-full rounded-l-md border border-l-0')
    expect(sessionGridSource).toContain('cursor-grab active:cursor-grabbing')
    expect(sessionGridSource).toContain('focus-visible:ring-2 focus-visible:ring-blue-500/80 focus-visible:ring-offset-1 focus-visible:ring-offset-background')
    expect(sessionGridSource).toContain('const trimmedTileLabel = tileLabel?.trim()')
    expect(sessionGridSource).toContain('const trimmedDraggedTileLabel = draggedTileLabel?.trim()')
    expect(sessionGridSource).toContain('const draggedReorderLabel = trimmedDraggedTileLabel && trimmedDraggedTileLabel.length > 0')
    expect(sessionGridSource).toContain('const reorderTargetLabel = trimmedTileLabel && trimmedTileLabel.length > 0')
    expect(sessionGridSource).toContain('const reorderHandleTitle =')
    expect(sessionGridSource).toContain('const reorderHandleAriaLabel =')
    expect(sessionGridSource).toContain('const dropTargetMoveLabel = trimmedDraggedTileLabel')
    expect(sessionGridSource).toContain('? `Move ${draggedReorderLabel}`')
    expect(sessionGridSource).toContain('dropTargetIndicatorContextLabel?: string | null')
    expect(sessionGridSource).toContain('dropTargetIndicatorTitle?: string | null')
    expect(sessionGridSource).toContain('const dropTargetContextLabel = dropTargetIndicatorContextLabel?.trim() || `before ${reorderTargetLabel}`')
    expect(sessionGridSource).toContain('const effectiveDropTargetIndicatorTitle = dropTargetIndicatorTitle?.trim() ||')
    expect(sessionGridSource).toContain('? `Move ${draggedReorderLabel} ${dropTargetContextLabel}`')
    expect(sessionGridSource).toContain('Drag to reorder ${trimmedTileLabel}. Focus and use arrow keys to move earlier or later.')
    expect(sessionGridSource).toContain('Reorder ${trimmedTileLabel}. Use arrow keys to move earlier or later')
    expect(sessionGridSource).toContain('title={reorderHandleTitle}')
    expect(sessionGridSource).toContain('aria-label={reorderHandleAriaLabel}')
    expect(sessionGridSource).toContain('aria-keyshortcuts="ArrowLeft ArrowUp ArrowRight ArrowDown"')
    expect(sessionGridSource).toContain('const reorderHandleLabelClassName = cn(')
    expect(sessionGridSource).toContain('max-w-0 overflow-hidden whitespace-nowrap opacity-0 transition-[max-width,opacity,margin] duration-200')
    expect(sessionGridSource).toContain('group-hover/session-tile:max-w-16')
    expect(sessionGridSource).toContain('group-hover/session-tile:opacity-100 group-hover/session-tile:shadow-md group-focus-within/session-tile:opacity-100 group-focus-within/session-tile:shadow-md')
    expect(sessionGridSource).toContain('absolute inset-x-3 top-0 z-20 -translate-y-1/2')
    expect(sessionGridSource).toContain('h-1 w-full rounded-full bg-blue-500/90 shadow-sm')
    expect(sessionGridSource).toContain('flex max-w-full min-w-0 flex-col items-end gap-0.5 rounded-xl bg-blue-500 px-2 py-1.5 text-[10px] font-medium leading-none text-white shadow-sm')
    expect(sessionGridSource).toContain('className="max-w-[13rem] truncate text-white/85"')
    expect(sessionGridSource).toContain('{dropTargetMoveLabel}')
    expect(sessionGridSource).toContain('title={effectiveDropTargetIndicatorTitle}')
    expect(sessionGridSource).toContain('className="max-w-[15rem] truncate font-semibold text-right"')
    expect(sessionGridSource).toContain('{dropTargetContextLabel}')
    expect(sessionsSource).toContain('draggedTileLabel={draggedSessionId ? draggedSessionReorderLabel : null}')
  })

  it("shows a neutral grid-level hint while dragging without an active drop target so empty-space release stays predictable", () => {
    expect(sessionsSource).toContain('const showGridReorderIdleHint =')
    expect(sessionsSource).toContain('canReorderTiles && !!draggedSessionId && dragTargetIndex === null')
    expect(sessionsSource).toContain('const gridReorderIdleHintLabel = isCompactSessionHeader')
    expect(sessionsSource).toContain('"Release to keep order"')
    expect(sessionsSource).toContain('isResponsiveStackedLayout')
    expect(sessionsSource).toContain('"Drag over a tile to reorder · Drag below the last tile to move to bottom · Release to keep order"')
    expect(sessionsSource).toContain('"Drag over a tile to reorder · Drag below the last tile to move to end · Release to keep order"')
    expect(sessionsSource).toContain('overlay={showGridReorderIdleHint ? (')
    expect(sessionsSource).toContain('role="status"')
    expect(sessionsSource).toContain('aria-live="polite"')
    expect(sessionsSource).toContain('className="pointer-events-none absolute inset-x-4 top-4 z-10 flex justify-center px-2"')
    expect(sessionsSource).toContain('rounded-full border border-dashed')
    expect(sessionsSource).toContain('{gridReorderIdleHintLabel}')
  })

  it("adds a dedicated trailing drop target so dragging below the last tile can intentionally move a session to the end", () => {
    expect(sessionsSource).toContain('const trailingReorderDropTargetIndex = allProgressEntries.length')
    expect(sessionsSource).toContain('const draggedSessionReorderLabel = draggedSessionId')
    expect(sessionsSource).toContain('const showGridReorderEndDropZone =')
    expect(sessionsSource).toContain('const isGridReorderEndDropTarget =')
    expect(sessionsSource).toContain('const gridReorderEndDropZonePreviewCopy = draggedSessionId')
    expect(sessionsSource).toContain('trailingReorderDropTargetIndex,')
    expect(sessionsSource).toContain('const gridReorderEndDropZoneMoveLabel = draggedSessionId')
    expect(sessionsSource).toContain('const gridReorderEndDropZoneLabel =')
    expect(sessionsSource).toContain('gridReorderEndDropZonePreviewCopy?.contextLabel ??')
    expect(sessionsSource).toContain('const gridReorderEndDropZoneTitle =')
    expect(sessionsSource).toContain('gridReorderEndDropZonePreviewCopy?.title ??')
    expect(sessionsSource).toContain('`Move ${draggedSessionReorderLabel}`')
    expect(sessionsSource).toContain('? "To end"')
    expect(sessionsSource).toContain(': "To end of sessions"')
    expect(sessionsSource).toContain('`Move ${draggedSessionReorderLabel} to the end of sessions`')
    expect(sessionsSource).toContain('? "To bottom"')
    expect(sessionsSource).toContain(': "To bottom of stack"')
    expect(sessionsSource).toContain('`Move ${draggedSessionReorderLabel} below all visible sessions`')
    expect(sessionsSource).toContain('"Drop to move session below all visible sessions"')
    expect(sessionsSource).toContain('const gridReorderEndDropZoneMarkerLabel = isGridReorderEndDropTarget')
    expect(sessionsSource).toContain('"Release to bottom"')
    expect(sessionsSource).toContain('"Release at bottom of stack"')
    expect(sessionsSource).toContain('"Bottom of stack"')
    expect(sessionsSource).toContain('"Release to end"')
    expect(sessionsSource).toContain('"Release at last position"')
    expect(sessionsSource).toContain('"Last position"')
    expect(sessionsSource).toContain('const handleTrailingReorderDropZoneDragOver = useCallback(')
    expect(sessionsSource).toContain('handleDragOver(allProgressEntries.length)')
    expect(sessionsSource).toContain('const handleTrailingReorderDropZoneDragLeave = useCallback(')
    expect(sessionsSource).toContain('handleDragLeave(allProgressEntries.length)')
    expect(sessionsSource).toContain('const handleTrailingReorderDropZoneDrop = useCallback(')
    expect(sessionsSource).toContain('handleDrop(allProgressEntries.length)')
    expect(sessionsSource).toContain('{showGridReorderEndDropZone ? (')
    expect(sessionsSource).toContain('relative flex min-h-[4.75rem] w-full items-center justify-center overflow-visible rounded-xl border border-dashed px-4 pb-3 pt-5 transition-all duration-150')
    expect(sessionsSource).toContain('title={gridReorderEndDropZoneTitle}')
    expect(sessionsSource).toContain('onDragOver={handleTrailingReorderDropZoneDragOver}')
    expect(sessionsSource).toContain('onDragLeave={handleTrailingReorderDropZoneDragLeave}')
    expect(sessionsSource).toContain('onDrop={handleTrailingReorderDropZoneDrop}')
    expect(sessionsSource).toContain('absolute inset-x-4 top-0 flex -translate-y-1/2 items-center justify-center')
    expect(sessionsSource).toContain('rounded-full border px-2.5 py-1 text-[10px] font-semibold uppercase tracking-[0.08em] shadow-sm transition-colors duration-150')
    expect(sessionsSource).toContain('<ArrowDownToLine className="h-3 w-3 shrink-0" aria-hidden="true" />')
    expect(sessionsSource).toContain('{gridReorderEndDropZoneMarkerLabel}')
    expect(sessionsSource).toContain('pointer-events-none absolute left-5 right-5 top-0 h-px -translate-y-1/2 transition-colors duration-150')
    expect(sessionsSource).toContain('flex max-w-full min-w-0 flex-col items-center gap-0.5 rounded-lg px-3 py-1.5 text-[11px] font-medium leading-none')
    expect(sessionsSource).toContain('{gridReorderEndDropZoneMoveLabel ? (')
    expect(sessionsSource).toContain('className="max-w-full truncate opacity-80"')
    expect(sessionsSource).toContain('{gridReorderEndDropZoneLabel}')
  })

  it("only commits session reordering after an actual drop instead of reordering on drag end alone", () => {
    expect(sessionsSource).toContain('const handleDrop = useCallback(')
    expect(sessionsSource).toContain('if (!draggedSessionId) return')
    expect(sessionsSource).toContain('function getDropBeforeInsertIndex(draggedIndex: number, targetIndex: number): number {')
    expect(sessionsSource).toContain('return draggedIndex < targetIndex ? targetIndex - 1 : targetIndex')
    expect(sessionsSource).toContain('const insertionIndex = getDropBeforeInsertIndex(draggedIndex, targetIndex)')
    expect(sessionsSource).toContain('const nextOrder = moveSessionToIndex(currentOrder, draggedSessionId, insertionIndex)')
    expect(sessionsSource).toContain('setSessionOrder(nextOrder)')
    expect(sessionsSource).toContain('const handleDragLeave = useCallback((targetIndex: number) => {')
    expect(sessionsSource).toContain('currentTargetIndex === targetIndex ? null : currentTargetIndex')
    expect(sessionsSource).toContain('setDragTargetIndex(null)')
    expect(sessionsSource).toContain('const handleDragEnd = useCallback(() => {')
    expect(sessionsSource).not.toContain('if (draggedSessionId && dragTargetIndex !== null) {')
  })

  it("lets focused reorder handles move sessions earlier or later without starting a drag", () => {
    expect(sessionsSource).toContain('const handleKeyboardReorder = useCallback(')
    expect(sessionsSource).toContain('(sessionId: string, direction: "earlier" | "later") => {')
    expect(sessionsSource).toContain('function moveSessionToIndex(')
    expect(sessionsSource).toContain('const currentIndex = currentOrder.indexOf(sessionId)')
    expect(sessionsSource).toContain('direction === "earlier" ? currentIndex - 1 : currentIndex + 1')
    expect(sessionsSource).toContain('const nextOrder = moveSessionToIndex(currentOrder, sessionId, targetIndex)')
    expect(sessionsSource).toContain('setSessionOrder(nextOrder)')
    expect(sessionsSource).toContain('scrollSessionTileIntoView(sessionId)')
    expect(sessionsSource).toContain('onKeyboardReorder={handleKeyboardReorder}')
    expect(sessionsSource).toContain('canMoveEarlier={index > 0}')
    expect(sessionsSource).toContain('canMoveLater={index < visibleProgressEntries.length - 1}')
  })

  it("announces successful drag and keyboard reorders through a polite live region", () => {
    expect(sessionsSource).toContain('function getSessionReorderNeighborContextLabel(')
    expect(sessionsSource).toContain('function getSessionReorderAnnouncement(')
    expect(sessionsSource).toContain('function getSessionReorderAnnouncementContext(')
    expect(sessionsSource).toContain('const previousSessionLabel = options?.previousSessionLabel?.trim() || null')
    expect(sessionsSource).toContain('const nextSessionLabel = options?.nextSessionLabel?.trim() || null')
    expect(sessionsSource).toContain('vertical?: boolean')
    expect(sessionsSource).toContain('const trailingRelation = options?.vertical ? "below" : "after"')
    expect(sessionsSource).toContain('const leadingRelation = options?.vertical ? "above" : "before"')
    expect(sessionsSource).toContain('? `between ${previousSessionLabel} and ${nextSessionLabel}`')
    expect(sessionsSource).toContain(': `${trailingRelation} ${previousSessionLabel}`')
    expect(sessionsSource).toContain('? `${leadingRelation} ${nextSessionLabel}`')
    expect(sessionsSource).toContain('const neighborContext = getSessionReorderNeighborContextLabel(options)')
    expect(sessionsSource).toContain('Moved ${sessionLabel} to position ${position} of ${totalSessions}, ${neighborContext}.')
    expect(sessionsSource).toContain('return `Moved ${sessionLabel} to position ${position} of ${totalSessions}.`')
    expect(sessionsSource).toContain('function getSessionReorderDropTargetIndicatorCopy(')
    expect(sessionsSource).toContain('const insertionIndex = getDropBeforeInsertIndex(draggedIndex, targetIndex)')
    expect(sessionsSource).toContain('const neighborContextLabel = getSessionReorderNeighborContextLabel(')
    expect(sessionsSource).toContain('vertical: options?.vertical')
    expect(sessionsSource).toContain('title: `Move ${draggedSessionLabel} ${neighborContextLabel}`')
    expect(sessionsSource).toContain('const [reorderAnnouncement, setReorderAnnouncement] = useState("")')
    expect(sessionsSource).toContain('const reorderableSessionLabelById = useMemo(')
    expect(sessionsSource).toContain('const previousSessionId = orderedSessionIds[movedSessionIndex - 1] ?? null')
    expect(sessionsSource).toContain('const nextSessionId = orderedSessionIds[movedSessionIndex + 1] ?? null')
    expect(sessionsSource).toContain('getSessionReorderAnnouncementContext(')
    expect(sessionsSource).toContain('setReorderAnnouncement(')
    expect(sessionsSource).toContain('getSessionReorderAnnouncement(')
    expect(sessionsSource).toContain('vertical: isResponsiveStackedLayout')
    expect(sessionsSource).toContain('className="sr-only" role="status" aria-live="polite" aria-atomic="true"')
    expect(sessionsSource).toContain('{reorderAnnouncement}')
  })

  it("briefly marks the moved tile so reorder results stay visually obvious after the drag or arrow-key action completes", () => {
    expect(sessionsSource).toContain('const RECENT_REORDER_VISUAL_CUE_DURATION_MS = 1_600')
    expect(sessionsSource).toContain('const [recentlyReorderedSessionId, setRecentlyReorderedSessionId] = useState<string | null>(null)')
    expect(sessionsSource).toContain('const recentReorderVisualCueTimeoutRef = useRef<number | null>(null)')
    expect(sessionsSource).toContain('const clearRecentReorderVisualCue = useCallback(() => {')
    expect(sessionsSource).toContain('window.clearTimeout(recentReorderVisualCueTimeoutRef.current)')
    expect(sessionsSource).toContain('const showRecentReorderVisualCue = useCallback(')
    expect(sessionsSource).toContain('setRecentlyReorderedSessionId(sessionId)')
    expect(sessionsSource).toContain('recentReorderVisualCueTimeoutRef.current = window.setTimeout(() => {')
    expect(sessionsSource).toContain('showRecentReorderVisualCue(draggedSessionId)')
    expect(sessionsSource).toContain('showRecentReorderVisualCue(sessionId)')
    expect(sessionsSource).toContain('isRecentlyReordered={recentlyReorderedSessionId === sessionId}')
    expect(sessionGridSource).toContain('isRecentlyReordered?: boolean')
    expect(sessionGridSource).toContain('isRecentlyReordered = false')
    expect(sessionGridSource).toContain('isRecentlyReordered\n        ? "opacity-100 border-emerald-500/60 bg-emerald-500/12 text-emerald-700 shadow-md dark:text-emerald-200"')
    expect(sessionGridSource).toContain('isRecentlyReordered\n        ? "ml-0.5 max-w-16 opacity-100"')
    expect(sessionGridSource).toContain('isRecentlyReordered\n      ? "ring-2 ring-emerald-500/60 ring-offset-2 shadow-lg shadow-emerald-500/15"')
    expect(sessionGridSource).toContain('isRecentlyReordered ? (')
    expect(sessionGridSource).toContain('<Check className="h-3 w-3 shrink-0" />')
    expect(sessionGridSource).toContain('const reorderHandleLabel = isRecentlyReordered')
    expect(sessionGridSource).toContain('? "Moved"')
    expect(sessionGridSource).toContain('? "Move"')
    expect(sessionGridSource).toContain(': "Reorder"')
    expect(sessionGridSource).toContain('{reorderHandleLabel}')
  })

  it("briefly marks the tile kept visible after leaving single view so restored layouts are easier to scan", () => {
    expect(sessionGridSource).toContain('isRecentlyRestoredFromSingleView?: boolean')
    expect(sessionGridSource).toContain('isRecentlyRestoredFromSingleView = false')
    expect(sessionGridSource).toContain('const showRecentSingleViewReturnCue =')
    expect(sessionGridSource).toContain('const singleViewReturnCueLabel = showRecentSingleViewReturnCue')
    expect(sessionGridSource).toContain('"Kept visible"')
    expect(sessionGridSource).toContain('const tileAttentionRingClassName = isDragTarget')
    expect(sessionGridSource).toContain('isRecentlyRestoredFromSingleView\n        ? "ring-2 ring-blue-500/60 ring-offset-2 shadow-lg shadow-blue-500/15"')
    expect(sessionGridSource).toContain('pointer-events-none absolute inset-x-3 top-0 z-20 -translate-y-1/2 flex justify-end')
    expect(sessionGridSource).toContain('{singleViewReturnCueLabel}')
  })

  it("keeps drag target indices aligned with reorderable sessions so pending tiles do not skew the Drop before cue", () => {
    expect(sessionsSource).not.toContain('const adjustedIndex = hasVisiblePendingTile ? index + 1 : index')
    expect(sessionsSource).toContain('const tileLabel = getSessionTileLabel(sessionId, progress)')
    expect(sessionsSource).toContain('tileLabel={tileLabel}')
    expect(sessionsSource).toContain('index={index}')
    expect(sessionsSource).toContain('dragTargetIndex === index &&')
    expect(sessionsSource).toContain('const currentReorderSessionIds =')
    expect(sessionsSource).toContain('sessionOrder.length > 0 ? sessionOrder : allProgressEntries.map(([id]) => id)')
    expect(sessionsSource).toContain('const dropTargetIndicatorCopy =')
    expect(sessionsSource).toContain('getSessionReorderDropTargetIndicatorCopy(')
    expect(sessionsSource).toContain('dropTargetIndicatorContextLabel={')
    expect(sessionsSource).toContain('dropTargetIndicatorCopy?.contextLabel')
    expect(sessionsSource).toContain('dropTargetIndicatorTitle={dropTargetIndicatorCopy?.title}')
    expect(sessionsSource).toContain('vertical: isResponsiveStackedLayout')
  })
})