import { readFileSync } from "node:fs"
import { describe, expect, it } from "vitest"

const sessionGridSource = readFileSync(new URL("./session-grid.tsx", import.meta.url), "utf8")

describe("session grid resize affordances", () => {
  it("keeps height resizing visible while replacing width-changing handles with a width-lock explanation in full-width tile states", () => {
    expect(sessionGridSource).toContain('const resizeRailClassName = cn(')
    expect(sessionGridSource).toContain('bg-border/40 opacity-75 group-hover/session-tile:bg-blue-500/30 group-hover/session-tile:opacity-100 group-focus-within/session-tile:bg-blue-500/30 group-focus-within/session-tile:opacity-100')
    expect(sessionGridSource).toContain('const lockedWidthHintClassName = cn(')
    expect(sessionGridSource).toContain('const lockedWidthCornerClassName = cn(')
    expect(sessionGridSource).toContain('const lockedWidthCornerHintClassName = cn(')
    expect(sessionGridSource).toContain('const heightResizeRailClassName = cn(')
    expect(sessionGridSource).toContain('group-hover/resize-height:h-2 group-focus-within/session-tile:h-2')
    expect(sessionGridSource).toContain('const heightResizeHintClassName = cn(')
    expect(sessionGridSource).toContain('const isWidthResizeLocked = shouldLockTileWidth(containerWidth, gap, layoutMode, sessionCount)')
    expect(sessionGridSource).toContain('{!isWidthResizeLocked && (')
    expect(sessionGridSource).toContain('className="group/resize-width absolute top-2 bottom-4 -right-2 z-10 flex w-5 items-center justify-center cursor-ew-resize"')
    expect(sessionGridSource).toContain('"h-[calc(100%-18px)] w-1.5 group-hover/resize-width:w-2 group-focus-within/session-tile:w-2"')
    expect(sessionGridSource).toContain('className="group/locked-width absolute top-2 bottom-4 -right-2 z-10 flex w-5 items-center justify-center cursor-help"')
    expect(sessionGridSource).toContain('title={lockedWidthHint.title}')
    expect(sessionGridSource).toContain('group-hover/session-tile:translate-x-0 group-hover/session-tile:opacity-100')
    expect(sessionGridSource).toContain('group-focus-within/session-tile:translate-x-0 group-focus-within/session-tile:opacity-100')
    expect(sessionGridSource).toContain('group-focus-within/session-tile:border-blue-500/35 group-focus-within/session-tile:bg-blue-500/5 group-focus-within/session-tile:opacity-100')
    expect(sessionGridSource).toContain('className="pointer-events-none absolute -bottom-2 -right-2 z-20 flex h-7 w-7 items-end justify-end"')
    expect(sessionGridSource).toContain('lockedWidthCornerClassName,')
    expect(sessionGridSource).toContain('const lockedWidthCornerHintLabel = isWidthResizeLocked && lockedWidthHint')
    expect(sessionGridSource).toContain('"Use bottom edge"')
    expect(sessionGridSource).toContain('{lockedWidthCornerHintLabel ? (')
    expect(sessionGridSource).toContain('className={lockedWidthCornerHintClassName}')
    expect(sessionGridSource).toContain('{lockedWidthCornerHintLabel}')
    expect(sessionGridSource).toContain('group-hover/session-tile:translate-y-0 group-hover/session-tile:opacity-100 group-focus-within/session-tile:translate-y-0 group-focus-within/session-tile:opacity-100 group-hover/resize-height:translate-y-0 group-hover/resize-height:opacity-100')
    expect(sessionGridSource).toContain('{lockedWidthHint.label}')
    expect(sessionGridSource).toContain('className={cn(')
    expect(sessionGridSource).toContain('"group/resize-height absolute left-2 -bottom-2 z-10 flex h-5 items-center justify-center cursor-ns-resize"')
    expect(sessionGridSource).toContain('isWidthResizeLocked ? "right-2" : "right-4"')
    expect(sessionGridSource).toContain('className={heightResizeRailClassName}')
    expect(sessionGridSource).toContain('className={cn(')
    expect(sessionGridSource).toContain('heightResizeHintClassName,')
  })

  it("locks persisted narrow widths back to the computed full-width target when resize should not change the row footprint", () => {
    expect(sessionGridSource).toContain('export function shouldLockTileWidth(containerWidth: number, gap: number, layoutMode: TileLayoutMode, sessionCount = 2): boolean {')
    expect(sessionGridSource).toContain('layoutMode === "1x1" || shouldUseSingleVisibleTileFallback(sessionCount) || getEffectiveTileColumnCount(containerWidth, gap, layoutMode) === 1')
    expect(sessionGridSource).toContain('if (!isWidthResizeLocked || containerWidth <= 0 || isResizing || width === targetTileWidth) {')
    expect(sessionGridSource).toContain('setSize({ width: targetTileWidth })')
  })

  it("adds axis-specific hover hints while keeping explicit resize guidance where width resizing is allowed", () => {
    expect(sessionGridSource).toContain('type TileResizeHandle = "width" | "height" | "corner"')
    expect(sessionGridSource).toContain('export function getActiveTileResizeHintLabel(')
    expect(sessionGridSource).toContain('return `Width · ${roundedWidth}px`')
    expect(sessionGridSource).toContain('return `${isWidthResizeLocked ? "Height only" : "Height"} · ${roundedHeight}px`')
    expect(sessionGridSource).toContain('return `${roundedWidth}px × ${roundedHeight}px`')
    expect(sessionGridSource).toContain('const resizeHintClassName =')
    expect(sessionGridSource).toContain('const activeResizeHintClassName = "border-blue-500/45 bg-blue-500/12 text-blue-700 opacity-100 shadow-md dark:text-blue-200"')
    expect(sessionGridSource).toContain('const resizeGripClassName = cn(')
    expect(sessionGridSource).toContain('const resizeGripBarClassName = "rounded-full bg-current opacity-70"')
    expect(sessionGridSource).toContain('const widthResizeHintLabel = activeResizeHandle === "width"')
    expect(sessionGridSource).toContain('const activeHeightResizeLabel = activeResizeHandle === "height"')
    expect(sessionGridSource).toContain('const cornerResizeHintLabel = activeResizeHandle === "corner"')
    expect(sessionGridSource).toContain('export function getTileResizeHandleTitle(')
    expect(sessionGridSource).toContain('return isWidthResizeLocked')
    expect(sessionGridSource).toContain('const heightResizeAriaLabel = isWidthResizeLocked')
    expect(sessionGridSource).toContain('"Resize tile height only"')
    expect(sessionGridSource).toContain('"Drag the bottom edge to resize tile height while tile width follows the current layout. Double-click to restore the layout height."')
    expect(sessionGridSource).toContain('setActiveResizeHandle("width")')
    expect(sessionGridSource).toContain('setActiveResizeHandle("height")')
    expect(sessionGridSource).toContain('setActiveResizeHandle("corner")')
    expect(sessionGridSource).toContain('if (!isResizing && activeResizeHandle !== null) {')
    expect(sessionGridSource).toContain('"right-0 top-1/2 h-8 w-3 -translate-y-1/2 translate-x-1/2 flex-col gap-0.5"')
    expect(sessionGridSource).toContain('"bottom-0 left-1/2 h-3 w-8 -translate-x-1/2 translate-y-1/2 gap-0.5"')
    expect(sessionGridSource).toContain('group-hover/resize-width:opacity-100')
    expect(sessionGridSource).toContain('group-hover/resize-height:opacity-100')
    expect(sessionGridSource).toContain('group-hover/resize-corner:opacity-100')
    expect(sessionGridSource).toContain('title={getTileResizeHandleTitle("width", false)}')
    expect(sessionGridSource).toContain('aria-label="Resize tile width"')
    expect(sessionGridSource).toContain('title={getTileResizeHandleTitle("height", isWidthResizeLocked)}')
    expect(sessionGridSource).toContain('aria-label={heightResizeAriaLabel}')
    expect(sessionGridSource).toContain('title={getTileResizeHandleTitle("corner", false)}')
    expect(sessionGridSource).toContain('aria-label="Resize tile width and height"')
    expect(sessionGridSource).toContain('activeResizeHandle === "width" && activeResizeHintClassName')
    expect(sessionGridSource).toContain('{widthResizeHintLabel}')
    expect(sessionGridSource).toContain('activeResizeHandle === "corner" && activeResizeHintClassName')
    expect(sessionGridSource).toContain('{cornerResizeHintLabel}')
    expect(sessionGridSource).toContain('activeResizeHandle === "height" && activeResizeHintClassName')
    expect(sessionGridSource).toContain('{activeHeightResizeLabel}')
    expect(sessionGridSource).toContain('const resizeCornerClassName = cn(')
    expect(sessionGridSource).toContain('group-hover/session-tile:border-blue-500/40 group-hover/session-tile:bg-background group-hover/session-tile:text-foreground group-focus-within/session-tile:border-blue-500/40 group-focus-within/session-tile:bg-background group-focus-within/session-tile:text-foreground')
    expect(sessionGridSource).toContain('group-hover/resize-corner:h-6 group-hover/resize-corner:w-6 group-focus-within/session-tile:h-6 group-focus-within/session-tile:w-6')
  })

  it("keeps the bottom-right resize hotspot visually explained even when width is layout-locked", () => {
    expect(sessionGridSource).toContain('title:\n        "Tile width fills Single view. Corner resize is unavailable here, so drag the bottom edge to resize height, or switch back to Compare or Grid to resize width again."')
    expect(sessionGridSource).toContain('title:\n        "Only one session is visible, so tile width fills the row. Corner resize is unavailable here; drag the bottom edge to resize height until more sessions appear or you switch layouts."')
    expect(sessionGridSource).toContain('title:\n        "Tile width fills the stacked layout. Corner resize is unavailable here, so drag the bottom edge to resize height, or widen the sessions area or switch layouts to resize width again."')
    expect(sessionGridSource).toContain('<path d="M4 4L12 12" stroke="currentColor" strokeWidth="1.5" strokeLinecap="round" fill="none" opacity="0.8" />')
  })
})