/**
 * Agent progress tracking types — unified superset for desktop and mobile.
 *
 * Desktop‑only and mobile‑only fields are marked optional so both platforms
 * can consume the same interface without breaking.
 */

import type { ToolCall, ToolResult, ConversationHistoryMessage } from './types'
import {
  normalizeAgentConversationState,
  type AgentConversationState,
} from './conversation-state'

// ---------------------------------------------------------------------------
// ACP (Agent Communication Protocol) related types
// ---------------------------------------------------------------------------

/**
 * A message in a sub-agent conversation (desktop-specific, optional in shared).
 */
export interface ACPSubAgentMessage {
  /** Role of the sender */
  role: 'user' | 'assistant' | 'tool'
  /** Message content */
  content: string
  /** Structured tool calls when available */
  toolCalls?: ToolCall[]
  /** Structured tool results when available */
  toolResults?: ToolResult[]
  /** Tool name if this is a tool call/result */
  toolName?: string
  /** Tool input (for tool calls) */
  toolInput?: unknown
  /** Timestamp */
  timestamp: number
}

/**
 * Progress information for a delegated ACP sub-agent.
 */
export interface ACPDelegationProgress {
  /** Unique identifier for this delegation run */
  runId: string
  /** Name of the ACP agent being delegated to */
  agentName: string
  /** How this delegated run is connected/executed */
  connectionType?: 'internal' | 'acpx' | 'acp' | 'stdio' | 'remote'
  /** The task that was delegated */
  task: string
  /** Current status of the delegation */
  status: 'pending' | 'spawning' | 'running' | 'completed' | 'failed' | 'cancelled'
  /** Optional progress message from the sub-agent */
  progressMessage?: string
  /** When the delegation started */
  startTime: number
  /** When the delegation ended (if complete) */
  endTime?: number
  /** Result summary (if completed) */
  resultSummary?: string
  /** Error message (if failed) */
  error?: string
  /** Session ID for local ACP/stdio delegated sessions */
  acpSessionId?: string
  /** Internal DotAgents sub-session ID for internal delegations */
  subSessionId?: string
  /** DotAgents conversation ID for internal/stateful delegated sessions */
  conversationId?: string
  /** Remote ACP run ID for externally-managed async delegations */
  acpRunId?: string
  /** Full conversation history from the sub-agent */
  conversation?: ACPSubAgentMessage[]
}

/**
 * State of all active ACP delegations for a session.
 */
export interface ACPDelegationState {
  /** Session ID of the parent agent */
  parentSessionId: string
  /** All delegations for this session */
  delegations: ACPDelegationProgress[]
  /** Number of active (non-completed) delegations */
  activeCount: number
}

/**
 * Value option for an ACP configuration dropdown/choice.
 */
export interface ACPConfigOptionValue {
  value: string
  name: string
  description?: string
}

/**
 * A configurable option exposed by an ACP agent.
 */
export interface ACPConfigOption {
  id: string
  name: string
  description?: string
  category?: string
  type: string
  currentValue: string
  options: ACPConfigOptionValue[]
}

// ---------------------------------------------------------------------------
// Agent step summary (dual-model mode, desktop-specific)
// ---------------------------------------------------------------------------

/**
 * Agent step summary generated by a weak/summarization model.
 */
export interface AgentStepSummary {
  id: string
  sessionId: string
  stepNumber: number
  timestamp: number

  /** What the agent just did (single line) */
  actionSummary: string

  /**
   * Durable note candidates extracted from this step.
   * These should be reusable in future sessions (preferences, constraints,
   * decisions, facts, insights), NOT step-by-step telemetry.
   */
  noteCandidates?: string[]

  // --- Desktop-specific metadata ---
  importance?: 'low' | 'medium' | 'high' | 'critical'
  savedToKnowledgeNote?: boolean
  userNotes?: string
  tags?: string[]

  // Legacy fields (kept for backward compatibility)
  keyFindings?: string[]
  nextSteps?: string
  decisionsMade?: string[]
}

// ---------------------------------------------------------------------------
// AgentProgressStep — unified superset
// ---------------------------------------------------------------------------

/**
 * A single step in an agent's progress.
 *
 * The `type` field is the union of desktop and mobile step types.
 * The `status` field is the union of desktop and mobile status values.
 */
export interface AgentProgressStep {
  id: string
  type:
    | 'thinking'
    | 'tool_call'
    | 'tool_result'
    | 'completion'
    | 'tool_approval'
    // Mobile-specific types:
    | 'response'
    | 'error'
    | 'pending_approval'
  title: string
  description?: string
  status:
    | 'pending'
    | 'in_progress'
    | 'completed'
    | 'error'
    // Desktop-specific statuses:
    | 'awaiting_approval'
  timestamp: number

  // --- Shared fields ---
  llmContent?: string
  toolCall?: ToolCall
  toolResult?: ToolResult

  // --- Mobile-specific ---
  /** Raw content string (mobile uses this instead of llmContent in some cases) */
  content?: string

  // --- Desktop-specific ---
  approvalRequest?: {
    approvalId: string
    toolName: string
    arguments: any
  }
  /** If this step is a delegation to a sub-agent */
  delegation?: ACPDelegationProgress
  executionStats?: {
    durationMs?: number
    totalTokens?: number
    toolUseCount?: number
    inputTokens?: number
    outputTokens?: number
    cacheHitTokens?: number
  }
  subagentId?: string
}

export type AgentRetryInfo = {
  isRetrying: boolean
  attempt: number
  maxAttempts?: number
  delaySeconds: number
  reason: string
  startedAt: number
}

export type AgentRetryProgressCallback = (info: AgentRetryInfo) => void

/**
 * Ordered user-facing response emitted during a single agent run.
 * Consumers should use `id` for playback/delivery dedupe instead of raw text.
 */
export interface AgentUserResponseEvent {
  id: string
  sessionId: string
  runId?: number
  ordinal: number
  text: string
  timestamp: number
}

// ---------------------------------------------------------------------------
// AgentProgressUpdate — unified superset
// ---------------------------------------------------------------------------

/**
 * Full progress update for an agent session.
 *
 * All platform-specific fields are optional so that both desktop and mobile
 * can use this single type without breaking.
 */
export interface AgentProgressUpdate {
  sessionId: string
  /** Parent session ID when this update belongs to a delegated sub-agent/sub-session. */
  parentSessionId?: string
  conversationId?: string
  currentIteration: number
  maxIterations: number
  steps: AgentProgressStep[]
  isComplete: boolean

  // --- Shared fields ---
  conversationState?: AgentConversationState
  finalContent?: string
  /**
   * User-facing response set via respond_to_user tool.
   * On voice interfaces: spoken aloud via TTS.
   * On messaging channels (mobile, WhatsApp): sent as a message.
   * Consumers should fall back to finalContent if this is not set.
   */
  userResponse?: string
  /**
   * Ordered respond_to_user events for the current run.
   * Prefer this over `userResponse` / `userResponseHistory` when available.
   */
  responseEvents?: AgentUserResponseEvent[]
  conversationHistory?: ConversationHistoryMessage[]
  /** Total history size when `conversationHistory` is a lazy-loaded display window. */
  conversationHistoryTotalCount?: number
  /** Start index of `conversationHistory` within the full persisted history window. */
  conversationHistoryStartIndex?: number
  streamingContent?: {
    text: string
    isStreaming: boolean
  }

  // --- Mobile-specific ---
  /** @deprecated Use userResponse instead. Kept for backward compatibility with older backends. */
  spokenContent?: string

  // --- Desktop-specific ---
  /**
   * Monotonic run counter for a reused session ID.
   * Lets the renderer ignore stale updates from older runs.
   */
  runId?: number
  conversationTitle?: string
  isSnoozed?: boolean
  /**
   * History of past respond_to_user calls (excluding the current/latest one).
   * Shown as collapsed items in the UI with TTS playback support.
   */
  userResponseHistory?: string[]
  sessionStartIndex?: number
  pendingToolApproval?: {
    approvalId: string
    toolName: string
    arguments: any
  }
  retryInfo?: AgentRetryInfo
  contextInfo?: {
    estTokens: number
    maxTokens: number
  }
  modelInfo?: {
    provider: string
    model: string
  }
  /** Profile name associated with this session (from profile snapshot) */
  profileName?: string
  acpSessionInfo?: {
    agentName?: string
    agentTitle?: string
    agentVersion?: string
    currentModel?: string
    currentMode?: string
    availableModels?: Array<{ id: string; name: string; description?: string }>
    availableModes?: Array<{ id: string; name: string; description?: string }>
    configOptions?: ACPConfigOption[]
  }
  /** Dual-model summarization data */
  stepSummaries?: AgentStepSummary[]
  latestSummary?: AgentStepSummary
}

/**
 * Callback type for progress updates.
 */
export type OnProgressCallback = (update: AgentProgressUpdate) => void

export type AgentProgressConversationStateInput =
  Pick<AgentProgressUpdate, 'conversationState' | 'isComplete' | 'pendingToolApproval' | 'finalContent'> &
  Partial<Pick<AgentProgressUpdate, 'steps'>>

export function resolveAgentProgressConversationState(
  update: AgentProgressConversationStateInput,
  lifecycleState: AgentConversationState = update.isComplete ? 'complete' : 'running',
): AgentConversationState {
  if (update.conversationState) {
    return normalizeAgentConversationState(update.conversationState, lifecycleState)
  }

  if (
    update.pendingToolApproval ||
    update.steps?.some((step) => step.type === 'pending_approval')
  ) {
    return 'needs_input'
  }

  const isKillSwitchCompletion =
    update.isComplete &&
    typeof update.finalContent === 'string' &&
    update.finalContent.includes('emergency kill switch')

  if (isKillSwitchCompletion) {
    return 'blocked'
  }

  return lifecycleState
}

export function getAgentDelegationChildSessionIds(delegation: ACPDelegationProgress): string[] {
  return [
    delegation.subSessionId,
    delegation.acpSessionId,
    delegation.runId,
  ].flatMap((value) => {
    const normalized = value?.trim()
    return normalized ? [normalized] : []
  })
}

export function getAgentDelegationDisplayTitle(delegation: ACPDelegationProgress): string | null {
  const task = delegation.task?.trim()
  if (task) return task

  const agentName = delegation.agentName?.trim()
  return agentName ? `${agentName} subagent` : null
}

export function getSubagentParentSessionIdMap(
  progressEntries: Iterable<[string, Pick<AgentProgressUpdate, "steps">]>,
): Map<string, string> {
  const parentSessionIdsByChildId = new Map<string, string>()

  for (const [parentSessionId, progress] of progressEntries) {
    for (const step of progress.steps ?? []) {
      const delegation = step.delegation
      if (!delegation) continue

      for (const normalizedChildSessionId of getAgentDelegationChildSessionIds(delegation)) {
        if (
          normalizedChildSessionId === parentSessionId ||
          parentSessionIdsByChildId.has(normalizedChildSessionId)
        ) {
          continue
        }
        parentSessionIdsByChildId.set(normalizedChildSessionId, parentSessionId)
      }
    }
  }

  return parentSessionIdsByChildId
}

export function getSubagentTitleBySessionIdMap(
  progressEntries: Iterable<[string, Pick<AgentProgressUpdate, "steps">]>,
): Map<string, string> {
  const titlesByChildId = new Map<string, string>()

  for (const [parentSessionId, progress] of progressEntries) {
    for (const step of progress.steps ?? []) {
      const delegation = step.delegation
      if (!delegation) continue

      const title = getAgentDelegationDisplayTitle(delegation)
      if (!title) continue

      for (const childSessionId of getAgentDelegationChildSessionIds(delegation)) {
        if (
          childSessionId === parentSessionId ||
          titlesByChildId.has(childSessionId)
        ) {
          continue
        }
        titlesByChildId.set(childSessionId, title)
      }
    }
  }

  return titlesByChildId
}

export interface AgentDelegationProgressMessage {
  id: string
  role: "assistant"
  content: string
  timestamp: number
  toolCalls?: ToolCall[]
  toolResults?: ToolResult[]
  /** Render-only aligned call/result pairs for pending delegation tool activity. */
  toolExecutions?: Array<{ toolCall: ToolCall; result?: ToolResult }>
  variant: "delegation"
}

function formatAgentDelegationStatus(status: ACPDelegationProgress["status"]): string {
  switch (status) {
    case "pending":
      return "Pending"
    case "spawning":
      return "Spawning"
    case "running":
      return "Running"
    case "completed":
      return "Completed"
    case "failed":
      return "Failed"
    case "cancelled":
      return "Cancelled"
    default:
      return status
  }
}

function summarizeAgentDelegation(delegation: ACPDelegationProgress): string {
  if (delegation.status === "failed") {
    return delegation.error || delegation.progressMessage || delegation.task
  }
  if (delegation.status === "completed") {
    return delegation.resultSummary || delegation.progressMessage || delegation.task
  }

  const conversationSnippet = delegation.conversation?.[delegation.conversation.length - 1]?.content
  return delegation.progressMessage || conversationSnippet || delegation.task
}

const TOOL_USE_PREFIX = /^using tool:\s*/i
const TOOL_RESULT_PREFIX = /^tool result:\s*/i

type DelegationToolEntry = {
  toolCall: ToolCall
  result?: ToolResult
  source: "structured" | "legacy"
}

function normalizeDelegationToolArguments(input: unknown): Record<string, unknown> {
  if (input && typeof input === "object" && !Array.isArray(input)) {
    return input as Record<string, unknown>
  }
  if (input === undefined) {
    return {}
  }
  return { input }
}

function parseDelegationToolUsePayload(content?: string): { name?: string; input?: unknown } | null {
  const trimmedContent = (content ?? "").trim()
  if (!TOOL_USE_PREFIX.test(trimmedContent)) {
    return null
  }

  const nameMatch = trimmedContent.match(/^using tool:\s*([^\n]+)/i)
  const inputMatch = trimmedContent.match(/\ninput:\s*([\s\S]*)$/i)
  const rawInput = inputMatch?.[1]?.trim()

  let parsedInput: unknown = undefined
  if (rawInput) {
    try {
      parsedInput = JSON.parse(rawInput)
    } catch {
      parsedInput = rawInput
    }
  }

  return {
    name: nameMatch?.[1]?.trim() || undefined,
    input: parsedInput,
  }
}

function normalizeDelegationToolResultContent(content?: string): string {
  return (content ?? "").replace(TOOL_RESULT_PREFIX, "").trim()
}

function hasDelegationToolError(result: { error?: string }): boolean {
  return result.error !== undefined && result.error !== null
}

function defaultDelegationToolResultContent(result: { success?: boolean; content?: string; error?: string }): string {
  if (typeof result.content === "string") {
    return result.content
  }
  if (result.success === false || hasDelegationToolError(result)) {
    return "Tool failed"
  }
  return "Tool completed"
}

function normalizeDelegationToolResult(result: Partial<ToolResult>): ToolResult {
  return {
    success: !hasDelegationToolError(result) && result.success !== false,
    content: defaultDelegationToolResultContent(result),
    error: result.error,
  }
}

function attachResultToPendingDelegationToolEntry(
  entries: DelegationToolEntry[],
  result: ToolResult,
  options: { source: DelegationToolEntry["source"]; direction: "earliest" | "latest" },
): boolean {
  const start = options.direction === "earliest" ? 0 : entries.length - 1
  const end = options.direction === "earliest" ? entries.length : -1
  const step = options.direction === "earliest" ? 1 : -1

  for (let index = start; index !== end; index += step) {
    const entry = entries[index]
    if (entry.source !== options.source || entry.result) {
      continue
    }
    entry.result = result
    return true
  }

  return false
}

function getAgentDelegationToolMetadata(
  delegation: ACPDelegationProgress,
): Pick<AgentDelegationProgressMessage, "toolCalls" | "toolResults" | "toolExecutions"> {
  const entries: DelegationToolEntry[] = []

  for (const message of delegation.conversation ?? []) {
    const structuredCalls = Array.isArray(message.toolCalls) ? message.toolCalls : []
    const structuredResults = Array.isArray(message.toolResults) ? message.toolResults : []
    if (structuredCalls.length > 0 || structuredResults.length > 0) {
      for (let index = 0; index < structuredCalls.length; index += 1) {
        const call = structuredCalls[index]
        const result = structuredResults[index]

        entries.push({
          toolCall: {
            name: call?.name?.trim() || "tool_call",
            arguments: normalizeDelegationToolArguments(call?.arguments),
          },
          result: result
            ? normalizeDelegationToolResult(result)
            : undefined,
          source: "structured",
        })
      }
      if (structuredResults.length > structuredCalls.length) {
        for (let index = structuredCalls.length; index < structuredResults.length; index += 1) {
          const result = structuredResults[index]
          if (!result) {
            continue
          }
          const normalizedResult = normalizeDelegationToolResult(result)
          const attached = attachResultToPendingDelegationToolEntry(entries, normalizedResult, {
            source: "structured",
            direction: "earliest",
          })
          if (!attached) {
            entries.push({
              toolCall: {
                name: "tool_call",
                arguments: {},
              },
              result: normalizedResult,
              source: "structured",
            })
          }
        }
      }
      continue
    }

    if (message.role !== "tool") {
      continue
    }

    const parsedToolUse = parseDelegationToolUsePayload(message.content)
    if (parsedToolUse) {
      entries.push({
        toolCall: {
          name: message.toolName || parsedToolUse.name || "tool_call",
          arguments: normalizeDelegationToolArguments(message.toolInput ?? parsedToolUse.input),
        },
        source: "legacy",
      })
      continue
    }

    const normalizedMessageContent = (message.content ?? "").trim()
    if (TOOL_RESULT_PREFIX.test(normalizedMessageContent)) {
      const attached = attachResultToPendingDelegationToolEntry(
        entries,
        normalizeDelegationToolResult({
          success: true,
          content: normalizeDelegationToolResultContent(message.content),
        }),
        { source: "legacy", direction: "latest" },
      )
      if (!attached) {
        entries.push({
          toolCall: {
            name: message.toolName || "tool_call",
            arguments: normalizeDelegationToolArguments(message.toolInput),
          },
          result: normalizeDelegationToolResult({
            success: true,
            content: normalizeDelegationToolResultContent(message.content),
          }),
          source: "legacy",
        })
      }
      continue
    }

    if (message.toolName || message.toolInput !== undefined) {
      const normalizedContent = normalizeDelegationToolResultContent(message.content)
      entries.push({
        toolCall: {
          name: message.toolName || "tool_call",
          arguments: normalizeDelegationToolArguments(message.toolInput),
        },
        result: normalizedContent
          ? normalizeDelegationToolResult({
              success: true,
              content: normalizedContent,
            })
          : undefined,
        source: "legacy",
      })
      continue
    }
  }

  const toolCalls = entries.map((entry) => entry.toolCall)
  const toolResults = entries
    .map((entry) => entry.result)
    .filter((result): result is ToolResult => !!result)
  const toolExecutions = entries.map((entry) => ({
    toolCall: entry.toolCall,
    ...(entry.result ? { result: entry.result } : {}),
  }))

  return {
    toolCalls: toolCalls.length > 0 ? toolCalls : undefined,
    toolResults: toolResults.length > 0 ? toolResults : undefined,
    toolExecutions: toolExecutions.length > 0 ? toolExecutions : undefined,
  }
}

export function createAgentDelegationProgressMessages(
  steps?: AgentProgressStep[],
): AgentDelegationProgressMessage[] {
  if (!steps || steps.length === 0) {
    return []
  }

  const latestDelegationsByRunId = new Map<string, { delegation: ACPDelegationProgress; timestamp: number }>()

  for (const step of steps) {
    if (!step.delegation?.runId) {
      continue
    }

    const timestamp = step.timestamp || step.delegation.endTime || step.delegation.startTime || Date.now()
    const existing = latestDelegationsByRunId.get(step.delegation.runId)

    if (!existing || timestamp >= existing.timestamp) {
      latestDelegationsByRunId.set(step.delegation.runId, {
        delegation: step.delegation,
        timestamp,
      })
    }
  }

  return Array.from(latestDelegationsByRunId.values())
    .sort((a, b) => a.timestamp - b.timestamp)
    .map(({ delegation, timestamp }) => {
      const summary = summarizeAgentDelegation(delegation)
      const fallbackContent = `Delegated to ${delegation.agentName} · ${formatAgentDelegationStatus(delegation.status)}${summary ? `\n${summary}` : ""}`

      return {
        id: `delegation-${delegation.runId}`,
        role: "assistant",
        variant: "delegation",
        timestamp,
        content: fallbackContent,
        ...getAgentDelegationToolMetadata(delegation),
      }
    })
}
