/**
 * Agent progress tracking types — unified superset for desktop and mobile.
 *
 * Desktop‑only and mobile‑only fields are marked optional so both platforms
 * can consume the same interface without breaking.
 */

import type { ToolCall, ToolResult, ConversationHistoryMessage } from './types'
import {
  normalizeAgentConversationState,
  type AgentConversationState,
} from './conversation-state'
import { extractSubAgentToolDisplayContent } from './delegation-tool-display'

// ---------------------------------------------------------------------------
// ACP (Agent Communication Protocol) related types
// ---------------------------------------------------------------------------

/**
 * A message in a sub-agent conversation (desktop-specific, optional in shared).
 */
export interface ACPSubAgentMessage {
  /** Role of the sender */
  role: 'user' | 'assistant' | 'tool'
  /** Message content */
  content: string
  /** Structured tool calls when available */
  toolCalls?: ToolCall[]
  /** Structured tool results when available */
  toolResults?: ToolResult[]
  /** Tool name if this is a tool call/result */
  toolName?: string
  /** Tool input (for tool calls) */
  toolInput?: unknown
  /** Timestamp */
  timestamp: number
}

/**
 * Progress information for a delegated ACP sub-agent.
 */
export interface ACPDelegationProgress {
  /** Unique identifier for this delegation run */
  runId: string
  /** Name of the ACP agent being delegated to */
  agentName: string
  /** How this delegated run is connected/executed */
  connectionType?: 'internal' | 'acpx' | 'acp' | 'stdio' | 'remote'
  /** The task that was delegated */
  task: string
  /** Current status of the delegation */
  status: 'pending' | 'spawning' | 'running' | 'completed' | 'failed' | 'cancelled'
  /** Optional progress message from the sub-agent */
  progressMessage?: string
  /** When the delegation started */
  startTime: number
  /** When the delegation ended (if complete) */
  endTime?: number
  /** Result summary (if completed) */
  resultSummary?: string
  /** Error message (if failed) */
  error?: string
  /** Session ID for local ACP/stdio delegated sessions */
  acpSessionId?: string
  /** Internal DotAgents sub-session ID for internal delegations */
  subSessionId?: string
  /** DotAgents conversation ID for internal/stateful delegated sessions */
  conversationId?: string
  /** Remote ACP run ID for externally-managed async delegations */
  acpRunId?: string
  /** Full conversation history from the sub-agent */
  conversation?: ACPSubAgentMessage[]
}

/**
 * State of all active ACP delegations for a session.
 */
export interface ACPDelegationState {
  /** Session ID of the parent agent */
  parentSessionId: string
  /** All delegations for this session */
  delegations: ACPDelegationProgress[]
  /** Number of active (non-completed) delegations */
  activeCount: number
}

/**
 * Value option for an ACP configuration dropdown/choice.
 */
export interface ACPConfigOptionValue {
  value: string
  name: string
  description?: string
}

/**
 * A configurable option exposed by an ACP agent.
 */
export interface ACPConfigOption {
  id: string
  name: string
  description?: string
  category?: string
  type: string
  currentValue: string
  options: ACPConfigOptionValue[]
}

// ---------------------------------------------------------------------------
// Agent step summary (dual-model mode, desktop-specific)
// ---------------------------------------------------------------------------

/**
 * Agent step summary generated by a weak/summarization model.
 */
export interface AgentStepSummary {
  id: string
  sessionId: string
  stepNumber: number
  timestamp: number

  /** What the agent just did (single line) */
  actionSummary: string

  /**
   * Durable note candidates extracted from this step.
   * These should be reusable in future sessions (preferences, constraints,
   * decisions, facts, insights), NOT step-by-step telemetry.
   */
  noteCandidates?: string[]

  // --- Desktop-specific metadata ---
  importance?: 'low' | 'medium' | 'high' | 'critical'
  savedToKnowledgeNote?: boolean
  userNotes?: string
  tags?: string[]

  // Legacy fields (kept for backward compatibility)
  keyFindings?: string[]
  nextSteps?: string
  decisionsMade?: string[]
}

// ---------------------------------------------------------------------------
// AgentProgressStep — unified superset
// ---------------------------------------------------------------------------

/**
 * A single step in an agent's progress.
 *
 * The `type` field is the union of desktop and mobile step types.
 * The `status` field is the union of desktop and mobile status values.
 */
export interface AgentProgressStep {
  id: string
  type:
    | 'thinking'
    | 'tool_call'
    | 'tool_result'
    | 'completion'
    | 'tool_approval'
    // Mobile-specific types:
    | 'response'
    | 'error'
    | 'pending_approval'
  title: string
  description?: string
  status:
    | 'pending'
    | 'in_progress'
    | 'completed'
    | 'error'
    // Desktop-specific statuses:
    | 'awaiting_approval'
  timestamp: number

  // --- Shared fields ---
  llmContent?: string
  toolCall?: ToolCall
  toolResult?: ToolResult

  // --- Mobile-specific ---
  /** Raw content string (mobile uses this instead of llmContent in some cases) */
  content?: string

  // --- Desktop-specific ---
  approvalRequest?: {
    approvalId: string
    toolName: string
    arguments: any
  }
  /** If this step is a delegation to a sub-agent */
  delegation?: ACPDelegationProgress
  executionStats?: {
    durationMs?: number
    totalTokens?: number
    toolUseCount?: number
    inputTokens?: number
    outputTokens?: number
    cacheHitTokens?: number
  }
  subagentId?: string
}

export type AgentRetryInfo = {
  isRetrying: boolean
  attempt: number
  maxAttempts?: number
  delaySeconds: number
  reason: string
  startedAt: number
}

export type AgentRetryProgressCallback = (info: AgentRetryInfo) => void

/**
 * Ordered user-facing response emitted during a single agent run.
 * Consumers should use `id` for playback/delivery dedupe instead of raw text.
 */
export interface AgentUserResponseEvent {
  id: string
  sessionId: string
  runId?: number
  ordinal: number
  text: string
  timestamp: number
}

// ---------------------------------------------------------------------------
// AgentProgressUpdate — unified superset
// ---------------------------------------------------------------------------

/**
 * Full progress update for an agent session.
 *
 * All platform-specific fields are optional so that both desktop and mobile
 * can use this single type without breaking.
 */
export interface AgentProgressUpdate {
  sessionId: string
  /** Parent session ID when this update belongs to a delegated sub-agent/sub-session. */
  parentSessionId?: string
  conversationId?: string
  currentIteration: number
  maxIterations: number
  steps: AgentProgressStep[]
  isComplete: boolean

  // --- Shared fields ---
  conversationState?: AgentConversationState
  finalContent?: string
  /**
   * User-facing response set via respond_to_user tool.
   * On voice interfaces: spoken aloud via TTS.
   * On messaging channels (mobile, WhatsApp): sent as a message.
   * Consumers should fall back to finalContent if this is not set.
   */
  userResponse?: string
  /**
   * Ordered respond_to_user events for the current run.
   * Prefer this over `userResponse` / `userResponseHistory` when available.
   */
  responseEvents?: AgentUserResponseEvent[]
  conversationHistory?: ConversationHistoryMessage[]
  /** Total history size when `conversationHistory` is a lazy-loaded display window. */
  conversationHistoryTotalCount?: number
  /** Start index of `conversationHistory` within the full persisted history window. */
  conversationHistoryStartIndex?: number
  streamingContent?: {
    text: string
    isStreaming: boolean
  }

  // --- Mobile-specific ---
  /** @deprecated Use userResponse instead. Kept for backward compatibility with older backends. */
  spokenContent?: string

  // --- Desktop-specific ---
  /**
   * Monotonic run counter for a reused session ID.
   * Lets the renderer ignore stale updates from older runs.
   */
  runId?: number
  conversationTitle?: string
  isSnoozed?: boolean
  /**
   * History of past respond_to_user calls (excluding the current/latest one).
   * Shown as collapsed items in the UI with TTS playback support.
   */
  userResponseHistory?: string[]
  sessionStartIndex?: number
  pendingToolApproval?: {
    approvalId: string
    toolName: string
    arguments: any
  }
  retryInfo?: AgentRetryInfo
  contextInfo?: {
    estTokens: number
    maxTokens: number
  }
  modelInfo?: {
    provider: string
    model: string
  }
  /** Profile name associated with this session (from profile snapshot) */
  profileName?: string
  acpSessionInfo?: {
    agentName?: string
    agentTitle?: string
    agentVersion?: string
    currentModel?: string
    currentMode?: string
    availableModels?: Array<{ id: string; name: string; description?: string }>
    availableModes?: Array<{ id: string; name: string; description?: string }>
    configOptions?: ACPConfigOption[]
  }
  /** Dual-model summarization data */
  stepSummaries?: AgentStepSummary[]
  latestSummary?: AgentStepSummary
}

/**
 * Callback type for progress updates.
 */
export type OnProgressCallback = (update: AgentProgressUpdate) => void

export type AgentProgressConversationStateInput =
  Pick<AgentProgressUpdate, 'conversationState' | 'isComplete' | 'pendingToolApproval' | 'finalContent'> &
  Partial<Pick<AgentProgressUpdate, 'steps'>>

export function resolveAgentProgressConversationState(
  update: AgentProgressConversationStateInput,
  lifecycleState: AgentConversationState = update.isComplete ? 'complete' : 'running',
): AgentConversationState {
  if (update.conversationState) {
    return normalizeAgentConversationState(update.conversationState, lifecycleState)
  }

  if (
    update.pendingToolApproval ||
    update.steps?.some((step) => step.type === 'pending_approval')
  ) {
    return 'needs_input'
  }

  const isKillSwitchCompletion =
    update.isComplete &&
    typeof update.finalContent === 'string' &&
    update.finalContent.includes('emergency kill switch')

  if (isKillSwitchCompletion) {
    return 'blocked'
  }

  return lifecycleState
}

export function getAgentDelegationChildSessionIds(delegation: ACPDelegationProgress): string[] {
  return [
    delegation.subSessionId,
    delegation.acpSessionId,
    delegation.runId,
  ].flatMap((value) => {
    const normalized = value?.trim()
    return normalized ? [normalized] : []
  })
}

export function getAgentDelegationDisplayTitle(delegation: ACPDelegationProgress): string | null {
  const task = delegation.task?.trim()
  if (task) return task

  const agentName = delegation.agentName?.trim()
  return agentName ? `${agentName} subagent` : null
}

export function getSubagentParentSessionIdMap(
  progressEntries: Iterable<[string, Pick<AgentProgressUpdate, "steps">]>,
): Map<string, string> {
  const parentSessionIdsByChildId = new Map<string, string>()

  for (const [parentSessionId, progress] of progressEntries) {
    for (const step of progress.steps ?? []) {
      const delegation = step.delegation
      if (!delegation) continue

      for (const normalizedChildSessionId of getAgentDelegationChildSessionIds(delegation)) {
        if (
          normalizedChildSessionId === parentSessionId ||
          parentSessionIdsByChildId.has(normalizedChildSessionId)
        ) {
          continue
        }
        parentSessionIdsByChildId.set(normalizedChildSessionId, parentSessionId)
      }
    }
  }

  return parentSessionIdsByChildId
}

export function getSubagentTitleBySessionIdMap(
  progressEntries: Iterable<[string, Pick<AgentProgressUpdate, "steps">]>,
): Map<string, string> {
  const titlesByChildId = new Map<string, string>()

  for (const [parentSessionId, progress] of progressEntries) {
    for (const step of progress.steps ?? []) {
      const delegation = step.delegation
      if (!delegation) continue

      const title = getAgentDelegationDisplayTitle(delegation)
      if (!title) continue

      for (const childSessionId of getAgentDelegationChildSessionIds(delegation)) {
        if (
          childSessionId === parentSessionId ||
          titlesByChildId.has(childSessionId)
        ) {
          continue
        }
        titlesByChildId.set(childSessionId, title)
      }
    }
  }

  return titlesByChildId
}

export interface AgentDelegationProgressMessage {
  id: string
  role: "assistant"
  content: string
  timestamp: number
  delegation: ACPDelegationProgress
  toolCalls?: ToolCall[]
  toolResults?: ToolResult[]
  /** Render-only aligned call/result pairs for pending delegation tool activity. */
  toolExecutions?: Array<{ toolCall: ToolCall; result?: ToolResult }>
  variant: "delegation"
}

export interface AgentDelegationPresentation {
  statusLabel: string
  subtitle: string
  sourceLabel: string
  trackingLabel: string | null
  activityTimestamp: number
  messageCount: number
  isActive: boolean
}

export interface AgentDelegationSummaryEntry extends AgentDelegationPresentation {
  delegation: ACPDelegationProgress
}

export interface AgentDelegationCardState<TToolEntry> {
  presentation: AgentDelegationPresentation
  conversationPreview: AgentDelegationConversationPreviewState
  toolPreview: AgentDelegationToolPreviewState<TToolEntry>
}

export interface AgentDelegationConversationPreviewRow {
  role: ACPSubAgentMessage["role"]
  roleLabel: string
  content: string
  timestamp: number
  timestampLabel: string | null
}

export interface AgentDelegationConversationPreviewState {
  rows: AgentDelegationConversationPreviewRow[]
  hiddenCount: number
}

export interface AgentDelegationToolPreviewState<TEntry> {
  rows: TEntry[]
  hiddenCount: number
}

export type AgentDelegationConversationMessageRoleTone = "user" | "assistant" | "tool" | "default"

export interface AgentDelegationConversationMessageRoleState {
  label: string
  tone: AgentDelegationConversationMessageRoleTone
}

export interface AgentDelegationConversationMessageDisplayState {
  role: AgentDelegationConversationMessageRoleState
  timestampLabel: string | null
  isToolMessage: boolean
  content: string
  isLongContent: boolean
  shouldShowToggle: boolean
  toolSummary: string | null
  serializedToolInput: string | null
  rawToolPayload: string | null
  shouldShowRawToolPayload: boolean
}

function formatAgentDelegationStatus(status: ACPDelegationProgress["status"]): string {
  switch (status) {
    case "pending":
      return "Pending"
    case "spawning":
      return "Spawning"
    case "running":
      return "Running"
    case "completed":
      return "Completed"
    case "failed":
      return "Failed"
    case "cancelled":
      return "Cancelled"
    default:
      return status
  }
}

export function formatAgentDelegationDisplayStatus(status: ACPDelegationProgress["status"]): string {
  switch (status) {
    case "pending":
    case "spawning":
      return "Starting"
    case "running":
      return "Running"
    case "completed":
      return "Completed"
    case "cancelled":
      return "Cancelled"
    case "failed":
    default:
      return "Failed"
  }
}

export function isAgentDelegationActiveStatus(status: ACPDelegationProgress["status"]): boolean {
  return status === "pending" || status === "spawning" || status === "running"
}

function truncateAgentDelegationPreview(text: string | undefined, maxLength: number): string {
  const normalized = (text ?? "").trim().replace(/\s+/g, " ")
  if (!normalized) return ""
  if (normalized.length <= maxLength) return normalized
  return `${normalized.slice(0, Math.max(0, maxLength - 1))}…`
}

export function formatAgentDelegationConversationTimestamp(timestamp?: number | null): string | null {
  if (typeof timestamp !== "number" || !Number.isFinite(timestamp) || timestamp <= 0) {
    return null
  }

  return new Date(timestamp).toLocaleTimeString([], { hour: "numeric", minute: "2-digit" })
}

export function getAgentDelegationConversationMessageRoleState(
  message: ACPSubAgentMessage,
  agentName: string,
): AgentDelegationConversationMessageRoleState {
  if (message.role === "assistant") {
    return {
      label: agentName,
      tone: "assistant",
    }
  }

  if (message.role === "tool") {
    const parsedToolUse = parseAgentDelegationToolUseMessage(message)
    const parsedToolResult = extractSubAgentToolDisplayContent(message.content ?? "")
    return {
      label: message.toolName || parsedToolUse?.toolName || parsedToolResult.toolName || "Tool",
      tone: "tool",
    }
  }

  if (message.role === "user") {
    return {
      label: "Task",
      tone: "user",
    }
  }

  return {
    label: "Message",
    tone: "default",
  }
}

function getAgentDelegationConversationMessagePreviewContent(
  message: ACPSubAgentMessage,
  maxLength: number,
): string {
  if (message.role === "tool" && message.content?.trim()) {
    const parsedToolResult = extractSubAgentToolDisplayContent(message.content)
    if (parsedToolResult.summary.trim()) {
      return truncateAgentDelegationPreview(parsedToolResult.summary, maxLength)
    }
  }

  if (message.content?.trim()) {
    return truncateAgentDelegationPreview(message.content, maxLength)
  }

  if (message.toolInput !== undefined) {
    try {
      return truncateAgentDelegationPreview(JSON.stringify(message.toolInput), maxLength)
    } catch {
      return truncateAgentDelegationPreview(String(message.toolInput), maxLength)
    }
  }

  return ""
}

function getAgentDelegationConversationPreviewRow(
  message: ACPSubAgentMessage,
  agentName: string,
  maxLength: number,
): AgentDelegationConversationPreviewRow | null {
  const content = getAgentDelegationConversationMessagePreviewContent(message, maxLength)
  if (!content) return null

  return {
    role: message.role,
    roleLabel: getAgentDelegationConversationMessageRoleState(message, agentName).label,
    content,
    timestamp: message.timestamp,
    timestampLabel: formatAgentDelegationConversationTimestamp(message.timestamp),
  }
}

export function getAgentDelegationConversationPreview(
  conversation: ACPSubAgentMessage[] | undefined,
  agentName: string,
  maxLength: number,
): string {
  const lastMessage = conversation?.[conversation.length - 1]
  if (!lastMessage) return "No conversation yet"

  const roleLabel = getAgentDelegationConversationMessageRoleState(lastMessage, agentName).label
  const content = getAgentDelegationConversationMessagePreviewContent(lastMessage, maxLength)

  return truncateAgentDelegationPreview(`${roleLabel}: ${content}`, maxLength)
}

export function formatAgentDelegationConversationTranscript(
  conversation: ACPSubAgentMessage[] | undefined,
  agentName: string,
): string {
  return (conversation ?? [])
    .map((message) => {
      const role = getAgentDelegationConversationMessageRoleState(message, agentName)
      return `[${role.label}]\n${message.content}`
    })
    .join("\n\n---\n\n")
}

function formatAgentDelegationToolInputForDisplay(toolInput: unknown): string | null {
  if (toolInput === undefined) {
    return null
  }

  try {
    return JSON.stringify(toolInput, null, 2)
  } catch {
    return String(toolInput)
  }
}

export function getAgentDelegationConversationMessageDisplayState(
  message: ACPSubAgentMessage,
  agentName: string,
  options: { longContentThreshold?: number } = {},
): AgentDelegationConversationMessageDisplayState {
  const isToolMessage = message.role === "tool"
  const role = getAgentDelegationConversationMessageRoleState(message, agentName)
  const timestampLabel = formatAgentDelegationConversationTimestamp(message.timestamp)
  const longContentThreshold = Math.max(0, Math.floor(options.longContentThreshold ?? 300))
  const toolContent = isToolMessage
    ? extractSubAgentToolDisplayContent(message.content ?? "")
    : null
  const content = toolContent?.summary ?? message.content
  const rawToolPayload = toolContent?.rawContent && toolContent.rawContent !== toolContent.summary
    ? toolContent.rawContent
    : null
  const isLongContent = content.length > longContentThreshold

  return {
    role,
    timestampLabel,
    isToolMessage,
    content,
    isLongContent,
    shouldShowToggle: isLongContent,
    toolSummary: toolContent?.summary ?? null,
    serializedToolInput: formatAgentDelegationToolInputForDisplay(message.toolInput),
    rawToolPayload,
    shouldShowRawToolPayload: !!rawToolPayload,
  }
}

export function getAgentDelegationConversationPreviewRows(
  conversation: ACPSubAgentMessage[] | undefined,
  agentName: string,
  options: {
    maxRows?: number
    maxLength?: number
    includeAll?: boolean
  } = {},
): AgentDelegationConversationPreviewRow[] {
  return getAgentDelegationConversationPreviewState(conversation, agentName, options).rows
}

export function getAgentDelegationConversationPreviewState(
  conversation: ACPSubAgentMessage[] | undefined,
  agentName: string,
  options: {
    maxRows?: number
    maxLength?: number
    includeAll?: boolean
  } = {},
): AgentDelegationConversationPreviewState {
  const maxRows = Math.max(0, Math.floor(options.maxRows ?? 2))
  const maxLength = Math.max(1, Math.floor(options.maxLength ?? 96))
  if (!conversation?.length) return { rows: [], hiddenCount: 0 }

  const renderableRows: AgentDelegationConversationPreviewRow[] = []
  for (let index = 0; index < conversation.length; index += 1) {
    const message = conversation[index]
    if (!message) continue

    const row = getAgentDelegationConversationPreviewRow(message, agentName, maxLength)
    if (row) renderableRows.push(row)
  }

  const rows = options.includeAll
    ? renderableRows
    : maxRows === 0
      ? []
      : renderableRows.slice(-maxRows)
  return {
    rows,
    hiddenCount: Math.max(0, renderableRows.length - rows.length),
  }
}

export function getAgentDelegationToolPreviewState<TEntry>(
  entries: readonly TEntry[] | undefined,
  options: {
    maxRows?: number
    includeAll?: boolean
  } = {},
): AgentDelegationToolPreviewState<TEntry> {
  const allEntries = entries ? Array.from(entries) : []
  if (allEntries.length === 0) return { rows: [], hiddenCount: 0 }

  const rawMaxRows = options.maxRows ?? 3
  const maxRows = Number.isFinite(rawMaxRows)
    ? Math.max(0, Math.floor(rawMaxRows))
    : 3
  const rows = options.includeAll
    ? allEntries
    : maxRows === 0
      ? []
      : allEntries.slice(0, maxRows)

  return {
    rows,
    hiddenCount: Math.max(0, allEntries.length - rows.length),
  }
}

export function getAgentDelegationSubtitle(delegation: ACPDelegationProgress, maxLength: number): string {
  const source = delegation.status === "failed"
    ? delegation.error ?? delegation.progressMessage
    : delegation.status === "completed"
      ? delegation.resultSummary ?? delegation.progressMessage
      : delegation.progressMessage

  const conversationPreview = delegation.conversation?.length
    ? getAgentDelegationConversationPreview(delegation.conversation, delegation.agentName, maxLength)
    : ""

  return truncateAgentDelegationPreview(source, maxLength)
    || conversationPreview
    || truncateAgentDelegationPreview(delegation.task, maxLength)
}

export function getAgentDelegationSourceLabel(delegation: ACPDelegationProgress): string {
  switch (delegation.connectionType) {
    case "internal":
      return "Internal session"
    case "acpx":
    case "acp":
    case "stdio":
      return delegation.acpSessionId ? "acpx session" : "acpx agent"
    case "remote":
      return delegation.acpRunId ? "Remote ACP run" : "Remote agent"
    default:
      return "Delegated run"
  }
}

export function getAgentDelegationTrackingLabel(delegation: ACPDelegationProgress): string | null {
  if (delegation.subSessionId) return `Session ${delegation.subSessionId.slice(-8)}`
  if (delegation.acpSessionId) return `Session ${delegation.acpSessionId.slice(-8)}`
  if (delegation.acpRunId) return `Run ${delegation.acpRunId.slice(-8)}`
  return null
}

export function getAgentDelegationActivityTimestamp(delegation: ACPDelegationProgress): number {
  return delegation.conversation?.[delegation.conversation.length - 1]?.timestamp
    ?? delegation.endTime
    ?? delegation.startTime
}

export function getAgentDelegationPresentation(
  delegation: ACPDelegationProgress,
  maxSubtitleLength: number,
): AgentDelegationPresentation {
  return {
    statusLabel: formatAgentDelegationDisplayStatus(delegation.status),
    subtitle: getAgentDelegationSubtitle(delegation, maxSubtitleLength),
    sourceLabel: getAgentDelegationSourceLabel(delegation),
    trackingLabel: getAgentDelegationTrackingLabel(delegation),
    activityTimestamp: getAgentDelegationActivityTimestamp(delegation),
    messageCount: delegation.conversation?.length ?? 0,
    isActive: isAgentDelegationActiveStatus(delegation.status),
  }
}

export function getAgentDelegationSummaryEntries(
  steps: AgentProgressStep[] | undefined,
  options: { maxSubtitleLength?: number } = {},
): AgentDelegationSummaryEntry[] {
  const latestByRunId = new Map<string, { delegation: ACPDelegationProgress; timestamp: number }>()

  for (const step of steps ?? []) {
    if (!step.delegation) continue

    const timestamp = step.timestamp ?? getAgentDelegationActivityTimestamp(step.delegation)
    const existing = latestByRunId.get(step.delegation.runId)
    if (!existing || timestamp >= existing.timestamp) {
      latestByRunId.set(step.delegation.runId, {
        delegation: step.delegation,
        timestamp,
      })
    }
  }

  const maxSubtitleLength = Math.max(0, Math.floor(options.maxSubtitleLength ?? 140))

  return Array.from(latestByRunId.values())
    .map(({ delegation, timestamp }) => ({
      delegation,
      ...getAgentDelegationPresentation(delegation, maxSubtitleLength),
      activityTimestamp: timestamp,
    }))
    .sort((a, b) => b.activityTimestamp - a.activityTimestamp)
}

export function getAgentDelegationCardState<TToolEntry>(
  delegation: ACPDelegationProgress,
  toolEntries: readonly TToolEntry[] | undefined,
  options: {
    maxSubtitleLength: number
    conversationPreviewMaxRows: number
    conversationPreviewMaxLength: number
    includeAllConversationPreview?: boolean
    toolPreviewMaxRows: number
    includeAllToolPreview?: boolean
  },
): AgentDelegationCardState<TToolEntry> {
  return {
    presentation: getAgentDelegationPresentation(delegation, options.maxSubtitleLength),
    conversationPreview: getAgentDelegationConversationPreviewState(
      delegation.conversation,
      delegation.agentName,
      {
        maxRows: options.conversationPreviewMaxRows,
        maxLength: options.conversationPreviewMaxLength,
        includeAll: options.includeAllConversationPreview,
      },
    ),
    toolPreview: getAgentDelegationToolPreviewState(toolEntries, {
      maxRows: options.toolPreviewMaxRows,
      includeAll: options.includeAllToolPreview,
    }),
  }
}

function summarizeAgentDelegation(delegation: ACPDelegationProgress): string {
  if (delegation.status === "failed") {
    return delegation.error || delegation.progressMessage || delegation.task
  }
  if (delegation.status === "completed") {
    return delegation.resultSummary || delegation.progressMessage || delegation.task
  }

  const conversationSnippet = delegation.conversation?.[delegation.conversation.length - 1]?.content
  return delegation.progressMessage || conversationSnippet || delegation.task
}

const TOOL_USE_PREFIX = /^using tool:\s*/i
const TOOL_RESULT_PREFIX = /^tool result:\s*/i

type DelegationToolEntry = {
  toolCall: ToolCall
  result?: ToolResult
  source: "structured" | "legacy"
}

export interface AgentDelegationToolExecutionData {
  timestamp: number
  calls: ToolCall[]
  results: Array<ToolResult | undefined>
}

export type AgentDelegationConversationRenderItem =
  | { kind: "message"; key: string; message: ACPSubAgentMessage }
  | {
      kind: "tool_execution"
      key: string
      execution: AgentDelegationToolExecutionData
    }

function normalizeDelegationToolArguments(input: unknown): Record<string, unknown> {
  if (input && typeof input === "object" && !Array.isArray(input)) {
    return input as Record<string, unknown>
  }
  if (input === undefined) {
    return {}
  }
  return { input }
}

function parseDelegationToolUsePayload(content?: string): { name?: string; input?: unknown } | null {
  const trimmedContent = (content ?? "").trim()
  if (!TOOL_USE_PREFIX.test(trimmedContent)) {
    return null
  }

  const nameMatch = trimmedContent.match(/^using tool:\s*([^\n]+)/i)
  const inputMatch = trimmedContent.match(/\ninput:\s*([\s\S]*)$/i)
  const rawInput = inputMatch?.[1]?.trim()

  let parsedInput: unknown = undefined
  if (rawInput) {
    try {
      parsedInput = JSON.parse(rawInput)
    } catch {
      parsedInput = rawInput
    }
  }

  return {
    name: nameMatch?.[1]?.trim() || undefined,
    input: parsedInput,
  }
}

function normalizeDelegationToolResultContent(content?: string): string {
  return (content ?? "").replace(TOOL_RESULT_PREFIX, "").trim()
}

function hasDelegationToolError(result: { error?: string }): boolean {
  return result.error !== undefined && result.error !== null
}

function defaultDelegationToolResultContent(result: { success?: boolean; content?: string; error?: string }): string {
  if (typeof result.content === "string") {
    return result.content
  }
  if (result.success === false || hasDelegationToolError(result)) {
    return "Tool failed"
  }
  return "Tool completed"
}

function normalizeDelegationToolResult(result: Partial<ToolResult>): ToolResult {
  return {
    success: !hasDelegationToolError(result) && result.success !== false,
    content: defaultDelegationToolResultContent(result),
    error: result.error,
  }
}

function parseAgentDelegationToolUseMessage(
  message: ACPSubAgentMessage,
): { toolName?: string; toolInput?: unknown } | null {
  if (message.role !== "tool") {
    return null
  }

  const parsed = parseDelegationToolUsePayload(message.content)
  if (!parsed) {
    return null
  }

  return {
    toolName: message.toolName || parsed.name,
    toolInput: message.toolInput ?? parsed.input,
  }
}

function isAgentDelegationToolUseMessage(message: ACPSubAgentMessage): boolean {
  return parseAgentDelegationToolUseMessage(message) !== null
}

function isAgentDelegationToolResultMessage(message: ACPSubAgentMessage): boolean {
  return message.role === "tool" && TOOL_RESULT_PREFIX.test((message.content ?? "").trim())
}

function isAgentDelegationStructuredToolInvocationMessage(message: ACPSubAgentMessage): boolean {
  if (message.role !== "tool") return false
  if (isAgentDelegationToolResultMessage(message)) return false
  return !!(message.toolName || message.toolInput !== undefined)
}

function toAgentDelegationToolExecutionResult(
  result: { success: boolean; content: string; error?: string },
): ToolResult {
  return {
    success: result.success,
    content: result.content,
    error: result.error,
  }
}

function normalizeAgentDelegationStructuredToolResultContent(
  result: { success?: boolean; content?: string; error?: string },
): string {
  if (typeof result.content === "string") {
    return result.content
  }

  if (result.success === false || hasDelegationToolError(result)) {
    return "Tool failed"
  }

  return "Tool completed"
}

function buildAgentDelegationStructuredToolExecution(
  message: ACPSubAgentMessage,
): AgentDelegationToolExecutionData | null {
  const toolCalls = Array.isArray(message.toolCalls) ? message.toolCalls : []
  const toolResults = Array.isArray(message.toolResults) ? message.toolResults : []
  if (toolCalls.length === 0 && toolResults.length === 0) {
    return null
  }

  const maxEntries = Math.max(toolCalls.length, toolResults.length)
  const calls: ToolCall[] = []
  const results: Array<ToolResult | undefined> = []

  for (let index = 0; index < maxEntries; index += 1) {
    const call = toolCalls[index]
    const result = toolResults[index]

    calls.push({
      name: call?.name?.trim() || "tool_call",
      arguments: normalizeDelegationToolArguments(call?.arguments),
    })

    if (!result) {
      results.push(undefined)
      continue
    }

    results.push(toAgentDelegationToolExecutionResult({
      success: !hasDelegationToolError(result) && result.success !== false,
      content: normalizeAgentDelegationStructuredToolResultContent(result),
      error: result.error,
    }))
  }

  return {
    timestamp: message.timestamp,
    calls,
    results,
  }
}

function buildAgentDelegationLegacyToolExecution(
  message: ACPSubAgentMessage,
  delegationStatus: ACPDelegationProgress["status"],
  resultMessage?: ACPSubAgentMessage,
): AgentDelegationToolExecutionData {
  const parsedUseMessage = parseAgentDelegationToolUseMessage(message)
  const isStructuredToolUseMessage = isAgentDelegationStructuredToolInvocationMessage(message)
  const parsedMessage = extractSubAgentToolDisplayContent(message.content ?? "")
  const parsedResult = resultMessage ? extractSubAgentToolDisplayContent(resultMessage.content ?? "") : null
  const toolName = parsedUseMessage?.toolName
    || message.toolName
    || parsedMessage.toolName
    || resultMessage?.toolName
    || parsedResult?.toolName
    || "Tool"
  const toolInput = parsedUseMessage?.toolInput ?? message.toolInput
  const isToolUseMessage = !!parsedUseMessage || isStructuredToolUseMessage
  const isDelegationActive = isAgentDelegationActiveStatus(delegationStatus)
  const isPending = isToolUseMessage && !resultMessage && isDelegationActive

  let result: ToolResult | undefined
  if (resultMessage) {
    result = toAgentDelegationToolExecutionResult({
      success: true,
      content: parsedResult?.summary || "Tool completed",
    })
  } else if (!isToolUseMessage) {
    result = toAgentDelegationToolExecutionResult({
      success: true,
      content: parsedMessage.summary || "Tool completed",
    })
  } else if (!isDelegationActive) {
    if (delegationStatus === "failed") {
      result = toAgentDelegationToolExecutionResult({
        success: false,
        content: "",
        error: "Delegation failed before a tool result was captured.",
      })
    } else if (delegationStatus === "cancelled") {
      result = toAgentDelegationToolExecutionResult({
        success: false,
        content: "",
        error: "Delegation was cancelled before a tool result was captured.",
      })
    } else {
      result = toAgentDelegationToolExecutionResult({
        success: true,
        content: "Tool completed",
      })
    }
  }

  return {
    timestamp: resultMessage?.timestamp ?? message.timestamp,
    calls: [{ name: toolName, arguments: normalizeDelegationToolArguments(toolInput) }],
    results: [isPending ? undefined : result],
  }
}

export function getAgentDelegationConversationRenderItems(
  conversation: ACPSubAgentMessage[],
  delegationStatus: ACPDelegationProgress["status"],
): AgentDelegationConversationRenderItem[] {
  const items: AgentDelegationConversationRenderItem[] = []
  const pendingStructuredResultSlots: Array<{ itemIndex: number; resultIndex: number }> = []

  const hasRenderableStructuredMessageContent = (message: ACPSubAgentMessage): boolean => {
    const content = (message.content ?? "").trim()
    if (!content) return false
    if (message.role !== "tool") return true
    return !TOOL_USE_PREFIX.test(content) && !TOOL_RESULT_PREFIX.test(content)
  }

  const attachStructuredResultToPendingExecution = (result: ToolResult): boolean => {
    while (pendingStructuredResultSlots.length > 0) {
      const pendingSlot = pendingStructuredResultSlots.shift()
      if (!pendingSlot) return false
      const pendingItem = items[pendingSlot.itemIndex]
      if (!pendingItem || pendingItem.kind !== "tool_execution") {
        continue
      }
      if (pendingItem.execution.results[pendingSlot.resultIndex]) {
        continue
      }
      pendingItem.execution.results[pendingSlot.resultIndex] = result
      return true
    }
    return false
  }

  const appendToolExecutionItem = (
    key: string,
    execution: AgentDelegationToolExecutionData,
    trackStructuredPendingSlots = false,
  ): void => {
    const itemIndex = items.length
    items.push({
      kind: "tool_execution",
      key,
      execution,
    })
    if (!trackStructuredPendingSlots) {
      return
    }
    execution.results.forEach((result, resultIndex) => {
      if (!result) {
        pendingStructuredResultSlots.push({ itemIndex, resultIndex })
      }
    })
  }

  for (let index = 0; index < conversation.length; index += 1) {
    const message = conversation[index]
    const structuredToolCalls = Array.isArray(message.toolCalls) ? message.toolCalls : []
    const structuredToolResults = Array.isArray(message.toolResults) ? message.toolResults : []
    const hasStructuredToolData = structuredToolCalls.length > 0 || structuredToolResults.length > 0

    if (hasStructuredToolData && structuredToolCalls.length === 0 && structuredToolResults.length > 0) {
      const unattachedResults: ToolResult[] = []
      for (const rawResult of structuredToolResults) {
        if (!rawResult) continue
        const result = toAgentDelegationToolExecutionResult({
          success: !hasDelegationToolError(rawResult) && rawResult.success !== false,
          content: normalizeAgentDelegationStructuredToolResultContent(rawResult),
          error: rawResult.error,
        })
        if (!attachStructuredResultToPendingExecution(result)) {
          unattachedResults.push(result)
        }
      }

      if (hasRenderableStructuredMessageContent(message)) {
        items.push({ kind: "message", key: `msg-structured-${index}`, message })
      }

      if (unattachedResults.length > 0) {
        appendToolExecutionItem(`tool-structured-orphan-${index}`, {
          timestamp: message.timestamp,
          calls: unattachedResults.map(() => ({ name: "tool_call", arguments: {} })),
          results: unattachedResults,
        }, true)
      }
      continue
    }

    const structuredExecution = buildAgentDelegationStructuredToolExecution(message)
    if (structuredExecution) {
      if (hasRenderableStructuredMessageContent(message)) {
        items.push({ kind: "message", key: `msg-structured-${index}`, message })
      }
      appendToolExecutionItem(`tool-structured-${index}`, structuredExecution, true)
      continue
    }

    if (isAgentDelegationToolUseMessage(message)) {
      const nextMessage = conversation[index + 1]
      if (nextMessage && isAgentDelegationToolResultMessage(nextMessage)) {
        appendToolExecutionItem(
          `tool-${index}-${index + 1}`,
          buildAgentDelegationLegacyToolExecution(message, delegationStatus, nextMessage),
        )
        index += 1
        continue
      }

      appendToolExecutionItem(`tool-${index}`, buildAgentDelegationLegacyToolExecution(message, delegationStatus))
      continue
    }

    if (isAgentDelegationStructuredToolInvocationMessage(message) || isAgentDelegationToolResultMessage(message)) {
      appendToolExecutionItem(`tool-${index}`, buildAgentDelegationLegacyToolExecution(message, delegationStatus))
      continue
    }

    items.push({ kind: "message", key: `msg-${index}`, message })
  }

  return items
}

function attachResultToPendingDelegationToolEntry(
  entries: DelegationToolEntry[],
  result: ToolResult,
  options: { source: DelegationToolEntry["source"]; direction: "earliest" | "latest" },
): boolean {
  const start = options.direction === "earliest" ? 0 : entries.length - 1
  const end = options.direction === "earliest" ? entries.length : -1
  const step = options.direction === "earliest" ? 1 : -1

  for (let index = start; index !== end; index += step) {
    const entry = entries[index]
    if (entry.source !== options.source || entry.result) {
      continue
    }
    entry.result = result
    return true
  }

  return false
}

function getAgentDelegationToolMetadata(
  delegation: ACPDelegationProgress,
): Pick<AgentDelegationProgressMessage, "toolCalls" | "toolResults" | "toolExecutions"> {
  const entries: DelegationToolEntry[] = []

  for (const message of delegation.conversation ?? []) {
    const structuredCalls = Array.isArray(message.toolCalls) ? message.toolCalls : []
    const structuredResults = Array.isArray(message.toolResults) ? message.toolResults : []
    if (structuredCalls.length > 0 || structuredResults.length > 0) {
      for (let index = 0; index < structuredCalls.length; index += 1) {
        const call = structuredCalls[index]
        const result = structuredResults[index]

        entries.push({
          toolCall: {
            name: call?.name?.trim() || "tool_call",
            arguments: normalizeDelegationToolArguments(call?.arguments),
          },
          result: result
            ? normalizeDelegationToolResult(result)
            : undefined,
          source: "structured",
        })
      }
      if (structuredResults.length > structuredCalls.length) {
        for (let index = structuredCalls.length; index < structuredResults.length; index += 1) {
          const result = structuredResults[index]
          if (!result) {
            continue
          }
          const normalizedResult = normalizeDelegationToolResult(result)
          const attached = attachResultToPendingDelegationToolEntry(entries, normalizedResult, {
            source: "structured",
            direction: "earliest",
          })
          if (!attached) {
            entries.push({
              toolCall: {
                name: "tool_call",
                arguments: {},
              },
              result: normalizedResult,
              source: "structured",
            })
          }
        }
      }
      continue
    }

    if (message.role !== "tool") {
      continue
    }

    const parsedToolUse = parseDelegationToolUsePayload(message.content)
    if (parsedToolUse) {
      entries.push({
        toolCall: {
          name: message.toolName || parsedToolUse.name || "tool_call",
          arguments: normalizeDelegationToolArguments(message.toolInput ?? parsedToolUse.input),
        },
        source: "legacy",
      })
      continue
    }

    const normalizedMessageContent = (message.content ?? "").trim()
    if (TOOL_RESULT_PREFIX.test(normalizedMessageContent)) {
      const attached = attachResultToPendingDelegationToolEntry(
        entries,
        normalizeDelegationToolResult({
          success: true,
          content: normalizeDelegationToolResultContent(message.content),
        }),
        { source: "legacy", direction: "latest" },
      )
      if (!attached) {
        entries.push({
          toolCall: {
            name: message.toolName || "tool_call",
            arguments: normalizeDelegationToolArguments(message.toolInput),
          },
          result: normalizeDelegationToolResult({
            success: true,
            content: normalizeDelegationToolResultContent(message.content),
          }),
          source: "legacy",
        })
      }
      continue
    }

    if (message.toolName || message.toolInput !== undefined) {
      const normalizedContent = normalizeDelegationToolResultContent(message.content)
      entries.push({
        toolCall: {
          name: message.toolName || "tool_call",
          arguments: normalizeDelegationToolArguments(message.toolInput),
        },
        result: normalizedContent
          ? normalizeDelegationToolResult({
              success: true,
              content: normalizedContent,
            })
          : undefined,
        source: "legacy",
      })
      continue
    }
  }

  const toolCalls = entries.map((entry) => entry.toolCall)
  const toolResults = entries
    .map((entry) => entry.result)
    .filter((result): result is ToolResult => !!result)
  const toolExecutions = entries.map((entry) => ({
    toolCall: entry.toolCall,
    ...(entry.result ? { result: entry.result } : {}),
  }))

  return {
    toolCalls: toolCalls.length > 0 ? toolCalls : undefined,
    toolResults: toolResults.length > 0 ? toolResults : undefined,
    toolExecutions: toolExecutions.length > 0 ? toolExecutions : undefined,
  }
}

export function createAgentDelegationProgressMessages(
  steps?: AgentProgressStep[],
): AgentDelegationProgressMessage[] {
  if (!steps || steps.length === 0) {
    return []
  }

  const latestDelegationsByRunId = new Map<string, { delegation: ACPDelegationProgress; timestamp: number }>()

  for (const step of steps) {
    if (!step.delegation?.runId) {
      continue
    }

    const timestamp = step.timestamp || step.delegation.endTime || step.delegation.startTime || Date.now()
    const existing = latestDelegationsByRunId.get(step.delegation.runId)

    if (!existing || timestamp >= existing.timestamp) {
      latestDelegationsByRunId.set(step.delegation.runId, {
        delegation: step.delegation,
        timestamp,
      })
    }
  }

  return Array.from(latestDelegationsByRunId.values())
    .sort((a, b) => a.timestamp - b.timestamp)
    .map(({ delegation, timestamp }) => {
      const summary = summarizeAgentDelegation(delegation)
      const fallbackContent = `Delegated to ${delegation.agentName} · ${formatAgentDelegationStatus(delegation.status)}${summary ? `\n${summary}` : ""}`

      return {
        id: `delegation-${delegation.runId}`,
        role: "assistant",
        variant: "delegation",
        timestamp,
        content: fallbackContent,
        delegation,
        ...getAgentDelegationToolMetadata(delegation),
      }
    })
}
