import type { MobileApiRouteActions } from "./mobile-api-routes"
import {
  exportBundle,
  getBundleExportableItems,
  importBundle,
  previewBundleImport,
} from "./bundle-actions"
import { handleChatCompletionRequest } from "./chat-completion-actions"
import {
  createAgentProfile,
  deleteAgentProfile,
  getAgentProfile,
  getAgentProfiles,
  toggleAgentProfile,
  updateAgentProfile,
} from "./agent-profile-actions"
import {
  createConversation,
  getConversation,
  getConversations,
  getConversationVideoAsset,
  updateConversation,
} from "./conversation-actions"
import { triggerEmergencyStop } from "./emergency-stop-actions"
import {
  createKnowledgeNote,
  deleteAllKnowledgeNotes,
  deleteKnowledgeNote,
  deleteMultipleKnowledgeNotes,
  getKnowledgeNote,
  getKnowledgeNotes,
  searchKnowledgeNotes,
  updateKnowledgeNote,
} from "./knowledge-note-actions"
import {
  deleteMcpServerConfig,
  exportMcpServerConfigs,
  getMcpServers,
  importMcpServerConfigs,
  toggleMcpServer,
  upsertMcpServerConfig,
} from "./mcp-server-actions"
import {
  getModels,
  getProviderModels,
} from "./model-actions"
import { recordOperatorAuditEvent } from "./operator-audit-actions"
import {
  exportProfile,
  getCurrentProfile,
  getProfiles,
  importProfile,
  setCurrentProfile,
} from "./profile-actions"
import {
  clearPushBadge,
  getPushStatus,
  registerPushToken,
  unregisterPushToken,
} from "./push-actions"
import {
  createRepeatTask,
  deleteRepeatTask,
  exportRepeatTaskToMarkdown,
  getRepeatTaskStatuses,
  getRepeatTasks,
  importRepeatTaskFromMarkdown,
  runRepeatTask,
  startRepeatTask,
  stopRepeatTask,
  toggleRepeatTask,
  updateRepeatTask,
} from "./repeat-task-actions"
import {
  getSettings,
  updateSettings,
} from "./settings-actions"
import { getAgentSessionCandidates } from "./session-candidate-actions"
import {
  createSkill,
  deleteSkill,
  exportSkillToMarkdown,
  getSkill,
  getSkills,
  importSkillFromGitHub,
  importSkillFromMarkdown,
  toggleProfileSkill,
  updateSkill,
} from "./skill-actions"
import { synthesizeSpeech } from "./tts-actions"

export const mobileApiDesktopActions: MobileApiRouteActions = {
  handleChatCompletionRequest,
  getModels,
  getProviderModels,
  getProfiles,
  getCurrentProfile,
  setCurrentProfile,
  exportProfile,
  importProfile,
  getBundleExportableItems,
  exportBundle,
  previewBundleImport,
  importBundle,
  getMcpServers,
  toggleMcpServer,
  exportMcpServerConfigs,
  importMcpServerConfigs,
  upsertMcpServerConfig,
  deleteMcpServerConfig,
  getSettings,
  updateSettings,
  getAgentSessionCandidates,
  recordOperatorAuditEvent,
  getConversation,
  getConversationVideoAsset,
  synthesizeSpeech,
  registerPushToken,
  unregisterPushToken,
  getPushStatus,
  clearPushBadge,
  getConversations,
  createConversation,
  updateConversation,
  triggerEmergencyStop,
  getSkills,
  getSkill,
  createSkill,
  importSkillFromMarkdown,
  importSkillFromGitHub,
  exportSkillToMarkdown,
  updateSkill,
  deleteSkill,
  toggleProfileSkill,
  getKnowledgeNotes,
  getKnowledgeNote,
  searchKnowledgeNotes,
  deleteKnowledgeNote,
  deleteMultipleKnowledgeNotes,
  deleteAllKnowledgeNotes,
  getAgentProfiles,
  toggleAgentProfile,
  getAgentProfile,
  createAgentProfile,
  updateAgentProfile,
  deleteAgentProfile,
  getRepeatTasks,
  getRepeatTaskStatuses,
  toggleRepeatTask,
  runRepeatTask,
  startRepeatTask,
  stopRepeatTask,
  importRepeatTaskFromMarkdown,
  exportRepeatTaskToMarkdown,
  createKnowledgeNote,
  updateKnowledgeNote,
  createRepeatTask,
  updateRepeatTask,
  deleteRepeatTask,
}
