import test from 'node:test'
import assert from 'node:assert/strict'
import fs from 'node:fs'
import path from 'node:path'
import { fileURLToPath } from 'node:url'

const __filename = fileURLToPath(import.meta.url)
const __dirname = path.dirname(__filename)

const settingsSource = fs.readFileSync(path.join(__dirname, 'settings-capabilities.tsx'), 'utf8')
const dialogSource = fs.readFileSync(path.join(__dirname, '..', 'components', 'bundle-import-dialog.tsx'), 'utf8')
const tipcSource = fs.readFileSync(path.join(__dirname, '..', '..', '..', 'main', 'tipc.ts'), 'utf8')
const bundleServiceSource = fs.readFileSync(path.join(__dirname, '..', '..', '..', 'main', 'bundle-service.ts'), 'utf8')
const configSource = fs.readFileSync(path.join(__dirname, '..', '..', '..', 'main', 'config.ts'), 'utf8')

test('settings capabilities exposes a restore-backup entrypoint that reuses the bundle import dialog', () => {
  assert.match(settingsSource, /import \{ useEffect, useState \} from "react"/)
  assert.match(settingsSource, /import \{ useSearchParams \} from "react-router-dom"/)
  assert.match(settingsSource, /function getRequestedTab\(searchParams: URLSearchParams\): TabId/)
  assert.match(settingsSource, /const \[searchParams, setSearchParams\] = useSearchParams\(\)/)
  assert.match(settingsSource, /const \[activeTab, setActiveTab\] = useState<TabId>\(\(\) => getRequestedTab\(searchParams\)\)/)
  assert.match(settingsSource, /useEffect\(\(\) => \{[\s\S]*const requestedTab = getRequestedTab\(searchParams\)/)
  assert.match(settingsSource, /const handleTabChange = \(tabId: TabId\) => \{[\s\S]*nextParams\.set\("tab", tabId\)/)
  assert.match(settingsSource, /handleTabChange\(tab\.id\)/)
  assert.match(settingsSource, /Restore Backup/)
  assert.match(settingsSource, /copyTextToClipboard/)
  assert.match(settingsSource, /tipcClient\.selectBundleBackupFile\(\)/)
  assert.match(settingsSource, /tipcClient\.listBundleBackups\(\{ limit: 4 \}\)/)
  assert.match(settingsSource, /tipcClient\.getBundleSlotState\(\)/)
  assert.match(settingsSource, /tipcClient\.openBundleBackupFolder\(\)/)
  assert.match(settingsSource, /tipcClient\.openBundleSlotsFolder\(\)/)
  assert.match(settingsSource, /tipcClient\.revealBundleBackupFile\(\{ filePath \}\)/)
  assert.match(settingsSource, /Recent backups/)
  assert.match(settingsSource, /Bundle slots/)
  assert.match(settingsSource, /Active slot/)
  assert.match(settingsSource, /Status only for now/)
  assert.match(settingsSource, /Open Slots Folder/)
  assert.match(settingsSource, /Open Backups Folder/)
  assert.match(settingsSource, /Copy path/)
  assert.match(settingsSource, /Reveal/)
  assert.match(settingsSource, /Backup path copied to clipboard/)
  assert.match(settingsSource, /function formatBackupTargetLabel\(backup: RecentBackup\["backup"\]\): string/)
  assert.match(settingsSource, /Global layer/)
  assert.match(settingsSource, /Workspace layer/)
  assert.match(settingsSource, /backup\.filePath/)
  assert.match(settingsSource, /handleCopyBackupPathClick\(backup\.filePath\)/)
  assert.match(settingsSource, /handleRevealBackupFileClick\(backup\.filePath\)/)
  assert.match(settingsSource, /openRestoreDialogForFile\(backup\.filePath\)/)
  assert.match(settingsSource, /<BundleImportDialog[\s\S]*title="Restore Backup"/)
  assert.match(settingsSource, /confirmLabel="Restore"/)
  assert.match(settingsSource, /successVerb="restored"/)
  assert.match(settingsSource, /queryClient\.invalidateQueries\(\{ queryKey: \["skills"\] \}\)/)
  assert.match(settingsSource, /queryClient\.invalidateQueries\(\{ queryKey: \["config"\] \}\)/)
  assert.match(settingsSource, /queryClient\.invalidateQueries\(\{ queryKey: \["bundle-import-backups"\] \}\)/)
  assert.match(settingsSource, /queryClient\.invalidateQueries\(\{ queryKey: \["bundle-slot-state"\] \}\)/)
})

test('bundle import dialog supports restore-specific labels and clearer import provenance without forking the flow', () => {
  assert.match(dialogSource, /confirmLabel\?: string/)
  assert.match(dialogSource, /successVerb\?: string/)
  assert.match(dialogSource, /confirmLabel = "Import"/)
  assert.match(dialogSource, /successVerb = "imported"/)
  assert.match(dialogSource, /function summarizeSelectedConflictPlan\(importPlanSections: Array<\{ key: BundleComponentKey; items: ImportPlanItem\[\] \}>\): \{/)
  assert.match(dialogSource, /function formatExpectedConflictOutcome\(summary: \{[\s\S]*skip: number[\s\S]*overwrite: number[\s\S]*rename: number[\s\S]*\}\): string \| null/)
  assert.match(dialogSource, /Current selection: \{expectedConflictOutcome\}/)
  assert.match(dialogSource, /function summarizeImportResult\(result: BundleImportResult\): \{/)
  assert.match(dialogSource, /Successfully \$\{successVerb\} \$\{importSummary\.outcomeLabel\}/)
  assert.match(dialogSource, /Progress: \$\{importSummary\.detailSummary\}\./)
  assert.match(dialogSource, /<Button onClick=\{handleImport\}[\s\S]*\{confirmLabel\}/)
})

test('main process offers backup picker and reveal actions rooted in the default backup directory', () => {
  assert.match(bundleServiceSource, /export function getDefaultImportBackupDirectory\(\): string/)
  assert.match(bundleServiceSource, /export interface BundleBackupMetadata \{/)
  assert.match(bundleServiceSource, /kind: "pre-import-snapshot"/)
  assert.match(bundleServiceSource, /targetLayer: BundleBackupTargetLayer/)
  assert.match(bundleServiceSource, /backupMetadata\?: BundleBackupMetadata/)
  assert.match(bundleServiceSource, /function createImportBackupMetadata\(targetAgentsDir: string\): BundleBackupMetadata/)
  assert.match(bundleServiceSource, /backupMetadata: createImportBackupMetadata\(targetAgentsDir\)/)
  assert.match(bundleServiceSource, /backup: bundle\.manifest\.backup/)
  assert.match(bundleServiceSource, /export async function selectImportBackupBundleFromDialog\(\): Promise<string \| null>/)
  assert.match(bundleServiceSource, /export function listImportBackups\(options\?: \{ limit\?: number \}\): ImportBackupSummary\[]/)
  assert.match(bundleServiceSource, /manifestName: bundle\.manifest\.name/)
  assert.match(bundleServiceSource, /\.sort\(\(a, b\) => b\.modifiedAt - a\.modifiedAt\)/)
  assert.match(bundleServiceSource, /title: "Restore Backup Bundle"/)
  assert.match(bundleServiceSource, /defaultPath: backupDir/)
  assert.match(tipcSource, /selectBundleBackupFile: t\.procedure\.action\(async \(\) =>/)
  assert.match(tipcSource, /openBundleBackupFolder: t\.procedure\.action\(async \(\) =>/)
  assert.match(tipcSource, /revealBundleBackupFile: t\.procedure/)
  assert.match(tipcSource, /const backupDir = getDefaultImportBackupDirectory\(\)/)
  assert.match(tipcSource, /shell\.openPath\(backupDir\)/)
  assert.match(tipcSource, /const resolvedFilePath = path\.resolve\(input\.filePath\)/)
  assert.match(tipcSource, /const relativePath = path\.relative\(backupDir, resolvedFilePath\)/)
  assert.match(tipcSource, /Backup file must be inside the backups directory/)
  assert.match(tipcSource, /return revealFileInFolder\(resolvedFilePath\)/)
  assert.match(tipcSource, /listBundleBackups: t\.procedure/)
  assert.match(tipcSource, /listImportBackups\(\{ limit: input\?\.limit \}\)/)
  assert.match(tipcSource, /selectImportBackupBundleFromDialog/)
})

test('bundle slot metadata is surfaced through config, TIPC, and the capabilities page without implying full activation yet', () => {
  assert.match(configSource, /export const bundleSlotsFolder = path\.join\(globalAgentsFolder, "bundle-slots"\)/)
  assert.match(configSource, /export const activeBundleSlotStatePath = path\.join\(bundleSlotsFolder, "active-slot\.json"\)/)
  assert.match(configSource, /Future bundle-slot work must keep workspace as the highest-priority override:[\s\S]*global -> active slot -> workspace/)
  assert.match(configSource, /export function getActiveBundleSlotState\(\): BundleSlotState/)
  assert.match(configSource, /runtimeActivationEnabled: false/)
  assert.match(tipcSource, /getBundleSlotState: t\.procedure\.action\(async \(\) =>/)
  assert.match(tipcSource, /const \{ getActiveBundleSlotState \} = await import\("\.\/config"\)/)
  assert.match(tipcSource, /openBundleSlotsFolder: t\.procedure\.action\(async \(\) =>/)
  assert.match(tipcSource, /const \{ bundleSlotsFolder \} = await import\("\.\/config"\)/)
  assert.match(tipcSource, /shell\.openPath\(bundleSlotsFolder\)/)
})