import test from 'node:test'
import assert from 'node:assert/strict'
import fs from 'node:fs'
import path from 'node:path'
import { fileURLToPath } from 'node:url'

const __filename = fileURLToPath(import.meta.url)
const __dirname = path.dirname(__filename)

const settingsSource = fs.readFileSync(path.join(__dirname, 'settings-capabilities.tsx'), 'utf8')
const dialogSource = fs.readFileSync(path.join(__dirname, '..', 'components', 'bundle-import-dialog.tsx'), 'utf8')
const tipcSource = fs.readFileSync(path.join(__dirname, '..', '..', '..', 'main', 'tipc.ts'), 'utf8')
const bundleServiceSource = fs.readFileSync(path.join(__dirname, '..', '..', '..', 'main', 'bundle-service.ts'), 'utf8')

test('settings capabilities exposes a restore-backup entrypoint that reuses the bundle import dialog', () => {
  assert.match(settingsSource, /Restore Backup/)
  assert.match(settingsSource, /copyTextToClipboard/)
  assert.match(settingsSource, /tipcClient\.selectBundleBackupFile\(\)/)
  assert.match(settingsSource, /tipcClient\.listBundleBackups\(\{ limit: 4 \}\)/)
  assert.match(settingsSource, /tipcClient\.openBundleBackupFolder\(\)/)
  assert.match(settingsSource, /tipcClient\.revealBundleBackupFile\(\{ filePath \}\)/)
  assert.match(settingsSource, /Recent backups/)
  assert.match(settingsSource, /Open Backups Folder/)
  assert.match(settingsSource, /Copy path/)
  assert.match(settingsSource, /Reveal/)
  assert.match(settingsSource, /Backup path copied to clipboard/)
  assert.match(settingsSource, /function formatBackupTargetLabel\(backup: RecentBackup\["backup"\]\): string/)
  assert.match(settingsSource, /Global layer/)
  assert.match(settingsSource, /Workspace layer/)
  assert.match(settingsSource, /backup\.filePath/)
  assert.match(settingsSource, /handleCopyBackupPathClick\(backup\.filePath\)/)
  assert.match(settingsSource, /handleRevealBackupFileClick\(backup\.filePath\)/)
  assert.match(settingsSource, /openRestoreDialogForFile\(backup\.filePath\)/)
  assert.match(settingsSource, /<BundleImportDialog[\s\S]*title="Restore Backup"/)
  assert.match(settingsSource, /confirmLabel="Restore"/)
  assert.match(settingsSource, /successVerb="restored"/)
  assert.match(settingsSource, /queryClient\.invalidateQueries\(\{ queryKey: \["skills"\] \}\)/)
  assert.match(settingsSource, /queryClient\.invalidateQueries\(\{ queryKey: \["config"\] \}\)/)
  assert.match(settingsSource, /queryClient\.invalidateQueries\(\{ queryKey: \["bundle-import-backups"\] \}\)/)
})

test('bundle import dialog supports restore-specific labels and clearer import provenance without forking the flow', () => {
  assert.match(dialogSource, /confirmLabel\?: string/)
  assert.match(dialogSource, /successVerb\?: string/)
  assert.match(dialogSource, /confirmLabel = "Import"/)
  assert.match(dialogSource, /successVerb = "imported"/)
  assert.match(dialogSource, /function formatExpectedConflictOutcome\(conflictCount: number, strategy: ConflictStrategy\): string \| null/)
  assert.match(dialogSource, /Current selection: \{expectedConflictOutcome\}/)
  assert.match(dialogSource, /function summarizeImportResult\(result: BundleImportResult\): \{/)
  assert.match(dialogSource, /Successfully \$\{successVerb\} \$\{importSummary\.outcomeLabel\}/)
  assert.match(dialogSource, /Progress: \$\{importSummary\.detailSummary\}\./)
  assert.match(dialogSource, /<Button onClick=\{handleImport\}[\s\S]*\{confirmLabel\}/)
})

test('main process offers backup picker and reveal actions rooted in the default backup directory', () => {
  assert.match(bundleServiceSource, /export function getDefaultImportBackupDirectory\(\): string/)
  assert.match(bundleServiceSource, /export interface BundleBackupMetadata \{/)
  assert.match(bundleServiceSource, /kind: "pre-import-snapshot"/)
  assert.match(bundleServiceSource, /targetLayer: BundleBackupTargetLayer/)
  assert.match(bundleServiceSource, /backupMetadata\?: BundleBackupMetadata/)
  assert.match(bundleServiceSource, /function createImportBackupMetadata\(targetAgentsDir: string\): BundleBackupMetadata/)
  assert.match(bundleServiceSource, /backupMetadata: createImportBackupMetadata\(targetAgentsDir\)/)
  assert.match(bundleServiceSource, /backup: bundle\.manifest\.backup/)
  assert.match(bundleServiceSource, /export async function selectImportBackupBundleFromDialog\(\): Promise<string \| null>/)
  assert.match(bundleServiceSource, /export function listImportBackups\(options\?: \{ limit\?: number \}\): ImportBackupSummary\[]/)
  assert.match(bundleServiceSource, /manifestName: bundle\.manifest\.name/)
  assert.match(bundleServiceSource, /\.sort\(\(a, b\) => b\.modifiedAt - a\.modifiedAt\)/)
  assert.match(bundleServiceSource, /title: "Restore Backup Bundle"/)
  assert.match(bundleServiceSource, /defaultPath: backupDir/)
  assert.match(tipcSource, /selectBundleBackupFile: t\.procedure\.action\(async \(\) =>/)
  assert.match(tipcSource, /openBundleBackupFolder: t\.procedure\.action\(async \(\) =>/)
  assert.match(tipcSource, /revealBundleBackupFile: t\.procedure/)
  assert.match(tipcSource, /const backupDir = getDefaultImportBackupDirectory\(\)/)
  assert.match(tipcSource, /shell\.openPath\(backupDir\)/)
  assert.match(tipcSource, /const resolvedFilePath = path\.resolve\(input\.filePath\)/)
  assert.match(tipcSource, /const relativePath = path\.relative\(backupDir, resolvedFilePath\)/)
  assert.match(tipcSource, /Backup file must be inside the backups directory/)
  assert.match(tipcSource, /return revealFileInFolder\(resolvedFilePath\)/)
  assert.match(tipcSource, /listBundleBackups: t\.procedure/)
  assert.match(tipcSource, /listImportBackups\(\{ limit: input\?\.limit \}\)/)
  assert.match(tipcSource, /selectImportBackupBundleFromDialog/)
})