import { readFileSync } from "node:fs"
import { describe, expect, it } from "vitest"

const settingsAgentsSource = readFileSync(new URL("./settings-agents.tsx", import.meta.url), "utf8")

describe("settings agents capability config", () => {
  it("uses shared agent editor presentation copy in the desktop editor", () => {
    expect(settingsAgentsSource).toContain("APP_SHELL_AGENT_EDITOR_PRESENTATION")
    expect(settingsAgentsSource).toContain("APP_SHELL_AGENT_EDITOR_PRESENTATION.description")
    expect(settingsAgentsSource).toContain("APP_SHELL_AGENT_EDITOR_PRESENTATION.avatar.uploadActionLabel")
    expect(settingsAgentsSource).toContain("APP_SHELL_AGENT_EDITOR_PRESENTATION.fields.displayName.placeholder")
    expect(settingsAgentsSource).toContain("APP_SHELL_AGENT_EDITOR_PRESENTATION.fields.command.placeholder")
    expect(settingsAgentsSource).toContain("APP_SHELL_AGENT_EDITOR_PRESENTATION.externalSetup.verifyActionLabel")
    expect(settingsAgentsSource).not.toContain("Configure agent identity, behavior, model, and capabilities.</CardDescription>")
    expect(settingsAgentsSource).not.toContain('placeholder="e.g., claude-code-acp"')
  })

  it("uses shared agent profile capability helpers for desktop MCP and runtime toggles", () => {
    expect(settingsAgentsSource).toContain("countEnabledAgentProfileMcpServers(agent.toolConfig, serverNames)")
    expect(settingsAgentsSource).toContain("getAgentProfileMcpConfigAfterServerToggle")
    expect(settingsAgentsSource).toContain("getAgentProfileMcpConfigAfterSetAllServersEnabled")
    expect(settingsAgentsSource).toContain("getAgentProfileMcpConfigAfterToolToggle")
    expect(settingsAgentsSource).toContain("getAgentProfileRuntimeToolsConfigAfterSetAllEnabled")
    expect(settingsAgentsSource).toContain("getAgentProfileRuntimeToolsConfigAfterToggle")
    expect(settingsAgentsSource).toContain("hasAllAgentProfileMcpServersEnabled(editing?.toolConfig, serverNames)")
    expect(settingsAgentsSource).toContain("hasNoAgentProfileMcpServersEnabled(editing?.toolConfig, serverNames)")
    expect(settingsAgentsSource).toContain("hasAllAgentProfileRuntimeToolsEnabled(editing?.toolConfig, runtimeToolNames)")
    expect(settingsAgentsSource).toContain("hasOnlyEssentialAgentProfileRuntimeToolsEnabled(editing?.toolConfig)")
    expect(settingsAgentsSource).toContain("countEnabledAgentProfileMcpServers(editing?.toolConfig, serverNames)")
    expect(settingsAgentsSource).toContain("countEnabledAgentProfileRuntimeTools(editing?.toolConfig, runtimeToolNames)")
    expect(settingsAgentsSource).toContain("isAgentProfileEssentialRuntimeToolName(tool.name)")
    expect(settingsAgentsSource).toContain("isAgentProfileMcpServerEnabled(editing?.toolConfig, serverName)")
    expect(settingsAgentsSource).toContain("isAgentProfileRuntimeToolEnabled(editing?.toolConfig, toolName)")
    expect(settingsAgentsSource).not.toContain("agent.toolConfig?.enabledServers?.length")
    expect(settingsAgentsSource).not.toContain("serverNames.every(n => isServerEnabled(n))")
    expect(settingsAgentsSource).not.toContain("serverNames.filter(n => isServerEnabled(n)).length")
    expect(settingsAgentsSource).not.toContain("runtimeTools.filter(t => isRuntimeToolEnabled(t.name)).length")
    expect(settingsAgentsSource).not.toContain("editing.toolConfig.enabledRuntimeTools.length === 0")
    expect(settingsAgentsSource).not.toContain("tool.name === \"mark_work_complete\"")
  })

  it("uses shared skill enablement semantics in the desktop agent editor", () => {
    expect(settingsAgentsSource).toContain("countEnabledAgentProfileSkills(agent.skillsConfig, availableSkillIds)")
    expect(settingsAgentsSource).toContain("isAgentProfileSkillEnabled(editing?.skillsConfig, skillId)")
    expect(settingsAgentsSource).toContain("toggleAgentProfileSkillConfig(editing.skillsConfig, skillId, skillIds)")
    expect(settingsAgentsSource).toContain("getAgentProfileSkillsConfigAfterSetAllEnabled(true)")
    expect(settingsAgentsSource).toContain("getAgentProfileSkillsConfigAfterSetAllEnabled(false)")
    expect(settingsAgentsSource).toContain("hasAllAgentProfileSkillsEnabled(editing?.skillsConfig, skillIds)")
    expect(settingsAgentsSource).toContain("hasNoAgentProfileSkillsEnabled(editing?.skillsConfig, skillIds)")
    expect(settingsAgentsSource).toContain("countEnabledAgentProfileSkills(editing?.skillsConfig, skillIds)")
    expect(settingsAgentsSource).not.toContain("skills.filter(s => isSkillEnabled(s.id)).length")
    expect(settingsAgentsSource).not.toContain("skillsConfig: { enabledSkillIds: [], allSkillsDisabledByDefault")
    expect(settingsAgentsSource).not.toContain("editing?.skillsConfig?.enabledSkillIds?.length === skills.length")
    expect(settingsAgentsSource).not.toContain("agent.skillsConfig.allSkillsDisabledByDefault")
  })

  it("uses shared runtime tool counts in desktop agent card summaries", () => {
    expect(settingsAgentsSource).toContain("countEnabledAgentProfileRuntimeTools(agent.toolConfig, runtimeToolNames)")
    expect(settingsAgentsSource).not.toContain("const runtimeList = agent.toolConfig?.enabledRuntimeTools")
    expect(settingsAgentsSource).not.toContain("runtimeList.length")
  })

  it("uses shared per-agent model field helpers in the desktop agent editor", () => {
    expect(settingsAgentsSource).toContain("AGENT_PROFILE_AGENT_MODEL_PROVIDER_OPTIONS")
    expect(settingsAgentsSource).toContain("getAgentProfileAgentModelProvider")
    expect(settingsAgentsSource).toContain("getAgentProfileAgentModelProviderFromOptionValue")
    expect(settingsAgentsSource).toContain("getAgentProfileAgentModelProviderOptionValue")
    expect(settingsAgentsSource).toContain("getAgentProfileAgentModelValue")
    expect(settingsAgentsSource).toContain("getAgentProfileModelConfigAfterProviderSelect")
    expect(settingsAgentsSource).toContain("buildAgentProfileAgentModelUpdate")
    expect(settingsAgentsSource).toContain("mergeAgentProfileModelConfig")
    expect(settingsAgentsSource).not.toContain("<SelectItem value=\"chatgpt-web\">ChatGPT Web</SelectItem>")
    expect(settingsAgentsSource).not.toContain("v === \"__global__\"")
    expect(settingsAgentsSource).not.toContain("editing.modelConfig.agentOpenaiModel || editing.modelConfig.mcpToolsOpenaiModel")
    expect(settingsAgentsSource).not.toContain("setEditing({ ...editing, modelConfig: undefined })")
    expect(settingsAgentsSource).not.toContain("updateModelConfig({ agentProviderId:")
  })

  it("uses shared connection normalization before saving desktop agents", () => {
    expect(settingsAgentsSource).toContain("AGENT_EDIT_CONNECTION_TYPE_OPTIONS")
    expect(settingsAgentsSource).toContain("DEFAULT_AGENT_CONNECTION_FORM_FIELDS")
    expect(settingsAgentsSource).toContain("...DEFAULT_AGENT_CONNECTION_FORM_FIELDS")
    expect(settingsAgentsSource).toContain("applyConnectionTypeChange")
    expect(settingsAgentsSource).toContain("buildAgentConnectionCommandPreview")
    expect(settingsAgentsSource).toContain("getAgentConnectionFormValidationError")
    expect(settingsAgentsSource).toContain("normalizeAgentConnectionFormFieldsForEdit")
    expect(settingsAgentsSource).toContain("normalizeAgentConnectionArgs")
    expect(settingsAgentsSource).toContain("sanitizeAgentProfileConnection")
    expect(settingsAgentsSource).not.toContain("setEditing({ ...editing, connectionType: v })")
    expect(settingsAgentsSource).not.toContain("editing.connectionType === 'acpx' && !editing.connectionCommand?.trim()")
    expect(settingsAgentsSource).not.toContain("editing.connectionType === \"remote\" && !editing.connectionBaseUrl?.trim()")
    expect(settingsAgentsSource).not.toContain("agent.connection.args?.join(\" \")")
    expect(settingsAgentsSource).not.toContain("function buildCommandPreview")
    expect(settingsAgentsSource).not.toContain("editing.connectionArgs?.split(\" \").filter(Boolean)")
    expect(settingsAgentsSource).not.toContain("const connection: AgentProfileConnection")
    expect(settingsAgentsSource).not.toContain("baseUrl: editing.connectionBaseUrl")
    expect(settingsAgentsSource).not.toContain("connectionType: agent.connection.type")
    expect(settingsAgentsSource).not.toContain("<SelectItem value=\"internal\">Internal (built-in agent)</SelectItem>")
  })

  it("uses shared editable preset fields in the desktop agent editor", () => {
    expect(settingsAgentsSource).toContain("getAgentProfilePresetFormFields")
    expect(settingsAgentsSource).toContain("getAgentProfilePresetFormFields(presetKey)")
    expect(settingsAgentsSource).not.toContain("...emptyAgent(), ...preset, presetKey")
  })

  it("uses shared profile property helpers in the desktop agent editor", () => {
    expect(settingsAgentsSource).toContain("DEFAULT_AGENT_PROFILE_ENABLED")
    expect(settingsAgentsSource).toContain("DEFAULT_AGENT_PROFILE_AUTO_SPAWN")
    expect(settingsAgentsSource).toContain("enabled: DEFAULT_AGENT_PROFILE_ENABLED")
    expect(settingsAgentsSource).toContain("autoSpawn: DEFAULT_AGENT_PROFILE_AUTO_SPAWN")
    expect(settingsAgentsSource).toContain("agent.autoSpawn ?? DEFAULT_AGENT_PROFILE_AUTO_SPAWN")
    expect(settingsAgentsSource).toContain("editing.autoSpawn ?? DEFAULT_AGENT_PROFILE_AUTO_SPAWN")
    expect(settingsAgentsSource).toContain("normalizeAgentProfileProperties")
    expect(settingsAgentsSource).toContain("formatAgentProfilePropertiesForRequest")
    expect(settingsAgentsSource).toContain("getAgentProfileAvatarFileSizeError")
    expect(settingsAgentsSource).not.toContain("Object.keys(editing.properties).length > 0 ? editing.properties : undefined")
  })

  it("uses shared profile config edit helpers in the desktop agent editor", () => {
    expect(settingsAgentsSource).toContain("normalizeAgentProfileModelConfigForEdit")
    expect(settingsAgentsSource).toContain("normalizeAgentProfileMcpConfigForEdit")
    expect(settingsAgentsSource).toContain("normalizeAgentProfileSkillsConfigForEdit")
    expect(settingsAgentsSource).toContain("formatAgentProfileModelConfigForRequest")
    expect(settingsAgentsSource).toContain("formatAgentProfileMcpConfigForRequest")
    expect(settingsAgentsSource).toContain("formatAgentProfileSkillsConfigForRequest")
    expect(settingsAgentsSource).not.toContain("modelConfig: agent.modelConfig ? { ...agent.modelConfig } : undefined")
    expect(settingsAgentsSource).not.toContain("toolConfig: agent.toolConfig ? { ...agent.toolConfig } : undefined")
    expect(settingsAgentsSource).not.toContain("skillsConfig: agent.skillsConfig ? { ...agent.skillsConfig } : undefined")
  })
})
