const test = require('node:test');
const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');

const chatScreenSource = fs.readFileSync(
  path.join(__dirname, '..', 'src', 'screens', 'ChatScreen.tsx'),
  'utf8'
);
const chatRuntimeMobileStylesSource = fs.readFileSync(
  path.join(__dirname, '..', 'src', 'ui', 'ChatRuntimeMobileStyles.ts'),
  'utf8'
);
const screenSource = `${chatScreenSource}\n${chatRuntimeMobileStylesSource}`;
const chatMessageChromeSource = fs.readFileSync(
  path.join(__dirname, '..', 'src', 'ui', 'ChatMessageChrome.tsx'),
  'utf8'
);
const sessionPresentationSource = fs.readFileSync(
  path.join(__dirname, '..', '..', '..', 'packages', 'shared', 'src', 'session-presentation.ts'),
  'utf8'
);

test('shows desktop library items directly in the new-chat prompt launchers', () => {
  assert.doesNotMatch(screenSource, /const promptQuickStarts = useMemo/);
  assert.doesNotMatch(screenSource, /buildPromptLibraryShortcutItems,/);
  assert.doesNotMatch(screenSource, /createChatConversationHomeQuickStartItems,/);
  assert.doesNotMatch(chatMessageChromeSource, /createChatConversationHomeQuickStartItems\(\{/);
  assert.doesNotMatch(chatMessageChromeSource, /buildPromptLibraryShortcutItems,/);
  assert.match(sessionPresentationSource, /quickStartItems: getChatRuntimeHomeQuickStartItemsMobileState\(\{/);
  assert.match(sessionPresentationSource, /buildPromptLibraryShortcutItems\(\{/);
  assert.match(screenSource, /quickStartPrompts: predefinedPrompts,/);
  assert.match(screenSource, /quickStartSkills: availableSkills,/);
  assert.match(screenSource, /quickStartTasks: availableTasks,/);
  assert.match(screenSource, /quickStartCanAddPrompt: Boolean\(settingsClient\),/);
  assert.match(sessionPresentationSource, /prompts: quickStartPrompts,\s+skills: quickStartSkills,\s+tasks: quickStartTasks,\s+canAddPrompt: quickStartCanAddPrompt,/);
  assert.doesNotMatch(screenSource, /addPromptTitle: mobilePromptLibraryCopy\.addPromptTitle,/);
  assert.doesNotMatch(screenSource, /addPromptDescription: mobilePromptLibraryCopy\.addPromptDescription,/);
  assert.doesNotMatch(screenSource, /taskDescriptionFallback: mobilePromptLibraryCopy\.taskDescriptionFallback,/);
  assert.match(sessionPresentationSource, /addPromptTitle: mobilePromptLibraryCopy\.addPromptTitle,/);
  assert.match(sessionPresentationSource, /addPromptDescription: mobilePromptLibraryCopy\.addPromptDescription,/);
  assert.match(sessionPresentationSource, /taskDescriptionFallback: mobilePromptLibraryCopy\.taskDescriptionFallback,/);
  assert.doesNotMatch(screenSource, /settingsClient\.getSkills\(\)/);
  assert.doesNotMatch(screenSource, /settingsClient\.getLoops\(\)/);
  assert.match(chatMessageChromeSource, /quickStartClient\.getSkills\(\)/);
  assert.match(chatMessageChromeSource, /quickStartClient\.getLoops\(\)/);
  assert.match(screenSource, /handleRunPromptTask/);
  assert.doesNotMatch(chatMessageChromeSource, /getPromptLibraryShortcutSourceLabel\(item\.source\)/);
  assert.match(chatMessageChromeSource, /type PromptLibraryLauncherShortcutSource,/);
  assert.match(chatMessageChromeSource, /type PromptLibraryShortcutItem,/);
  assert.match(chatMessageChromeSource, /type PromptLibraryEditorMobileRenderState,/);
  assert.match(chatMessageChromeSource, /type PromptLibraryMobileShortcutRenderState,/);
  assert.match(chatMessageChromeSource, /type ChatRuntimeHomeQuickStartsMobilePropsParts,/);
  assert.match(chatMessageChromeSource, /createChatRuntimeHomeQuickStartsMobilePropsParts,/);
  assert.match(chatMessageChromeSource, /type ChatConversationHomeQuickStartsParts<[\s\S]*?ChatRuntimeHomeQuickStartsMobilePropsParts<[\s\S]*?GestureResponderEvent,[\s\S]*?ChatConversationHomeQuickStartsStyles/);
  assert.match(chatMessageChromeSource, /type ChatConversationHomeQuickStartCardProps<[\s\S]*?Pick<[\s\S]*?ChatConversationHomeQuickStartsItemPart/);
  assert.doesNotMatch(chatMessageChromeSource, /type ChatConversationHomeQuickStartsContainerPart = \{/);
  assert.doesNotMatch(chatMessageChromeSource, /type ChatConversationHomeQuickStart(SourcePill|AddIcon|CardPressable|Text|Description|ActionButtonPressable|ActionButtonIcon|ActionButtonLabel|Actions|EmptyState|Card|Grid)Part =/);
  assert.match(sessionPresentationSource, /getPromptLibraryMobileShortcutEmptyRenderState,/);
  assert.match(sessionPresentationSource, /getPromptLibraryMobileShortcutItemRenderState,/);
  assert.match(chatMessageChromeSource, /export type ChatConversationHomeQuickStartSource = PromptLibraryLauncherShortcutSource;/);
  assert.match(chatMessageChromeSource, /export type ChatConversationHomeQuickStartItem<[\s\S]*?> = PromptLibraryShortcutItem<TPrompt, TTask>;/);
  assert.doesNotMatch(screenSource, /getPromptLibraryCopyState,/);
  assert.match(sessionPresentationSource, /getPromptLibraryCopyState,/);
  assert.match(sessionPresentationSource, /getPromptLibraryEditorMobileRenderState/);
  assert.doesNotMatch(screenSource, /getPromptLibraryEditorMobileRenderState,/);
  assert.doesNotMatch(screenSource, /getPromptLibraryShortcutPressIntent,/);
  assert.match(chatMessageChromeSource, /getChatRuntimeHomeQuickStartPressIntent,/);
  assert.match(sessionPresentationSource, /return getPromptLibraryShortcutPressIntent\(item\)/);
  assert.doesNotMatch(screenSource, /getPromptLibraryEditorTitle,/);
  assert.doesNotMatch(screenSource, /getPromptLibraryEditorSaveActionLabel,/);
  assert.match(sessionPresentationSource, /return getPromptLibraryEditorTitle\(isEditing\)/);
  assert.match(sessionPresentationSource, /return getPromptLibraryEditorSaveActionState\(/);
  assert.doesNotMatch(screenSource, /getPromptLibraryEditorMobileChromeState,/);
  assert.match(sessionPresentationSource, /getPromptLibraryMobileShortcutRenderState/);
  assert.doesNotMatch(screenSource, /getPromptLibraryMobileShortcutRenderState,/);
  assert.doesNotMatch(screenSource, /getPromptLibraryMobileShortcutChromeState,/);
  assert.doesNotMatch(screenSource, /getPromptLibraryMobileShortcutCopyState,/);
  assert.doesNotMatch(screenSource, /getPromptLibraryMobileShortcutSurfaceState,/);
  assert.match(sessionPresentationSource, /getPromptLibraryMobileSurfaceRenderState/);
  assert.doesNotMatch(screenSource, /getPromptLibraryMobileSurfaceState,/);
  assert.doesNotMatch(screenSource, /getPromptLibraryMobileCopyState,/);
  assert.match(sessionPresentationSource, /getPromptLibraryMobileCopyState/);
  assert.doesNotMatch(screenSource, /getPromptLibraryMobileEmptyLibraryLabel,/);
  assert.doesNotMatch(screenSource, /getPromptLibraryMobileIconColors,/);
  assert.doesNotMatch(screenSource, /getPromptLibraryMobileSurfaceColors,/);
  assert.doesNotMatch(screenSource, /const mobilePromptLibrarySurface = getPromptLibraryMobileSurfaceState\(\);/);
  assert.doesNotMatch(screenSource, /const promptLibraryCopy = getChatConversationHomePromptLibraryCopyState\(\);/);
  assert.doesNotMatch(screenSource, /getChatConversationHomePromptLibraryCopyState,/);
  assert.doesNotMatch(screenSource, /const promptLibraryEditorRenderState = useMemo/);
  assert.doesNotMatch(screenSource, /const promptLibraryShortcutRenderState = useMemo/);
  assert.doesNotMatch(screenSource, /const mobilePromptLibraryCopy = getPromptLibraryMobileCopyState\(\);/);
  assert.match(sessionPresentationSource, /const mobilePromptLibraryCopy = getPromptLibraryMobileCopyState\(\)/);
  assert.doesNotMatch(screenSource, /const mobilePromptLibraryEmptyLabel = getPromptLibraryMobileEmptyLibraryLabel\(\);/);
  assert.match(screenSource, /runningPromptTaskId,/);
  assert.match(sessionPresentationSource, /runningTaskId: runningPromptTaskId,/);
  assert.doesNotMatch(screenSource, /shortcutRenderState: promptLibraryShortcutRenderState/);
  assert.match(sessionPresentationSource, /shortcutRenderState: getPromptLibraryMobileShortcutRenderState\(colors\),/);
  assert.match(screenSource, /useChatConversationHomeQuickStartActionsState,/);
  assert.match(screenSource, /const \{ handleQuickStartPress \} = useChatConversationHomeQuickStartActionsState<PredefinedPromptSummary, Loop>\(\{\s+setComposerInput: setInput,\s+focusComposerInput,\s+openAddPrompt: openAddPromptModal,\s+runPromptTask: handleRunPromptTask,\s+\}\);/);
  assert.match(chatMessageChromeSource, /export function useChatConversationHomeQuickStartActionsState/);
  assert.doesNotMatch(screenSource, /const pressIntent = getChatConversationHomeQuickStartPressIntent\(item\);/);
  assert.doesNotMatch(chatMessageChromeSource, /const pressIntent = getChatConversationHomeQuickStartPressIntent\(item\);/);
  assert.doesNotMatch(chatMessageChromeSource, /export function getChatConversationHomeQuickStartPressIntent/);
  assert.match(chatMessageChromeSource, /const pressIntent = getChatRuntimeHomeQuickStartPressIntent\(item\);/);
  assert.doesNotMatch(screenSource, /if \(pressIntent\.kind === 'add-prompt'\)/);
  assert.match(chatMessageChromeSource, /if \(pressIntent\.kind === 'add-prompt'\)/);
  assert.doesNotMatch(screenSource, /if \(pressIntent\.kind === 'run-task'\)/);
  assert.match(chatMessageChromeSource, /if \(pressIntent\.kind === 'run-task'\)/);
  assert.doesNotMatch(screenSource, /handleRunPromptTask\(pressIntent\.task\)/);
  assert.match(chatMessageChromeSource, /runPromptTask\(pressIntent\.task\)/);
  assert.doesNotMatch(screenSource, /handleInsertQuickStartPrompt\(pressIntent\.content\)/);
  assert.match(chatMessageChromeSource, /const trimmed = pressIntent\.content\.trim\(\);/);
  assert.doesNotMatch(screenSource, /item\.action === 'add-prompt'/);
  assert.doesNotMatch(screenSource, /item\.source === 'task' && item\.task/);
  assert.doesNotMatch(screenSource, /handleInsertQuickStartPrompt\(item\.content\)/);
  assert.doesNotMatch(screenSource, /shortcutCopy: promptLibraryShortcutCopy/);
  assert.doesNotMatch(screenSource, /loadingLabel: mobilePromptLibraryCopy\.loadingLibraryLabel/);
  assert.doesNotMatch(screenSource, /emptyLabel: mobilePromptLibraryEmptyLabel/);
  assert.doesNotMatch(screenSource, /shortcutSurface: promptLibraryShortcutSurface/);
  assert.doesNotMatch(screenSource, /sourceLabelNumberOfLines: mobilePromptLibrarySurface\.shortcutSourceLabel\.numberOfLines/);
  assert.match(chatMessageChromeSource, /shortcutRenderState: PromptLibraryMobileShortcutRenderState;/);
  assert.match(sessionPresentationSource, /const shortcutSurface = shortcutRenderState\.surface/);
  assert.match(sessionPresentationSource, /const shortcutEmptyRenderState = getChatRuntimeHomeQuickStartEmptyMobileRenderState\(\s+shortcutRenderState,\s+isLoading,\s+\)/);
  assert.match(sessionPresentationSource, /numberOfLines: shortcutSurface\.shortcutSourceLabel\.numberOfLines/);
  assert.match(chatMessageChromeSource, /<ChatConversationHomeQuickStarts\s+\{\.\.\.viewportParts\.homeQuickStarts\.props\}/);
  assert.doesNotMatch(screenSource, /shortcutChrome: promptLibraryShortcutChrome/);
  assert.doesNotMatch(screenSource, /addIcon: promptLibraryShortcutChrome\.addIcon/);
  assert.doesNotMatch(screenSource, /sourceIcons: promptLibraryShortcutChrome\.sourceIcons/);
  assert.doesNotMatch(chatMessageChromeSource, /const sourceIcon = shortcutChrome\.sourceIcons\[item\.source\];/);
  assert.doesNotMatch(chatMessageChromeSource, /const shortcutSourceIconColors = shortcutChrome\.sourceIconColors\[item\.source\];/);
  assert.match(sessionPresentationSource, /const shortcutItemRenderState = getChatRuntimeHomeQuickStartItemMobileRenderState\(\s+item,\s+shortcutRenderState,\s+runningTaskId,\s+\)/);
  assert.match(sessionPresentationSource, /const shortcutInteraction = shortcutItemRenderState\.interaction/);
  assert.match(sessionPresentationSource, /const promptActions = shortcutItemRenderState\.promptActions/);
  assert.match(sessionPresentationSource, /disabled: shortcutInteraction\.isDisabled/);
  assert.match(sessionPresentationSource, /accessibilityState: shortcutInteraction\.accessibilityState/);
  assert.match(sessionPresentationSource, /accessibilityRole: shortcutItemRenderState\.accessibilityRole/);
  assert.match(sessionPresentationSource, /accessibilityLabel: shortcutItemRenderState\.accessibilityLabel/);
  assert.match(sessionPresentationSource, /accessibilityHint: shortcutItemRenderState\.accessibilityHint/);
  assert.doesNotMatch(chatMessageChromeSource, /createButtonAccessibilityLabel/);
  assert.doesNotMatch(chatMessageChromeSource, /const isAddPrompt = item\.action === 'add-prompt'/);
  assert.doesNotMatch(chatMessageChromeSource, /const isTaskRunning = item\.source === 'task' && runningTaskId === item\.task\?\.id/);
  assert.match(sessionPresentationSource, /name: shortcutItemRenderState\.sourceIcon\.name/);
  assert.match(sessionPresentationSource, /size: shortcutItemRenderState\.sourceIcon\.size/);
  assert.match(sessionPresentationSource, /color: shortcutItemRenderState\.sourceIconColors\.color/);
  assert.match(sessionPresentationSource, /name: shortcutItemRenderState\.addAction\.icon\.name/);
  assert.match(sessionPresentationSource, /size: shortcutItemRenderState\.addAction\.icon\.size/);
  assert.match(sessionPresentationSource, /color: shortcutItemRenderState\.addAction\.iconColors\.color/);
  assert.match(sessionPresentationSource, /style: styles\.addIcon/);
  assert.doesNotMatch(chatMessageChromeSource, /shortcutChrome\.addIcon/);
  assert.doesNotMatch(chatMessageChromeSource, /shortcutChrome\.addIconColors/);
  assert.match(sessionPresentationSource, /pressed && styles\.actionButtonPressed/);
  assert.match(sessionPresentationSource, /prompt && promptActions/);
  assert.match(sessionPresentationSource, /accessibilityRole: promptActions\.edit\.accessibilityRole/);
  assert.match(sessionPresentationSource, /accessibilityLabel: promptActions\.edit\.accessibilityLabel/);
  assert.match(sessionPresentationSource, /name: promptActions\.edit\.icon\.name/);
  assert.match(sessionPresentationSource, /size: promptActions\.edit\.icon\.size/);
  assert.match(sessionPresentationSource, /color: promptActions\.edit\.iconColors\.color/);
  assert.match(sessionPresentationSource, /text: promptActions\.edit\.label/);
  assert.match(sessionPresentationSource, /accessibilityRole: promptActions\.delete\.accessibilityRole/);
  assert.match(sessionPresentationSource, /accessibilityLabel: promptActions\.delete\.accessibilityLabel/);
  assert.match(sessionPresentationSource, /name: promptActions\.delete\.icon\.name/);
  assert.match(sessionPresentationSource, /size: promptActions\.delete\.icon\.size/);
  assert.match(sessionPresentationSource, /color: promptActions\.delete\.iconColors\.color/);
  assert.match(sessionPresentationSource, /text: promptActions\.delete\.label/);
  assert.doesNotMatch(chatMessageChromeSource, /getPromptLibraryEditPromptAccessibilityLabel\(item\.title\)/);
  assert.doesNotMatch(chatMessageChromeSource, /getPromptLibraryDeletePromptAccessibilityLabel\(item\.title\)/);
  assert.doesNotMatch(chatMessageChromeSource, /shortcutChrome\.(edit|delete)Icon/);
  assert.doesNotMatch(chatMessageChromeSource, /shortcutChrome\.(edit|delete)IconColors/);
  assert.match(sessionPresentationSource, /homeQuickStartStyles: \{\s+card: styles\.chatHomeCard,\s+emptyText: styles\.chatHomeEmptyText,\s+grid: styles\.chatHomeShortcutGrid,\s+shortcutCard: styles\.chatHomeShortcutCard,/);
  assert.match(screenSource, /const promptLibraryStyleSlots = composerChromeStyleSlots\.promptLibrary;/);
  assert.match(screenSource, /chatHomeShortcutSourcePill:\s*\{\s+\.\.\.promptLibraryStyleSlots\.chatHomeShortcutSourcePill/);
  assert.match(screenSource, /chatHomeShortcutAddIcon:\s*\{\s+\.\.\.promptLibraryStyleSlots\.chatHomeShortcutAddIcon/);
  assert.match(screenSource, /chatHomeShortcutSourceLabel:\s*\{\s+\.\.\.promptLibraryStyleSlots\.chatHomeShortcutSourceLabel/);
  assert.match(screenSource, /chatHomeShortcutActionButton:\s*\{\s+\.\.\.promptLibraryStyleSlots\.chatHomeShortcutActionButton/);
  assert.match(screenSource, /chatHomeShortcutActionButtonPressed:\s*\{\s+\.\.\.promptLibraryStyleSlots\.chatHomeShortcutActionButtonPressed/);
  assert.doesNotMatch(screenSource, /predefinedPrompts\s*\.slice/);
  assert.doesNotMatch(screenSource, /availableSkills\.slice/);
  assert.doesNotMatch(screenSource, /availableTasks\.slice/);
  assert.match(sessionPresentationSource, /items\.map\(\(item\) => \{/);
  assert.doesNotMatch(chatMessageChromeSource, /shortcutCopy\.(edit|delete)Label/);
  assert.doesNotMatch(chatMessageChromeSource, /shortcutCopy\.(loading|empty)Label/);
  assert.match(sessionPresentationSource, /text: shortcutEmptyRenderState\.label/);
  assert.doesNotMatch(screenSource, /source: isSlashCommandPrompt\(prompt\) \? 'command' as const : 'saved-prompt' as const/);
  assert.doesNotMatch(screenSource, /source: 'skill' as const/);
  assert.doesNotMatch(screenSource, /source: 'task' as const/);
  assert.doesNotMatch(screenSource, /id: `skill-\$\{skill\.id\}`/);
  assert.doesNotMatch(screenSource, /id: `task-\$\{task\.id\}`/);
  assert.doesNotMatch(screenSource, /id: 'action-add-prompt'/);
  assert.doesNotMatch(screenSource, /getPromptLibraryMobileShortcutSourceIconState\('command'\)/);
  assert.doesNotMatch(screenSource, /getPromptLibraryMobileIconColors\(promptLibraryShortcutSourceIcons\./);
  assert.doesNotMatch(screenSource, /getPromptLibraryMobileAddShortcutIconState\(\)/);
  assert.doesNotMatch(screenSource, /getPromptLibraryMobileShortcutActionIconState\('edit'\)/);
  assert.doesNotMatch(screenSource, /getPromptLibraryMobileLauncherShortcutSourceIconColors\(theme\.colors\)/);
  assert.doesNotMatch(chatMessageChromeSource, /PromptLibraryShortcutSource,/);
  assert.doesNotMatch(chatMessageChromeSource, /Extract<\s*PromptLibraryShortcutSource,/);
  assert.doesNotMatch(chatMessageChromeSource, /source: ChatConversationHomeQuickStartSource;/);
  assert.doesNotMatch(screenSource, /PROMPT_LIBRARY_PRESENTATION/);
  assert.doesNotMatch(screenSource, /const promptLibraryStyleState = composerChromeStyleState\.promptLibrary;/);
  assert.doesNotMatch(screenSource, /const promptLibrarySurface = promptLibraryStyleState\.surface;/);
  assert.doesNotMatch(screenSource, /const promptLibrarySurfaceColors = promptLibraryStyleState\.colors;/);
  assert.doesNotMatch(screenSource, /theme\.colors\[(sourceIcon|promptLibraryAddShortcutIcon|promptLibraryEditActionIcon|promptLibraryDeleteActionIcon)\.colorToken\]/);
  assert.doesNotMatch(screenSource, /theme\.colors\[promptLibrarySurface\./);
  assert.doesNotMatch(screenSource, /PROMPT_LIBRARY_SURFACE_PRESENTATION,/);
  assert.doesNotMatch(screenSource, /PROMPT_LIBRARY_SURFACE_PRESENTATION\.mobile/);
  assert.doesNotMatch(screenSource, /promptLibrarySurface\.shortcutActionIcon\.editName/);
  assert.doesNotMatch(screenSource, /promptLibrarySurface\.shortcutSourceIcon\.skillName/);
  assert.doesNotMatch(screenSource, /promptLibrarySurface\.addShortcutIcon\.name/);
  assert.doesNotMatch(screenSource, /title: 'Custom Commands'/);
  assert.doesNotMatch(screenSource, /title: 'Saved Prompts'/);
  assert.doesNotMatch(screenSource, /title: 'Prompt Library'/);
  assert.doesNotMatch(screenSource, /title: 'Starter Packs'/);
  assert.doesNotMatch(screenSource, /STARTER_PACK_SHORTCUTS/);
});

test('can create a new predefined prompt from mobile and save it to desktop settings', () => {
  assert.match(screenSource, /quickStartCanAddPrompt: Boolean\(settingsClient\)/);
  assert.doesNotMatch(screenSource, /addPromptTitle: mobilePromptLibraryCopy\.addPromptTitle/);
  assert.doesNotMatch(screenSource, /addPromptDescription: mobilePromptLibraryCopy\.addPromptDescription/);
  assert.match(sessionPresentationSource, /addPromptTitle: mobilePromptLibraryCopy\.addPromptTitle/);
  assert.match(sessionPresentationSource, /addPromptDescription: mobilePromptLibraryCopy\.addPromptDescription/);
  assert.match(screenSource, /useChatConversationHomePromptEditorState,/);
  assert.match(screenSource, /openAddPromptEditor: openAddPromptModal/);
  assert.match(screenSource, /openEditPromptEditor: openEditPromptModal/);
  assert.match(screenSource, /closePromptEditor: closePromptModal/);
  assert.match(chatMessageChromeSource, /export function useChatConversationHomePromptEditorState/);
  assert.match(chatMessageChromeSource, /setPromptEditorVisible\(true\)/);
  assert.doesNotMatch(screenSource, /setAddPromptModalVisible\(true\)/);
  assert.match(screenSource, /useChatConversationHomePromptEditorSaveChromeActionsState,/);
  assert.match(screenSource, /const \{ handleSavePrompt \} = useChatConversationHomePromptEditorSaveChromeActionsState<ExtendedSettingsApiClient>\(\{\s+promptClient: settingsClient,\s+predefinedPrompts,\s+editingPrompt,\s+promptName: newPromptName,\s+promptContent: newPromptContent,\s+isSavingPrompt,\s+setPredefinedPrompts,\s+beginPromptEditorSave,\s+clearPromptEditorSave,\s+dismissPromptEditor,\s+\}\);/);
  assert.match(chatMessageChromeSource, /export function useChatConversationHomePromptEditorSaveActionsState/);
  assert.match(chatMessageChromeSource, /export function useChatConversationHomePromptEditorSaveChromeActionsState/);
  assert.match(chatMessageChromeSource, /useChatConversationHomePromptEditorSaveChromeActionsState[\s\S]*?showAlert: Alert\.alert,/);
  assert.doesNotMatch(screenSource, /const handleSavePrompt = async \(\) =>/);
  assert.doesNotMatch(screenSource, /createChatConversationHomePromptEditorSaveActionState\(\{\s+draft,\s+isEditing: Boolean\(editingPrompt\),\s+isSaving: isSavingPrompt,\s+\}\)/);
  assert.match(chatMessageChromeSource, /createChatConversationHomePromptEditorSaveActionState\(\{\s+draft,\s+isEditing: Boolean\(editingPrompt\),\s+isSaving: isSavingPrompt,\s+\}\)/);
  assert.doesNotMatch(screenSource, /getPromptLibraryEditorSaveActionState,/);
  assert.doesNotMatch(screenSource, /if \(!settingsClient \|\| saveActionState\.isDisabled\) return;/);
  assert.match(chatMessageChromeSource, /if \(!promptClient \|\| saveActionState\.isDisabled\) return;/);
  assert.match(screenSource, /onPromptEditorSave: handleSavePrompt/);
  assert.match(sessionPresentationSource, /onPress: onSave/);
  assert.doesNotMatch(screenSource, /await settingsClient\.updateSettings\(\{ predefinedPrompts: updatedPrompts \}\)/);
  assert.match(chatMessageChromeSource, /await promptClient\.updateSettings\(\{ predefinedPrompts: updatedPrompts \}\)/);
  assert.doesNotMatch(screenSource, /const wasEditingPrompt = Boolean\(editingPrompt\);/);
  assert.match(chatMessageChromeSource, /const wasEditingPrompt = Boolean\(editingPrompt\);/);
  assert.doesNotMatch(screenSource, /getChatConversationHomePromptSaveSuccessAlertState\(wasEditingPrompt\)/);
  assert.match(chatMessageChromeSource, /getChatConversationHomePromptSaveSuccessAlertState\(wasEditingPrompt\)/);
  assert.doesNotMatch(screenSource, /getChatConversationHomePromptSaveFailedAlertState\(error\)/);
  assert.match(chatMessageChromeSource, /getChatConversationHomePromptSaveFailedAlertState\(error\)/);
  assert.match(screenSource, /useChatConversationHomePromptEditorDeleteChromeActionsState,/);
  assert.match(screenSource, /const \{ handleDeletePrompt \} = useChatConversationHomePromptEditorDeleteChromeActionsState<ExtendedSettingsApiClient>\(\{\s+promptClient: settingsClient,\s+predefinedPrompts,\s+setPredefinedPrompts,\s+beginPromptEditorSave,\s+clearPromptEditorSave,\s+\.\.\.chatRuntimeChrome\.environment,\s+\}\);/);
  assert.doesNotMatch(screenSource, /createChatConversationHomePromptDeleteNativeConfirmPresenter,/);
  assert.doesNotMatch(screenSource, /showChatConversationHomePromptDeleteNativeConfirmAlert,/);
  assert.match(chatMessageChromeSource, /export function showChatConversationHomePromptDeleteNativeConfirmAlert/);
  assert.match(chatMessageChromeSource, /export function createChatConversationHomePromptDeleteNativeConfirmPresenter/);
  assert.match(chatMessageChromeSource, /export function confirmChatRuntimeWebDialog/);
  assert.match(chatMessageChromeSource, /export function useChatConversationHomePromptEditorDeleteActionsState/);
  assert.match(chatMessageChromeSource, /export function useChatConversationHomePromptEditorDeleteChromeActionsState/);
  assert.match(chatMessageChromeSource, /useChatConversationHomePromptEditorDeleteChromeActionsState[\s\S]*?confirmWeb: confirmChatRuntimeWebDialog,[\s\S]*?confirmNative: createChatConversationHomePromptDeleteNativeConfirmPresenter\(Alert\.alert\),[\s\S]*?showAlert: Alert\.alert,/);
  assert.doesNotMatch(screenSource, /getChatConversationHomePromptDeleteFailedAlertState\(error\)/);
  assert.match(chatMessageChromeSource, /getChatConversationHomePromptDeleteFailedAlertState\(error\)/);
  assert.doesNotMatch(screenSource, /getChatConversationHomePromptTaskRunFailedAlertState\(error\)/);
  assert.match(chatMessageChromeSource, /getChatConversationHomePromptTaskRunFailedAlertState\(error\)/);
  assert.doesNotMatch(screenSource, /getChatConversationHomePromptTaskStartedAlertState\(task\.name\)/);
  assert.match(chatMessageChromeSource, /getChatConversationHomePromptTaskStartedAlertState\(task\.name\)/);
  assert.doesNotMatch(screenSource, /getChatConversationHomePromptDeleteConfirmAlertState\(prompt\.name\)/);
  assert.match(chatMessageChromeSource, /getChatConversationHomePromptDeleteConfirmAlertState\(prompt\.name\)/);
  assert.doesNotMatch(screenSource, /confirmFn\?\.\(confirmAlert\.webMessage\)/);
  assert.match(chatMessageChromeSource, /confirmWeb\(confirmAlert\.webMessage\)/);
  assert.doesNotMatch(screenSource, /getPromptLibrarySaveSuccessMessage/);
  assert.match(sessionPresentationSource, /getPromptLibrarySaveSuccessMessage/);
  assert.match(sessionPresentationSource, /export function getChatConversationHomePromptSaveSuccessAlertState/);
  assert.match(sessionPresentationSource, /export function getChatConversationHomePromptSaveFailedAlertState/);
  assert.match(sessionPresentationSource, /export function getChatConversationHomePromptDeleteConfirmAlertState/);
  assert.match(sessionPresentationSource, /export function getChatConversationHomePromptDeleteFailedAlertState/);
  assert.match(sessionPresentationSource, /export function getChatConversationHomePromptTaskStartedAlertState/);
  assert.match(sessionPresentationSource, /export function getChatConversationHomePromptTaskRunFailedAlertState/);
  assert.doesNotMatch(chatMessageChromeSource, /export function formatChatConversationHomePrompt(SaveSuccess|SaveFailed|DeleteWebConfirm|DeleteConfirm|DeleteFailed|TaskStarted|TaskRunFailed)Message/);
  assert.match(sessionPresentationSource, /message: getChatRuntimeAlertMessage\(error, copy\.feedback\.promptSaveFailed\)/);
  assert.match(sessionPresentationSource, /message: getChatRuntimeAlertMessage\(error, copy\.feedback\.promptDeleteFailed\)/);
  assert.match(sessionPresentationSource, /message: getChatRuntimeAlertMessage\(error, copy\.feedback\.taskRunFailed\)/);
  assert.doesNotMatch(screenSource, /error\??\.message \|\| promptLibraryCopy\.feedback\.(promptSaveFailed|promptDeleteFailed|taskRunFailed)/);
  assert.doesNotMatch(screenSource, /promptLibraryCopy\.feedback\.(successTitle|errorTitle|taskStartedTitle|deletePromptTitle)/);
  assert.doesNotMatch(screenSource, /promptLibraryCopy\.actions\.(cancel|delete)/);
  assert.doesNotMatch(screenSource, /newPrompt(Name|Content)\.trim\(\)/);
  assert.doesNotMatch(screenSource, /createChatConversationHomePromptEditorModalChromeProps,/);
  assert.doesNotMatch(screenSource, /promptEditorModalChrome/);
  assert.doesNotMatch(screenSource, /promptEditorRenderStateInput:/);
  assert.match(screenSource, /const chatMessageRuntimeSurface: ChatMessageRuntimeChromePropsInput<PredefinedPromptSummary, Loop> = \{\s+\.\.\.chatRuntimeChrome\.messageRuntime,/);
  assert.match(screenSource, /surface: \{\s+keyboardVerticalOffset: headerHeight,/);
  assert.doesNotMatch(screenSource, /surface: \{\s+platform: Platform\.OS,\s+colors: theme\.colors,/);
  assert.match(sessionPresentationSource, /renderState: getPromptLibraryEditorMobileRenderState\(\{\s+colors,\s+platform,\s+\}\),/);
  assert.match(sessionPresentationSource, /renderState: surfaceChromeRenderState\.promptEditor\.renderState,/);
  assert.match(screenSource, /promptEditorIsEditing,/);
  assert.match(chatScreenSource, /\.\.\.chatRuntimeChrome\.messageRuntime,/);
  assert.doesNotMatch(chatScreenSource, /surface: \{[\s\S]*?promptEditorStyles: promptEditorModalStyles,/);
  assert.doesNotMatch(screenSource, /promptLibraryEditorRenderState\.copy\.(nameLabel|namePlaceholder|contentLabel|contentPlaceholder|cancelLabel)/);
  assert.doesNotMatch(screenSource, /title: getPromptLibraryEditorTitle\(Boolean\(editingPrompt\)\)/);
  assert.doesNotMatch(screenSource, /saveLabel: getPromptLibraryEditorSaveActionLabel\(Boolean\(editingPrompt\), isSavingPrompt\)/);
  assert.match(sessionPresentationSource, /return getPromptLibraryEditorTitle\(isEditing\)/);
  assert.match(sessionPresentationSource, /return getPromptLibraryEditorDismissActionState\(isSaving\)/);
  assert.match(sessionPresentationSource, /createChatConversationHomePromptEditorSaveActionState\(\{\s+draft: \{ name: nameValue, content: contentValue \},\s+isEditing,\s+isSaving,\s+\}\)/);
  assert.doesNotMatch(chatMessageChromeSource, /export function createChatConversationHomePromptEditorModalChromeProps/);
  assert.match(chatMessageChromeSource, /type ChatConversationHomePromptEditorModalMobilePropsParts,/);
  assert.match(chatMessageChromeSource, /type ChatConversationHomePromptEditorModalParts =\s+ChatConversationHomePromptEditorModalMobilePropsParts<ChatConversationHomePromptEditorModalStyles>;/);
  assert.doesNotMatch(chatMessageChromeSource, /type ChatConversationHomePromptEditorModalParts = ReturnType<typeof createChatConversationHomePromptEditorModalMobilePropsParts/);
  assert.match(chatMessageChromeSource, /export function ChatConversationHomePromptEditorModal\(\s+props: ChatConversationHomePromptEditorModalProps,\s+\)/);
  assert.match(chatMessageChromeSource, /const modalParts: ChatConversationHomePromptEditorModalParts =\s+createChatConversationHomePromptEditorModalMobilePropsParts\(props\);/);
  assert.match(chatMessageChromeSource, /type ChatConversationHomePromptEditorModalModalPart = \{\s+props: ComponentProps<typeof Modal>;\s+\};/);
  assert.match(chatMessageChromeSource, /type ChatConversationHomePromptEditorModalKeyboardAvoidingViewPart = \{\s+props: ComponentProps<typeof KeyboardAvoidingView>;\s+\};/);
  assert.match(chatMessageChromeSource, /type ChatConversationHomePromptEditorModalTextPart = \{\s+text: string;\s+props: ComponentProps<typeof Text>;\s+\};/);
  assert.match(chatMessageChromeSource, /type ChatConversationHomePromptEditorModalFrameProps = \{\s+modal: ChatConversationHomePromptEditorModalModalPart;\s+keyboardAvoidingView: ChatConversationHomePromptEditorModalKeyboardAvoidingViewPart;\s+overlay: ChatConversationHomePromptEditorModalViewPart;\s+content: ChatConversationHomePromptEditorModalViewPart;\s+children: ReactNode;\s+\};/);
  assert.match(chatMessageChromeSource, /type ChatConversationHomePromptEditorModalFieldProps = \{\s+label: ChatConversationHomePromptEditorModalTextPart;\s+input: ChatConversationHomePromptEditorModalInputPart;\s+\};/);
  assert.match(chatMessageChromeSource, /type ChatConversationHomePromptEditorModalActionButtonProps = \{\s+button: ChatConversationHomePromptEditorModalTouchablePart;\s+label: ChatConversationHomePromptEditorModalTextPart;\s+\};/);
  assert.doesNotMatch(chatMessageChromeSource, /ChatConversationHomePromptEditorModalParts\['/);
  assert.doesNotMatch(chatMessageChromeSource, /Pick<\s*ChatConversationHomePromptEditorModalParts,/);
  assert.match(chatMessageChromeSource, /<ChatConversationHomePromptEditorModalBody\s+header=\{modalParts\.header\}/);
  assert.match(sessionPresentationSource, /style: styles\.header/);
  assert.match(sessionPresentationSource, /style: styles\.closeButton/);
  assert.match(sessionPresentationSource, /activeOpacity: surface\.closeButton\.pressedOpacity/);
  assert.match(sessionPresentationSource, /accessibilityLabel: copy\.closeAccessibilityLabel/);
  assert.match(sessionPresentationSource, /disabled: editorDismissActionState\.isDisabled/);
  assert.match(sessionPresentationSource, /accessibilityState: editorDismissActionState\.accessibilityState/);
  assert.match(chatMessageChromeSource, /renderState: PromptLibraryEditorMobileRenderState;/);
  assert.match(sessionPresentationSource, /name: chrome\.closeIcon\.name/);
  assert.match(sessionPresentationSource, /size: chrome\.closeIcon\.size/);
  assert.match(sessionPresentationSource, /color: chrome\.closeIconColors\.color/);
  assert.match(sessionPresentationSource, /text: copy\.nameLabel/);
  assert.match(sessionPresentationSource, /accessibilityLabel: copy\.nameAccessibilityLabel/);
  assert.match(sessionPresentationSource, /placeholder: copy\.namePlaceholder/);
  assert.match(sessionPresentationSource, /text: copy\.contentLabel/);
  assert.match(sessionPresentationSource, /accessibilityLabel: copy\.contentAccessibilityLabel/);
  assert.match(sessionPresentationSource, /placeholder: copy\.contentPlaceholder/);
  assert.match(sessionPresentationSource, /text: copy\.cancelLabel/);
  assert.match(sessionPresentationSource, /accessibilityLabel: copy\.cancelAccessibilityLabel/);
  assert.match(sessionPresentationSource, /accessibilityLabel: editorSaveActionState\.accessibilityLabel/);
  assert.match(sessionPresentationSource, /accessibilityState: editorSaveActionState\.accessibilityState/);
  assert.match(sessionPresentationSource, /style: styles\.keyboardAvoidingView/);
  assert.match(sessionPresentationSource, /modalKeyboardAvoidingView: \{\s+flex: surface\.keyboardAvoidingView\.flex/);
  assert.match(sessionPresentationSource, /modalOverlay: \{\s+flex: surface\.overlay\.flex/);
  assert.match(sessionPresentationSource, /getPromptLibraryMobileSurfaceRenderState/);
  assert.doesNotMatch(screenSource, /const promptLibrarySurfaceColors = promptLibraryStyleState\.colors;/);
  assert.match(sessionPresentationSource, /backgroundColor: colors\.overlay\.backgroundColor/);
  assert.match(sessionPresentationSource, /placeholderTextColor: colors\.input\.placeholderColor/);
  assert.match(sessionPresentationSource, /backgroundColor: colors\.content\.backgroundColor/);
  assert.match(sessionPresentationSource, /modalHeader: \{[\s\S]*?flexDirection: surface\.header\.flexDirection/);
  assert.match(sessionPresentationSource, /modalCloseButton: \{[\s\S]*?width: surface\.closeButton\.width/);
  assert.match(sessionPresentationSource, /surface\.actions\.flexDirection/);
  assert.match(sessionPresentationSource, /backgroundColor: colors\.saveButton\.backgroundColor/);
  assert.match(sessionPresentationSource, /color: colors\.saveButtonText\.color/);
  assert.match(sessionPresentationSource, /surface\.saveButton\.alignItems/);
  assert.match(sessionPresentationSource, /surface\.saveButton\.disabledOpacity/);
  assert.doesNotMatch(screenSource, /theme\.colors\[promptEditorModalSurface\.(content|title|label|input|cancelButton|saveButton)\./);
  assert.doesNotMatch(screenSource, /modalOverlay:\s*\{[^}]*?flex:\s*1/);
  assert.doesNotMatch(screenSource, /hexToRgba\(\s*promptEditorModalSurface\.overlay\.backgroundColor/);
  assert.doesNotMatch(screenSource, /backgroundColor:\s*['"]rgba\(0,\s*0,\s*0,\s*0\.5\)['"]/);
  assert.doesNotMatch(screenSource, /modalActions:\s*\{[^}]*?flexDirection:\s*'row'/);
  assert.doesNotMatch(screenSource, /modalSaveButton:\s*\{[^}]*?alignItems:\s*'center'/);
  assert.doesNotMatch(screenSource, /promptEditorModalSurface\.closeIcon\.name/);
});

test('removes the bottom composer prompt-library button', () => {
  assert.doesNotMatch(screenSource, /Open prompts, skills, and tasks/);
  assert.doesNotMatch(screenSource, /promptLibraryVisible/);
  assert.doesNotMatch(screenSource, /Prompts, Skills & Tasks/);
});
