const test = require('node:test');
const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');

const screenSource = fs.readFileSync(
  path.join(__dirname, '..', 'src', 'screens', 'ChatScreen.tsx'),
  'utf8'
);
const chatMessageChromeSource = fs.readFileSync(
  path.join(__dirname, '..', 'src', 'ui', 'ChatMessageChrome.tsx'),
  'utf8'
);

test('shows desktop library items directly in the new-chat prompt launchers', () => {
  assert.match(screenSource, /const promptQuickStarts = useMemo/);
  assert.match(screenSource, /buildPromptLibraryShortcutItems,/);
  assert.match(screenSource, /\(\) => buildPromptLibraryShortcutItems\(\{/);
  assert.match(screenSource, /prompts: predefinedPrompts,/);
  assert.match(screenSource, /skills: availableSkills,/);
  assert.match(screenSource, /tasks: availableTasks,/);
  assert.match(screenSource, /canAddPrompt: Boolean\(settingsClient\),/);
  assert.match(screenSource, /addPromptTitle: mobilePromptLibraryCopy\.addPromptTitle,/);
  assert.match(screenSource, /addPromptDescription: mobilePromptLibraryCopy\.addPromptDescription,/);
  assert.match(screenSource, /taskDescriptionFallback: mobilePromptLibraryCopy\.taskDescriptionFallback,/);
  assert.match(screenSource, /settingsClient\.getSkills\(\)/);
  assert.match(screenSource, /settingsClient\.getLoops\(\)/);
  assert.match(screenSource, /handleRunPromptTask/);
  assert.doesNotMatch(chatMessageChromeSource, /getPromptLibraryShortcutSourceLabel\(item\.source\)/);
  assert.match(chatMessageChromeSource, /type PromptLibraryLauncherShortcutSource,/);
  assert.match(chatMessageChromeSource, /type PromptLibraryShortcutItem,/);
  assert.match(chatMessageChromeSource, /type PromptLibraryEditorMobileRenderState,/);
  assert.match(chatMessageChromeSource, /type PromptLibraryMobileShortcutRenderState,/);
  assert.match(chatMessageChromeSource, /getPromptLibraryMobileShortcutItemRenderState,/);
  assert.match(chatMessageChromeSource, /export type ChatConversationHomeQuickStartSource = PromptLibraryLauncherShortcutSource;/);
  assert.match(chatMessageChromeSource, /export type ChatConversationHomeQuickStartItem<[\s\S]*?> = PromptLibraryShortcutItem<TPrompt, TTask>;/);
  assert.match(screenSource, /getPromptLibraryCopyState,/);
  assert.match(screenSource, /getPromptLibraryEditorMobileRenderState,/);
  assert.match(screenSource, /getPromptLibraryShortcutPressIntent,/);
  assert.doesNotMatch(screenSource, /getPromptLibraryEditorTitle,/);
  assert.doesNotMatch(screenSource, /getPromptLibraryEditorSaveActionLabel,/);
  assert.match(chatMessageChromeSource, /getPromptLibraryEditorTitle,/);
  assert.match(chatMessageChromeSource, /getPromptLibraryEditorSaveActionLabel,/);
  assert.doesNotMatch(screenSource, /getPromptLibraryEditorMobileChromeState,/);
  assert.match(screenSource, /getPromptLibraryMobileShortcutRenderState,/);
  assert.doesNotMatch(screenSource, /getPromptLibraryMobileShortcutChromeState,/);
  assert.doesNotMatch(screenSource, /getPromptLibraryMobileShortcutCopyState,/);
  assert.doesNotMatch(screenSource, /getPromptLibraryMobileShortcutSurfaceState,/);
  assert.match(screenSource, /getPromptLibraryMobileSurfaceState,/);
  assert.match(screenSource, /getPromptLibraryMobileCopyState,/);
  assert.doesNotMatch(screenSource, /getPromptLibraryMobileEmptyLibraryLabel,/);
  assert.doesNotMatch(screenSource, /getPromptLibraryMobileIconColors,/);
  assert.match(screenSource, /getPromptLibraryMobileSurfaceColors,/);
  assert.match(screenSource, /const mobilePromptLibrarySurface = getPromptLibraryMobileSurfaceState\(\);/);
  assert.match(screenSource, /const promptLibraryCopy = getPromptLibraryCopyState\(\);/);
  assert.match(screenSource, /const promptLibraryEditorRenderState = useMemo\(\s+\(\) => getPromptLibraryEditorMobileRenderState\(\{\s+colors: theme\.colors,\s+platform: Platform\.OS,\s+\}\),\s+\[theme\.colors\],\s+\);/);
  assert.match(screenSource, /const promptLibraryShortcutRenderState = useMemo\(\s+\(\) => getPromptLibraryMobileShortcutRenderState\(theme\.colors\),\s+\[theme\.colors\],\s+\);/);
  assert.match(screenSource, /const mobilePromptLibraryCopy = getPromptLibraryMobileCopyState\(\);/);
  assert.doesNotMatch(screenSource, /const mobilePromptLibraryEmptyLabel = getPromptLibraryMobileEmptyLibraryLabel\(\);/);
  assert.match(screenSource, /runningTaskId: runningPromptTaskId/);
  assert.match(screenSource, /shortcutRenderState: promptLibraryShortcutRenderState/);
  assert.match(screenSource, /const pressIntent = getPromptLibraryShortcutPressIntent\(item\);/);
  assert.match(screenSource, /if \(pressIntent\.kind === 'add-prompt'\)/);
  assert.match(screenSource, /if \(pressIntent\.kind === 'run-task'\)/);
  assert.match(screenSource, /handleRunPromptTask\(pressIntent\.task\)/);
  assert.match(screenSource, /handleInsertQuickStartPrompt\(pressIntent\.content\)/);
  assert.doesNotMatch(screenSource, /item\.action === 'add-prompt'/);
  assert.doesNotMatch(screenSource, /item\.source === 'task' && item\.task/);
  assert.doesNotMatch(screenSource, /handleInsertQuickStartPrompt\(item\.content\)/);
  assert.doesNotMatch(screenSource, /shortcutCopy: promptLibraryShortcutCopy/);
  assert.doesNotMatch(screenSource, /loadingLabel: mobilePromptLibraryCopy\.loadingLibraryLabel/);
  assert.doesNotMatch(screenSource, /emptyLabel: mobilePromptLibraryEmptyLabel/);
  assert.doesNotMatch(screenSource, /shortcutSurface: promptLibraryShortcutSurface/);
  assert.doesNotMatch(screenSource, /sourceLabelNumberOfLines: mobilePromptLibrarySurface\.shortcutSourceLabel\.numberOfLines/);
  assert.match(chatMessageChromeSource, /shortcutRenderState: PromptLibraryMobileShortcutRenderState;/);
  assert.match(chatMessageChromeSource, /const \{ chrome: shortcutChrome, copy: shortcutCopy, surface: shortcutSurface \} = shortcutRenderState;/);
  assert.match(chatMessageChromeSource, /numberOfLines=\{shortcutSurface\.shortcutSourceLabel\.numberOfLines\}/);
  assert.match(chatMessageChromeSource, /<ChatConversationHomeQuickStarts\s+\{\.\.\.homeQuickStarts\}\s+styles=\{styles\.homeQuickStarts\}/);
  assert.doesNotMatch(screenSource, /shortcutChrome: promptLibraryShortcutChrome/);
  assert.doesNotMatch(screenSource, /addIcon: promptLibraryShortcutChrome\.addIcon/);
  assert.doesNotMatch(screenSource, /sourceIcons: promptLibraryShortcutChrome\.sourceIcons/);
  assert.doesNotMatch(chatMessageChromeSource, /const sourceIcon = shortcutChrome\.sourceIcons\[item\.source\];/);
  assert.doesNotMatch(chatMessageChromeSource, /const shortcutSourceIconColors = shortcutChrome\.sourceIconColors\[item\.source\];/);
  assert.match(chatMessageChromeSource, /const shortcutItemRenderState = getPromptLibraryMobileShortcutItemRenderState\(\s+item,\s+shortcutRenderState,\s+runningTaskId,\s+\);/);
  assert.match(chatMessageChromeSource, /const \{ interaction: shortcutInteraction \} = shortcutItemRenderState;/);
  assert.match(chatMessageChromeSource, /const promptActions = shortcutItemRenderState\.promptActions;/);
  assert.match(chatMessageChromeSource, /disabled=\{shortcutInteraction\.isDisabled\}/);
  assert.match(chatMessageChromeSource, /accessibilityState=\{shortcutInteraction\.accessibilityState\}/);
  assert.match(chatMessageChromeSource, /accessibilityHint=\{shortcutItemRenderState\.accessibilityHint\}/);
  assert.doesNotMatch(chatMessageChromeSource, /const isAddPrompt = item\.action === 'add-prompt'/);
  assert.doesNotMatch(chatMessageChromeSource, /const isTaskRunning = item\.source === 'task' && runningTaskId === item\.task\?\.id/);
  assert.match(chatMessageChromeSource, /name=\{shortcutItemRenderState\.sourceIcon\.name\}/);
  assert.match(chatMessageChromeSource, /size=\{shortcutItemRenderState\.sourceIcon\.size\}/);
  assert.match(chatMessageChromeSource, /color=\{shortcutItemRenderState\.sourceIconColors\.color\}/);
  assert.match(chatMessageChromeSource, /name=\{shortcutChrome\.addIcon\.name\}/);
  assert.match(chatMessageChromeSource, /size=\{shortcutChrome\.addIcon\.size\}/);
  assert.match(chatMessageChromeSource, /color=\{shortcutChrome\.addIconColors\.color\}/);
  assert.match(chatMessageChromeSource, /style=\{styles\.addIcon\}/);
  assert.match(chatMessageChromeSource, /pressed && styles\.actionButtonPressed/);
  assert.match(chatMessageChromeSource, /\{item\.prompt && promptActions \? \(/);
  assert.match(chatMessageChromeSource, /accessibilityLabel=\{promptActions\.edit\.accessibilityLabel\}/);
  assert.match(chatMessageChromeSource, /name=\{promptActions\.edit\.icon\.name\}/);
  assert.match(chatMessageChromeSource, /size=\{promptActions\.edit\.icon\.size\}/);
  assert.match(chatMessageChromeSource, /color=\{promptActions\.edit\.iconColors\.color\}/);
  assert.match(chatMessageChromeSource, /\{promptActions\.edit\.label\}/);
  assert.match(chatMessageChromeSource, /accessibilityLabel=\{promptActions\.delete\.accessibilityLabel\}/);
  assert.match(chatMessageChromeSource, /name=\{promptActions\.delete\.icon\.name\}/);
  assert.match(chatMessageChromeSource, /size=\{promptActions\.delete\.icon\.size\}/);
  assert.match(chatMessageChromeSource, /color=\{promptActions\.delete\.iconColors\.color\}/);
  assert.match(chatMessageChromeSource, /\{promptActions\.delete\.label\}/);
  assert.doesNotMatch(chatMessageChromeSource, /getPromptLibraryEditPromptAccessibilityLabel\(item\.title\)/);
  assert.doesNotMatch(chatMessageChromeSource, /getPromptLibraryDeletePromptAccessibilityLabel\(item\.title\)/);
  assert.doesNotMatch(chatMessageChromeSource, /shortcutChrome\.(edit|delete)Icon/);
  assert.doesNotMatch(chatMessageChromeSource, /shortcutChrome\.(edit|delete)IconColors/);
  assert.match(chatMessageChromeSource, /homeQuickStarts: \{\s+card: styles\.chatHomeCard,\s+emptyText: styles\.chatHomeEmptyText,\s+grid: styles\.chatHomeShortcutGrid,\s+shortcutCard: styles\.chatHomeShortcutCard,/);
  assert.match(screenSource, /chatHomeShortcutSourcePill:\s*\{[\s\S]*?promptLibrarySurface\.shortcutSourcePill\.alignSelf/);
  assert.match(screenSource, /chatHomeShortcutSourcePill:\s*\{[\s\S]*?flexDirection:\s*promptLibrarySurface\.shortcutSourcePill\.flexDirection/);
  assert.match(screenSource, /chatHomeShortcutSourcePill:\s*\{[\s\S]*?alignItems:\s*promptLibrarySurface\.shortcutSourcePill\.alignItems/);
  assert.match(screenSource, /chatHomeShortcutAddIcon:\s*\{[\s\S]*?marginBottom:\s*promptLibrarySurface\.addShortcutIcon\.marginBottom/);
  assert.match(screenSource, /chatHomeShortcutSourceLabel:\s*\{[\s\S]*?promptLibrarySurface\.shortcutSourceLabel\.textTransform/);
  assert.match(screenSource, /chatHomeShortcutActionButton:\s*\{[\s\S]*?flexDirection:\s*promptLibrarySurface\.shortcutActionButton\.flexDirection/);
  assert.match(screenSource, /chatHomeShortcutActionButtonPressed:\s*\{[\s\S]*?opacity:\s*promptLibrarySurface\.shortcutActionButton\.pressedOpacity/);
  assert.doesNotMatch(screenSource, /predefinedPrompts\s*\.slice/);
  assert.doesNotMatch(screenSource, /availableSkills\.slice/);
  assert.doesNotMatch(screenSource, /availableTasks\.slice/);
  assert.match(chatMessageChromeSource, /items\.map\(\(item\) =>/);
  assert.doesNotMatch(chatMessageChromeSource, /shortcutCopy\.(edit|delete)Label/);
  assert.match(chatMessageChromeSource, /\{isLoading \? shortcutCopy\.loadingLabel : shortcutCopy\.emptyLabel\}/);
  assert.doesNotMatch(screenSource, /source: isSlashCommandPrompt\(prompt\) \? 'command' as const : 'saved-prompt' as const/);
  assert.doesNotMatch(screenSource, /source: 'skill' as const/);
  assert.doesNotMatch(screenSource, /source: 'task' as const/);
  assert.doesNotMatch(screenSource, /id: `skill-\$\{skill\.id\}`/);
  assert.doesNotMatch(screenSource, /id: `task-\$\{task\.id\}`/);
  assert.doesNotMatch(screenSource, /id: 'action-add-prompt'/);
  assert.doesNotMatch(screenSource, /getPromptLibraryMobileShortcutSourceIconState\('command'\)/);
  assert.doesNotMatch(screenSource, /getPromptLibraryMobileIconColors\(promptLibraryShortcutSourceIcons\./);
  assert.doesNotMatch(screenSource, /getPromptLibraryMobileAddShortcutIconState\(\)/);
  assert.doesNotMatch(screenSource, /getPromptLibraryMobileShortcutActionIconState\('edit'\)/);
  assert.doesNotMatch(screenSource, /getPromptLibraryMobileLauncherShortcutSourceIconColors\(theme\.colors\)/);
  assert.doesNotMatch(chatMessageChromeSource, /PromptLibraryShortcutSource,/);
  assert.doesNotMatch(chatMessageChromeSource, /Extract<\s*PromptLibraryShortcutSource,/);
  assert.doesNotMatch(chatMessageChromeSource, /source: ChatConversationHomeQuickStartSource;/);
  assert.doesNotMatch(screenSource, /PROMPT_LIBRARY_PRESENTATION/);
  assert.match(screenSource, /const promptLibrarySurface = mobilePromptLibrarySurface;/);
  assert.match(screenSource, /const promptLibrarySurfaceColors = getPromptLibraryMobileSurfaceColors\(theme\.colors\);/);
  assert.doesNotMatch(screenSource, /theme\.colors\[(sourceIcon|promptLibraryAddShortcutIcon|promptLibraryEditActionIcon|promptLibraryDeleteActionIcon)\.colorToken\]/);
  assert.doesNotMatch(screenSource, /theme\.colors\[promptLibrarySurface\./);
  assert.doesNotMatch(screenSource, /PROMPT_LIBRARY_SURFACE_PRESENTATION,/);
  assert.doesNotMatch(screenSource, /PROMPT_LIBRARY_SURFACE_PRESENTATION\.mobile/);
  assert.doesNotMatch(screenSource, /promptLibrarySurface\.shortcutActionIcon\.editName/);
  assert.doesNotMatch(screenSource, /promptLibrarySurface\.shortcutSourceIcon\.skillName/);
  assert.doesNotMatch(screenSource, /promptLibrarySurface\.addShortcutIcon\.name/);
  assert.doesNotMatch(screenSource, /title: 'Custom Commands'/);
  assert.doesNotMatch(screenSource, /title: 'Saved Prompts'/);
  assert.doesNotMatch(screenSource, /title: 'Prompt Library'/);
  assert.doesNotMatch(screenSource, /title: 'Starter Packs'/);
  assert.doesNotMatch(screenSource, /STARTER_PACK_SHORTCUTS/);
});

test('can create a new predefined prompt from mobile and save it to desktop settings', () => {
  assert.match(screenSource, /canAddPrompt: Boolean\(settingsClient\)/);
  assert.match(screenSource, /addPromptTitle: mobilePromptLibraryCopy\.addPromptTitle/);
  assert.match(screenSource, /addPromptDescription: mobilePromptLibraryCopy\.addPromptDescription/);
  assert.match(screenSource, /setAddPromptModalVisible\(true\)/);
  assert.match(screenSource, /const handleSavePrompt = async \(\) =>/);
  assert.match(screenSource, /isPromptLibraryEditorSaveDisabled\(draft, isSavingPrompt\)/);
  assert.match(screenSource, /onSave: handleSavePrompt/);
  assert.match(chatMessageChromeSource, /onPress=\{onSave\}/);
  assert.match(screenSource, /await settingsClient\.updateSettings\(\{ predefinedPrompts: updatedPrompts \}\)/);
  assert.match(screenSource, /getPromptLibrarySaveSuccessMessage\(Boolean\(editingPrompt\)\)/);
  assert.doesNotMatch(screenSource, /newPrompt(Name|Content)\.trim\(\)/);
  assert.doesNotMatch(screenSource, /createChatConversationHomePromptEditorModalChromeProps,/);
  assert.doesNotMatch(screenSource, /promptEditorModalChrome/);
  assert.match(screenSource, /renderState: promptLibraryEditorRenderState/);
  assert.match(screenSource, /isEditing: Boolean\(editingPrompt\)/);
  assert.match(screenSource, /styles: promptEditorModalStyles/);
  assert.doesNotMatch(screenSource, /promptLibraryEditorRenderState\.copy\.(nameLabel|namePlaceholder|contentLabel|contentPlaceholder|cancelLabel)/);
  assert.doesNotMatch(screenSource, /title: getPromptLibraryEditorTitle\(Boolean\(editingPrompt\)\)/);
  assert.doesNotMatch(screenSource, /saveLabel: getPromptLibraryEditorSaveActionLabel\(Boolean\(editingPrompt\), isSavingPrompt\)/);
  assert.match(chatMessageChromeSource, /getPromptLibraryEditorTitle\(isEditing\)/);
  assert.match(chatMessageChromeSource, /getPromptLibraryEditorSaveActionLabel\(isEditing, isSaving\)/);
  assert.doesNotMatch(chatMessageChromeSource, /export function createChatConversationHomePromptEditorModalChromeProps/);
  assert.match(chatMessageChromeSource, /style=\{styles\.header\}/);
  assert.match(chatMessageChromeSource, /style=\{styles\.closeButton\}/);
  assert.match(chatMessageChromeSource, /activeOpacity=\{surface\.closeButton\.pressedOpacity\}/);
  assert.match(chatMessageChromeSource, /accessibilityLabel=\{copy\.closeAccessibilityLabel\}/);
  assert.match(chatMessageChromeSource, /renderState: PromptLibraryEditorMobileRenderState;/);
  assert.match(chatMessageChromeSource, /name=\{editorChrome\.closeIcon\.name\}/);
  assert.match(chatMessageChromeSource, /size=\{editorChrome\.closeIcon\.size\}/);
  assert.match(chatMessageChromeSource, /color=\{editorChrome\.closeIconColors\.color\}/);
  assert.match(chatMessageChromeSource, /\{copy\.nameLabel\}/);
  assert.match(chatMessageChromeSource, /placeholder=\{copy\.namePlaceholder\}/);
  assert.match(chatMessageChromeSource, /\{copy\.contentLabel\}/);
  assert.match(chatMessageChromeSource, /placeholder=\{copy\.contentPlaceholder\}/);
  assert.match(chatMessageChromeSource, /\{copy\.cancelLabel\}/);
  assert.match(chatMessageChromeSource, /style=\{styles\.keyboardAvoidingView\}/);
  assert.match(screenSource, /promptEditorModalSurface\.keyboardAvoidingView\.flex/);
  assert.match(screenSource, /promptEditorModalSurface\.overlay\.flex/);
  assert.match(screenSource, /getPromptLibraryMobileSurfaceColors,/);
  assert.match(screenSource, /const promptLibrarySurfaceColors = getPromptLibraryMobileSurfaceColors\(theme\.colors\);/);
  assert.match(screenSource, /backgroundColor:\s*promptLibrarySurfaceColors\.editorModal\.overlay\.backgroundColor/);
  assert.match(chatMessageChromeSource, /placeholderTextColor=\{colors\.input\.placeholderColor\}/);
  assert.match(screenSource, /backgroundColor:\s*promptLibrarySurfaceColors\.editorModal\.content\.backgroundColor/);
  assert.match(screenSource, /modalHeader:\s*\{[\s\S]*?flexDirection:\s*promptEditorModalSurface\.header\.flexDirection/);
  assert.match(screenSource, /modalCloseButton:\s*\{[\s\S]*?width:\s*promptEditorModalSurface\.closeButton\.width/);
  assert.match(screenSource, /promptEditorModalSurface\.actions\.flexDirection/);
  assert.match(screenSource, /promptLibrarySurfaceColors\.editorModal\.saveButton\.backgroundColor/);
  assert.match(screenSource, /promptLibrarySurfaceColors\.editorModal\.saveButtonText\.color/);
  assert.match(screenSource, /promptEditorModalSurface\.saveButton\.alignItems/);
  assert.match(screenSource, /promptEditorModalSurface\.saveButton\.disabledOpacity/);
  assert.doesNotMatch(screenSource, /theme\.colors\[promptEditorModalSurface\.(content|title|label|input|cancelButton|saveButton)\./);
  assert.doesNotMatch(screenSource, /modalOverlay:\s*\{[^}]*?flex:\s*1/);
  assert.doesNotMatch(screenSource, /hexToRgba\(\s*promptEditorModalSurface\.overlay\.backgroundColor/);
  assert.doesNotMatch(screenSource, /backgroundColor:\s*['"]rgba\(0,\s*0,\s*0,\s*0\.5\)['"]/);
  assert.doesNotMatch(screenSource, /modalActions:\s*\{[^}]*?flexDirection:\s*'row'/);
  assert.doesNotMatch(screenSource, /modalSaveButton:\s*\{[^}]*?alignItems:\s*'center'/);
  assert.doesNotMatch(screenSource, /promptEditorModalSurface\.closeIcon\.name/);
});

test('removes the bottom composer prompt-library button', () => {
  assert.doesNotMatch(screenSource, /Open prompts, skills, and tasks/);
  assert.doesNotMatch(screenSource, /promptLibraryVisible/);
  assert.doesNotMatch(screenSource, /Prompts, Skills & Tasks/);
});
