const test = require('node:test');
const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');

const rendererSource = fs.readFileSync(
  path.join(__dirname, '..', 'src', 'ui', 'MarkdownRenderer.tsx'),
  'utf8',
);
const markdownRenderPartsSource = fs.readFileSync(
  path.join(__dirname, '..', '..', '..', 'packages', 'shared', 'src', 'markdown-render-parts.ts'),
  'utf8',
);

test('markdown renderer loads conversation image assets through authenticated remote API', () => {
  assert.match(rendererSource, /parseConversationImageAssetUrl/);
  assert.match(rendererSource, /isAllowedMarkdownImageUrl/);
  assert.match(rendererSource, /getMarkdownImageFallbackLabel/);
  assert.match(rendererSource, /getMarkdownImageUnavailableLabel/);
  assert.match(rendererSource, /getMarkdownImageInvalidAssetUrlMessage/);
  assert.match(rendererSource, /getMarkdownImageLoadErrorFallback/);
  assert.match(rendererSource, /getMarkdownRenderOptions/);
  assert.match(rendererSource, /isAllowedMarkdownContentLinkUrl/);
  assert.match(rendererSource, /formatMarkdownImageRequestFailedMessage/);
  assert.match(rendererSource, /getConversationImageAssetResponse\(assetRef\.conversationId, assetRef\.fileName\)/);
  assert.match(rendererSource, /throw new Error\(formatMarkdownImageRequestFailedMessage\(response\.status\)\)/);
  assert.match(rendererSource, /buildConversationImageAssetHttpUrl\(assetBaseUrl, sourceUrl\)/);
  assert.match(rendererSource, /setError\(getMarkdownImageUnavailableLabel\(\)\)/);
  assert.match(rendererSource, /throw new Error\(getMarkdownImageInvalidAssetUrlMessage\(\)\)/);
  assert.match(rendererSource, /getMarkdownImageLoadErrorFallback\(\)/);
  assert.match(rendererSource, /const imageLabel = getMarkdownImageFallbackLabel\(alt\);/);
  assert.match(rendererSource, /return <Text>\{imageLabel\}<\/Text>;/);
  assert.match(rendererSource, /accessibilityLabel=\{imageLabel\}/);
  assert.match(rendererSource, /await client\.buildRequestHeaders\(\)/);
  assert.match(rendererSource, /rules=\{markdownRules\}/);
  assert.match(rendererSource, /<ThinkSection[\s\S]*?markdownRules=\{markdownRules\}/);
  assert.match(rendererSource, /splitMarkdownContent\(content, getMarkdownRenderOptions\(\)\)/);
  assert.match(rendererSource, /onLinkPress=\{isAllowedMarkdownContentLinkUrl\}/);
  assert.doesNotMatch(rendererSource, /MARKDOWN_CONTENT_PRESENTATION/);
  assert.doesNotMatch(rendererSource, /setError\('Image unavailable\.'\)/);
  assert.doesNotMatch(rendererSource, /throw new Error\('Invalid image asset URL\.'\)/);
  assert.doesNotMatch(rendererSource, /'Unable to load image\.'/);
  assert.doesNotMatch(rendererSource, /alt \|\| 'Image'/);
  assert.doesNotMatch(rendererSource, /accessibilityLabel=\{alt\}/);
});

test('markdown renderer uses shared think-section copy and surface tokens', () => {
  assert.match(rendererSource, /getMarkdownThinkSectionAccessibilityLabel\(collapsed\)/);
  assert.match(rendererSource, /getMarkdownThinkSectionAccessibilityState\(collapsed\)/);
  assert.match(rendererSource, /getMarkdownThinkSectionDisplayLabel\(collapsed\)/);
  assert.match(rendererSource, /getMarkdownThinkSectionMobileChevronIconState/);
  assert.match(rendererSource, /getMarkdownThinkSectionMobileLeadingIconState/);
  assert.match(rendererSource, /getMarkdownThinkSectionMobileSurfaceRenderState/);
  assert.match(rendererSource, /getMarkdownThinkSectionControlState/);
  assert.match(rendererSource, /type MarkdownThinkSectionMobileSurfaceRenderState/);
  assert.match(rendererSource, /type MarkdownThinkSectionControlOptions/);
  assert.match(rendererSource, /interface MarkdownRendererProps extends MarkdownThinkSectionControlOptions/);
  assert.match(rendererSource, /createMarkdownThinkSectionMobileStyleSlots/);
  assert.match(markdownRenderPartsSource, /export function createMarkdownThinkSectionMobileStyleSlots\(\{/);
  assert.match(markdownRenderPartsSource, /const surface = renderState\.surface/);
  assert.match(rendererSource, /surface: MarkdownThinkSectionMobileSurfaceRenderState\['surface'\]/);
  assert.match(markdownRenderPartsSource, /const colors = renderState\.colors/);
  assert.match(rendererSource, /const thinkSectionRenderState = React\.useMemo\([\s\S]*?getMarkdownThinkSectionMobileSurfaceRenderState\(\{ isDark \}\)/);
  assert.match(rendererSource, /const thinkSectionColors = thinkSectionRenderState\.colors;/);
  assert.match(rendererSource, /const thinkSectionStyleSlots = React\.useMemo\([\s\S]*?createMarkdownThinkSectionMobileStyleSlots\(\{[\s\S]*?renderState: thinkSectionRenderState,[\s\S]*?spacing,[\s\S]*?radius,[\s\S]*?\}\)/);
  assert.match(rendererSource, /const thinkStyles = React\.useMemo\([\s\S]*?StyleSheet\.create\(thinkSectionStyleSlots\)/);
  assert.match(rendererSource, /const chevronIcon = getMarkdownThinkSectionMobileChevronIconState\(collapsed\);/);
  assert.match(rendererSource, /const thinkIcon = getMarkdownThinkSectionMobileLeadingIconState\(\);/);
  assert.match(rendererSource, /name=\{chevronIcon\.name\}/);
  assert.match(rendererSource, /size=\{chevronIcon\.size\}/);
  assert.match(rendererSource, /name=\{thinkIcon\.name\}/);
  assert.match(rendererSource, /size=\{thinkIcon\.size\}/);
  assert.match(rendererSource, /color=\{colors\.chevron\.color\}/);
  assert.match(rendererSource, /color=\{colors\.icon\.color\}/);
  assert.match(rendererSource, /accessibilityRole=\{surface\.header\.accessibilityRole\}/);
  assert.match(rendererSource, /accessibilityState=\{getMarkdownThinkSectionAccessibilityState\(collapsed\)\}/);
  assert.match(rendererSource, /surface=\{thinkSectionRenderState\.surface\}/);
  assert.match(rendererSource, /colors=\{thinkSectionColors\}/);
  assert.match(rendererSource, /const thinkControl = getMarkdownThinkSectionControlState\(part\.content, index, \{/);
  assert.match(rendererSource, /key=\{thinkControl\.key\}/);
  assert.match(rendererSource, /defaultCollapsed=\{true\}/);
  assert.match(rendererSource, /thinkControl\.isControlled \? \{/);
  assert.match(rendererSource, /isCollapsed: thinkControl\.isCollapsed/);
  assert.match(rendererSource, /onToggle: thinkControl\.onToggle/);
  assert.match(rendererSource, /const collapsed = isCollapsed \?\? internalCollapsed;/);
  assert.match(rendererSource, /if \(onToggle\) \{\s+onToggle\(\);\s+return;\s+\}/);
  assert.doesNotMatch(rendererSource, /const keyBase = getThinkKey/);
  assert.doesNotMatch(rendererSource, /const isControlled = !!\(isThinkExpanded && onToggleThink\)/);
  assert.match(markdownRenderPartsSource, /borderRadius:\s*radius\[surface\.container\.borderRadius\]/);
  assert.match(markdownRenderPartsSource, /borderColor:\s*colors\.collapsedContainer\.borderColor/);
  assert.match(markdownRenderPartsSource, /backgroundColor:\s*colors\.expandedContainer\.backgroundColor/);
  assert.match(markdownRenderPartsSource, /paddingHorizontal:\s*resolveMarkdownMobileSpacing\(surface\.header\.paddingHorizontal, spacing\)/);
  assert.match(markdownRenderPartsSource, /color:\s*colors\.label\.color/);
  assert.match(markdownRenderPartsSource, /paddingBottom:\s*resolveMarkdownMobileSpacing\(surface\.content\.paddingBottom, spacing\)/);
  assert.match(markdownRenderPartsSource, /function resolveMarkdownMobileSpacing\(/);
  assert.doesNotMatch(rendererSource, /resolveThemedColor/);
  assert.doesNotMatch(rendererSource, /resolveThemedAlphaColor/);
  assert.doesNotMatch(rendererSource, /ThemedAlphaColor/);
  assert.doesNotMatch(rendererSource, /ThemedColor/);
  assert.doesNotMatch(rendererSource, /const thinkSectionIcons = getMarkdownThinkSectionMobileIconState\(\);/);
  assert.doesNotMatch(rendererSource, /getMarkdownThinkSectionMobileSurfaceState/);
  assert.doesNotMatch(rendererSource, /getMarkdownThinkSectionMobileSurfaceColors/);
  assert.doesNotMatch(rendererSource, /getMarkdownThinkSectionMobile(Container|Content|Header|Label)State/);
  assert.doesNotMatch(rendererSource, /type MarkdownThinkSectionMobileSurfaceColors/);
  assert.doesNotMatch(rendererSource, /thinkSectionIcons\.(collapsedName|expandedName|thinkName)/);
  assert.doesNotMatch(rendererSource, /thinkSectionSurface\.(chevron|icon)\.(size|color)/);
  assert.doesNotMatch(rendererSource, /accessibilityLabel=\{collapsed \? 'Show thinking' : 'Hide thinking'\}/);
  assert.doesNotMatch(rendererSource, /accessibilityState=\{\{ expanded: !collapsed \}\}/);
  assert.doesNotMatch(rendererSource, /accessibilityRole="button"/);
  assert.doesNotMatch(rendererSource, /\{collapsed \? 'Thinking' : 'Hide thinking'\}/);
  assert.doesNotMatch(rendererSource, /MARKDOWN_THINK_SECTION_PRESENTATION/);
  assert.doesNotMatch(rendererSource, /MARKDOWN_THINK_SECTION_SURFACE_PRESENTATION/);
  assert.doesNotMatch(rendererSource, /MARKDOWN_THINK_SECTION_PRESENTATION\.mobileGlyphs/);
  assert.doesNotMatch(rendererSource, /borderColor:\s*isDark \? 'rgba\(251,191,36,0\.28\)'/);
  assert.doesNotMatch(rendererSource, /rgba\(251,191,36,0\.28\)/);
});

test('markdown renderer uses shared compact markdown content surface tokens', () => {
  assert.match(rendererSource, /getMarkdownContentMobileSurfaceRenderState/);
  assert.match(rendererSource, /createMarkdownContentMobileStyleSlots/);
  assert.match(markdownRenderPartsSource, /export function createMarkdownContentMobileStyleSlots\(\{/);
  assert.match(rendererSource, /type MarkdownContentMobileSurfaceRenderState/);
  assert.match(rendererSource, /const markdownContentRenderState = React\.useMemo\([\s\S]*?getMarkdownContentMobileSurfaceRenderState\(\{[\s\S]*?colors: theme\.colors,[\s\S]*?isDark,[\s\S]*?\}\)/);
  assert.match(markdownRenderPartsSource, /const surface = renderState\.surface/);
  assert.match(rendererSource, /const markdownContentColors = markdownContentRenderState\.colors;/);
  assert.match(markdownRenderPartsSource, /function resolveMarkdownMobileFontFamily\(/);
  assert.doesNotMatch(rendererSource, /from '\.\/mobileTypography'/);
  assert.match(markdownRenderPartsSource, /fontSize:\s*surface\.body\.fontSize/);
  assert.match(markdownRenderPartsSource, /lineHeight:\s*surface\.body\.lineHeight/);
  assert.match(markdownRenderPartsSource, /color:\s*colors\.body\.color/);
  assert.match(markdownRenderPartsSource, /const inlineCodeFontFamily = resolveMarkdownMobileFontFamily\(surface\.inlineCode\.fontFamilyByPlatform, platform\)/);
  assert.match(markdownRenderPartsSource, /const codeBlockFontFamily = resolveMarkdownMobileFontFamily\(surface\.codeBlock\.fontFamilyByPlatform, platform\)/);
  assert.match(markdownRenderPartsSource, /borderRadius:\s*radius\[surface\.codeBlock\.borderRadius\]/);
  assert.match(rendererSource, /import \* as Clipboard from 'expo-clipboard';/);
  assert.match(rendererSource, /Ionicons/);
  assert.match(rendererSource, /const MarkdownCodeBlock/);
  assert.match(rendererSource, /createMarkdownCodeBlockCopyMobilePropsParts/);
  assert.match(markdownRenderPartsSource, /export function createMarkdownCodeBlockCopyMobilePropsParts/);
  assert.match(rendererSource, /getMarkdownCodeBlockCopyMobileRenderState/);
  assert.match(rendererSource, /const codeBlockCopyRenderState = getMarkdownCodeBlockCopyMobileRenderState\(\{[\s\S]*?isCopied: copied,[\s\S]*?colors,/);
  assert.match(rendererSource, /const codeBlockCopyParts = createMarkdownCodeBlockCopyMobilePropsParts\(\{[\s\S]*?renderState: codeBlockCopyRenderState,[\s\S]*?styles,[\s\S]*?codeContent,[\s\S]*?isCopied: copied,[\s\S]*?onCopy: handleCopy,/);
  assert.match(markdownRenderPartsSource, /const codeBlockCopyButton = getMarkdownCodeBlockCopyMobileRenderState\(\{ colors \}\)/);
  assert.match(markdownRenderPartsSource, /const copiedCodeBlockCopyButton = getMarkdownCodeBlockCopyMobileRenderState\(\{[\s\S]*?isCopied: true,[\s\S]*?colors,[\s\S]*?\}\)/);
  assert.match(markdownRenderPartsSource, /accessibilityRole: renderState\.button\.accessibilityRole/);
  assert.match(markdownRenderPartsSource, /accessibilityLabel: renderState\.label/);
  assert.match(rendererSource, /<Pressable\s+\{\.\.\.codeBlockCopyParts\.button\.props\}/);
  assert.match(rendererSource, /getMarkdownCodeBlockFeedbackResetDelayMs\(\)/);
  assert.match(rendererSource, /Clipboard\.setStringAsync\(codeContent\)/);
  assert.match(markdownRenderPartsSource, /props: renderState\.icon/);
  assert.match(rendererSource, /<Ionicons\s+\{\.\.\.codeBlockCopyParts\.button\.icon\.props\}/);
  assert.match(rendererSource, /colors=\{markdownContentColors\}/);
  assert.match(markdownRenderPartsSource, /paddingRight:\s*surface\.codeBlock\.copyPaddingRight/);
  assert.match(markdownRenderPartsSource, /codeBlockCopyButton:\s*\{[\s\S]*?position:\s*codeBlockCopyButton\.button\.position,[\s\S]*?width:\s*codeBlockCopyButton\.button\.size,[\s\S]*?borderColor:\s*codeBlockCopyButton\.buttonColors\.borderColor/);
  assert.match(markdownRenderPartsSource, /codeBlockCopyButton:\s*\{[\s\S]*?alignItems:\s*codeBlockCopyButton\.button\.alignItems,[\s\S]*?justifyContent:\s*codeBlockCopyButton\.button\.justifyContent,/);
  assert.match(rendererSource, /code_block: \(node: any\) => \(/);
  assert.match(rendererSource, /fence: \(node: any\) => \(/);
  assert.match(markdownRenderPartsSource, /codeBlockCopyButtonCopied:\s*\{[\s\S]*?borderColor:\s*copiedCodeBlockCopyButton\.buttonColors\.borderColor,[\s\S]*?backgroundColor:\s*copiedCodeBlockCopyButton\.buttonColors\.backgroundColor/);
  assert.match(markdownRenderPartsSource, /blockquote:\s*\{[\s\S]*?backgroundColor:\s*colors\.blockquote\.backgroundColor/);
  assert.match(markdownRenderPartsSource, /maxHeight:\s*surface\.image\.maxHeight/);
  assert.match(markdownRenderPartsSource, /fontWeight:\s*surface\.tableCell\.headerFontWeight/);
  assert.doesNotMatch(rendererSource, /theme\.colors\[[^\]]+\]/);
  assert.doesNotMatch(rendererSource, /hexToRgba\(/);
  assert.doesNotMatch(rendererSource, /fontSize:\s*13,\s*lineHeight:\s*18/);
  assert.doesNotMatch(rendererSource, /type MobileMarkdownFontFamilyByPlatform = Readonly<\{/);
  assert.doesNotMatch(rendererSource, /const resolveMobileMarkdownFontFamily = \(fontFamilyByPlatform: MobileMarkdownFontFamilyByPlatform\) =>/);
  assert.doesNotMatch(rendererSource, /Platform\.OS === 'ios' \? 'Menlo' : 'monospace'/);
  assert.doesNotMatch(rendererSource, /maxHeight:\s*320/);
  assert.doesNotMatch(rendererSource, /setCopied\(false\), 2000/);
  assert.doesNotMatch(rendererSource, /getMarkdownContentMobileSurfaceState\(\)/);
  assert.doesNotMatch(rendererSource, /getMarkdownContentMobileSurfaceColors\(theme\.colors/);
  assert.doesNotMatch(rendererSource, /type MarkdownContentMobileSurfaceColors/);
  assert.doesNotMatch(rendererSource, /getMarkdownCodeBlockCopyLabel\(copied\)/);
  assert.doesNotMatch(rendererSource, /getMarkdownCodeBlockCopyMobileButtonState/);
  assert.doesNotMatch(rendererSource, /getMarkdownCodeBlockCopyMobileIconState/);
  assert.doesNotMatch(rendererSource, /accessibilityRole=\{codeBlockCopyRenderState\.button\.accessibilityRole\}/);
  assert.doesNotMatch(rendererSource, /name=\{codeBlockCopyRenderState\.icon\.name\}/);
  assert.doesNotMatch(rendererSource, /codeBlockCopyIconColor/);
  assert.doesNotMatch(rendererSource, /markdownContentSurface\.codeBlockCopyIcon\.(copyName|copiedName|size|colorToken|copiedColorToken)/);
  assert.doesNotMatch(rendererSource, /markdownContentSurface\.codeBlockCopyButton\.(position|top|right|size|borderRadius|borderWidth|borderColorToken|copiedBorderColorToken|backgroundColorToken|copiedBackgroundColorToken|backgroundAlpha|copiedBackgroundAlpha|alignItems|justifyContent|pressedOpacity)/);
  assert.doesNotMatch(rendererSource, /codeBlockCopyButton:\s*\{[\s\S]*?alignItems:\s*'center'/);
  assert.doesNotMatch(rendererSource, /codeBlockCopyButton:\s*\{[\s\S]*?justifyContent:\s*'center'/);
  assert.doesNotMatch(rendererSource, /MARKDOWN_CONTENT_PRESENTATION/);
  assert.doesNotMatch(rendererSource, /MARKDOWN_CONTENT_SURFACE_PRESENTATION/);
  assert.doesNotMatch(rendererSource, /rgba\(255,255,255,0\.05\)/);
});
