const test = require('node:test');
const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');

const rendererSource = fs.readFileSync(
  path.join(__dirname, '..', 'src', 'ui', 'MarkdownRenderer.tsx'),
  'utf8',
);

test('markdown renderer loads conversation image assets through authenticated remote API', () => {
  assert.match(rendererSource, /parseConversationImageAssetUrl/);
  assert.match(rendererSource, /isAllowedMarkdownImageUrl/);
  assert.match(rendererSource, /getMarkdownImageFallbackLabel/);
  assert.match(rendererSource, /getMarkdownImageUnavailableLabel/);
  assert.match(rendererSource, /getMarkdownImageInvalidAssetUrlMessage/);
  assert.match(rendererSource, /getMarkdownImageLoadErrorFallback/);
  assert.match(rendererSource, /getMarkdownRenderOptions/);
  assert.match(rendererSource, /isAllowedMarkdownContentLinkUrl/);
  assert.match(rendererSource, /formatMarkdownImageRequestFailedMessage/);
  assert.match(rendererSource, /getConversationImageAssetResponse\(assetRef\.conversationId, assetRef\.fileName\)/);
  assert.match(rendererSource, /throw new Error\(formatMarkdownImageRequestFailedMessage\(response\.status\)\)/);
  assert.match(rendererSource, /buildConversationImageAssetHttpUrl\(assetBaseUrl, sourceUrl\)/);
  assert.match(rendererSource, /setError\(getMarkdownImageUnavailableLabel\(\)\)/);
  assert.match(rendererSource, /throw new Error\(getMarkdownImageInvalidAssetUrlMessage\(\)\)/);
  assert.match(rendererSource, /getMarkdownImageLoadErrorFallback\(\)/);
  assert.match(rendererSource, /await client\.buildRequestHeaders\(\)/);
  assert.match(rendererSource, /rules=\{markdownRules\}/);
  assert.match(rendererSource, /<ThinkSection[\s\S]*?markdownRules=\{markdownRules\}/);
  assert.match(rendererSource, /splitMarkdownContent\(content, getMarkdownRenderOptions\(\)\)/);
  assert.match(rendererSource, /onLinkPress=\{isAllowedMarkdownContentLinkUrl\}/);
  assert.doesNotMatch(rendererSource, /MARKDOWN_CONTENT_PRESENTATION/);
  assert.doesNotMatch(rendererSource, /setError\('Image unavailable\.'\)/);
  assert.doesNotMatch(rendererSource, /throw new Error\('Invalid image asset URL\.'\)/);
  assert.doesNotMatch(rendererSource, /'Unable to load image\.'/);
  assert.doesNotMatch(rendererSource, /alt \|\| 'Image'/);
});

test('markdown renderer uses shared think-section copy and surface tokens', () => {
  assert.match(rendererSource, /getMarkdownThinkSectionAccessibilityLabel\(collapsed\)/);
  assert.match(rendererSource, /getMarkdownThinkSectionAccessibilityState\(collapsed\)/);
  assert.match(rendererSource, /getMarkdownThinkSectionDisplayLabel\(collapsed\)/);
  assert.match(rendererSource, /getMarkdownThinkSectionMobileChevronIconState/);
  assert.match(rendererSource, /getMarkdownThinkSectionMobileLeadingIconState/);
  assert.match(rendererSource, /getMarkdownThinkSectionMobileSurfaceRenderState/);
  assert.match(rendererSource, /getMarkdownThinkSectionControlState/);
  assert.match(rendererSource, /type MarkdownThinkSectionMobileSurfaceRenderState/);
  assert.match(rendererSource, /type MarkdownThinkSectionControlOptions/);
  assert.match(rendererSource, /interface MarkdownRendererProps extends MarkdownThinkSectionControlOptions/);
  assert.match(rendererSource, /const createThinkStyles = \(renderState: MarkdownThinkSectionMobileSurfaceRenderState\) =>/);
  assert.match(rendererSource, /const thinkSectionSurface = renderState\.surface;/);
  assert.match(rendererSource, /surface: MarkdownThinkSectionMobileSurfaceRenderState\['surface'\]/);
  assert.match(rendererSource, /const colors = renderState\.colors;/);
  assert.match(rendererSource, /const thinkSectionRenderState = React\.useMemo\([\s\S]*?getMarkdownThinkSectionMobileSurfaceRenderState\(\{ isDark \}\)/);
  assert.match(rendererSource, /const thinkSectionColors = thinkSectionRenderState\.colors;/);
  assert.match(rendererSource, /const thinkStyles = React\.useMemo\([\s\S]*?createThinkStyles\(thinkSectionRenderState\)/);
  assert.match(rendererSource, /const chevronIcon = getMarkdownThinkSectionMobileChevronIconState\(collapsed\);/);
  assert.match(rendererSource, /const thinkIcon = getMarkdownThinkSectionMobileLeadingIconState\(\);/);
  assert.match(rendererSource, /name=\{chevronIcon\.name\}/);
  assert.match(rendererSource, /size=\{chevronIcon\.size\}/);
  assert.match(rendererSource, /name=\{thinkIcon\.name\}/);
  assert.match(rendererSource, /size=\{thinkIcon\.size\}/);
  assert.match(rendererSource, /color=\{colors\.chevron\.color\}/);
  assert.match(rendererSource, /color=\{colors\.icon\.color\}/);
  assert.match(rendererSource, /accessibilityRole=\{surface\.header\.accessibilityRole\}/);
  assert.match(rendererSource, /accessibilityState=\{getMarkdownThinkSectionAccessibilityState\(collapsed\)\}/);
  assert.match(rendererSource, /surface=\{thinkSectionRenderState\.surface\}/);
  assert.match(rendererSource, /colors=\{thinkSectionColors\}/);
  assert.match(rendererSource, /const thinkControl = getMarkdownThinkSectionControlState\(part\.content, index, \{/);
  assert.match(rendererSource, /key=\{thinkControl\.key\}/);
  assert.match(rendererSource, /defaultCollapsed=\{true\}/);
  assert.match(rendererSource, /thinkControl\.isControlled \? \{/);
  assert.match(rendererSource, /isCollapsed: thinkControl\.isCollapsed/);
  assert.match(rendererSource, /onToggle: thinkControl\.onToggle/);
  assert.match(rendererSource, /const collapsed = isCollapsed \?\? internalCollapsed;/);
  assert.match(rendererSource, /if \(onToggle\) \{\s+onToggle\(\);\s+return;\s+\}/);
  assert.doesNotMatch(rendererSource, /const keyBase = getThinkKey/);
  assert.doesNotMatch(rendererSource, /const isControlled = !!\(isThinkExpanded && onToggleThink\)/);
  assert.match(rendererSource, /borderRadius:\s*radius\[thinkSectionSurface\.container\.borderRadius\]/);
  assert.match(rendererSource, /borderColor:\s*colors\.collapsedContainer\.borderColor/);
  assert.match(rendererSource, /backgroundColor:\s*colors\.expandedContainer\.backgroundColor/);
  assert.match(rendererSource, /paddingHorizontal:\s*spacing\[thinkSectionSurface\.header\.paddingHorizontal\]/);
  assert.match(rendererSource, /color:\s*colors\.label\.color/);
  assert.match(rendererSource, /paddingBottom:\s*spacing\[thinkSectionSurface\.content\.paddingBottom\]/);
  assert.match(rendererSource, /const resolveMobileMarkdownSpacing = \(value: keyof typeof spacing \| number\) =>/);
  assert.doesNotMatch(rendererSource, /resolveThemedColor/);
  assert.doesNotMatch(rendererSource, /resolveThemedAlphaColor/);
  assert.doesNotMatch(rendererSource, /ThemedAlphaColor/);
  assert.doesNotMatch(rendererSource, /ThemedColor/);
  assert.doesNotMatch(rendererSource, /const thinkSectionIcons = getMarkdownThinkSectionMobileIconState\(\);/);
  assert.doesNotMatch(rendererSource, /getMarkdownThinkSectionMobileSurfaceState/);
  assert.doesNotMatch(rendererSource, /getMarkdownThinkSectionMobileSurfaceColors/);
  assert.doesNotMatch(rendererSource, /getMarkdownThinkSectionMobile(Container|Content|Header|Label)State/);
  assert.doesNotMatch(rendererSource, /type MarkdownThinkSectionMobileSurfaceColors/);
  assert.doesNotMatch(rendererSource, /thinkSectionIcons\.(collapsedName|expandedName|thinkName)/);
  assert.doesNotMatch(rendererSource, /thinkSectionSurface\.(chevron|icon)\.(size|color)/);
  assert.doesNotMatch(rendererSource, /accessibilityLabel=\{collapsed \? 'Show thinking' : 'Hide thinking'\}/);
  assert.doesNotMatch(rendererSource, /accessibilityState=\{\{ expanded: !collapsed \}\}/);
  assert.doesNotMatch(rendererSource, /accessibilityRole="button"/);
  assert.doesNotMatch(rendererSource, /\{collapsed \? 'Thinking' : 'Hide thinking'\}/);
  assert.doesNotMatch(rendererSource, /MARKDOWN_THINK_SECTION_PRESENTATION/);
  assert.doesNotMatch(rendererSource, /MARKDOWN_THINK_SECTION_SURFACE_PRESENTATION/);
  assert.doesNotMatch(rendererSource, /MARKDOWN_THINK_SECTION_PRESENTATION\.mobileGlyphs/);
  assert.doesNotMatch(rendererSource, /borderColor:\s*isDark \? 'rgba\(251,191,36,0\.28\)'/);
  assert.doesNotMatch(rendererSource, /rgba\(251,191,36,0\.28\)/);
});

test('markdown renderer uses shared compact markdown content surface tokens', () => {
  assert.match(rendererSource, /getMarkdownContentMobileSurfaceRenderState/);
  assert.match(rendererSource, /type MarkdownContentMobileSurfaceRenderState/);
  assert.match(rendererSource, /const markdownContentRenderState = React\.useMemo\([\s\S]*?getMarkdownContentMobileSurfaceRenderState\(\{[\s\S]*?colors: theme\.colors,[\s\S]*?isDark,[\s\S]*?\}\)/);
  assert.match(rendererSource, /const markdownContentSurface = markdownContentRenderState\.surface;/);
  assert.match(rendererSource, /const markdownContentColors = markdownContentRenderState\.colors;/);
  assert.match(rendererSource, /import \{ resolveChatRuntimeMobileFontFamily \} from '@dotagents\/shared\/session-presentation';/);
  assert.doesNotMatch(rendererSource, /from '\.\/mobileTypography'/);
  assert.match(rendererSource, /fontSize:\s*markdownContentSurface\.body\.fontSize/);
  assert.match(rendererSource, /lineHeight:\s*markdownContentSurface\.body\.lineHeight/);
  assert.match(rendererSource, /color:\s*markdownContentColors\.body\.color/);
  assert.match(rendererSource, /fontFamily:\s*resolveChatRuntimeMobileFontFamily\(\s*markdownContentSurface\.inlineCode\.fontFamilyByPlatform,\s*Platform\.OS,\s*\)/);
  assert.match(rendererSource, /fontFamily:\s*resolveChatRuntimeMobileFontFamily\(\s*markdownContentSurface\.codeBlock\.fontFamilyByPlatform,\s*Platform\.OS,\s*\)/);
  assert.match(rendererSource, /borderRadius:\s*radius\[markdownContentSurface\.codeBlock\.borderRadius\]/);
  assert.match(rendererSource, /import \* as Clipboard from 'expo-clipboard';/);
  assert.match(rendererSource, /Ionicons/);
  assert.match(rendererSource, /const MarkdownCodeBlock/);
  assert.match(rendererSource, /getMarkdownCodeBlockCopyMobileRenderState/);
  assert.match(rendererSource, /const codeBlockCopyRenderState = getMarkdownCodeBlockCopyMobileRenderState\(\{[\s\S]*?isCopied: copied,[\s\S]*?colors,/);
  assert.match(rendererSource, /const codeBlockCopyButtonRenderState = React\.useMemo\([\s\S]*?getMarkdownCodeBlockCopyMobileRenderState\(\{[\s\S]*?colors: markdownContentColors,[\s\S]*?\}\)/);
  assert.match(rendererSource, /const copiedCodeBlockCopyButtonRenderState = React\.useMemo\([\s\S]*?getMarkdownCodeBlockCopyMobileRenderState\(\{[\s\S]*?isCopied: true,[\s\S]*?colors: markdownContentColors,[\s\S]*?\}\)/);
  assert.match(rendererSource, /accessibilityRole=\{codeBlockCopyRenderState\.button\.accessibilityRole\}/);
  assert.match(rendererSource, /accessibilityLabel=\{codeBlockCopyRenderState\.label\}/);
  assert.match(rendererSource, /getMarkdownCodeBlockFeedbackResetDelayMs\(\)/);
  assert.match(rendererSource, /Clipboard\.setStringAsync\(codeContent\)/);
  assert.match(rendererSource, /name=\{codeBlockCopyRenderState\.icon\.name\}/);
  assert.match(rendererSource, /size=\{codeBlockCopyRenderState\.icon\.size\}/);
  assert.match(rendererSource, /color=\{codeBlockCopyRenderState\.icon\.color\}/);
  assert.match(rendererSource, /colors=\{markdownContentColors\}/);
  assert.match(rendererSource, /paddingRight:\s*markdownContentSurface\.codeBlock\.copyPaddingRight/);
  assert.match(rendererSource, /codeBlockCopyButton:\s*\{[\s\S]*?position:\s*codeBlockCopyButtonRenderState\.button\.position,[\s\S]*?width:\s*codeBlockCopyButtonRenderState\.button\.size,[\s\S]*?borderColor:\s*codeBlockCopyButtonRenderState\.buttonColors\.borderColor/);
  assert.match(rendererSource, /codeBlockCopyButton:\s*\{[\s\S]*?alignItems:\s*codeBlockCopyButtonRenderState\.button\.alignItems,[\s\S]*?justifyContent:\s*codeBlockCopyButtonRenderState\.button\.justifyContent,/);
  assert.match(rendererSource, /code_block: \(node: any\) => \(/);
  assert.match(rendererSource, /fence: \(node: any\) => \(/);
  assert.match(rendererSource, /codeBlockCopyButtonCopied:\s*\{[\s\S]*?borderColor:\s*copiedCodeBlockCopyButtonRenderState\.buttonColors\.borderColor,[\s\S]*?backgroundColor:\s*copiedCodeBlockCopyButtonRenderState\.buttonColors\.backgroundColor/);
  assert.match(rendererSource, /blockquote:\s*\{[\s\S]*?backgroundColor:\s*markdownContentColors\.blockquote\.backgroundColor/);
  assert.match(rendererSource, /maxHeight:\s*markdownContentSurface\.image\.maxHeight/);
  assert.match(rendererSource, /fontWeight:\s*markdownContentSurface\.tableCell\.headerFontWeight/);
  assert.doesNotMatch(rendererSource, /theme\.colors\[[^\]]+\]/);
  assert.doesNotMatch(rendererSource, /hexToRgba\(/);
  assert.doesNotMatch(rendererSource, /fontSize:\s*13,\s*lineHeight:\s*18/);
  assert.doesNotMatch(rendererSource, /type MobileMarkdownFontFamilyByPlatform = Readonly<\{/);
  assert.doesNotMatch(rendererSource, /const resolveMobileMarkdownFontFamily = \(fontFamilyByPlatform: MobileMarkdownFontFamilyByPlatform\) =>/);
  assert.doesNotMatch(rendererSource, /Platform\.OS === 'ios' \? 'Menlo' : 'monospace'/);
  assert.doesNotMatch(rendererSource, /maxHeight:\s*320/);
  assert.doesNotMatch(rendererSource, /setCopied\(false\), 2000/);
  assert.doesNotMatch(rendererSource, /getMarkdownContentMobileSurfaceState\(\)/);
  assert.doesNotMatch(rendererSource, /getMarkdownContentMobileSurfaceColors\(theme\.colors/);
  assert.doesNotMatch(rendererSource, /type MarkdownContentMobileSurfaceColors/);
  assert.doesNotMatch(rendererSource, /getMarkdownCodeBlockCopyLabel\(copied\)/);
  assert.doesNotMatch(rendererSource, /getMarkdownCodeBlockCopyMobileButtonState/);
  assert.doesNotMatch(rendererSource, /getMarkdownCodeBlockCopyMobileIconState/);
  assert.doesNotMatch(rendererSource, /codeBlockCopyIconColor/);
  assert.doesNotMatch(rendererSource, /markdownContentSurface\.codeBlockCopyIcon\.(copyName|copiedName|size|colorToken|copiedColorToken)/);
  assert.doesNotMatch(rendererSource, /markdownContentSurface\.codeBlockCopyButton\.(position|top|right|size|borderRadius|borderWidth|borderColorToken|copiedBorderColorToken|backgroundColorToken|copiedBackgroundColorToken|backgroundAlpha|copiedBackgroundAlpha|alignItems|justifyContent|pressedOpacity)/);
  assert.doesNotMatch(rendererSource, /codeBlockCopyButton:\s*\{[\s\S]*?alignItems:\s*'center'/);
  assert.doesNotMatch(rendererSource, /codeBlockCopyButton:\s*\{[\s\S]*?justifyContent:\s*'center'/);
  assert.doesNotMatch(rendererSource, /MARKDOWN_CONTENT_PRESENTATION/);
  assert.doesNotMatch(rendererSource, /MARKDOWN_CONTENT_SURFACE_PRESENTATION/);
  assert.doesNotMatch(rendererSource, /rgba\(255,255,255,0\.05\)/);
});
