const test = require('node:test');
const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');

const source = fs.readFileSync(
  path.join(__dirname, '..', 'src', 'ui', 'MessageQueuePanel.tsx'),
  'utf8'
);

test('mobile queued-message rows use text-first actions with explicit accessibility labels', () => {
  assert.match(source, /getQueuedMessageItemMobileRenderState/);
  assert.match(source, /const queuePanelCopy = queuedMessageRenderState\.copy;/);
  assert.match(source, /createQueuedMessageActionButtonMobilePropsParts/);
  assert.match(source, /const actionParts = createQueuedMessageActionButtonMobilePropsParts\(\{[\s\S]*?copy: queuePanelCopy,[\s\S]*?onRetry,[\s\S]*?onEdit: \(\) => setIsEditing\(true\),[\s\S]*?onRemove,/);
  assert.match(source, /<Text style=\{action\.label\.style\}>\{action\.label\.text\}<\/Text>/);
  assert.match(source, /accessibilityLabel=\{action\.accessibilityLabel\}/);
  assert.match(source, /accessibilityLabel=\{editParts\.input\.accessibilityLabel\}/);
  assert.match(source, /accessibilityLabel=\{editParts\.cancelButton\.accessibilityLabel\}/);
  assert.match(source, /accessibilityLabel=\{editParts\.saveButton\.accessibilityLabel\}/);
  assert.match(source, /getQueuedMessageEditDraftState/);
  assert.match(source, /const editDraftState = getQueuedMessageEditDraftState\(editText, message\.text\);/);
  assert.match(source, /const editSubmitState = editDraftState\.submitState;/);
  assert.match(source, /onUpdate\(editSubmitState\.trimmedText\);/);
  assert.match(source, /editSubmitState\.shouldRestoreOriginalText/);
  assert.match(source, /disabled=\{editParts\.saveButton\.disabled\}/);
  assert.match(source, /accessibilityState=\{editParts\.saveButton\.accessibilityState\}/);
  assert.doesNotMatch(source, /getQueuedMessageEditSaveActionState/);
  assert.doesNotMatch(source, /getQueuedMessageEditSubmitState/);
  assert.doesNotMatch(source, /accessibilityState=\{\{ disabled: !editText\.trim\(\) \}\}/);
  assert.doesNotMatch(source, /const trimmed = editText\.trim\(\);/);
  assert.match(source, /accessibilityRole=\{action\.accessibilityRole\}/);
  assert.match(source, /activeOpacity=\{action\.activeOpacity\}/);
  assert.match(source, /accessibilityRole=\{editParts\.saveButton\.accessibilityRole\}/);
  assert.match(source, /activeOpacity=\{editParts\.saveButton\.activeOpacity\}/);
  assert.doesNotMatch(source, /getMessageQueuePanelCopyState/);
  assert.doesNotMatch(source, /mobileMessageQueuePanelCopy/);
  assert.doesNotMatch(source, /<Ionicons name="refresh" size=\{16\} color=\{theme\.colors\.foreground\} \/>/);
  assert.doesNotMatch(source, /<Ionicons name="pencil" size=\{16\} color=\{theme\.colors\.foreground\} \/>/);
  assert.doesNotMatch(source, /<Ionicons name="close" size=\{16\} color=\{theme\.colors\.foreground\} \/>/);
});

test('mobile queued-message actions keep wrap-safe chip sizing instead of a tiny side icon rail', () => {
  assert.match(source, /getQueuedMessageItemMobileRenderState/);
  assert.match(source, /colors: MessageQueuePanelColors;/);
  assert.doesNotMatch(source, /getMessageQueuePanelMobileSurfaceState/);
  assert.doesNotMatch(source, /const mobileMessageQueuePanelSurface = getMessageQueuePanelMobileSurfaceState\(\);/);
  assert.match(source, /const queuedMessageRenderState = getQueuedMessageItemMobileRenderState\(\{[\s\S]*?message,[\s\S]*?isExpanded,[\s\S]*?colors,[\s\S]*?\}\);/);
  assert.match(source, /const actionSurface = queuedMessageRenderState\.surface\.actions;/);
  assert.match(source, /const actionRowStyleSlot = createQueuedMessageActionRowMobileStyleSlot\(\{\s+surface: actionSurface,\s+\}\);/);
  assert.match(source, /const actionButtonStyleSlots = createQueuedMessageActionButtonMobileStyleSlots\(\{\s+surface: actionSurface,\s+colors: actionColors,\s+\}\);/);
  assert.match(source, /actions:\s*\{[\s\S]*?\.\.\.actionRowStyleSlot/);
  assert.match(source, /actionButton:\s*\{[\s\S]*?\.\.\.actionButtonStyleSlots\.button/);
  assert.match(source, /hitSlop=\{action\.hitSlop\}/);
  assert.match(source, /activeOpacity=\{expandButtonParts\.pressable\.activeOpacity\}/);
  assert.match(source, /accessibilityRole=\{expandButtonParts\.pressable\.accessibilityRole\}/);
  assert.match(source, /accessibilityLabel=\{expandButtonParts\.pressable\.accessibilityLabel\}/);
  assert.doesNotMatch(source, /getMessageQueuePanelMobileSurfaceRenderState\(/);
  assert.doesNotMatch(source, /actions:\s*\{\s*flexDirection:\s*'row',\s*flexWrap:\s*'wrap',/);
  assert.doesNotMatch(source, /actionButton:\s*\{\s*alignSelf:\s*'flex-start',/);
});

test('mobile queue panel exposes an explicit send-next action for queued drafts', () => {
  assert.match(source, /onProcessNext\?: \(\) => void;/);
  assert.match(source, /canProcessNext\?: boolean;/);
  assert.match(source, /accessibilityLabel=\{queuePanelCopy\.actions\.sendNextAccessibilityLabel\}/);
  assert.match(source, /activeOpacity=\{panelSurface\.actionPressedOpacity\}/);
  assert.match(source, /accessibilityRole=\{panelSurface\.actionAccessibilityRole\}/);
  assert.match(source, /<Text style=\{styles\.processButtonText\}>\{queuePanelCopy\.actions\.sendNextLabel\}<\/Text>/);
});

test('mobile queue panel mirrors desktop paused queue chrome with shared copy', () => {
  assert.match(source, /isPaused\?: boolean;/);
  assert.match(source, /onPause\?: \(\) => void;/);
  assert.match(source, /onResume\?: \(\) => void;/);
  assert.match(source, /isListCollapsed: boolean;/);
  assert.match(source, /onToggleListCollapsed: \(\) => void;/);
  assert.match(source, /getMessageQueuePanelMobileRenderState/);
  assert.match(source, /const queuePanelRenderState = getMessageQueuePanelMobileRenderState\(\{[\s\S]*?messages,[\s\S]*?colors,[\s\S]*?isPaused,[\s\S]*?isListCollapsed,[\s\S]*?canProcessNext,/);
  assert.match(source, /const queuePanelState = queuePanelRenderState\.panel;/);
  assert.match(source, /const panelStatusColors = panelColors\.status\[queuePanelState\.statusKey\];/);
  assert.match(source, /\{queuePanelState\.compactLabel\}/);
  assert.match(source, /\{queuePanelState\.title\}/);
  assert.match(source, /name=\{queuePanelState\.statusIconName\}/);
  assert.match(source, /const contentParts = createQueuedMessageContentMobilePropsParts\(\{[\s\S]*?message,[\s\S]*?presentation: messagePresentation,[\s\S]*?isExpanded,[\s\S]*?styles,/);
  assert.match(source, /\{contentParts\.metaText\.text\}/);
  assert.match(source, /queuePanelCopy\.actions\.pauseLabel/);
  assert.match(source, /queuePanelCopy\.actions\.resumeLabel/);
  assert.match(source, /const queuePanelIcons = queuePanelRenderState\.icons;/);
  assert.match(source, /name=\{statusIndicatorPart\.icon\.name\}/);
  assert.match(source, /name=\{expandButtonParts\.icon\.name\}/);
  assert.match(source, /name=\{queuePanelIcons\.resumeName\}/);
  assert.match(source, /name=\{queuePanelIcons\.pauseName\}/);
  assert.match(source, /name=\{queuePanelIcons\.sendNextName\}/);
  assert.match(source, /name=\{queuePanelIcons\.clearName\}/);
  assert.match(source, /name=\{queuePanelState\.toggleIconName\}/);
  assert.match(source, /onPress=\{onToggleListCollapsed\}/);
  assert.match(source, /accessibilityLabel=\{queuePanelState\.listToggleLabel\}/);
  assert.match(source, /accessibilityState=\{queuePanelState\.listToggleAccessibilityState\}/);
  assert.match(source, /queuePanelCopy\.pausedNotice/);
  assert.match(source, /pausedNoticeText:\s*\{[\s\S]*?\.\.\.panelStyleSlots\.pausedNoticeText/);
  assert.doesNotMatch(source, /getMessageQueuePanelState\(messages/);
  assert.doesNotMatch(source, /getMessageQueuePanelMobileIconState\(\)/);
  assert.doesNotMatch(source, /formatMessageQueueCompactLabel\(messages\.length, isPaused\)/);
  assert.doesNotMatch(source, /formatMessageQueuePanelTitle\(messages\.length, isPaused\)/);
  assert.doesNotMatch(source, /name="alert-circle"/);
  assert.doesNotMatch(source, /name="play"/);
  assert.doesNotMatch(source, /name="pause"/);
  assert.doesNotMatch(source, /name="trash-outline"/);
  assert.doesNotMatch(source, /name=\{isExpanded \? 'chevron-up' : 'chevron-down'\}/);
  assert.doesNotMatch(source, /name=\{isListCollapsed \? 'chevron-down' : 'chevron-up'\}/);
  assert.doesNotMatch(source, /accessibilityState=\{\{ expanded: queuePanelState\.isExpanded \}\}/);
  assert.doesNotMatch(source, /const \[isListCollapsed, setIsListCollapsed\] = useState\(false\);/);
  assert.doesNotMatch(source, /setIsListCollapsed\(false\);/);
  assert.doesNotMatch(source, /MESSAGE_QUEUE_PANEL_PRESENTATION\.mobileIcon/);
  assert.doesNotMatch(source, /MESSAGE_QUEUE_PANEL_PRESENTATION/);
  assert.doesNotMatch(source, /accessibilityRole="button"/);
  assert.doesNotMatch(source, /toLocaleTimeString/);
  assert.doesNotMatch(source, /•\{' '\}/);
});

test('mobile queue panel uses shared queued-message eligibility rules', () => {
  assert.match(source, /getMessageQueuePanelMobileRenderState/);
  assert.match(source, /getQueuedMessageItemMobileRenderState/);
  assert.match(source, /panel: queuePanelState,/);
  assert.match(source, /queuePanelState\.clearActionState\.isDisabled/);
  assert.match(source, /queuePanelState\.pauseActionState\.isDisabled/);
  assert.match(source, /queuePanelState\.clearActionState\.accessibilityState/);
  assert.match(source, /queuePanelState\.pauseActionState\.accessibilityState/);
  assert.doesNotMatch(source, /disabled=\{!queuePanelState\.(canClear|canPause)\}/);
  assert.doesNotMatch(source, /queuePanelState\.(clearActionAccessibilityState|pauseActionAccessibilityState)/);
  assert.match(source, /queuePanelState\.shouldShowCompactProcessNext/);
  assert.match(source, /queuePanelState\.shouldShowProcessNext/);
  assert.match(source, /queuePanelState\.shouldRenderClear/);
  assert.match(source, /queuePanelState\.shouldRenderPausedNotice/);
  assert.match(source, /queuePanelState\.shouldRenderList/);
  assert.match(source, /queuePanelState\.items\.map/);
  assert.match(source, /item\.shouldRenderSeparator/);
  assert.match(source, /const messagePresentation = queuedMessageRenderState\.presentation;/);
  assert.match(source, /createQueuedMessageContentMobilePropsParts/);
  assert.match(source, /contentParts\.errorText/);

  assert.doesNotMatch(source, /Queued Messages \(\{messages\.length\}\)/);
  assert.doesNotMatch(source, /Error: \{message\.errorMessage\}/);
  assert.doesNotMatch(source, /formatMessageQueueCompactLabel\(messages\.length, isPaused\)/);
  assert.doesNotMatch(source, /formatMessageQueuePanelTitle\(messages\.length, isPaused\)/);
  assert.doesNotMatch(source, /getMessageQueueListToggleLabel\(isListCollapsed\)/);
  assert.doesNotMatch(source, /getQueuedMessageItemPresentation\(message, isExpanded\)/);
  assert.doesNotMatch(source, /hasProcessingQueuedMessage\(messages\)/);
  assert.doesNotMatch(source, /message\.status === ['"]processing['"]/);
  assert.doesNotMatch(source, /message\.status === ['"]failed['"]/);
  assert.doesNotMatch(source, /isQueuedMessageProcessing\(message\)/);
  assert.doesNotMatch(source, /isQueuedMessageFailed\(message\)/);
  assert.doesNotMatch(source, /isFailed \? 'Failed' : isProcessing \? 'Processing\.\.\.' : 'Queued'/);
  assert.doesNotMatch(source, /messages\.some\(\(m\) => m\.status === ['"]processing['"]\)/);
});

test('mobile queue panel reads compact panel sizing from shared surface tokens', () => {
  assert.doesNotMatch(source, /const mobileMessageQueuePanelSurface = getMessageQueuePanelMobileSurfaceState\(\);/);
  assert.doesNotMatch(source, /getMessageQueuePanelMobileSurfaceColors/);
  assert.match(source, /const queuePanelRenderState = getMessageQueuePanelMobileRenderState\(\{[\s\S]*?colors,/);
  assert.match(source, /<QueuedMessageItem[\s\S]*?message=\{msg\}[\s\S]*?colors=\{colors\}/);
  assert.doesNotMatch(source, /useTheme\(\)/);
  assert.doesNotMatch(source, /colors: theme\.colors/);
  assert.match(source, /const queuePanelColors = queuePanelRenderState\.colors;/);
  assert.match(source, /const itemSurface = queuedMessageRenderState\.surface\.item;/);
  assert.match(source, /const editSurface = queuedMessageRenderState\.surface\.edit;/);
  assert.match(source, /const panelSurface = queuePanelRenderState\.surface\.panel;/);
  assert.match(source, /const itemColors = queuedMessageRenderState\.colors\.item;/);
  assert.match(source, /const actionColors = queuedMessageRenderState\.colors\.actions;/);
  assert.match(source, /const editColors = queuedMessageRenderState\.colors\.edit;/);
  assert.match(source, /const panelColors = queuePanelColors\.panel;/);
  assert.match(source, /const statusColor = queuedMessageRenderState\.statusColor;/);
  assert.match(source, /const itemStyleSlots = createQueuedMessageItemMobileStyleSlots\(\{[\s\S]*?surface: itemSurface,[\s\S]*?colors: itemColors,[\s\S]*?presentation: messagePresentation,[\s\S]*?statusColor,[\s\S]*?statusMetaColor,/);
  assert.match(source, /container:\s*\{[\s\S]*?\.\.\.itemStyleSlots\.container/);
  assert.match(source, /row:\s*\{[\s\S]*?\.\.\.itemStyleSlots\.row/);
  assert.match(source, /content:\s*\{[\s\S]*?\.\.\.itemStyleSlots\.content/);
  assert.match(source, /messageText:\s*\{[\s\S]*?\.\.\.itemStyleSlots\.messageText/);
  assert.match(source, /numberOfLines=\{contentParts\.messageText\.numberOfLines\}/);
  assert.match(source, /metaRow:\s*\{[\s\S]*?\.\.\.itemStyleSlots\.metaRow/);
  assert.match(source, /const statusMetaColor = queuedMessageRenderState\.statusMetaColor;/);
  assert.match(source, /metaText:\s*\{[\s\S]*?\.\.\.itemStyleSlots\.metaText/);
  assert.match(source, /expandButton:\s*\{[\s\S]*?\.\.\.itemStyleSlots\.expandButton/);
  assert.match(source, /const actionButtonStyleSlots = createQueuedMessageActionButtonMobileStyleSlots\(\{[\s\S]*?surface: actionSurface,[\s\S]*?colors: actionColors,/);
  assert.match(source, /actionButton:\s*\{[\s\S]*?\.\.\.actionButtonStyleSlots\.button/);
  assert.match(source, /removeActionText:\s*\{[\s\S]*?\.\.\.actionButtonStyleSlots\.removeText/);
  assert.match(source, /const editStyleSlots = createQueuedMessageEditMobileStyleSlots\(\{[\s\S]*?surface: editSurface,[\s\S]*?colors: editColors,/);
  assert.match(source, /editInput:\s*\{[\s\S]*?\.\.\.editStyleSlots\.input/);
  assert.match(source, /editActions:\s*\{[\s\S]*?\.\.\.editStyleSlots\.actions/);
  assert.match(source, /cancelButton:\s*\{[\s\S]*?\.\.\.editStyleSlots\.cancelButton/);
  assert.match(source, /saveButton:\s*\{[\s\S]*?\.\.\.editStyleSlots\.saveButton/);
  assert.match(source, /const panelStyleSlots = createMessageQueuePanelMobileStyleSlots\(\{[\s\S]*?surface: panelSurface,[\s\S]*?colors: panelColors,[\s\S]*?panel: queuePanelState,/);
  assert.match(source, /container:\s*\{[\s\S]*?\.\.\.panelStyleSlots\.container/);
  assert.match(source, /header:\s*\{[\s\S]*?\.\.\.panelStyleSlots\.header/);
  assert.match(source, /style=\{\[styles\.header, queuePanelState\.isListCollapsed && styles\.headerCollapsed\]\}/);
  assert.match(source, /headerCollapsed:\s*\{[\s\S]*?\.\.\.panelStyleSlots\.headerCollapsed/);
  assert.match(source, /headerLeft:\s*\{[\s\S]*?\.\.\.panelStyleSlots\.headerLeft/);
  assert.match(source, /headerActions:\s*\{[\s\S]*?\.\.\.panelStyleSlots\.headerActions/);
  assert.match(source, /headerTitle:\s*\{[\s\S]*?\.\.\.panelStyleSlots\.headerTitle/);
  assert.match(source, /queueControlTextDisabled:\s*\{[\s\S]*?\.\.\.panelStyleSlots\.queueControlTextDisabled/);
  assert.match(source, /processButtonText:\s*\{[\s\S]*?\.\.\.panelStyleSlots\.processButtonText/);
  assert.match(source, /color=\{panelColors\.toggleIconColor\}/);
  assert.match(source, /list:\s*\{[\s\S]*?\.\.\.panelStyleSlots\.list/);
  assert.match(source, /separator:\s*\{[\s\S]*?\.\.\.panelStyleSlots\.separator/);
  assert.match(source, /compactContainer:\s*\{[\s\S]*?\.\.\.panelStyleSlots\.compactContainer/);
  assert.match(source, /compactText:\s*\{[\s\S]*?\.\.\.panelStyleSlots\.compactText/);
  assert.doesNotMatch(source, /import \{ hexToRgba \} from '\.\/theme';/);
  assert.doesNotMatch(source, /hexToRgba\(/);
  assert.doesNotMatch(source, /getMessageQueuePanelMobileSurfaceRenderState\(/);
  assert.doesNotMatch(source, /theme\.colors\[[^\]]+\]/);
  assert.doesNotMatch(source, /row:\s*\{\s*flexDirection:\s*'row',\s*alignItems:\s*'flex-start',/);
  assert.doesNotMatch(source, /content:\s*\{\s*flex:\s*1,\s*minWidth:\s*0,/);
  assert.doesNotMatch(source, /metaRow:\s*\{\s*flexDirection:\s*'row',\s*alignItems:\s*'center',\s*flexWrap:\s*'wrap',/);
  assert.doesNotMatch(source, /expandButton:\s*\{\s*flexDirection:\s*'row',\s*alignItems:\s*'center',/);
  assert.doesNotMatch(source, /textAlignVertical:\s*'top'/);
  assert.doesNotMatch(source, /editActions:\s*\{\s*flexDirection:\s*'row',\s*justifyContent:\s*'flex-end',/);
  assert.doesNotMatch(source, /overflow:\s*'hidden'/);
  assert.doesNotMatch(source, /header:\s*\{\s*flexDirection:\s*'row',\s*alignItems:\s*'center',\s*justifyContent:\s*'space-between',/);
  assert.doesNotMatch(source, /isListCollapsed && \{ borderBottomWidth: 0 \}/);
  assert.doesNotMatch(source, /headerLeft:\s*\{\s*flexDirection:\s*'row',\s*alignItems:\s*'center',/);
  assert.doesNotMatch(source, /headerActions:\s*\{\s*flexDirection:\s*'row',\s*alignItems:\s*'center',/);
  assert.doesNotMatch(source, /compactContainer:\s*\{\s*flexDirection:\s*'row',\s*alignItems:\s*'center',/);
  assert.doesNotMatch(source, /compactText:\s*\{\s*flex:\s*1,/);
  assert.doesNotMatch(source, /numberOfLines=\{isExpanded \? undefined : 2\}/);
  assert.doesNotMatch(source, /maxHeight:\s*200,/);
  assert.doesNotMatch(source, /borderRadius:\s*999,/);
  assert.doesNotMatch(source, /AlphaHex/);
  assert.doesNotMatch(source, /MESSAGE_QUEUE_PANEL_SURFACE_PRESENTATION/);
  assert.doesNotMatch(source, /theme\.colors\.(background|foreground|card|border|muted|mutedForeground|primary|primaryForeground|destructive|success|warning|info)/);
});
