const test = require('node:test');
const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');

const source = fs.readFileSync(
  path.join(__dirname, '..', 'src', 'ui', 'MessageQueuePanel.tsx'),
  'utf8'
);

test('mobile queued-message rows use text-first actions with explicit accessibility labels', () => {
  assert.match(source, /getQueuedMessageItemMobileRenderState/);
  assert.match(source, /renderState: queuedMessageRenderState,/);
  assert.match(source, /createQueuedMessageItemMobilePropsParts/);
  assert.match(source, /actions: actionParts,/);
  assert.match(source, /createQueuedMessageItemMobilePropsParts\(\{[\s\S]*?renderState: queuedMessageRenderState,[\s\S]*?message,[\s\S]*?editDraftState,[\s\S]*?isExpanded,[\s\S]*?styles,[\s\S]*?onRetry,[\s\S]*?onEdit: \(\) => setIsEditing\(true\),[\s\S]*?onRemove,[\s\S]*?onToggleExpanded: \(\) => setIsExpanded\(!isExpanded\),[\s\S]*?onCancelEdit: handleCancelEdit,[\s\S]*?onSaveEdit: handleSaveEdit,/);
  assert.match(source, /<TouchableOpacity\s+key=\{action\.key\}\s+\{\.\.\.action\.props\}/);
  assert.match(source, /<Text\s+\{\.\.\.action\.label\.props\}>\{action\.label\.text\}<\/Text>/);
  assert.match(source, /<TextInput\s+\{\.\.\.editParts\.input\.props\}/);
  assert.match(source, /<TouchableOpacity\s+\{\.\.\.editParts\.cancelButton\.props\}/);
  assert.match(source, /<TouchableOpacity\s+\{\.\.\.editParts\.saveButton\.props\}/);
  assert.match(source, /getQueuedMessageEditDraftState/);
  assert.match(source, /const editDraftState = getQueuedMessageEditDraftState\(editText, message\.text\);/);
  assert.match(source, /const editSubmitState = editDraftState\.submitState;/);
  assert.match(source, /onUpdate\(editSubmitState\.trimmedText\);/);
  assert.match(source, /editSubmitState\.shouldRestoreOriginalText/);
  assert.doesNotMatch(source, /disabled=\{editParts\.saveButton\.disabled\}/);
  assert.doesNotMatch(source, /accessibilityState=\{editParts\.saveButton\.accessibilityState\}/);
  assert.doesNotMatch(source, /getQueuedMessageEditSaveActionState/);
  assert.doesNotMatch(source, /getQueuedMessageEditSubmitState/);
  assert.doesNotMatch(source, /accessibilityState=\{\{ disabled: !editText\.trim\(\) \}\}/);
  assert.doesNotMatch(source, /const trimmed = editText\.trim\(\);/);
  assert.doesNotMatch(source, /accessibility(Role|Label)=\{action\.accessibility(Role|Label)\}/);
  assert.doesNotMatch(source, /activeOpacity=\{action\.activeOpacity\}/);
  assert.doesNotMatch(source, /accessibilityRole=\{editParts\.saveButton\.accessibilityRole\}/);
  assert.doesNotMatch(source, /activeOpacity=\{editParts\.saveButton\.activeOpacity\}/);
  assert.doesNotMatch(source, /getMessageQueuePanelCopyState/);
  assert.doesNotMatch(source, /mobileMessageQueuePanelCopy/);
  assert.doesNotMatch(source, /<Ionicons name="refresh" size=\{16\} color=\{theme\.colors\.foreground\} \/>/);
  assert.doesNotMatch(source, /<Ionicons name="pencil" size=\{16\} color=\{theme\.colors\.foreground\} \/>/);
  assert.doesNotMatch(source, /<Ionicons name="close" size=\{16\} color=\{theme\.colors\.foreground\} \/>/);
});

test('mobile queued-message actions keep wrap-safe chip sizing instead of a tiny side icon rail', () => {
  assert.match(source, /getQueuedMessageItemMobileRenderState/);
  assert.match(source, /colors: MessageQueuePanelColors;/);
  assert.doesNotMatch(source, /getMessageQueuePanelMobileSurfaceState/);
  assert.doesNotMatch(source, /const mobileMessageQueuePanelSurface = getMessageQueuePanelMobileSurfaceState\(\);/);
  assert.match(source, /const queuedMessageRenderState = getQueuedMessageItemMobileRenderState\(\{[\s\S]*?message,[\s\S]*?isExpanded,[\s\S]*?colors,[\s\S]*?\}\);/);
  assert.match(source, /createQueuedMessageItemMobileStyleSheetSlots/);
  assert.match(source, /const itemStyleSheetSlots = createQueuedMessageItemMobileStyleSheetSlots\(\{\s+renderState: queuedMessageRenderState,\s+\}\);/);
  assert.match(source, /const styles = StyleSheet\.create\(\{ \.\.\.itemStyleSheetSlots \}\);/);
  assert.match(source, /createQueuedMessageItemMobilePropsParts/);
  assert.match(source, /chrome: itemChromeParts,/);
  assert.match(source, /<View\s+\{\.\.\.itemChromeParts\.actions\.props\}>/);
  assert.doesNotMatch(source, /style=\{itemChromeParts\.actions\.style\}/);
  assert.doesNotMatch(source, /actionParts\.shouldRender &&/);
  assert.doesNotMatch(source, /const actionSurface = queuedMessageRenderState\.surface\.actions;/);
  assert.doesNotMatch(source, /createQueuedMessageActionRowMobileStyleSlot/);
  assert.doesNotMatch(source, /createQueuedMessageActionButtonMobileStyleSlots/);
  assert.match(source, /<TouchableOpacity\s+key=\{action\.key\}\s+\{\.\.\.action\.props\}/);
  assert.match(source, /const expandButtonPressable = expandButtonParts\.pressable;/);
  assert.match(source, /<TouchableOpacity\s+\{\.\.\.expandButtonPressable\.props\}/);
  assert.doesNotMatch(source, /hitSlop=\{action\.hitSlop\}/);
  assert.doesNotMatch(source, /activeOpacity=\{expandButtonParts\.pressable\.activeOpacity\}/);
  assert.doesNotMatch(source, /accessibilityRole=\{expandButtonParts\.pressable\.accessibilityRole\}/);
  assert.doesNotMatch(source, /accessibilityLabel=\{expandButtonParts\.pressable\.accessibilityLabel\}/);
  assert.doesNotMatch(source, /getMessageQueuePanelMobileSurfaceRenderState\(/);
  assert.doesNotMatch(source, /actions:\s*\{\s*flexDirection:\s*'row',\s*flexWrap:\s*'wrap',/);
  assert.doesNotMatch(source, /actionButton:\s*\{\s*alignSelf:\s*'flex-start',/);
});

test('mobile queue panel exposes an explicit send-next action for queued drafts', () => {
  assert.match(source, /onProcessNext\?: \(\) => void;/);
  assert.match(source, /canProcessNext\?: boolean;/);
  assert.match(source, /createMessageQueuePanelMobilePropsParts/);
  assert.match(source, /headerActionParts\.actions\.map\(\(action\) =>/);
  assert.match(source, /<Text\s+\{\.\.\.action\.label\.props\}>\{action\.label\.text\}<\/Text>/);
});

test('mobile queue panel mirrors desktop paused queue chrome with shared copy', () => {
  assert.match(source, /isPaused\?: boolean;/);
  assert.match(source, /onPause\?: \(\) => void;/);
  assert.match(source, /onResume\?: \(\) => void;/);
  assert.match(source, /isListCollapsed: boolean;/);
  assert.match(source, /onToggleListCollapsed: \(\) => void;/);
  assert.match(source, /getMessageQueuePanelMobileRenderState/);
  assert.match(source, /const queuePanelRenderState = getMessageQueuePanelMobileRenderState\(\{[\s\S]*?messages,[\s\S]*?colors,[\s\S]*?isPaused,[\s\S]*?isListCollapsed,[\s\S]*?canProcessNext,/);
  assert.match(source, /createMessageQueuePanelMobilePropsParts/);
  assert.match(source, /const \{[\s\S]*?compactActions: compactActionParts,[\s\S]*?headerActions: headerActionParts,[\s\S]*?chrome: panelChromeParts,[\s\S]*?list: panelListParts,[\s\S]*?\} = createMessageQueuePanelMobilePropsParts\(\{[\s\S]*?renderState: queuePanelRenderState,[\s\S]*?styles,[\s\S]*?onPause,[\s\S]*?onResume,[\s\S]*?onProcessNext,[\s\S]*?onClear,[\s\S]*?onToggleListCollapsed,[\s\S]*?onRemove,[\s\S]*?onUpdate,[\s\S]*?onRetry,/);
  assert.doesNotMatch(source, /const panelStatusColors = panelColors\.status\[queuePanelState\.statusKey\];/);
  assert.match(source, /\{panelChromeParts\.compactLabel\.text\}/);
  assert.match(source, /\{panelChromeParts\.headerTitle\.text\}/);
  assert.match(source, /<View\s+\{\.\.\.panelChromeParts\.container\.props\}>/);
  assert.match(source, /<View\s+\{\.\.\.panelChromeParts\.headerActions\.props\}>/);
  assert.match(source, /<Ionicons\s+\{\.\.\.panelChromeParts\.headerStatusIcon\.props\}/);
  assert.match(source, /content: contentParts,/);
  assert.match(source, /\{contentParts\.metaText\.text\}/);
  assert.match(source, /<Ionicons\s+\{\.\.\.itemChromeParts\.failedStatusIcon\.props\}/);
  assert.match(source, /<ActivityIndicator\s+\{\.\.\.itemChromeParts\.processingStatusIndicator\.props\}/);
  assert.match(source, /<Ionicons\s+\{\.\.\.expandButtonPressable\.content\.icon\.props\}/);
  assert.match(source, /compactActionParts\.actions\.map\(\(action\) =>/);
  assert.match(source, /compactActionParts\.actions\.map\(\(action\) => \([\s\S]*?<TouchableOpacity\s+key=\{action\.key\}[\s\S]*?\{\.\.\.action\.props\}/);
  assert.match(source, /<Ionicons\s+\{\.\.\.action\.icon\.props\}/);
  assert.match(source, /headerActionParts\.actions\.map\(\(action\) =>/);
  assert.match(source, /headerActionParts\.actions\.map\(\(action\) => \([\s\S]*?<TouchableOpacity\s+key=\{action\.key\}[\s\S]*?\{\.\.\.action\.props\}/);
  assert.match(source, /action\.label\.shouldRender \? \(/);
  assert.match(source, /panelChromeParts\.pausedNotice/);
  assert.match(source, /<View\s+\{\.\.\.panelChromeParts\.pausedNotice\.container\.props\}>/);
  assert.match(source, /<Text\s+\{\.\.\.panelChromeParts\.pausedNotice\.message\.props\}>/);
  assert.match(source, /\{panelChromeParts\.pausedNotice\.message\.text\}/);
  assert.doesNotMatch(source, /panelChromeParts\.pausedNotice\.(containerStyle|textStyle|text)/);
  assert.match(source, /const styles = StyleSheet\.create\(\{ \.\.\.panelStyleSheetSlots \}\);/);
  assert.doesNotMatch(source, /getMessageQueuePanelState\(messages/);
  assert.doesNotMatch(source, /getMessageQueuePanelMobileIconState\(\)/);
  assert.doesNotMatch(source, /formatMessageQueueCompactLabel\(messages\.length, isPaused\)/);
  assert.doesNotMatch(source, /formatMessageQueuePanelTitle\(messages\.length, isPaused\)/);
  assert.doesNotMatch(source, /name="alert-circle"/);
  assert.doesNotMatch(source, /name="play"/);
  assert.doesNotMatch(source, /name="pause"/);
  assert.doesNotMatch(source, /name="trash-outline"/);
  assert.doesNotMatch(source, /name=\{isExpanded \? 'chevron-up' : 'chevron-down'\}/);
  assert.doesNotMatch(source, /name=\{isListCollapsed \? 'chevron-down' : 'chevron-up'\}/);
  assert.doesNotMatch(source, /accessibilityState=\{\{ expanded: queuePanelState\.isExpanded \}\}/);
  assert.doesNotMatch(source, /const queuePanelState = queuePanelRenderState\.panel;/);
  assert.doesNotMatch(source, /const queuePanelIcons = queuePanelRenderState\.icons;/);
  assert.doesNotMatch(source, /const queuePanelCopy = queuePanelRenderState\.copy;/);
  assert.doesNotMatch(source, /const \[isListCollapsed, setIsListCollapsed\] = useState\(false\);/);
  assert.doesNotMatch(source, /setIsListCollapsed\(false\);/);
  assert.doesNotMatch(source, /MESSAGE_QUEUE_PANEL_PRESENTATION\.mobileIcon/);
  assert.doesNotMatch(source, /MESSAGE_QUEUE_PANEL_PRESENTATION/);
  assert.doesNotMatch(source, /accessibilityRole="button"/);
  assert.doesNotMatch(source, /toLocaleTimeString/);
  assert.doesNotMatch(source, /•\{' '\}/);
});

test('mobile queue panel uses shared queued-message eligibility rules', () => {
  assert.match(source, /getMessageQueuePanelMobileRenderState/);
  assert.match(source, /getQueuedMessageItemMobileRenderState/);
  assert.match(source, /createMessageQueuePanelMobilePropsParts/);
  assert.match(source, /renderState: queuePanelRenderState,/);
  assert.doesNotMatch(source, /disabled=\{!queuePanelState\.(canClear|canPause)\}/);
  assert.doesNotMatch(source, /queuePanelState\.(clearActionAccessibilityState|pauseActionAccessibilityState)/);
  assert.doesNotMatch(source, /createMessageQueuePanelCompactActionMobilePropsParts/);
  assert.doesNotMatch(source, /createMessageQueuePanelHeaderActionMobilePropsParts/);
  assert.doesNotMatch(source, /createMessageQueuePanelChromeMobilePropsParts/);
  assert.doesNotMatch(source, /createMessageQueuePanelListMobilePropsParts/);
  assert.match(source, /createQueuedMessageItemMobilePropsParts/);
  assert.doesNotMatch(source, /queuePanelState\.shouldRenderPausedNotice &&/);
  assert.doesNotMatch(source, /queuePanelState\.shouldRenderList &&/);
  assert.doesNotMatch(source, /statusIndicatorPart\?\.type ===/);
  assert.doesNotMatch(source, /actionParts\.shouldRender &&/);
  assert.match(source, /panelListParts\.items\.map\(\(item\) =>/);
  assert.match(source, /item\.separator\.shouldRender \?/);
  assert.match(source, /<View \{\.\.\.item\.separator\.props\} \/>/);
  assert.doesNotMatch(source, /item\.shouldRenderSeparator/);
  assert.match(source, /const messagePresentation = queuedMessageRenderState\.presentation;/);
  assert.match(source, /content: contentParts,/);
  assert.match(source, /contentParts\.errorText/);

  assert.doesNotMatch(source, /Queued Messages \(\{messages\.length\}\)/);
  assert.doesNotMatch(source, /Error: \{message\.errorMessage\}/);
  assert.doesNotMatch(source, /formatMessageQueueCompactLabel\(messages\.length, isPaused\)/);
  assert.doesNotMatch(source, /formatMessageQueuePanelTitle\(messages\.length, isPaused\)/);
  assert.doesNotMatch(source, /getMessageQueueListToggleLabel\(isListCollapsed\)/);
  assert.doesNotMatch(source, /getQueuedMessageItemPresentation\(message, isExpanded\)/);
  assert.doesNotMatch(source, /hasProcessingQueuedMessage\(messages\)/);
  assert.doesNotMatch(source, /message\.status === ['"]processing['"]/);
  assert.doesNotMatch(source, /message\.status === ['"]failed['"]/);
  assert.doesNotMatch(source, /isQueuedMessageProcessing\(message\)/);
  assert.doesNotMatch(source, /isQueuedMessageFailed\(message\)/);
  assert.doesNotMatch(source, /isFailed \? 'Failed' : isProcessing \? 'Processing\.\.\.' : 'Queued'/);
  assert.doesNotMatch(source, /messages\.some\(\(m\) => m\.status === ['"]processing['"]\)/);
});

test('mobile queue panel reads compact panel sizing from shared surface tokens', () => {
  assert.doesNotMatch(source, /const mobileMessageQueuePanelSurface = getMessageQueuePanelMobileSurfaceState\(\);/);
  assert.doesNotMatch(source, /getMessageQueuePanelMobileSurfaceColors/);
  assert.match(source, /const queuePanelRenderState = getMessageQueuePanelMobileRenderState\(\{[\s\S]*?colors,/);
  assert.match(source, /<QueuedMessageItem[\s\S]*?\{\.\.\.item\.messageProps\}[\s\S]*?colors=\{colors\}/);
  assert.doesNotMatch(source, /useTheme\(\)/);
  assert.doesNotMatch(source, /colors: theme\.colors/);
  assert.doesNotMatch(source, /const queuePanelColors = queuePanelRenderState\.colors;/);
  assert.doesNotMatch(source, /const panelSurface = queuePanelRenderState\.surface\.panel;/);
  assert.doesNotMatch(source, /const panelColors = queuePanelColors\.panel;/);
  assert.match(source, /const itemStyleSheetSlots = createQueuedMessageItemMobileStyleSheetSlots\(\{[\s\S]*?renderState: queuedMessageRenderState,/);
  assert.match(source, /const styles = StyleSheet\.create\(\{ \.\.\.itemStyleSheetSlots \}\);/);
  assert.match(source, /<View\s+\{\.\.\.itemChromeParts\.container\.props\}>/);
  assert.match(source, /<View\s+\{\.\.\.itemChromeParts\.row\.props\}>/);
  assert.match(source, /<View\s+\{\.\.\.contentParts\.container\.props\}>/);
  assert.match(source, /<View\s+\{\.\.\.contentParts\.metaRow\.props\}>/);
  assert.match(source, /<View\s+\{\.\.\.editParts\.container\.props\}>/);
  assert.match(source, /<View\s+\{\.\.\.editParts\.actions\.props\}>/);
  assert.match(source, /<View\s+\{\.\.\.itemChromeParts\.actions\.props\}>/);
  assert.doesNotMatch(source, /style=\{itemChromeParts\.(container|row|actions)\.style\}/);
  assert.doesNotMatch(source, /style=\{contentParts\.(container|metaRow)\.style\}/);
  assert.doesNotMatch(source, /style=\{editParts\.(container|actions)\.style\}/);
  assert.match(source, /<Text\s+\{\.\.\.contentParts\.messageText\.props\}>/);
  assert.match(source, /<TextInput\s+\{\.\.\.editParts\.input\.props\}/);
  assert.doesNotMatch(source, /const itemSurface = queuedMessageRenderState\.surface\.item;/);
  assert.doesNotMatch(source, /const editSurface = queuedMessageRenderState\.surface\.edit;/);
  assert.doesNotMatch(source, /const itemColors = queuedMessageRenderState\.colors\.item;/);
  assert.doesNotMatch(source, /const actionColors = queuedMessageRenderState\.colors\.actions;/);
  assert.doesNotMatch(source, /const editColors = queuedMessageRenderState\.colors\.edit;/);
  assert.doesNotMatch(source, /const statusColor = queuedMessageRenderState\.statusColor;/);
  assert.doesNotMatch(source, /const statusMetaColor = queuedMessageRenderState\.statusMetaColor;/);
  assert.doesNotMatch(source, /createQueuedMessageItemMobileStyleSlots/);
  assert.doesNotMatch(source, /createQueuedMessageEditMobileStyleSlots/);
  assert.match(source, /createMessageQueuePanelMobileStyleSheetSlots/);
  assert.match(source, /const panelStyleSheetSlots = createMessageQueuePanelMobileStyleSheetSlots\(\{\s+renderState: queuePanelRenderState,\s+\}\);/);
  assert.match(source, /const styles = StyleSheet\.create\(\{ \.\.\.panelStyleSheetSlots \}\);/);
  assert.match(source, /<View\s+\{\.\.\.panelChromeParts\.container\.props\}>/);
  assert.match(source, /<View\s+\{\.\.\.panelChromeParts\.headerContainer\.props\}>/);
  assert.match(source, /<View\s+\{\.\.\.panelChromeParts\.headerActions\.props\}>/);
  assert.match(source, /<Ionicons\s+\{\.\.\.action\.icon\.props\}/);
  assert.match(source, /<TouchableOpacity\s+key=\{action\.key\}\s+\{\.\.\.action\.props\}/);
  assert.doesNotMatch(source, /style=\{action\.style\}/);
  assert.doesNotMatch(source, /activeOpacity=\{action\.activeOpacity\}/);
  assert.doesNotMatch(source, /accessibilityRole=\{action\.accessibilityRole\}/);
  assert.match(source, /<View\s+\{\.\.\.panelChromeParts\.compactContainer\.props\}>/);
  assert.match(source, /<ScrollView\s+\{\.\.\.panelChromeParts\.list\.props\}/);
  assert.match(source, /item\.separator\.shouldRender \? <View \{\.\.\.item\.separator\.props\} \/> : null/);
  assert.doesNotMatch(source, /style=\{panelChromeParts\.list\.style\}/);
  assert.doesNotMatch(source, /showsVerticalScrollIndicator=\{panelChromeParts\.list\.showsVerticalScrollIndicator\}/);
  assert.doesNotMatch(source, /style=\{item\.separator\.style\}/);
  assert.doesNotMatch(source, /import \{ hexToRgba \} from '\.\/theme';/);
  assert.doesNotMatch(source, /hexToRgba\(/);
  assert.doesNotMatch(source, /getMessageQueuePanelMobileSurfaceRenderState\(/);
  assert.doesNotMatch(source, /theme\.colors\[[^\]]+\]/);
  assert.doesNotMatch(source, /row:\s*\{\s*flexDirection:\s*'row',\s*alignItems:\s*'flex-start',/);
  assert.doesNotMatch(source, /content:\s*\{\s*flex:\s*1,\s*minWidth:\s*0,/);
  assert.doesNotMatch(source, /metaRow:\s*\{\s*flexDirection:\s*'row',\s*alignItems:\s*'center',\s*flexWrap:\s*'wrap',/);
  assert.doesNotMatch(source, /expandButton:\s*\{\s*flexDirection:\s*'row',\s*alignItems:\s*'center',/);
  assert.doesNotMatch(source, /textAlignVertical:\s*'top'/);
  assert.doesNotMatch(source, /editActions:\s*\{\s*flexDirection:\s*'row',\s*justifyContent:\s*'flex-end',/);
  assert.doesNotMatch(source, /overflow:\s*'hidden'/);
  assert.doesNotMatch(source, /header:\s*\{\s*flexDirection:\s*'row',\s*alignItems:\s*'center',\s*justifyContent:\s*'space-between',/);
  assert.doesNotMatch(source, /style=\{styles\.container\}/);
  assert.doesNotMatch(source, /style=\{styles\.headerActions\}/);
  assert.doesNotMatch(source, /isListCollapsed && \{ borderBottomWidth: 0 \}/);
  assert.doesNotMatch(source, /headerLeft:\s*\{\s*flexDirection:\s*'row',\s*alignItems:\s*'center',/);
  assert.doesNotMatch(source, /headerActions:\s*\{\s*flexDirection:\s*'row',\s*alignItems:\s*'center',/);
  assert.doesNotMatch(source, /compactContainer:\s*\{\s*flexDirection:\s*'row',\s*alignItems:\s*'center',/);
  assert.doesNotMatch(source, /compactText:\s*\{\s*flex:\s*1,/);
  assert.doesNotMatch(source, /name=\{queuePanelIcons\.(resumeName|pauseName|sendNextName|clearName)\}/);
  assert.doesNotMatch(source, /size=\{panelSurface\.compactActionIconSize\}/);
  assert.doesNotMatch(source, /numberOfLines=\{isExpanded \? undefined : 2\}/);
  assert.doesNotMatch(source, /\s+multiline\s+autoFocus/);
  assert.doesNotMatch(source, /maxHeight:\s*200,/);
  assert.doesNotMatch(source, /borderRadius:\s*999,/);
  assert.doesNotMatch(source, /AlphaHex/);
  assert.doesNotMatch(source, /MESSAGE_QUEUE_PANEL_SURFACE_PRESENTATION/);
  assert.doesNotMatch(source, /createMessageQueuePanelMobileStyleSlots/);
  assert.doesNotMatch(source, /panelStyleSlots\./);
  assert.doesNotMatch(source, /theme\.colors\.(background|foreground|card|border|muted|mutedForeground|primary|primaryForeground|destructive|success|warning|info)/);
});
