const test = require('node:test');
const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');

const operationsSource = fs.readFileSync(
  path.join(__dirname, '..', 'src', 'screens', 'OperationsScreen.tsx'),
  'utf8'
);
const remoteAccessDraftsSource = fs.readFileSync(
  path.join(__dirname, '..', '..', '..', 'packages', 'shared', 'src', 'operator-remote-access-drafts.ts'),
  'utf8'
);

test('exposes compact remote access settings for mobile remote ops', () => {
  assert.match(operationsSource, /OPERATOR_CONNECTION_REQUIRED_PANEL_METADATA\.panelTitle/);
  assert.match(operationsSource, /OPERATOR_CONNECTION_REQUIRED_PANEL_METADATA\.bodyText/);
  assert.match(operationsSource, /OPERATOR_CONNECTION_REQUIRED_PANEL_METADATA\.openSettingsAccessibilityLabel/);
  assert.match(operationsSource, /OPERATOR_CONNECTION_REQUIRED_PANEL_METADATA\.openSettingsButtonLabel/);
  assert.doesNotMatch(operationsSource, /<Text style=\{styles\.panelTitle\}>Connection required<\/Text>/);
  assert.doesNotMatch(operationsSource, /createButtonAccessibilityLabel\('Open connection settings'\)/);
  assert.match(operationsSource, /OPERATOR_REMOTE_ACCESS_SETTINGS_PANEL_METADATA\.panelTitle/);
  assert.match(operationsSource, /OPERATOR_REMOTE_ACCESS_SETTINGS_PANEL_METADATA\.helperText/);
  assert.match(operationsSource, /OPERATOR_REMOTE_ACCESS_SETTINGS_PANEL_METADATA\.remoteServerSectionTitle/);
  assert.match(operationsSource, /OPERATOR_REMOTE_ACCESS_SETTINGS_PANEL_METADATA\.portDisconnectHelperText/);
  assert.doesNotMatch(operationsSource, /<Text style=\{styles\.panelTitle\}>Remote access settings<\/Text>/);
  assert.doesNotMatch(operationsSource, /These controls use the desktop settings API/);
  assert.doesNotMatch(operationsSource, /<Text style=\{styles\.subsectionTitle\}>Remote server<\/Text>/);
  assert.doesNotMatch(operationsSource, /Changing the port can temporarily disconnect this mobile session\./);
  assert.match(operationsSource, /REMOTE_SERVER_ENABLED_FIELD_METADATA/);
  assert.match(operationsSource, /REMOTE_SERVER_BIND_ADDRESS_FIELD_METADATA/);
  assert.match(operationsSource, /REMOTE_SERVER_BIND_ADDRESS_DISPLAY_OPTIONS/);
  assert.match(operationsSource, /REMOTE_SERVER_CORS_ORIGINS_FIELD_METADATA/);
  assert.match(operationsSource, /REMOTE_SERVER_LOG_LEVEL_FIELD_METADATA/);
  assert.match(operationsSource, /REMOTE_SERVER_LOG_LEVEL_DISPLAY_OPTIONS/);
  assert.match(operationsSource, /DEFAULT_REMOTE_SERVER_BIND_ADDRESS/);
  assert.match(operationsSource, /DEFAULT_REMOTE_SERVER_ENABLED/);
  assert.match(operationsSource, /DEFAULT_REMOTE_SERVER_AUTO_SHOW_PANEL/);
  assert.match(operationsSource, /DEFAULT_REMOTE_SERVER_LOG_LEVEL/);
  assert.match(operationsSource, /DEFAULT_REMOTE_SERVER_CORS_ORIGINS/);
  assert.match(operationsSource, /DEFAULT_REMOTE_SERVER_PORT/);
  assert.match(operationsSource, /DEFAULT_REMOTE_SERVER_TERMINAL_QR_ENABLED/);
  assert.match(operationsSource, /REMOTE_SERVER_AUTO_SHOW_PANEL_FIELD_METADATA/);
  assert.match(operationsSource, /REMOTE_SERVER_TERMINAL_QR_FIELD_METADATA/);
  assert.match(operationsSource, /DEFAULT_HIDE_DOCK_ICON/);
  assert.match(operationsSource, /DEFAULT_LAUNCH_AT_LOGIN/);
  assert.match(operationsSource, /DEFAULT_TEXT_INPUT_ENABLED/);
  assert.match(operationsSource, /DEFAULT_THEME_PREFERENCE/);
  assert.match(operationsSource, /THEME_PREFERENCE_OPTIONS/);
  assert.doesNotMatch(operationsSource, /DESKTOP_THEME_OPTIONS/);
  assert.match(operationsSource, /DEFAULT_FLOATING_PANEL_AUTO_SHOW/);
  assert.match(operationsSource, /DEFAULT_HIDE_PANEL_WHEN_MAIN_FOCUSED/);
  assert.match(operationsSource, /DEFAULT_PANEL_DRAG_ENABLED/);
  assert.match(operationsSource, /DEFAULT_PANEL_POSITION/);
  assert.match(operationsSource, /PANEL_POSITION_OPTIONS/);
  assert.match(operationsSource, /option\.compactLabel/);
  assert.doesNotMatch(operationsSource, /const PANEL_POSITION_OPTIONS/);
  assert.match(operationsSource, /REMOTE_SERVER_PORT_FIELD_METADATA/);
  assert.match(operationsSource, /REMOTE_SERVER_PORT_FIELD_METADATA\.pendingLabel/);
  assert.match(operationsSource, /REMOTE_SERVER_PORT_FIELD_METADATA\.formatSuccessMessage\(parsed\)/);
  assert.match(operationsSource, /isRemoteServerPortUpdateValue/);
  assert.match(operationsSource, /buildOperatorRemoteAccessDrafts as buildDrafts/);
  assert.match(remoteAccessDraftsSource, /DEFAULT_REMOTE_SERVER_CORS_ORIGINS/);
  assert.match(remoteAccessDraftsSource, /DEFAULT_REMOTE_SERVER_PORT/);
  assert.match(remoteAccessDraftsSource, /remoteServerPort: String\(settings\?\.remoteServerPort \?\? DEFAULT_REMOTE_SERVER_PORT\)/);
  assert.match(remoteAccessDraftsSource, /remoteServerCorsOrigins: formatConfigListInput\(settings\?\.remoteServerCorsOrigins \?\? DEFAULT_REMOTE_SERVER_CORS_ORIGINS\)/);
  assert.match(operationsSource, /remoteServerBindAddress: option\.value/);
  assert.match(operationsSource, /REMOTE_SERVER_BIND_ADDRESS_FIELD_METADATA\.pendingLabel/);
  assert.match(operationsSource, /option\.successMessage/);
  assert.match(operationsSource, /REMOTE_SERVER_ENABLED_FIELD_METADATA\.pendingLabel/);
  assert.match(operationsSource, /REMOTE_SERVER_ENABLED_FIELD_METADATA\.enableSuccessMessage/);
  assert.match(operationsSource, /REMOTE_SERVER_ENABLED_FIELD_METADATA\.disableConfirmTitle/);
  assert.match(operationsSource, /REMOTE_SERVER_ENABLED_FIELD_METADATA\.disableConfirmMessage/);
  assert.match(operationsSource, /REMOTE_SERVER_ENABLED_FIELD_METADATA\.disableConfirmButtonLabel/);
  assert.match(operationsSource, /REMOTE_SERVER_ENABLED_FIELD_METADATA\.disableSuccessMessage/);
  assert.match(operationsSource, /REMOTE_SERVER_ENABLED_FIELD_METADATA\.updateSuccessMessage/);
  assert.match(operationsSource, /REMOTE_SERVER_ENABLED_FIELD_METADATA\.accessibilityLabel/);
  assert.doesNotMatch(operationsSource, /<Text style=\{styles\.label\}>Remote Server<\/Text>/);
  assert.doesNotMatch(operationsSource, /createSwitchAccessibilityLabel\('Remote Server'\)/);
  assert.match(operationsSource, /REMOTE_SERVER_BIND_ADDRESS_FIELD_METADATA\.accessibilityLabel/);
  assert.match(operationsSource, /remoteServerLogLevel: option\.value/);
  assert.match(operationsSource, /REMOTE_SERVER_LOG_LEVEL_FIELD_METADATA\.pendingLabel/);
  assert.match(operationsSource, /REMOTE_SERVER_LOG_LEVEL_FIELD_METADATA\.accessibilityLabel/);
  assert.match(operationsSource, /remoteServerCorsOrigins: origins\.length > 0 \? origins : \[\.\.\.DEFAULT_REMOTE_SERVER_CORS_ORIGINS\]/);
  assert.match(operationsSource, /REMOTE_SERVER_CORS_ORIGINS_FIELD_METADATA\.pendingLabel/);
  assert.match(operationsSource, /REMOTE_SERVER_CORS_ORIGINS_FIELD_METADATA\.successMessage/);
  assert.doesNotMatch(operationsSource, /placeholder="\* or http:\/\/localhost:8081/);
  assert.match(operationsSource, /REMOTE_SERVER_AUTO_SHOW_PANEL_FIELD_METADATA\.pendingLabel/);
  assert.match(operationsSource, /REMOTE_SERVER_AUTO_SHOW_PANEL_FIELD_METADATA\.successMessage/);
  assert.match(operationsSource, /REMOTE_SERVER_AUTO_SHOW_PANEL_FIELD_METADATA\.accessibilityLabel/);
  assert.doesNotMatch(operationsSource, /<Text style=\{styles\.label\}>Auto-Show Panel<\/Text>/);
  assert.doesNotMatch(operationsSource, /createSwitchAccessibilityLabel\('Auto-Show Panel'\)/);
  assert.match(operationsSource, /REMOTE_SERVER_TERMINAL_QR_FIELD_METADATA\.pendingLabel/);
  assert.match(operationsSource, /REMOTE_SERVER_TERMINAL_QR_FIELD_METADATA\.successMessage/);
  assert.match(operationsSource, /REMOTE_SERVER_TERMINAL_QR_FIELD_METADATA\.accessibilityLabel/);
  assert.doesNotMatch(operationsSource, /<Text style=\{styles\.label\}>Terminal QR<\/Text>/);
  assert.doesNotMatch(operationsSource, /createSwitchAccessibilityLabel\('Terminal QR'\)/);
  assert.match(operationsSource, /REMOTE_SERVER_OPERATOR_DEVICE_ALLOWLIST_FIELD_METADATA\.sectionTitle/);
  assert.match(operationsSource, /REMOTE_SERVER_OPERATOR_DEVICE_ALLOWLIST_FIELD_METADATA\.helperText/);
  assert.match(operationsSource, /REMOTE_SERVER_OPERATOR_DEVICE_ALLOWLIST_FIELD_METADATA\.currentDeviceLabel/);
  assert.match(operationsSource, /REMOTE_SERVER_OPERATOR_DEVICE_ALLOWLIST_FIELD_METADATA\.currentDeviceLoadingText/);
  assert.match(operationsSource, /REMOTE_SERVER_OPERATOR_DEVICE_ALLOWLIST_FIELD_METADATA\.placeholder/);
  assert.match(operationsSource, /REMOTE_SERVER_OPERATOR_DEVICE_ALLOWLIST_FIELD_METADATA\.accessibilityLabel/);
  assert.match(operationsSource, /REMOTE_SERVER_OPERATOR_DEVICE_ALLOWLIST_FIELD_METADATA\.trustAccessibilityLabel/);
  assert.match(operationsSource, /REMOTE_SERVER_OPERATOR_DEVICE_ALLOWLIST_FIELD_METADATA\.pendingLabel/);
  assert.match(operationsSource, /REMOTE_SERVER_OPERATOR_DEVICE_ALLOWLIST_FIELD_METADATA\.updateSuccessMessage/);
  assert.match(operationsSource, /REMOTE_SERVER_OPERATOR_DEVICE_ALLOWLIST_FIELD_METADATA\.trustSuccessMessage/);
  assert.match(operationsSource, /REMOTE_SERVER_OPERATOR_DEVICE_ALLOWLIST_FIELD_METADATA\.trustButtonLabel/);
  assert.match(operationsSource, /REMOTE_SERVER_OPERATOR_DEVICE_ALLOWLIST_FIELD_METADATA\.trustedButtonLabel/);
  assert.match(operationsSource, /isDesktopMac/);
  assert.match(operationsSource, /DESKTOP_SHELL_SETTINGS_SECTION_METADATA\.sectionTitle/);
  assert.match(operationsSource, /const desktopShellFields = DESKTOP_SHELL_SETTINGS_SECTION_METADATA\.fields/);
  assert.match(operationsSource, /const desktopFloatingPanelFields = DESKTOP_FLOATING_PANEL_SETTINGS_SECTION_METADATA\.fields/);
  assert.match(operationsSource, /desktopShellFields\.hideDockIcon\.label/);
  assert.match(operationsSource, /desktopShellFields\.hideDockIcon\.pendingLabel/);
  assert.match(operationsSource, /desktopShellFields\.hideDockIcon\.successMessage/);
  assert.match(operationsSource, /desktopShellFields\.hideDockIcon\.accessibilityLabel/);
  assert.match(operationsSource, /desktopShellFields\.launchAtLogin\.label/);
  assert.match(operationsSource, /desktopShellFields\.launchAtLogin\.pendingLabel/);
  assert.match(operationsSource, /desktopShellFields\.launchAtLogin\.successMessage/);
  assert.match(operationsSource, /desktopShellFields\.launchAtLogin\.accessibilityLabel/);
  assert.match(operationsSource, /DESKTOP_THEME_PREFERENCE_FIELD_METADATA\.label/);
  assert.match(operationsSource, /DESKTOP_THEME_PREFERENCE_FIELD_METADATA\.pendingLabel/);
  assert.match(operationsSource, /DESKTOP_THEME_PREFERENCE_FIELD_METADATA\.formatSuccessMessage\(option\.label\)/);
  assert.match(operationsSource, /DESKTOP_THEME_PREFERENCE_FIELD_METADATA\.formatButtonAccessibilityLabel\(option\.label\)/);
  assert.match(operationsSource, /hideDockIcon: value/);
  assert.match(operationsSource, /launchAtLogin: value/);
  assert.match(operationsSource, /themePreference: option\.value/);
  assert.match(operationsSource, /DESKTOP_TEXT_INPUT_FIELD_METADATA\.label/);
  assert.match(operationsSource, /DESKTOP_TEXT_INPUT_FIELD_METADATA\.helperText/);
  assert.match(operationsSource, /DESKTOP_TEXT_INPUT_FIELD_METADATA\.pendingLabel/);
  assert.match(operationsSource, /DESKTOP_TEXT_INPUT_FIELD_METADATA\.successMessage/);
  assert.match(operationsSource, /DESKTOP_TEXT_INPUT_FIELD_METADATA\.accessibilityLabel/);
  assert.doesNotMatch(operationsSource, /<Text style=\{styles\.label\}>Text Input<\/Text>/);
  assert.doesNotMatch(operationsSource, /createSwitchAccessibilityLabel\('Desktop Text Input'\)/);
  assert.match(operationsSource, /textInputEnabled: value/);
  assert.match(operationsSource, /DESKTOP_FLOATING_PANEL_SETTINGS_SECTION_METADATA\.sectionTitle/);
  assert.match(operationsSource, /desktopFloatingPanelFields\.floatingPanelAutoShow\.label/);
  assert.match(operationsSource, /desktopFloatingPanelFields\.floatingPanelAutoShow\.helperText/);
  assert.match(operationsSource, /desktopFloatingPanelFields\.floatingPanelAutoShow\.pendingLabel/);
  assert.match(operationsSource, /desktopFloatingPanelFields\.floatingPanelAutoShow\.successMessage/);
  assert.match(operationsSource, /desktopFloatingPanelFields\.floatingPanelAutoShow\.accessibilityLabel/);
  assert.match(operationsSource, /desktopFloatingPanelFields\.hidePanelWhenMainFocused\.label/);
  assert.match(operationsSource, /desktopFloatingPanelFields\.hidePanelWhenMainFocused\.helperText/);
  assert.match(operationsSource, /desktopFloatingPanelFields\.hidePanelWhenMainFocused\.pendingLabel/);
  assert.match(operationsSource, /desktopFloatingPanelFields\.hidePanelWhenMainFocused\.successMessage/);
  assert.match(operationsSource, /desktopFloatingPanelFields\.hidePanelWhenMainFocused\.accessibilityLabel/);
  assert.match(operationsSource, /desktopFloatingPanelFields\.panelDragEnabled\.label/);
  assert.match(operationsSource, /desktopFloatingPanelFields\.panelDragEnabled\.helperText/);
  assert.match(operationsSource, /desktopFloatingPanelFields\.panelDragEnabled\.pendingLabel/);
  assert.match(operationsSource, /desktopFloatingPanelFields\.panelDragEnabled\.successMessage/);
  assert.match(operationsSource, /desktopFloatingPanelFields\.panelDragEnabled\.accessibilityLabel/);
  assert.match(operationsSource, /desktopFloatingPanelFields\.panelPosition\.label/);
  assert.match(operationsSource, /desktopFloatingPanelFields\.panelPosition\.pendingLabel/);
  assert.match(operationsSource, /desktopFloatingPanelFields\.panelPosition\.formatSuccessMessage\(option\.compactLabel\)/);
  assert.match(operationsSource, /desktopFloatingPanelFields\.panelPosition\.formatButtonAccessibilityLabel\(option\.compactLabel\)/);
  assert.doesNotMatch(operationsSource, /<Text style=\{styles\.subsectionTitle\}>Desktop floating panel<\/Text>/);
  assert.doesNotMatch(operationsSource, /<Text style=\{styles\.label\}>Auto-Show Floating Panel<\/Text>/);
  assert.doesNotMatch(operationsSource, /createSwitchAccessibilityLabel\('Auto-Show Floating Panel'\)/);
  assert.match(operationsSource, /floatingPanelAutoShow: value/);
  assert.match(operationsSource, /hidePanelWhenMainFocused: value/);
  assert.match(operationsSource, /panelDragEnabled: value/);
  assert.match(operationsSource, /panelPosition: option\.value/);
  assert.match(operationsSource, /CLOUDFLARE_TUNNEL_MODE_FIELD_METADATA/);
  assert.match(operationsSource, /CLOUDFLARE_TUNNEL_MODE_FIELD_METADATA\.pendingLabel/);
  assert.match(operationsSource, /CLOUDFLARE_TUNNEL_MODE_FIELD_METADATA\.accessibilityLabel/);
  assert.match(operationsSource, /CLOUDFLARE_TUNNEL_SECTION_METADATA\.sectionTitle/);
  assert.match(operationsSource, /CLOUDFLARE_TUNNEL_SECTION_METADATA\.namedTunnelHelperText/);
  assert.doesNotMatch(operationsSource, /<Text style=\{styles\.label\}>Tunnel Mode<\/Text>/);
  assert.match(operationsSource, /CLOUDFLARE_TUNNEL_MODE_DISPLAY_OPTIONS/);
  assert.match(operationsSource, /DEFAULT_CLOUDFLARE_TUNNEL_MODE/);
  assert.match(operationsSource, /DEFAULT_CLOUDFLARE_TUNNEL_AUTO_START/);
  assert.match(operationsSource, /CLOUDFLARE_TUNNEL_AUTO_START_FIELD_METADATA/);
  assert.match(operationsSource, /CLOUDFLARE_TUNNEL_AUTO_START_FIELD_METADATA\.pendingLabel/);
  assert.match(operationsSource, /CLOUDFLARE_TUNNEL_AUTO_START_FIELD_METADATA\.successMessage/);
  assert.match(operationsSource, /CLOUDFLARE_TUNNEL_AUTO_START_FIELD_METADATA\.accessibilityLabel/);
  assert.doesNotMatch(operationsSource, /<Text style=\{styles\.label\}>Auto-Start Tunnel<\/Text>/);
  assert.doesNotMatch(operationsSource, /createSwitchAccessibilityLabel\('Auto-Start Tunnel'\)/);
  assert.match(operationsSource, /CLOUDFLARE_TUNNEL_ID_FIELD_METADATA/);
  assert.match(operationsSource, /CLOUDFLARE_TUNNEL_ID_FIELD_METADATA\.pendingLabel/);
  assert.match(operationsSource, /CLOUDFLARE_TUNNEL_ID_FIELD_METADATA\.successMessage/);
  assert.match(operationsSource, /CLOUDFLARE_TUNNEL_ID_FIELD_METADATA\.mobilePlaceholder/);
  assert.match(operationsSource, /CLOUDFLARE_TUNNEL_ID_FIELD_METADATA\.accessibilityLabel/);
  assert.doesNotMatch(operationsSource, /<Text style=\{styles\.label\}>Tunnel ID<\/Text>/);
  assert.doesNotMatch(operationsSource, /placeholder="Tunnel UUID"/);
  assert.match(operationsSource, /CLOUDFLARE_TUNNEL_HOSTNAME_FIELD_METADATA/);
  assert.match(operationsSource, /CLOUDFLARE_TUNNEL_HOSTNAME_FIELD_METADATA\.pendingLabel/);
  assert.match(operationsSource, /CLOUDFLARE_TUNNEL_HOSTNAME_FIELD_METADATA\.successMessage/);
  assert.match(operationsSource, /CLOUDFLARE_TUNNEL_HOSTNAME_FIELD_METADATA\.mobilePlaceholder/);
  assert.match(operationsSource, /CLOUDFLARE_TUNNEL_HOSTNAME_FIELD_METADATA\.accessibilityLabel/);
  assert.doesNotMatch(operationsSource, /<Text style=\{styles\.label\}>Hostname<\/Text>/);
  assert.doesNotMatch(operationsSource, /placeholder="agent\.example\.com"/);
  assert.match(operationsSource, /CLOUDFLARE_TUNNEL_NAME_FIELD_METADATA/);
  assert.match(operationsSource, /CLOUDFLARE_TUNNEL_NAME_FIELD_METADATA\.pendingLabel/);
  assert.match(operationsSource, /CLOUDFLARE_TUNNEL_NAME_FIELD_METADATA\.successMessage/);
  assert.match(operationsSource, /CLOUDFLARE_TUNNEL_NAME_FIELD_METADATA\.mobilePlaceholder/);
  assert.match(operationsSource, /CLOUDFLARE_TUNNEL_NAME_FIELD_METADATA\.accessibilityLabel/);
  assert.doesNotMatch(operationsSource, /<Text style=\{styles\.label\}>Tunnel Name<\/Text>/);
  assert.doesNotMatch(operationsSource, /placeholder="my-dotagents-tunnel"/);
  assert.match(remoteAccessDraftsSource, /cloudflareTunnelName: settings\?\.cloudflareTunnelName \?\? ""/);
  assert.match(operationsSource, /cloudflareTunnelMode: option\.value/);
  assert.match(operationsSource, /cloudflareTunnelName: drafts\.cloudflareTunnelName\.trim\(\)/);
  assert.match(operationsSource, /CLOUDFLARE_TUNNEL_CREDENTIALS_PATH_FIELD_METADATA/);
  assert.match(operationsSource, /CLOUDFLARE_TUNNEL_CREDENTIALS_PATH_FIELD_METADATA\.pendingLabel/);
  assert.match(operationsSource, /CLOUDFLARE_TUNNEL_CREDENTIALS_PATH_FIELD_METADATA\.successMessage/);
  assert.match(operationsSource, /CLOUDFLARE_TUNNEL_CREDENTIALS_PATH_FIELD_METADATA\.mobilePlaceholder/);
  assert.match(operationsSource, /CLOUDFLARE_TUNNEL_CREDENTIALS_PATH_FIELD_METADATA\.accessibilityLabel/);
  assert.doesNotMatch(operationsSource, /<Text style=\{styles\.label\}>Credentials Path<\/Text>/);
  assert.doesNotMatch(operationsSource, /placeholder="\/path\/to\/credentials\.json"/);
  assert.match(operationsSource, /CHANNEL_OPERATOR_ALLOWLISTS_SECTION_METADATA\.sectionTitle/);
  assert.match(operationsSource, /CHANNEL_OPERATOR_ALLOWLISTS_SECTION_METADATA\.helperText/);
  assert.match(operationsSource, /CHANNEL_OPERATOR_ALLOWLISTS_SECTION_METADATA\.footerText/);
  assert.match(operationsSource, /const channelAllowlistFields = CHANNEL_OPERATOR_ALLOWLISTS_SECTION_METADATA\.fields/);
  assert.match(operationsSource, /channelAllowlistFields\.discordOperatorAllowUserIds\.label/);
  assert.match(operationsSource, /channelAllowlistFields\.discordOperatorAllowGuildIds\.label/);
  assert.match(operationsSource, /channelAllowlistFields\.discordOperatorAllowChannelIds\.label/);
  assert.match(operationsSource, /channelAllowlistFields\.discordOperatorAllowRoleIds\.label/);
  assert.match(operationsSource, /channelAllowlistFields\.whatsappOperatorAllowFrom\.label/);
  assert.match(operationsSource, /channelAllowlistFields\.discordOperatorAllowUserIds\.pendingLabel/);
  assert.match(operationsSource, /channelAllowlistFields\.discordOperatorAllowGuildIds\.successMessage/);
  assert.match(operationsSource, /channelAllowlistFields\.discordOperatorAllowChannelIds\.placeholder/);
  assert.match(operationsSource, /channelAllowlistFields\.discordOperatorAllowRoleIds\.accessibilityLabel/);
  assert.match(operationsSource, /channelAllowlistFields\.whatsappOperatorAllowFrom\.successMessage/);
  assert.match(remoteAccessDraftsSource, /discordOperatorAllowRoleIds: formatConfigListInput\(settings\?\.discordOperatorAllowRoleIds\)/);
  assert.match(operationsSource, /discordOperatorAllowRoleIds: parseConfigListInput\(drafts\.discordOperatorAllowRoleIds, \{ unique: true \}\)/);
  assert.match(operationsSource, /getDeviceIdentity/);
});

test('includes tunnel, Discord, and WhatsApp operator controls and summaries', () => {
  assert.match(operationsSource, /OPERATOR_RUNTIME_STATUS_PANEL_METADATA\.panelTitle/);
  assert.match(operationsSource, /OPERATOR_RUNTIME_STATUS_PANEL_METADATA\.formatConfigured\(settings\?\.remoteServerEnabled\)/);
  assert.match(operationsSource, /OPERATOR_RUNTIME_STATUS_PANEL_METADATA\.formatRunning\(status\.remoteServer\.running\)/);
  assert.match(operationsSource, /OPERATOR_RUNTIME_STATUS_PANEL_METADATA\.formatBind\(status\.remoteServer\.bind, status\.remoteServer\.port\)/);
  assert.match(operationsSource, /OPERATOR_RUNTIME_STATUS_PANEL_METADATA\.formatConnectableUrl\(status\.remoteServer\.connectableUrl, status\.remoteServer\.url\)/);
  assert.match(operationsSource, /OPERATOR_RUNTIME_STATUS_PANEL_METADATA\.formatLastError\(status\.remoteServer\.lastError\)/);
  assert.doesNotMatch(operationsSource, /OPERATOR_RUNTIME_STATUS_PANEL_METADATA\.configuredLabel/);
  assert.doesNotMatch(operationsSource, /OPERATOR_RUNTIME_STATUS_PANEL_METADATA\.runningLabel/);
  assert.doesNotMatch(operationsSource, /OPERATOR_RUNTIME_STATUS_PANEL_METADATA\.bindLabel/);
  assert.doesNotMatch(operationsSource, /OPERATOR_RUNTIME_STATUS_PANEL_METADATA\.connectableUrlLabel/);
  assert.doesNotMatch(operationsSource, /OPERATOR_RUNTIME_STATUS_PANEL_METADATA\.lastErrorLabel/);
  assert.match(operationsSource, /OPERATOR_TUNNEL_STATUS_PANEL_METADATA\.panelTitle/);
  assert.match(operationsSource, /OPERATOR_TUNNEL_STATUS_PANEL_METADATA\.formatState\(tunnelStatus\)/);
  assert.match(operationsSource, /OPERATOR_TUNNEL_STATUS_PANEL_METADATA\.formatMode/);
  assert.match(operationsSource, /OPERATOR_TUNNEL_STATUS_PANEL_METADATA\.formatUrl\(tunnelStatus\?\.url\)/);
  assert.match(operationsSource, /OPERATOR_TUNNEL_STATUS_PANEL_METADATA\.formatRemoteServerRunning\(status\?\.remoteServer\.running\)/);
  assert.match(operationsSource, /OPERATOR_TUNNEL_STATUS_PANEL_METADATA\.setupTitle/);
  assert.match(operationsSource, /OPERATOR_TUNNEL_STATUS_PANEL_METADATA\.formatInstalled\(tunnelSetup\?\.installed\)/);
  assert.match(operationsSource, /OPERATOR_TUNNEL_STATUS_PANEL_METADATA\.formatLoggedIn\(tunnelSetup\?\.loggedIn\)/);
  assert.match(operationsSource, /OPERATOR_TUNNEL_STATUS_PANEL_METADATA\.formatNamedTunnelConfigured\(tunnelSetup\?\.namedTunnelConfigured\)/);
  assert.match(operationsSource, /OPERATOR_TUNNEL_STATUS_PANEL_METADATA\.formatCredentialsPathConfigured\(tunnelSetup\?\.credentialsPathConfigured\)/);
  assert.match(operationsSource, /OPERATOR_TUNNEL_STATUS_PANEL_METADATA\.formatDiscoveredNamedTunnels\(tunnelSetup\?\.tunnelCount\)/);
  assert.match(operationsSource, /OPERATOR_TUNNEL_STATUS_PANEL_METADATA\.formatConfiguredTunnelId\(tunnelSetup\.configuredTunnelId\)/);
  assert.match(operationsSource, /OPERATOR_TUNNEL_STATUS_PANEL_METADATA\.formatConfiguredHostname\(tunnelSetup\.configuredHostname\)/);
  assert.match(operationsSource, /OPERATOR_TUNNEL_STATUS_PANEL_METADATA\.formatNamedTunnel\(tunnel\.name, tunnel\.id\)/);
  assert.match(operationsSource, /OPERATOR_TUNNEL_STATUS_PANEL_METADATA\.formatTunnelError\(tunnelStatus\.error\)/);
  assert.match(operationsSource, /OPERATOR_TUNNEL_STATUS_PANEL_METADATA\.formatSetupError\(tunnelSetup\.error\)/);
  assert.match(operationsSource, /OPERATOR_TUNNEL_STATUS_PANEL_METADATA\.startButtonLabel/);
  assert.match(operationsSource, /OPERATOR_TUNNEL_STATUS_PANEL_METADATA\.stopButtonLabel/);
  assert.match(operationsSource, /OPERATOR_TUNNEL_STATUS_PANEL_METADATA\.helperText/);
  assert.doesNotMatch(operationsSource, /OPERATOR_TUNNEL_STATUS_PANEL_METADATA\.stateLabel/);
  assert.doesNotMatch(operationsSource, /OPERATOR_TUNNEL_STATUS_PANEL_METADATA\.modeLabel/);
  assert.doesNotMatch(operationsSource, /OPERATOR_TUNNEL_STATUS_PANEL_METADATA\.urlLabel/);
  assert.doesNotMatch(operationsSource, /OPERATOR_TUNNEL_STATUS_PANEL_METADATA\.remoteServerRunningLabel/);
  assert.doesNotMatch(operationsSource, /OPERATOR_TUNNEL_STATUS_PANEL_METADATA\.installedLabel/);
  assert.doesNotMatch(operationsSource, /OPERATOR_TUNNEL_STATUS_PANEL_METADATA\.loggedInLabel/);
  assert.doesNotMatch(operationsSource, /OPERATOR_TUNNEL_STATUS_PANEL_METADATA\.tunnelErrorLabel/);
  assert.doesNotMatch(operationsSource, /OPERATOR_TUNNEL_STATUS_PANEL_METADATA\.setupErrorLabel/);
  assert.doesNotMatch(operationsSource, /getTunnelStateLabel/);
  assert.doesNotMatch(operationsSource, /formatYesNo/);
  assert.doesNotMatch(operationsSource, /<Text style=\{styles\.panelTitle\}>Tunnel status<\/Text>/);
  assert.doesNotMatch(operationsSource, /createButtonAccessibilityLabel\('Start tunnel'\)/);
  assert.doesNotMatch(operationsSource, /createButtonAccessibilityLabel\('Stop tunnel'\)/);
  assert.match(operationsSource, /OPERATOR_DISCORD_PANEL_METADATA\.panelTitle/);
  assert.match(operationsSource, /OPERATOR_DISCORD_PANEL_METADATA\.formatStatus\(discord\)/);
  assert.match(operationsSource, /OPERATOR_DISCORD_PANEL_METADATA\.formatAvailable\(discord\.available\)/);
  assert.match(operationsSource, /OPERATOR_DISCORD_PANEL_METADATA\.formatTokenConfigured\(discord\.tokenConfigured\)/);
  assert.match(operationsSource, /OPERATOR_DISCORD_PANEL_METADATA\.formatBotUsername\(discord\.botUsername\)/);
  assert.match(operationsSource, /OPERATOR_DISCORD_PANEL_METADATA\.formatDefaultProfile\(discord\.defaultProfileName, discord\.defaultProfileId\)/);
  assert.match(operationsSource, /OPERATOR_DISCORD_PANEL_METADATA\.formatLogs\(discord\.logs\)/);
  assert.match(operationsSource, /OPERATOR_DISCORD_PANEL_METADATA\.formatLastEvent\(discord\.lastEventAt\)/);
  assert.match(operationsSource, /OPERATOR_DISCORD_PANEL_METADATA\.formatLastError\(discord\.lastError\)/);
  assert.match(operationsSource, /OPERATOR_DISCORD_PANEL_METADATA\.connectButton\.accessibilityLabel/);
  assert.match(operationsSource, /OPERATOR_DISCORD_PANEL_METADATA\.connectButton\.buttonLabel/);
  assert.match(operationsSource, /OPERATOR_DISCORD_PANEL_METADATA\.disconnectAction\.confirmTitle/);
  assert.match(operationsSource, /OPERATOR_DISCORD_PANEL_METADATA\.disconnectAction\.confirmMessage/);
  assert.match(operationsSource, /OPERATOR_DISCORD_PANEL_METADATA\.disconnectAction\.confirmButtonLabel/);
  assert.match(operationsSource, /OPERATOR_DISCORD_PANEL_METADATA\.disconnectAction\.accessibilityLabel/);
  assert.match(operationsSource, /OPERATOR_DISCORD_PANEL_METADATA\.disconnectAction\.buttonLabel/);
  assert.match(operationsSource, /OPERATOR_DISCORD_PANEL_METADATA\.clearLogsAction\.confirmTitle/);
  assert.match(operationsSource, /OPERATOR_DISCORD_PANEL_METADATA\.clearLogsAction\.confirmMessage/);
  assert.match(operationsSource, /OPERATOR_DISCORD_PANEL_METADATA\.clearLogsAction\.confirmButtonLabel/);
  assert.match(operationsSource, /OPERATOR_DISCORD_PANEL_METADATA\.clearLogsAction\.accessibilityLabel/);
  assert.match(operationsSource, /OPERATOR_DISCORD_PANEL_METADATA\.clearLogsAction\.buttonLabel/);
  assert.match(operationsSource, /OPERATOR_DISCORD_PANEL_METADATA\.logsSectionTitle/);
  assert.match(operationsSource, /OPERATOR_DISCORD_PANEL_METADATA\.emptyLogsText/);
  assert.match(operationsSource, /OPERATOR_DISCORD_PANEL_METADATA\.formatLogLevel\(entry\)/);
  assert.match(operationsSource, /OPERATOR_DISCORD_PANEL_METADATA\.formatLogTimestamp\(entry\)/);
  assert.match(operationsSource, /OPERATOR_DISCORD_PANEL_METADATA\.formatLogMessage\(entry\)/);
  assert.match(operationsSource, /OPERATOR_WHATSAPP_PANEL_METADATA\.panelTitle/);
  assert.match(operationsSource, /OPERATOR_WHATSAPP_PANEL_METADATA\.formatStatus\(whatsApp\)/);
  assert.match(operationsSource, /OPERATOR_WHATSAPP_PANEL_METADATA\.formatServerConfigured\(whatsApp\.serverConfigured\)/);
  assert.match(operationsSource, /OPERATOR_WHATSAPP_PANEL_METADATA\.formatServerConnected\(whatsApp\.serverConnected\)/);
  assert.match(operationsSource, /OPERATOR_WHATSAPP_PANEL_METADATA\.formatAvailable\(whatsApp\.available\)/);
  assert.match(operationsSource, /OPERATOR_WHATSAPP_PANEL_METADATA\.formatAutoReply\(whatsApp\.autoReplyEnabled\)/);
  assert.match(operationsSource, /OPERATOR_WHATSAPP_PANEL_METADATA\.formatLogMessages\(whatsApp\.logMessagesEnabled\)/);
  assert.match(operationsSource, /OPERATOR_WHATSAPP_PANEL_METADATA\.formatAllowedSenders\(whatsApp\.allowedSenderCount\)/);
  assert.match(operationsSource, /OPERATOR_WHATSAPP_PANEL_METADATA\.formatCredentialsPresent\(whatsApp\.hasCredentials\)/);
  assert.match(operationsSource, /OPERATOR_WHATSAPP_PANEL_METADATA\.formatLogs\(whatsApp\.logs\)/);
  assert.match(operationsSource, /OPERATOR_WHATSAPP_PANEL_METADATA\.formatLastError\(whatsApp\.lastError\)/);
  assert.match(operationsSource, /OPERATOR_WHATSAPP_PANEL_METADATA\.connectButton\.accessibilityLabel/);
  assert.match(operationsSource, /OPERATOR_WHATSAPP_PANEL_METADATA\.connectButton\.buttonLabel/);
  assert.match(operationsSource, /OPERATOR_WHATSAPP_PANEL_METADATA\.logoutAction\.confirmTitle/);
  assert.match(operationsSource, /OPERATOR_WHATSAPP_PANEL_METADATA\.logoutAction\.confirmMessage/);
  assert.match(operationsSource, /OPERATOR_WHATSAPP_PANEL_METADATA\.logoutAction\.confirmButtonLabel/);
  assert.match(operationsSource, /OPERATOR_WHATSAPP_PANEL_METADATA\.logoutAction\.accessibilityLabel/);
  assert.match(operationsSource, /OPERATOR_WHATSAPP_PANEL_METADATA\.logoutAction\.buttonLabel/);
  assert.doesNotMatch(operationsSource, /<Text style=\{styles\.panelTitle\}>Discord<\/Text>/);
  assert.doesNotMatch(operationsSource, /<Text style=\{styles\.panelTitle\}>WhatsApp<\/Text>/);
  assert.doesNotMatch(operationsSource, /createButtonAccessibilityLabel\('Connect Discord'\)/);
  assert.doesNotMatch(operationsSource, /createButtonAccessibilityLabel\('Connect WhatsApp'\)/);
  assert.doesNotMatch(operationsSource, /confirmAction\(\s*'Disconnect Discord'/);
  assert.doesNotMatch(operationsSource, /confirmAction\(\s*'Log Out of WhatsApp'/);
  assert.doesNotMatch(operationsSource, /<Text style=\{styles\.logLevel\}>\{entry\.level\}<\/Text>/);
});

test('surfaces recent operator audit entries and rotates the API key using the saved mobile config', () => {
  assert.match(operationsSource, /OPERATOR_AUDIT_PANEL_METADATA\.panelTitle/);
  assert.match(operationsSource, /OPERATOR_AUDIT_PANEL_METADATA\.helperText/);
  assert.match(operationsSource, /OPERATOR_AUDIT_PANEL_METADATA\.emptyText/);
  assert.match(operationsSource, /OPERATOR_AUDIT_PANEL_METADATA\.formatAction\(entry\)/);
  assert.match(operationsSource, /OPERATOR_AUDIT_PANEL_METADATA\.formatStatus\(entry\)/);
  assert.match(operationsSource, /OPERATOR_AUDIT_PANEL_METADATA\.formatPath\(entry\)/);
  assert.match(operationsSource, /OPERATOR_AUDIT_PANEL_METADATA\.formatTimestamp\(entry\)/);
  assert.match(operationsSource, /OPERATOR_AUDIT_PANEL_METADATA\.formatSource\(sourceText\)/);
  assert.match(operationsSource, /OPERATOR_AUDIT_PANEL_METADATA\.formatDetails\(detailsText\)/);
  assert.match(operationsSource, /OPERATOR_AUDIT_PANEL_METADATA\.formatFailure\(entry\.failureReason\)/);
  assert.doesNotMatch(operationsSource, /<Text style=\{styles\.panelTitle\}>Recent operator audit<\/Text>/);
  assert.doesNotMatch(operationsSource, /No recent operator audit entries returned by the desktop server\./);
  assert.doesNotMatch(operationsSource, /entry\.success \? 'success' : 'failed'/);
  assert.doesNotMatch(operationsSource, /<Text style=\{styles\.auditAction\}>\{entry\.action\}<\/Text>/);
  assert.doesNotMatch(operationsSource, /<Text style=\{styles\.auditPath\}>\{entry\.path\}<\/Text>/);
  assert.doesNotMatch(operationsSource, /<Text style=\{styles\.auditTimestamp\}>\{formatTimestamp\(entry\.timestamp\)\}<\/Text>/);
  assert.doesNotMatch(operationsSource, />Source: \{sourceText\}</);
  assert.doesNotMatch(operationsSource, />Details: \{detailsText\}</);
  assert.doesNotMatch(operationsSource, />Failure: \{entry\.failureReason\}</);
  assert.match(operationsSource, /OPERATOR_ALERT_METADATA\.actionFailedTitle/);
  assert.match(operationsSource, /OPERATOR_ALERT_METADATA\.updateFailedTitle/);
  assert.match(operationsSource, /OPERATOR_ALERT_METADATA\.connectionRequiredTitle/);
  assert.match(operationsSource, /OPERATOR_ALERT_METADATA\.promptRequiredTitle/);
  assert.match(operationsSource, /OPERATOR_ALERT_METADATA\.promptRequiredMessage/);
  assert.match(operationsSource, /OPERATOR_ALERT_METADATA\.cancelButtonLabel/);
  assert.match(operationsSource, /OPERATOR_ALERT_METADATA\.connectionRequiredMessages\.rotateApiKey/);
  assert.match(operationsSource, /OPERATOR_ALERT_METADATA\.connectionRequiredMessages\.operatorActions/);
  assert.match(operationsSource, /OPERATOR_ALERT_METADATA\.connectionRequiredMessages\.mcpLogs/);
  assert.match(operationsSource, /OPERATOR_ALERT_METADATA\.connectionRequiredMessages\.mcpTools/);
  assert.match(operationsSource, /OPERATOR_ALERT_METADATA\.connectionRequiredMessages\.mcpToolChange/);
  assert.match(operationsSource, /OPERATOR_ALERT_METADATA\.connectionRequiredMessages\.runAgent/);
  assert.match(operationsSource, /OPERATOR_ALERT_METADATA\.connectionRequiredMessages\.settingsSave/);
  assert.match(operationsSource, /OPERATOR_ALERT_METADATA\.defaultApiKeyRotationFailureMessage/);
  assert.match(operationsSource, /OPERATOR_ALERT_METADATA\.defaultActionFailureMessage/);
  assert.match(operationsSource, /OPERATOR_ALERT_METADATA\.defaultActionCompletedMessage/);
  assert.match(operationsSource, /OPERATOR_ALERT_METADATA\.defaultMcpToolToggleFailureMessage/);
  assert.match(operationsSource, /OPERATOR_ALERT_METADATA\.defaultAgentRunFailureMessage/);
  assert.match(operationsSource, /OPERATOR_ALERT_METADATA\.connectionSettlingSuffix/);
  assert.doesNotMatch(operationsSource, /Alert\.alert\('Action Failed'/);
  assert.doesNotMatch(operationsSource, /Alert\.alert\('Connection Required'/);
  assert.doesNotMatch(operationsSource, /Alert\.alert\('Prompt Required'/);
  assert.doesNotMatch(operationsSource, /Alert\.alert\('Update Failed'/);
  assert.doesNotMatch(operationsSource, /Configure your desktop server connection before/);
  assert.doesNotMatch(operationsSource, /Enter a prompt for the desktop agent to run\./);
  assert.doesNotMatch(operationsSource, /Load the connected desktop settings before saving operator changes\./);
  assert.match(operationsSource, /REMOTE_SERVER_API_KEY_FIELD_METADATA/);
  assert.match(operationsSource, /REMOTE_SERVER_API_KEY_FIELD_METADATA\.rotateConfirmTitle/);
  assert.match(operationsSource, /REMOTE_SERVER_API_KEY_FIELD_METADATA\.rotateConfirmMessage/);
  assert.match(operationsSource, /REMOTE_SERVER_API_KEY_FIELD_METADATA\.rotateConfirmButtonLabel/);
  assert.match(operationsSource, /REMOTE_SERVER_API_KEY_FIELD_METADATA\.rotateAccessibilityLabel/);
  assert.match(operationsSource, /REMOTE_SERVER_API_KEY_FIELD_METADATA\.rotatePendingButtonLabel/);
  assert.match(operationsSource, /REMOTE_SERVER_API_KEY_FIELD_METADATA\.rotateButtonLabel/);
  assert.match(operationsSource, /REMOTE_SERVER_API_KEY_FIELD_METADATA\.rotateHelperText/);
  assert.match(operationsSource, /REMOTE_SERVER_API_KEY_FIELD_METADATA\.formatRotateSuccessMessage\(response\.restartScheduled\)/);
  assert.doesNotMatch(operationsSource, /'Rotate API Key'/);
  assert.doesNotMatch(operationsSource, /'Rotate Key'/);
  assert.doesNotMatch(operationsSource, /API key rotated and saved locally\./);
  assert.match(operationsSource, /OPERATOR_ACTIONS_PANEL_METADATA\.panelTitle/);
  assert.match(operationsSource, /OPERATOR_ACTIONS_PANEL_METADATA\.runAgentLabel/);
  assert.match(operationsSource, /OPERATOR_ACTIONS_PANEL_METADATA\.runAgentPromptPlaceholder/);
  assert.match(operationsSource, /OPERATOR_ACTIONS_PANEL_METADATA\.runAgentPromptAccessibilityLabel/);
  assert.match(operationsSource, /OPERATOR_ACTIONS_PANEL_METADATA\.runAgentPromptAccessibilityHint/);
  assert.match(operationsSource, /OPERATOR_ACTIONS_PANEL_METADATA\.runAgentButton\.accessibilityLabel/);
  assert.match(operationsSource, /OPERATOR_ACTIONS_PANEL_METADATA\.runAgentButton\.pendingLabel/);
  assert.match(operationsSource, /OPERATOR_ACTIONS_PANEL_METADATA\.runAgentButton\.buttonLabel/);
  assert.match(operationsSource, /OPERATOR_ACTIONS_PANEL_METADATA\.formatAgentRunCompletedMessage/);
  assert.match(operationsSource, /settingsClient\.runOperatorAgent\(\{ prompt \}\)/);
  assert.match(operationsSource, /OPERATOR_UPDATER_PANEL_METADATA\.panelTitle/);
  assert.match(operationsSource, /OPERATOR_UPDATER_PANEL_METADATA\.formatMode\(status\.updater\.mode\)/);
  assert.match(operationsSource, /OPERATOR_UPDATER_PANEL_METADATA\.formatCurrentVersion\(status\.updater\.currentVersion\)/);
  assert.match(operationsSource, /OPERATOR_UPDATER_PANEL_METADATA\.formatUpdateAvailable\(status\.updater\.updateAvailable\)/);
  assert.match(operationsSource, /OPERATOR_UPDATER_PANEL_METADATA\.formatLastChecked\(status\.updater\.lastCheckedAt\)/);
  assert.match(operationsSource, /OPERATOR_UPDATER_PANEL_METADATA\.formatLatestRelease\(status\.updater\.latestRelease\.tagName\)/);
  assert.match(operationsSource, /OPERATOR_UPDATER_PANEL_METADATA\.formatPublished\(status\.updater\.latestRelease\.publishedAt\)/);
  assert.match(operationsSource, /OPERATOR_UPDATER_PANEL_METADATA\.formatAssets\(status\.updater\.latestRelease\.assetCount\)/);
  assert.match(operationsSource, /OPERATOR_UPDATER_PANEL_METADATA\.formatReleaseUrl\(status\.updater\.latestRelease\.url\)/);
  assert.match(operationsSource, /OPERATOR_UPDATER_PANEL_METADATA\.formatRecommendedAsset\(status\.updater\.preferredAsset\.name\)/);
  assert.match(operationsSource, /OPERATOR_UPDATER_PANEL_METADATA\.formatAssetUrl\(status\.updater\.preferredAsset\.downloadUrl\)/);
  assert.match(operationsSource, /OPERATOR_UPDATER_PANEL_METADATA\.formatLastDownloadedFile\(status\.updater\.lastDownloadedFileName\)/);
  assert.match(operationsSource, /OPERATOR_UPDATER_PANEL_METADATA\.formatDownloadedAt\(status\.updater\.lastDownloadedAt\)/);
  assert.match(operationsSource, /OPERATOR_UPDATER_PANEL_METADATA\.formatLastCheckError\(status\.updater\.lastCheckError\)/);
  assert.match(operationsSource, /OPERATOR_UPDATER_PANEL_METADATA\.formatManualReleases\(status\.updater\.manualReleasesUrl\)/);
  assert.match(operationsSource, /OPERATOR_UPDATER_PANEL_METADATA\.checkLatestReleaseButton\.accessibilityLabel/);
  assert.match(operationsSource, /OPERATOR_UPDATER_PANEL_METADATA\.checkLatestReleaseButton\.pendingLabel/);
  assert.match(operationsSource, /OPERATOR_UPDATER_PANEL_METADATA\.checkLatestReleaseButton\.buttonLabel/);
  assert.match(operationsSource, /OPERATOR_UPDATER_PANEL_METADATA\.downloadLatestInstallerAction\.confirmTitle/);
  assert.match(operationsSource, /OPERATOR_UPDATER_PANEL_METADATA\.downloadLatestInstallerAction\.confirmMessage/);
  assert.match(operationsSource, /OPERATOR_UPDATER_PANEL_METADATA\.downloadLatestInstallerAction\.confirmButtonLabel/);
  assert.match(operationsSource, /OPERATOR_UPDATER_PANEL_METADATA\.downloadLatestInstallerAction\.accessibilityLabel/);
  assert.match(operationsSource, /OPERATOR_UPDATER_PANEL_METADATA\.downloadLatestInstallerAction\.pendingLabel/);
  assert.match(operationsSource, /OPERATOR_UPDATER_PANEL_METADATA\.downloadLatestInstallerAction\.buttonLabel/);
  assert.match(operationsSource, /OPERATOR_UPDATER_PANEL_METADATA\.revealDownloadedInstallerButton\.accessibilityLabel/);
  assert.match(operationsSource, /OPERATOR_UPDATER_PANEL_METADATA\.revealDownloadedInstallerButton\.pendingLabel/);
  assert.match(operationsSource, /OPERATOR_UPDATER_PANEL_METADATA\.revealDownloadedInstallerButton\.buttonLabel/);
  assert.match(operationsSource, /OPERATOR_UPDATER_PANEL_METADATA\.openDownloadedInstallerAction\.confirmTitle/);
  assert.match(operationsSource, /OPERATOR_UPDATER_PANEL_METADATA\.openDownloadedInstallerAction\.confirmMessage/);
  assert.match(operationsSource, /OPERATOR_UPDATER_PANEL_METADATA\.openDownloadedInstallerAction\.confirmButtonLabel/);
  assert.match(operationsSource, /OPERATOR_UPDATER_PANEL_METADATA\.openDownloadedInstallerAction\.accessibilityLabel/);
  assert.match(operationsSource, /OPERATOR_UPDATER_PANEL_METADATA\.openDownloadedInstallerAction\.pendingLabel/);
  assert.match(operationsSource, /OPERATOR_UPDATER_PANEL_METADATA\.openDownloadedInstallerAction\.buttonLabel/);
  assert.match(operationsSource, /OPERATOR_UPDATER_PANEL_METADATA\.openReleasePageButton\.accessibilityLabel/);
  assert.match(operationsSource, /OPERATOR_UPDATER_PANEL_METADATA\.openReleasePageButton\.pendingLabel/);
  assert.match(operationsSource, /OPERATOR_UPDATER_PANEL_METADATA\.openReleasePageButton\.buttonLabel/);
  assert.doesNotMatch(operationsSource, /<Text style=\{styles\.panelTitle\}>Updater<\/Text>/);
  assert.doesNotMatch(operationsSource, /createButtonAccessibilityLabel\('Check latest release'\)/);
  assert.doesNotMatch(operationsSource, /confirmAction\(\s*'Download Latest Installer'/);
  assert.match(operationsSource, /settingsClient\.rotateOperatorApiKey\(\)/);
  assert.match(operationsSource, /settingsClient\.checkOperatorUpdater\(\)/);
  assert.match(operationsSource, /settingsClient\.downloadOperatorUpdateAsset\(\)/);
  assert.match(operationsSource, /settingsClient\.revealOperatorUpdateAsset\(\)/);
  assert.match(operationsSource, /settingsClient\.openOperatorUpdateAsset\(\)/);
  assert.match(operationsSource, /settingsClient\.openOperatorReleasesPage\(\)/);
  assert.match(operationsSource, /settingsClient\.stopOperatorTtsPlayback\(\)/);
  assert.match(operationsSource, /settingsClient\.showOperatorMainWindow\(\)/);
  assert.match(operationsSource, /settingsClient\.showOperatorMainWindow\('\/'\)/);
  assert.match(operationsSource, /settingsClient\.showOperatorMainWindow\('\/settings'\)/);
  assert.match(operationsSource, /settingsClient\.showOperatorPanelWindow\(\)/);
  assert.match(operationsSource, /settingsClient\.hideOperatorPanelWindow\(\)/);
  assert.match(operationsSource, /settingsClient\.resetOperatorPanelWindow\(\)/);
  assert.match(operationsSource, /OPERATOR_ACTIONS_PANEL_METADATA\.refreshButton\.accessibilityLabel/);
  assert.match(operationsSource, /OPERATOR_ACTIONS_PANEL_METADATA\.stopSpeechButton\.accessibilityLabel/);
  assert.match(operationsSource, /OPERATOR_ACTIONS_PANEL_METADATA\.stopSpeechButton\.buttonLabel/);
  assert.match(operationsSource, /OPERATOR_ACTIONS_PANEL_METADATA\.showAppButton\.buttonLabel/);
  assert.match(operationsSource, /OPERATOR_ACTIONS_PANEL_METADATA\.showHistoryButton\.buttonLabel/);
  assert.match(operationsSource, /OPERATOR_ACTIONS_PANEL_METADATA\.showSettingsButton\.buttonLabel/);
  assert.match(operationsSource, /OPERATOR_ACTIONS_PANEL_METADATA\.showPanelButton\.buttonLabel/);
  assert.match(operationsSource, /OPERATOR_ACTIONS_PANEL_METADATA\.hidePanelButton\.buttonLabel/);
  assert.match(operationsSource, /OPERATOR_ACTIONS_PANEL_METADATA\.resetPanelButton\.buttonLabel/);
  assert.match(operationsSource, /OPERATOR_ACTIONS_PANEL_METADATA\.restartRemoteServerAction\.confirmTitle/);
  assert.match(operationsSource, /OPERATOR_ACTIONS_PANEL_METADATA\.restartAppAction\.confirmTitle/);
  assert.match(operationsSource, /OPERATOR_ACTIONS_PANEL_METADATA\.emergencyStopAction\.confirmTitle/);
  assert.doesNotMatch(operationsSource, /<Text style=\{styles\.panelTitle\}>Actions<\/Text>/);
  assert.doesNotMatch(operationsSource, /createButtonAccessibilityLabel\('Stop desktop speech playback'\)/);
  assert.doesNotMatch(operationsSource, /'Restart Remote Server'/);
  assert.doesNotMatch(operationsSource, /Agent run finished in \$\{response\.conversationId\}/);
  assert.match(operationsSource, /setConfig\(nextConfig\)/);
  assert.match(operationsSource, /saveConfig\(nextConfig\)/);
});

test('displays system metrics and agent sessions from operator status', () => {
  assert.match(operationsSource, /OPERATOR_STATUS_PANEL_METADATA\.panelTitle/);
  assert.match(operationsSource, /OPERATOR_STATUS_PANEL_METADATA\.formatUpdatedText\(status\.health\.overall, status\.timestamp\)/);
  assert.match(operationsSource, /OPERATOR_STATUS_PANEL_METADATA\.waitingText/);
  assert.match(operationsSource, /OPERATOR_STATUS_PANEL_METADATA\.loadingText/);
  assert.match(operationsSource, /OPERATOR_STATUS_PANEL_METADATA\.formatIntegrationSummary/);
  assert.match(operationsSource, /OPERATOR_STATUS_PANEL_METADATA\.formatPendingSettingText\(pendingSetting\)/);
  assert.match(operationsSource, /OPERATOR_SYSTEM_PANEL_METADATA\.panelTitle/);
  assert.match(operationsSource, /OPERATOR_SYSTEM_PANEL_METADATA\.formatPlatformSummary\(status\.system\)/);
  assert.match(operationsSource, /OPERATOR_SYSTEM_PANEL_METADATA\.formatRuntimeSummary\(status\.system\)/);
  assert.match(operationsSource, /OPERATOR_SYSTEM_PANEL_METADATA\.formatMemorySummary\(status\.system\)/);
  assert.match(operationsSource, /OPERATOR_SYSTEM_PANEL_METADATA\.formatUptimeSummary\(status\.system\)/);
  assert.match(operationsSource, /status\?\.system/);
  assert.doesNotMatch(operationsSource, /<Text style=\{styles\.panelTitle\}>Operator status<\/Text>/);
  assert.doesNotMatch(operationsSource, /<Text style=\{styles\.panelTitle\}>System<\/Text>/);
  assert.doesNotMatch(operationsSource, /Waiting for operator status…/);
  assert.doesNotMatch(operationsSource, /Loading operator data…/);
  assert.match(operationsSource, /OPERATOR_HEALTH_CHECKS_PANEL_METADATA\.panelTitle/);
  assert.doesNotMatch(operationsSource, /<Text style=\{styles\.panelTitle\}>Health checks<\/Text>/);
  assert.match(operationsSource, /OPERATOR_AGENT_SESSIONS_PANEL_METADATA\.panelTitle/);
  assert.match(operationsSource, /OPERATOR_AGENT_SESSIONS_PANEL_METADATA\.formatSummary/);
  assert.match(operationsSource, /status\.sessions\.activeSessions/);
  assert.match(operationsSource, /status\.sessions\.activeSessionDetails/);
  assert.match(operationsSource, /status\.sessions\.recentSessionDetails/);
  assert.match(operationsSource, /formatActiveAgentSessionSummary\(s\)/);
  assert.match(operationsSource, /formatRecentAgentSessionSummary\(s\)/);
  assert.match(operationsSource, /OPERATOR_AGENT_SESSIONS_PANEL_METADATA\.formatActiveStartedAt\(s\.startTime\)/);
  assert.match(operationsSource, /OPERATOR_AGENT_SESSIONS_PANEL_METADATA\.formatRecentTime\(s\.startTime, s\.endTime\)/);
  assert.match(operationsSource, /const sessionName = getAgentSessionDisplayName\(s\)/);
  assert.match(operationsSource, /showOperatorAgentSession\(s\.id\)/);
  assert.match(operationsSource, /snoozeOperatorAgentSession\(s\.id\)/);
  assert.match(operationsSource, /unsnoozeOperatorAgentSession\(s\.id\)/);
  assert.match(operationsSource, /snoozeOperatorAgentSessionsAndHidePanel/);
  assert.match(operationsSource, /clearOperatorAgentSession\(s\.id\)/);
  assert.match(operationsSource, /clearInactiveOperatorAgentSessions\(\)/);
  assert.match(operationsSource, /OPERATOR_AGENT_SESSIONS_PANEL_METADATA\.hideActiveAccessibilityLabel/);
  assert.match(operationsSource, /OPERATOR_AGENT_SESSIONS_PANEL_METADATA\.hideActiveButtonLabel/);
  assert.match(operationsSource, /OPERATOR_AGENT_SESSIONS_PANEL_METADATA\.formatDismissAccessibilityLabel\(sessionName\)/);
  assert.match(operationsSource, /OPERATOR_AGENT_SESSIONS_PANEL_METADATA\.clearInactiveAccessibilityLabel/);
  assert.match(operationsSource, /OPERATOR_AGENT_SESSIONS_PANEL_METADATA\.clearInactiveConfirmMessage/);
  assert.match(operationsSource, /OPERATOR_AGENT_SESSIONS_PANEL_METADATA\.formatShowAccessibilityLabel\(sessionName\)/);
  assert.match(operationsSource, /OPERATOR_AGENT_SESSIONS_PANEL_METADATA\.formatSnoozeButtonLabel\(isSnoozed\)/);
  assert.match(operationsSource, /OPERATOR_AGENT_SESSIONS_PANEL_METADATA\.formatSnoozePendingLabel\(isSnoozed\)/);
  assert.match(operationsSource, /stopOperatorAgentSession\(s\.id\)/);
  assert.match(operationsSource, /OPERATOR_AGENT_SESSIONS_PANEL_METADATA\.formatStopAccessibilityLabel\(sessionName\)/);
  assert.match(operationsSource, /OPERATOR_AGENT_SESSIONS_PANEL_METADATA\.noActiveSessionsText/);
  assert.doesNotMatch(operationsSource, /<Text style=\{styles\.panelTitle\}>Agent sessions<\/Text>/);
  assert.doesNotMatch(operationsSource, /Since \{formatTimestamp\(s\.startTime\)\}/);
  assert.doesNotMatch(operationsSource, /Ended \$\{formatTimestamp\(s\.endTime\)\}/);
  assert.doesNotMatch(operationsSource, /Started \$\{formatTimestamp\(s\.startTime\)\}/);
  assert.doesNotMatch(operationsSource, /createButtonAccessibilityLabel\('Clear inactive agent sessions on desktop'\)/);
  assert.doesNotMatch(operationsSource, /createButtonAccessibilityLabel\(`Show \$\{s\.title \?\? s\.id\} agent session on desktop`\)/);
});

test('displays desktop message queues from operator API', () => {
  assert.match(operationsSource, /getOperatorMessageQueues\(\)/);
  assert.match(operationsSource, /setMessageQueues/);
  assert.match(operationsSource, /OPERATOR_MESSAGE_QUEUES_PANEL_METADATA\.panelTitle/);
  assert.match(operationsSource, /OPERATOR_MESSAGE_QUEUES_PANEL_METADATA\.formatSummary/);
  assert.match(operationsSource, /OPERATOR_MESSAGE_QUEUES_PANEL_METADATA\.formatQueueSummary\(queue\.conversationId, queue\.messageCount, queue\.isPaused\)/);
  assert.match(operationsSource, /OPERATOR_MESSAGE_QUEUES_PANEL_METADATA\.formatMessageSummary\(message\.status, message\.text\)/);
  assert.match(operationsSource, /messageQueues\.map/);
  assert.match(operationsSource, /clearOperatorMessageQueue\(queue\.conversationId\)/);
  assert.match(operationsSource, /pauseOperatorMessageQueue\(queue\.conversationId\)/);
  assert.match(operationsSource, /resumeOperatorMessageQueue\(queue\.conversationId\)/);
  assert.match(operationsSource, /retryOperatorQueuedMessage\(queue\.conversationId, message\.id\)/);
  assert.match(operationsSource, /removeOperatorQueuedMessage\(queue\.conversationId, message\.id\)/);
  assert.match(operationsSource, /updateOperatorQueuedMessageText\(queue\.conversationId, message\.id, editedText\)/);
  assert.match(operationsSource, /OPERATOR_MESSAGE_QUEUES_PANEL_METADATA\.formatClearQueueAccessibilityLabel\(queue\.conversationId\)/);
  assert.match(operationsSource, /OPERATOR_MESSAGE_QUEUES_PANEL_METADATA\.formatPauseQueueAccessibilityLabel\(queue\.conversationId\)/);
  assert.match(operationsSource, /OPERATOR_MESSAGE_QUEUES_PANEL_METADATA\.formatResumeQueueAccessibilityLabel\(queue\.conversationId\)/);
  assert.match(operationsSource, /OPERATOR_MESSAGE_QUEUES_PANEL_METADATA\.formatRetryMessageAccessibilityLabel\(message\.id\)/);
  assert.match(operationsSource, /OPERATOR_MESSAGE_QUEUES_PANEL_METADATA\.formatEditMessageAccessibilityLabel\(message\.id\)/);
  assert.match(operationsSource, /OPERATOR_MESSAGE_QUEUES_PANEL_METADATA\.formatRemoveMessageAccessibilityLabel\(message\.id\)/);
  assert.match(operationsSource, /OPERATOR_MESSAGE_QUEUES_PANEL_METADATA\.formatMessageInputAccessibilityLabel\(message\.id\)/);
  assert.match(operationsSource, /OPERATOR_MESSAGE_QUEUES_PANEL_METADATA\.formatCancelEditAccessibilityLabel\(message\.id\)/);
  assert.match(operationsSource, /OPERATOR_MESSAGE_QUEUES_PANEL_METADATA\.formatSaveMessageAccessibilityLabel\(message\.id\)/);
  assert.match(operationsSource, /OPERATOR_MESSAGE_QUEUES_PANEL_METADATA\.formatRemoveMessageConfirmMessage\(message\.id, queue\.conversationId\)/);
  assert.match(operationsSource, /OPERATOR_MESSAGE_QUEUES_PANEL_METADATA\.formatClearQueueConfirmMessage\(queue\.conversationId\)/);
  assert.doesNotMatch(operationsSource, /<Text style=\{styles\.panelTitle\}>Desktop message queues<\/Text>/);
  assert.doesNotMatch(operationsSource, /\{message\.status\}: \{message\.text\}/);
  assert.doesNotMatch(operationsSource, /createButtonAccessibilityLabel\(`Clear \$\{queue\.conversationId\} desktop message queue`\)/);
  assert.doesNotMatch(operationsSource, /createButtonAccessibilityLabel\(`Retry queued message \$\{message\.id\}`\)/);
});

test('auto-refreshes operator data periodically', () => {
  assert.match(operationsSource, /AUTO_REFRESH_INTERVAL_MS/);
  assert.match(operationsSource, /setInterval/);
  assert.match(operationsSource, /clearInterval/);
  assert.match(operationsSource, /autoRefreshRef/);
});

test('displays recent conversations from operator API', () => {
  assert.match(operationsSource, /getOperatorConversations/);
  assert.match(operationsSource, /setConversations/);
  assert.match(operationsSource, /OPERATOR_CONVERSATIONS_PANEL_METADATA\.panelTitle/);
  assert.match(operationsSource, /OPERATOR_CONVERSATIONS_PANEL_METADATA\.formatConversationSummary\(c\.title, c\.messageCount\)/);
  assert.match(operationsSource, /OPERATOR_CONVERSATIONS_PANEL_METADATA\.formatConversationUpdatedPreview\(c\.updatedAt, c\.preview\)/);
  assert.match(operationsSource, /conversations\.map/);
  assert.doesNotMatch(operationsSource, /<Text style=\{styles\.panelTitle\}>Recent conversations<\/Text>/);
  assert.doesNotMatch(operationsSource, /c\.title \|\| 'Untitled'/);
  assert.doesNotMatch(operationsSource, /c\.messageCount\} msgs/);
  assert.doesNotMatch(operationsSource, /c\.preview\.slice\(0, 80\)/);
});

test('exposes desktop diagnostic report controls', () => {
  assert.match(operationsSource, /OPERATOR_DIAGNOSTIC_REPORT_ACTION_METADATA\.sectionTitle/);
  assert.match(operationsSource, /OPERATOR_DIAGNOSTIC_REPORT_ACTION_METADATA\.formatGeneratedMessage\(report\.errors\.length\)/);
  assert.match(operationsSource, /getOperatorDiagnosticReport\(\)/);
  assert.match(operationsSource, /saveOperatorDiagnosticReport\(\)/);
  assert.match(operationsSource, /OPERATOR_DIAGNOSTIC_REPORT_ACTION_METADATA\.generateAccessibilityLabel/);
  assert.match(operationsSource, /OPERATOR_DIAGNOSTIC_REPORT_ACTION_METADATA\.generatePendingLabel/);
  assert.match(operationsSource, /OPERATOR_DIAGNOSTIC_REPORT_ACTION_METADATA\.generateButtonLabel/);
  assert.match(operationsSource, /OPERATOR_DIAGNOSTIC_REPORT_ACTION_METADATA\.saveConfirmTitle/);
  assert.match(operationsSource, /OPERATOR_DIAGNOSTIC_REPORT_ACTION_METADATA\.saveConfirmMessage/);
  assert.match(operationsSource, /OPERATOR_DIAGNOSTIC_REPORT_ACTION_METADATA\.saveConfirmButtonLabel/);
  assert.match(operationsSource, /OPERATOR_DIAGNOSTIC_REPORT_ACTION_METADATA\.saveAccessibilityLabel/);
  assert.match(operationsSource, /OPERATOR_DIAGNOSTIC_REPORT_ACTION_METADATA\.savePendingLabel/);
  assert.match(operationsSource, /OPERATOR_DIAGNOSTIC_REPORT_ACTION_METADATA\.saveButtonLabel/);
  assert.match(operationsSource, /OPERATOR_DIAGNOSTIC_REPORT_ACTION_METADATA\.emptyReportText/);
  assert.match(operationsSource, /OPERATOR_DIAGNOSTIC_REPORT_ACTION_METADATA\.formatGeneratedAt\(diagnosticReport\.timestamp\)/);
  assert.match(operationsSource, /OPERATOR_DIAGNOSTIC_REPORT_ACTION_METADATA\.formatMcpSummary/);
  assert.match(operationsSource, /OPERATOR_DIAGNOSTIC_REPORT_ACTION_METADATA\.formatLogEntries\(diagnosticReport\.errors\.length\)/);
  assert.match(operationsSource, /OPERATOR_DIAGNOSTIC_REPORT_ACTION_METADATA\.formatToolDiscoveryError\(diagnosticReport\.mcp\.toolDiscoveryError\)/);
  assert.doesNotMatch(operationsSource, /createButtonAccessibilityLabel\('Generate desktop diagnostic report'\)/);
  assert.doesNotMatch(operationsSource, /createButtonAccessibilityLabel\('Save diagnostic report on desktop'\)/);
  assert.doesNotMatch(operationsSource, /<Text style=\{styles\.detailText\}>Generated:/);
  assert.doesNotMatch(operationsSource, /MCP tools: \{diagnosticReport\.mcp\.availableTools\}/);
  assert.doesNotMatch(operationsSource, /<Text style=\{styles\.detailText\}>Log entries:/);
  assert.doesNotMatch(operationsSource, /<Text style=\{styles\.warningText\}>Tool discovery:/);
  assert.match(operationsSource, /diagnosticReport\.mcp\.availableTools/);
});

test('displays recent operator logs from operator API', () => {
  assert.match(operationsSource, /RECENT_LOG_COUNT/);
  assert.match(operationsSource, /RECENT_ERROR_COUNT/);
  assert.match(operationsSource, /getOperatorLogs\(RECENT_LOG_COUNT\)/);
  assert.match(operationsSource, /getOperatorErrors\(RECENT_ERROR_COUNT\)/);
  assert.match(operationsSource, /setOperatorLogs/);
  assert.match(operationsSource, /setRecentErrors/);
  assert.match(operationsSource, /OPERATOR_LOGS_PANEL_METADATA\.panelTitle/);
  assert.match(operationsSource, /operatorLogs\.map/);
  assert.match(operationsSource, /settingsClient\.clearOperatorErrors\(\)/);
  assert.match(operationsSource, /OPERATOR_LOGS_PANEL_METADATA\.clearConfirmTitle/);
  assert.match(operationsSource, /OPERATOR_LOGS_PANEL_METADATA\.clearConfirmMessage/);
  assert.match(operationsSource, /OPERATOR_LOGS_PANEL_METADATA\.clearConfirmButtonLabel/);
  assert.match(operationsSource, /OPERATOR_LOGS_PANEL_METADATA\.clearAccessibilityLabel/);
  assert.match(operationsSource, /OPERATOR_LOGS_PANEL_METADATA\.clearPendingLabel/);
  assert.match(operationsSource, /OPERATOR_LOGS_PANEL_METADATA\.clearButtonLabel/);
  assert.match(operationsSource, /OPERATOR_LOGS_PANEL_METADATA\.emptyText/);
  assert.match(operationsSource, /OPERATOR_LOGS_PANEL_METADATA\.formatEntryHeader\(entry\)/);
  assert.match(operationsSource, /OPERATOR_LOGS_PANEL_METADATA\.formatEntryTimestamp\(entry\)/);
  assert.match(operationsSource, /OPERATOR_LOGS_PANEL_METADATA\.formatEntryMessage\(entry\)/);
  assert.doesNotMatch(operationsSource, /<Text style=\{styles\.panelTitle\}>Recent operator logs<\/Text>/);
  assert.doesNotMatch(operationsSource, /createButtonAccessibilityLabel\('Clear desktop operator error log'\)/);
  assert.match(operationsSource, /OPERATOR_ERRORS_PANEL_METADATA\.panelTitle/);
  assert.match(operationsSource, /OPERATOR_ERRORS_PANEL_METADATA\.emptyText/);
  assert.match(operationsSource, /OPERATOR_ERRORS_PANEL_METADATA\.formatEntryComponent\(entry\)/);
  assert.match(operationsSource, /OPERATOR_ERRORS_PANEL_METADATA\.formatEntryLevel\(entry\)/);
  assert.match(operationsSource, /OPERATOR_ERRORS_PANEL_METADATA\.formatEntryMessage\(entry\)/);
  assert.match(operationsSource, /OPERATOR_ERRORS_PANEL_METADATA\.formatEntryTimestamp\(entry\)/);
  assert.match(operationsSource, /recentErrors\.map/);
  assert.doesNotMatch(operationsSource, /<Text style=\{styles\.panelTitle\}>Recent errors<\/Text>/);
  assert.doesNotMatch(operationsSource, /\{entry\.level\} • \{entry\.component\}/);
  assert.doesNotMatch(operationsSource, /<Text style=\{styles\.errorComponent\}>\{entry\.component\}<\/Text>/);
  assert.doesNotMatch(operationsSource, /<Text style=\{styles\.errorLevel\}>\{entry\.level\}<\/Text>/);
  assert.doesNotMatch(operationsSource, /<Text style=\{styles\.errorMessage\}>\{entry\.message\}<\/Text>/);
});

test('displays MCP servers from operator API', () => {
  assert.match(operationsSource, /getOperatorMCP/);
  assert.match(operationsSource, /setMcpServers/);
  assert.match(operationsSource, /OPERATOR_MCP_SERVERS_PANEL_METADATA\.panelTitle/);
  assert.match(operationsSource, /OPERATOR_MCP_SERVERS_PANEL_METADATA\.formatSummary/);
  assert.match(operationsSource, /OPERATOR_MCP_SERVERS_PANEL_METADATA\.formatServerSummary\(s\.connected, s\.enabled, s\.name, s\.toolCount\)/);
  assert.match(operationsSource, /mcpServers\.map/);
  assert.match(operationsSource, /OPERATOR_MCP_SERVERS_PANEL_METADATA\.formatStartAccessibilityLabel\(s\.name\)/);
  assert.match(operationsSource, /OPERATOR_MCP_SERVERS_PANEL_METADATA\.formatStopAccessibilityLabel\(s\.name\)/);
  assert.match(operationsSource, /OPERATOR_MCP_SERVERS_PANEL_METADATA\.formatRestartAccessibilityLabel\(s\.name\)/);
  assert.match(operationsSource, /OPERATOR_MCP_SERVERS_PANEL_METADATA\.formatTestAccessibilityLabel\(s\.name\)/);
  assert.match(operationsSource, /OPERATOR_MCP_SERVERS_PANEL_METADATA\.formatTestSuccessMessage\(s\.name, response\.toolCount\)/);
  assert.match(operationsSource, /testOperatorMCPServer\(s\.name\)/);
  assert.match(operationsSource, /MCP_LOG_PREVIEW_COUNT/);
  assert.match(operationsSource, /getOperatorMCPServerLogs\(serverName, MCP_LOG_PREVIEW_COUNT\)/);
  assert.match(operationsSource, /clearOperatorMCPServerLogs\(s\.name\)/);
  assert.match(operationsSource, /getOperatorMCPTools\(serverName\)/);
  assert.match(operationsSource, /setOperatorMCPToolEnabled\(toolName, enabled\)/);
  assert.match(operationsSource, /OPERATOR_MCP_SERVERS_PANEL_METADATA\.formatLogsAccessibilityLabel\(s\.name, logsExpanded\)/);
  assert.match(operationsSource, /OPERATOR_MCP_SERVERS_PANEL_METADATA\.formatToolsAccessibilityLabel\(s\.name, toolsExpanded\)/);
  assert.match(operationsSource, /OPERATOR_MCP_SERVERS_PANEL_METADATA\.formatToolAccessibilityLabel\(tool\.name\)/);
  assert.match(operationsSource, /OPERATOR_MCP_SERVERS_PANEL_METADATA\.logsSectionTitle/);
  assert.match(operationsSource, /OPERATOR_MCP_SERVERS_PANEL_METADATA\.toolsSectionTitle/);
  assert.match(operationsSource, /OPERATOR_MCP_SERVERS_PANEL_METADATA\.formatLogTimestamp\(entry\)/);
  assert.match(operationsSource, /OPERATOR_MCP_SERVERS_PANEL_METADATA\.formatLogMessage\(entry\)/);
  assert.match(operationsSource, /OPERATOR_MCP_SERVERS_PANEL_METADATA\.formatClearLogsConfirmMessage\(s\.name\)/);
  assert.match(operationsSource, /OPERATOR_MCP_SERVERS_PANEL_METADATA\.formatClearLogsAccessibilityLabel\(s\.name\)/);
  assert.match(operationsSource, /settingsClient\.startMCPServer\(s\.name\)/);
  assert.match(operationsSource, /settingsClient\.stopMCPServer\(s\.name\)/);
  assert.match(operationsSource, /settingsClient\.restartMCPServer\(s\.name\)/);
  assert.match(operationsSource, /OPERATOR_MCP_SERVERS_PANEL_METADATA\.formatRestartedMessage\(s\.name\)/);
  assert.doesNotMatch(operationsSource, /<Text style=\{styles\.panelTitle\}>MCP servers<\/Text>/);
  assert.doesNotMatch(operationsSource, /s\.connected \? '✓' : s\.enabled \? '✗' : '○'/);
  assert.doesNotMatch(operationsSource, /createButtonAccessibilityLabel\(`Restart \$\{s\.name\} MCP server`\)/);
  assert.doesNotMatch(operationsSource, /<Text style=\{styles\.logMessage\}>\{entry\.message\}<\/Text>/);
});
