const test = require('node:test');
const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');

const operationsSource = fs.readFileSync(
  path.join(__dirname, '..', 'src', 'screens', 'OperationsScreen.tsx'),
  'utf8'
);
const remoteAccessDraftsSource = fs.readFileSync(
  path.join(__dirname, '..', '..', '..', 'packages', 'shared', 'src', 'operator-remote-access-drafts.ts'),
  'utf8'
);

test('exposes compact remote access settings for mobile remote ops', () => {
  assert.match(operationsSource, /Remote access settings/);
  assert.match(operationsSource, /REMOTE_SERVER_ENABLED_FIELD_METADATA/);
  assert.match(operationsSource, /REMOTE_SERVER_BIND_ADDRESS_FIELD_METADATA/);
  assert.match(operationsSource, /REMOTE_SERVER_BIND_ADDRESS_DISPLAY_OPTIONS/);
  assert.match(operationsSource, /REMOTE_SERVER_CORS_ORIGINS_FIELD_METADATA/);
  assert.match(operationsSource, /REMOTE_SERVER_LOG_LEVEL_FIELD_METADATA/);
  assert.match(operationsSource, /REMOTE_SERVER_LOG_LEVEL_DISPLAY_OPTIONS/);
  assert.match(operationsSource, /DEFAULT_REMOTE_SERVER_BIND_ADDRESS/);
  assert.match(operationsSource, /DEFAULT_REMOTE_SERVER_ENABLED/);
  assert.match(operationsSource, /DEFAULT_REMOTE_SERVER_AUTO_SHOW_PANEL/);
  assert.match(operationsSource, /DEFAULT_REMOTE_SERVER_LOG_LEVEL/);
  assert.match(operationsSource, /DEFAULT_REMOTE_SERVER_CORS_ORIGINS/);
  assert.match(operationsSource, /DEFAULT_REMOTE_SERVER_PORT/);
  assert.match(operationsSource, /DEFAULT_REMOTE_SERVER_TERMINAL_QR_ENABLED/);
  assert.match(operationsSource, /REMOTE_SERVER_AUTO_SHOW_PANEL_FIELD_METADATA/);
  assert.match(operationsSource, /REMOTE_SERVER_TERMINAL_QR_FIELD_METADATA/);
  assert.match(operationsSource, /DEFAULT_HIDE_DOCK_ICON/);
  assert.match(operationsSource, /DEFAULT_LAUNCH_AT_LOGIN/);
  assert.match(operationsSource, /DEFAULT_TEXT_INPUT_ENABLED/);
  assert.match(operationsSource, /DEFAULT_THEME_PREFERENCE/);
  assert.match(operationsSource, /THEME_PREFERENCE_OPTIONS/);
  assert.doesNotMatch(operationsSource, /DESKTOP_THEME_OPTIONS/);
  assert.match(operationsSource, /DEFAULT_FLOATING_PANEL_AUTO_SHOW/);
  assert.match(operationsSource, /DEFAULT_HIDE_PANEL_WHEN_MAIN_FOCUSED/);
  assert.match(operationsSource, /DEFAULT_PANEL_DRAG_ENABLED/);
  assert.match(operationsSource, /DEFAULT_PANEL_POSITION/);
  assert.match(operationsSource, /PANEL_POSITION_OPTIONS/);
  assert.match(operationsSource, /option\.compactLabel/);
  assert.doesNotMatch(operationsSource, /const PANEL_POSITION_OPTIONS/);
  assert.match(operationsSource, /REMOTE_SERVER_PORT_FIELD_METADATA/);
  assert.match(operationsSource, /REMOTE_SERVER_PORT_FIELD_METADATA\.pendingLabel/);
  assert.match(operationsSource, /REMOTE_SERVER_PORT_FIELD_METADATA\.formatSuccessMessage\(parsed\)/);
  assert.match(operationsSource, /isRemoteServerPortUpdateValue/);
  assert.match(operationsSource, /buildOperatorRemoteAccessDrafts as buildDrafts/);
  assert.match(remoteAccessDraftsSource, /DEFAULT_REMOTE_SERVER_CORS_ORIGINS/);
  assert.match(remoteAccessDraftsSource, /DEFAULT_REMOTE_SERVER_PORT/);
  assert.match(remoteAccessDraftsSource, /remoteServerPort: String\(settings\?\.remoteServerPort \?\? DEFAULT_REMOTE_SERVER_PORT\)/);
  assert.match(remoteAccessDraftsSource, /remoteServerCorsOrigins: formatConfigListInput\(settings\?\.remoteServerCorsOrigins \?\? DEFAULT_REMOTE_SERVER_CORS_ORIGINS\)/);
  assert.match(operationsSource, /remoteServerBindAddress: option\.value/);
  assert.match(operationsSource, /REMOTE_SERVER_BIND_ADDRESS_FIELD_METADATA\.pendingLabel/);
  assert.match(operationsSource, /option\.successMessage/);
  assert.match(operationsSource, /REMOTE_SERVER_ENABLED_FIELD_METADATA\.pendingLabel/);
  assert.match(operationsSource, /REMOTE_SERVER_ENABLED_FIELD_METADATA\.enableSuccessMessage/);
  assert.match(operationsSource, /REMOTE_SERVER_ENABLED_FIELD_METADATA\.disableConfirmTitle/);
  assert.match(operationsSource, /REMOTE_SERVER_ENABLED_FIELD_METADATA\.disableConfirmMessage/);
  assert.match(operationsSource, /REMOTE_SERVER_ENABLED_FIELD_METADATA\.disableConfirmButtonLabel/);
  assert.match(operationsSource, /REMOTE_SERVER_ENABLED_FIELD_METADATA\.disableSuccessMessage/);
  assert.match(operationsSource, /REMOTE_SERVER_ENABLED_FIELD_METADATA\.updateSuccessMessage/);
  assert.match(operationsSource, /REMOTE_SERVER_ENABLED_FIELD_METADATA\.accessibilityLabel/);
  assert.doesNotMatch(operationsSource, /<Text style=\{styles\.label\}>Remote Server<\/Text>/);
  assert.doesNotMatch(operationsSource, /createSwitchAccessibilityLabel\('Remote Server'\)/);
  assert.match(operationsSource, /REMOTE_SERVER_BIND_ADDRESS_FIELD_METADATA\.accessibilityLabel/);
  assert.match(operationsSource, /remoteServerLogLevel: option\.value/);
  assert.match(operationsSource, /REMOTE_SERVER_LOG_LEVEL_FIELD_METADATA\.pendingLabel/);
  assert.match(operationsSource, /REMOTE_SERVER_LOG_LEVEL_FIELD_METADATA\.accessibilityLabel/);
  assert.match(operationsSource, /remoteServerCorsOrigins: origins\.length > 0 \? origins : \[\.\.\.DEFAULT_REMOTE_SERVER_CORS_ORIGINS\]/);
  assert.match(operationsSource, /REMOTE_SERVER_CORS_ORIGINS_FIELD_METADATA\.pendingLabel/);
  assert.match(operationsSource, /REMOTE_SERVER_CORS_ORIGINS_FIELD_METADATA\.successMessage/);
  assert.doesNotMatch(operationsSource, /placeholder="\* or http:\/\/localhost:8081/);
  assert.match(operationsSource, /REMOTE_SERVER_AUTO_SHOW_PANEL_FIELD_METADATA\.pendingLabel/);
  assert.match(operationsSource, /REMOTE_SERVER_AUTO_SHOW_PANEL_FIELD_METADATA\.successMessage/);
  assert.match(operationsSource, /REMOTE_SERVER_AUTO_SHOW_PANEL_FIELD_METADATA\.accessibilityLabel/);
  assert.doesNotMatch(operationsSource, /<Text style=\{styles\.label\}>Auto-Show Panel<\/Text>/);
  assert.doesNotMatch(operationsSource, /createSwitchAccessibilityLabel\('Auto-Show Panel'\)/);
  assert.match(operationsSource, /REMOTE_SERVER_TERMINAL_QR_FIELD_METADATA\.pendingLabel/);
  assert.match(operationsSource, /REMOTE_SERVER_TERMINAL_QR_FIELD_METADATA\.successMessage/);
  assert.match(operationsSource, /REMOTE_SERVER_TERMINAL_QR_FIELD_METADATA\.accessibilityLabel/);
  assert.doesNotMatch(operationsSource, /<Text style=\{styles\.label\}>Terminal QR<\/Text>/);
  assert.doesNotMatch(operationsSource, /createSwitchAccessibilityLabel\('Terminal QR'\)/);
  assert.match(operationsSource, /REMOTE_SERVER_OPERATOR_DEVICE_ALLOWLIST_FIELD_METADATA\.sectionTitle/);
  assert.match(operationsSource, /REMOTE_SERVER_OPERATOR_DEVICE_ALLOWLIST_FIELD_METADATA\.helperText/);
  assert.match(operationsSource, /REMOTE_SERVER_OPERATOR_DEVICE_ALLOWLIST_FIELD_METADATA\.currentDeviceLabel/);
  assert.match(operationsSource, /REMOTE_SERVER_OPERATOR_DEVICE_ALLOWLIST_FIELD_METADATA\.currentDeviceLoadingText/);
  assert.match(operationsSource, /REMOTE_SERVER_OPERATOR_DEVICE_ALLOWLIST_FIELD_METADATA\.placeholder/);
  assert.match(operationsSource, /REMOTE_SERVER_OPERATOR_DEVICE_ALLOWLIST_FIELD_METADATA\.accessibilityLabel/);
  assert.match(operationsSource, /REMOTE_SERVER_OPERATOR_DEVICE_ALLOWLIST_FIELD_METADATA\.trustAccessibilityLabel/);
  assert.match(operationsSource, /REMOTE_SERVER_OPERATOR_DEVICE_ALLOWLIST_FIELD_METADATA\.pendingLabel/);
  assert.match(operationsSource, /REMOTE_SERVER_OPERATOR_DEVICE_ALLOWLIST_FIELD_METADATA\.updateSuccessMessage/);
  assert.match(operationsSource, /REMOTE_SERVER_OPERATOR_DEVICE_ALLOWLIST_FIELD_METADATA\.trustSuccessMessage/);
  assert.match(operationsSource, /REMOTE_SERVER_OPERATOR_DEVICE_ALLOWLIST_FIELD_METADATA\.trustButtonLabel/);
  assert.match(operationsSource, /REMOTE_SERVER_OPERATOR_DEVICE_ALLOWLIST_FIELD_METADATA\.trustedButtonLabel/);
  assert.match(operationsSource, /isDesktopMac/);
  assert.match(operationsSource, /Desktop app/);
  assert.match(operationsSource, /Hide Dock Icon/);
  assert.match(operationsSource, /Launch at Login/);
  assert.match(operationsSource, /Desktop Theme/);
  assert.match(operationsSource, /hideDockIcon: value/);
  assert.match(operationsSource, /launchAtLogin: value/);
  assert.match(operationsSource, /themePreference: option\.value/);
  assert.match(operationsSource, /Text Input/);
  assert.match(operationsSource, /textInputEnabled: value/);
  assert.match(operationsSource, /Desktop floating panel/);
  assert.match(operationsSource, /Auto-Show Floating Panel/);
  assert.match(operationsSource, /Hide When Main Focused/);
  assert.match(operationsSource, /Enable Dragging/);
  assert.match(operationsSource, /Default Position/);
  assert.match(operationsSource, /floatingPanelAutoShow: value/);
  assert.match(operationsSource, /hidePanelWhenMainFocused: value/);
  assert.match(operationsSource, /panelDragEnabled: value/);
  assert.match(operationsSource, /panelPosition: option\.value/);
  assert.match(operationsSource, /CLOUDFLARE_TUNNEL_MODE_FIELD_METADATA/);
  assert.match(operationsSource, /CLOUDFLARE_TUNNEL_MODE_FIELD_METADATA\.pendingLabel/);
  assert.match(operationsSource, /CLOUDFLARE_TUNNEL_MODE_FIELD_METADATA\.accessibilityLabel/);
  assert.match(operationsSource, /CLOUDFLARE_TUNNEL_SECTION_METADATA\.sectionTitle/);
  assert.match(operationsSource, /CLOUDFLARE_TUNNEL_SECTION_METADATA\.namedTunnelHelperText/);
  assert.doesNotMatch(operationsSource, /<Text style=\{styles\.label\}>Tunnel Mode<\/Text>/);
  assert.match(operationsSource, /CLOUDFLARE_TUNNEL_MODE_DISPLAY_OPTIONS/);
  assert.match(operationsSource, /DEFAULT_CLOUDFLARE_TUNNEL_MODE/);
  assert.match(operationsSource, /DEFAULT_CLOUDFLARE_TUNNEL_AUTO_START/);
  assert.match(operationsSource, /CLOUDFLARE_TUNNEL_AUTO_START_FIELD_METADATA/);
  assert.match(operationsSource, /CLOUDFLARE_TUNNEL_AUTO_START_FIELD_METADATA\.pendingLabel/);
  assert.match(operationsSource, /CLOUDFLARE_TUNNEL_AUTO_START_FIELD_METADATA\.successMessage/);
  assert.match(operationsSource, /CLOUDFLARE_TUNNEL_AUTO_START_FIELD_METADATA\.accessibilityLabel/);
  assert.doesNotMatch(operationsSource, /<Text style=\{styles\.label\}>Auto-Start Tunnel<\/Text>/);
  assert.doesNotMatch(operationsSource, /createSwitchAccessibilityLabel\('Auto-Start Tunnel'\)/);
  assert.match(operationsSource, /CLOUDFLARE_TUNNEL_ID_FIELD_METADATA/);
  assert.match(operationsSource, /CLOUDFLARE_TUNNEL_ID_FIELD_METADATA\.pendingLabel/);
  assert.match(operationsSource, /CLOUDFLARE_TUNNEL_ID_FIELD_METADATA\.successMessage/);
  assert.match(operationsSource, /CLOUDFLARE_TUNNEL_ID_FIELD_METADATA\.mobilePlaceholder/);
  assert.match(operationsSource, /CLOUDFLARE_TUNNEL_ID_FIELD_METADATA\.accessibilityLabel/);
  assert.doesNotMatch(operationsSource, /<Text style=\{styles\.label\}>Tunnel ID<\/Text>/);
  assert.doesNotMatch(operationsSource, /placeholder="Tunnel UUID"/);
  assert.match(operationsSource, /CLOUDFLARE_TUNNEL_HOSTNAME_FIELD_METADATA/);
  assert.match(operationsSource, /CLOUDFLARE_TUNNEL_HOSTNAME_FIELD_METADATA\.pendingLabel/);
  assert.match(operationsSource, /CLOUDFLARE_TUNNEL_HOSTNAME_FIELD_METADATA\.successMessage/);
  assert.match(operationsSource, /CLOUDFLARE_TUNNEL_HOSTNAME_FIELD_METADATA\.mobilePlaceholder/);
  assert.match(operationsSource, /CLOUDFLARE_TUNNEL_HOSTNAME_FIELD_METADATA\.accessibilityLabel/);
  assert.doesNotMatch(operationsSource, /<Text style=\{styles\.label\}>Hostname<\/Text>/);
  assert.doesNotMatch(operationsSource, /placeholder="agent\.example\.com"/);
  assert.match(operationsSource, /CLOUDFLARE_TUNNEL_NAME_FIELD_METADATA/);
  assert.match(operationsSource, /CLOUDFLARE_TUNNEL_NAME_FIELD_METADATA\.pendingLabel/);
  assert.match(operationsSource, /CLOUDFLARE_TUNNEL_NAME_FIELD_METADATA\.successMessage/);
  assert.match(operationsSource, /CLOUDFLARE_TUNNEL_NAME_FIELD_METADATA\.mobilePlaceholder/);
  assert.match(operationsSource, /CLOUDFLARE_TUNNEL_NAME_FIELD_METADATA\.accessibilityLabel/);
  assert.doesNotMatch(operationsSource, /<Text style=\{styles\.label\}>Tunnel Name<\/Text>/);
  assert.doesNotMatch(operationsSource, /placeholder="my-dotagents-tunnel"/);
  assert.match(remoteAccessDraftsSource, /cloudflareTunnelName: settings\?\.cloudflareTunnelName \?\? ""/);
  assert.match(operationsSource, /cloudflareTunnelMode: option\.value/);
  assert.match(operationsSource, /cloudflareTunnelName: drafts\.cloudflareTunnelName\.trim\(\)/);
  assert.match(operationsSource, /CLOUDFLARE_TUNNEL_CREDENTIALS_PATH_FIELD_METADATA/);
  assert.match(operationsSource, /CLOUDFLARE_TUNNEL_CREDENTIALS_PATH_FIELD_METADATA\.pendingLabel/);
  assert.match(operationsSource, /CLOUDFLARE_TUNNEL_CREDENTIALS_PATH_FIELD_METADATA\.successMessage/);
  assert.match(operationsSource, /CLOUDFLARE_TUNNEL_CREDENTIALS_PATH_FIELD_METADATA\.mobilePlaceholder/);
  assert.match(operationsSource, /CLOUDFLARE_TUNNEL_CREDENTIALS_PATH_FIELD_METADATA\.accessibilityLabel/);
  assert.doesNotMatch(operationsSource, /<Text style=\{styles\.label\}>Credentials Path<\/Text>/);
  assert.doesNotMatch(operationsSource, /placeholder="\/path\/to\/credentials\.json"/);
  assert.match(operationsSource, /CHANNEL_OPERATOR_ALLOWLISTS_SECTION_METADATA\.sectionTitle/);
  assert.match(operationsSource, /CHANNEL_OPERATOR_ALLOWLISTS_SECTION_METADATA\.helperText/);
  assert.match(operationsSource, /CHANNEL_OPERATOR_ALLOWLISTS_SECTION_METADATA\.footerText/);
  assert.match(operationsSource, /const channelAllowlistFields = CHANNEL_OPERATOR_ALLOWLISTS_SECTION_METADATA\.fields/);
  assert.match(operationsSource, /channelAllowlistFields\.discordOperatorAllowUserIds\.label/);
  assert.match(operationsSource, /channelAllowlistFields\.discordOperatorAllowGuildIds\.label/);
  assert.match(operationsSource, /channelAllowlistFields\.discordOperatorAllowChannelIds\.label/);
  assert.match(operationsSource, /channelAllowlistFields\.discordOperatorAllowRoleIds\.label/);
  assert.match(operationsSource, /channelAllowlistFields\.whatsappOperatorAllowFrom\.label/);
  assert.match(operationsSource, /channelAllowlistFields\.discordOperatorAllowUserIds\.pendingLabel/);
  assert.match(operationsSource, /channelAllowlistFields\.discordOperatorAllowGuildIds\.successMessage/);
  assert.match(operationsSource, /channelAllowlistFields\.discordOperatorAllowChannelIds\.placeholder/);
  assert.match(operationsSource, /channelAllowlistFields\.discordOperatorAllowRoleIds\.accessibilityLabel/);
  assert.match(operationsSource, /channelAllowlistFields\.whatsappOperatorAllowFrom\.successMessage/);
  assert.match(remoteAccessDraftsSource, /discordOperatorAllowRoleIds: formatConfigListInput\(settings\?\.discordOperatorAllowRoleIds\)/);
  assert.match(operationsSource, /discordOperatorAllowRoleIds: parseConfigListInput\(drafts\.discordOperatorAllowRoleIds, \{ unique: true \}\)/);
  assert.match(operationsSource, /getDeviceIdentity/);
});

test('includes tunnel, Discord, and WhatsApp operator controls and summaries', () => {
  assert.match(operationsSource, /Tunnel status/);
  assert.match(operationsSource, /Tunnel Setup/);
  assert.match(operationsSource, /Start tunnel/);
  assert.match(operationsSource, /Stop tunnel/);
  assert.match(operationsSource, /Discord log preview/);
  assert.match(operationsSource, /Connect Discord/);
  assert.match(operationsSource, /Clear logs/);
  assert.match(operationsSource, /Connect WhatsApp/);
  assert.match(operationsSource, /Log out/);
});

test('surfaces recent operator audit entries and rotates the API key using the saved mobile config', () => {
  assert.match(operationsSource, /Recent operator audit/);
  assert.match(operationsSource, /REMOTE_SERVER_API_KEY_FIELD_METADATA/);
  assert.match(operationsSource, /REMOTE_SERVER_API_KEY_FIELD_METADATA\.rotateConfirmTitle/);
  assert.match(operationsSource, /REMOTE_SERVER_API_KEY_FIELD_METADATA\.rotateConfirmMessage/);
  assert.match(operationsSource, /REMOTE_SERVER_API_KEY_FIELD_METADATA\.rotateConfirmButtonLabel/);
  assert.match(operationsSource, /REMOTE_SERVER_API_KEY_FIELD_METADATA\.rotateAccessibilityLabel/);
  assert.match(operationsSource, /REMOTE_SERVER_API_KEY_FIELD_METADATA\.rotatePendingButtonLabel/);
  assert.match(operationsSource, /REMOTE_SERVER_API_KEY_FIELD_METADATA\.rotateButtonLabel/);
  assert.match(operationsSource, /REMOTE_SERVER_API_KEY_FIELD_METADATA\.rotateHelperText/);
  assert.doesNotMatch(operationsSource, /'Rotate API Key'/);
  assert.doesNotMatch(operationsSource, /'Rotate Key'/);
  assert.match(operationsSource, /Run Agent on Desktop/);
  assert.match(operationsSource, /settingsClient\.runOperatorAgent\(\{ prompt \}\)/);
  assert.match(operationsSource, /Check latest release/);
  assert.match(operationsSource, /Download latest installer/);
  assert.match(operationsSource, /Reveal downloaded installer/);
  assert.match(operationsSource, /Open downloaded installer/);
  assert.match(operationsSource, /Open release page/);
  assert.match(operationsSource, /Latest release:/);
  assert.match(operationsSource, /Recommended asset:/);
  assert.match(operationsSource, /settingsClient\.rotateOperatorApiKey\(\)/);
  assert.match(operationsSource, /settingsClient\.checkOperatorUpdater\(\)/);
  assert.match(operationsSource, /settingsClient\.downloadOperatorUpdateAsset\(\)/);
  assert.match(operationsSource, /settingsClient\.revealOperatorUpdateAsset\(\)/);
  assert.match(operationsSource, /settingsClient\.openOperatorUpdateAsset\(\)/);
  assert.match(operationsSource, /settingsClient\.openOperatorReleasesPage\(\)/);
  assert.match(operationsSource, /settingsClient\.stopOperatorTtsPlayback\(\)/);
  assert.match(operationsSource, /settingsClient\.showOperatorMainWindow\(\)/);
  assert.match(operationsSource, /settingsClient\.showOperatorMainWindow\('\/'\)/);
  assert.match(operationsSource, /settingsClient\.showOperatorMainWindow\('\/settings'\)/);
  assert.match(operationsSource, /settingsClient\.showOperatorPanelWindow\(\)/);
  assert.match(operationsSource, /settingsClient\.hideOperatorPanelWindow\(\)/);
  assert.match(operationsSource, /settingsClient\.resetOperatorPanelWindow\(\)/);
  assert.match(operationsSource, /Stop speech/);
  assert.match(operationsSource, /Show app/);
  assert.match(operationsSource, /History/);
  assert.match(operationsSource, /Settings/);
  assert.match(operationsSource, /Show panel/);
  assert.match(operationsSource, /Hide panel/);
  assert.match(operationsSource, /Reset panel/);
  assert.match(operationsSource, /setConfig\(nextConfig\)/);
  assert.match(operationsSource, /saveConfig\(nextConfig\)/);
});

test('displays system metrics and agent sessions from operator status', () => {
  assert.match(operationsSource, /status\.system\.hostname/);
  assert.match(operationsSource, /status\.system\.platform/);
  assert.match(operationsSource, /status\.system\.memoryUsage\.rssMB/);
  assert.match(operationsSource, /status\.system\.processUptimeSeconds/);
  assert.match(operationsSource, /formatDuration/);
  assert.match(operationsSource, /Agent sessions/);
  assert.match(operationsSource, /status\.sessions\.activeSessions/);
  assert.match(operationsSource, /status\.sessions\.activeSessionDetails/);
  assert.match(operationsSource, /status\.sessions\.recentSessionDetails/);
  assert.match(operationsSource, /s\.profileName/);
  assert.match(operationsSource, /s\.isSnoozed === true/);
  assert.match(operationsSource, /showOperatorAgentSession\(s\.id\)/);
  assert.match(operationsSource, /snoozeOperatorAgentSession\(s\.id\)/);
  assert.match(operationsSource, /unsnoozeOperatorAgentSession\(s\.id\)/);
  assert.match(operationsSource, /snoozeOperatorAgentSessionsAndHidePanel/);
  assert.match(operationsSource, /clearOperatorAgentSession\(s\.id\)/);
  assert.match(operationsSource, /clearInactiveOperatorAgentSessions\(\)/);
  assert.match(operationsSource, /Hide active agent sessions and desktop panel/);
  assert.match(operationsSource, /Hide active/);
  assert.match(operationsSource, /Dismiss \$\{s\.title \?\? s\.id\} agent session progress on desktop/);
  assert.match(operationsSource, /Clear inactive agent sessions on desktop/);
  assert.match(operationsSource, /Sessions with queued follow-ups are kept/);
  assert.match(operationsSource, /Show \$\{s\.title \?\? s\.id\} agent session on desktop/);
  assert.match(operationsSource, /isSnoozed \? 'Restore' : 'Hide'/);
  assert.match(operationsSource, /stopOperatorAgentSession\(s\.id\)/);
  assert.match(operationsSource, /Stop \$\{s\.title \?\? s\.id\} agent session/);
  assert.match(operationsSource, /No active agent sessions/);
});

test('displays desktop message queues from operator API', () => {
  assert.match(operationsSource, /getOperatorMessageQueues\(\)/);
  assert.match(operationsSource, /setMessageQueues/);
  assert.match(operationsSource, /Desktop message queues/);
  assert.match(operationsSource, /messageQueues\.map/);
  assert.match(operationsSource, /clearOperatorMessageQueue\(queue\.conversationId\)/);
  assert.match(operationsSource, /pauseOperatorMessageQueue\(queue\.conversationId\)/);
  assert.match(operationsSource, /resumeOperatorMessageQueue\(queue\.conversationId\)/);
  assert.match(operationsSource, /retryOperatorQueuedMessage\(queue\.conversationId, message\.id\)/);
  assert.match(operationsSource, /removeOperatorQueuedMessage\(queue\.conversationId, message\.id\)/);
  assert.match(operationsSource, /updateOperatorQueuedMessageText\(queue\.conversationId, message\.id, editedText\)/);
  assert.match(operationsSource, /Clear \$\{queue\.conversationId\} desktop message queue/);
  assert.match(operationsSource, /Pause \$\{queue\.conversationId\} desktop message queue/);
  assert.match(operationsSource, /Resume \$\{queue\.conversationId\} desktop message queue/);
  assert.match(operationsSource, /Retry queued message \$\{message\.id\}/);
  assert.match(operationsSource, /Edit queued message \$\{message\.id\}/);
  assert.match(operationsSource, /Remove queued message \$\{message\.id\}/);
});

test('auto-refreshes operator data periodically', () => {
  assert.match(operationsSource, /AUTO_REFRESH_INTERVAL_MS/);
  assert.match(operationsSource, /setInterval/);
  assert.match(operationsSource, /clearInterval/);
  assert.match(operationsSource, /autoRefreshRef/);
});

test('displays recent conversations from operator API', () => {
  assert.match(operationsSource, /getOperatorConversations/);
  assert.match(operationsSource, /setConversations/);
  assert.match(operationsSource, /Recent conversations/);
  assert.match(operationsSource, /conversations\.map/);
});

test('exposes desktop diagnostic report controls', () => {
  assert.match(operationsSource, /Diagnostics/);
  assert.match(operationsSource, /getOperatorDiagnosticReport\(\)/);
  assert.match(operationsSource, /saveOperatorDiagnosticReport\(\)/);
  assert.match(operationsSource, /Generate desktop diagnostic report/);
  assert.match(operationsSource, /Save diagnostic report on desktop/);
  assert.match(operationsSource, /diagnosticReport\.mcp\.availableTools/);
});

test('displays recent operator logs from operator API', () => {
  assert.match(operationsSource, /RECENT_LOG_COUNT/);
  assert.match(operationsSource, /getOperatorLogs\(RECENT_LOG_COUNT\)/);
  assert.match(operationsSource, /setOperatorLogs/);
  assert.match(operationsSource, /Recent operator logs/);
  assert.match(operationsSource, /operatorLogs\.map/);
  assert.match(operationsSource, /settingsClient\.clearOperatorErrors\(\)/);
  assert.match(operationsSource, /Clear desktop operator error log/);
});

test('displays MCP servers from operator API', () => {
  assert.match(operationsSource, /getOperatorMCP/);
  assert.match(operationsSource, /setMcpServers/);
  assert.match(operationsSource, /MCP servers/);
  assert.match(operationsSource, /mcpServers\.map/);
  assert.match(operationsSource, /Start \$\{s\.name\} MCP server/);
  assert.match(operationsSource, /Stop \$\{s\.name\} MCP server/);
  assert.match(operationsSource, /Restart \$\{s\.name\} MCP server/);
  assert.match(operationsSource, /Test \$\{s\.name\} MCP server connection/);
  assert.match(operationsSource, /testOperatorMCPServer\(s\.name\)/);
  assert.match(operationsSource, /MCP_LOG_PREVIEW_COUNT/);
  assert.match(operationsSource, /getOperatorMCPServerLogs\(serverName, MCP_LOG_PREVIEW_COUNT\)/);
  assert.match(operationsSource, /clearOperatorMCPServerLogs\(s\.name\)/);
  assert.match(operationsSource, /getOperatorMCPTools\(serverName\)/);
  assert.match(operationsSource, /setOperatorMCPToolEnabled\(toolName, enabled\)/);
  assert.match(operationsSource, /Show'} \$\{s\.name\} MCP server tools/);
  assert.match(operationsSource, /Enable \$\{tool\.name\} MCP tool/);
  assert.match(operationsSource, /settingsClient\.startMCPServer\(s\.name\)/);
  assert.match(operationsSource, /settingsClient\.stopMCPServer\(s\.name\)/);
  assert.match(operationsSource, /settingsClient\.restartMCPServer\(s\.name\)/);
  assert.match(operationsSource, /Restarted \$\{s\.name\}/);
});
