const test = require('node:test');
const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');

const source = fs.readFileSync(
  path.join(__dirname, '..', 'src', 'ui', 'ResponseHistoryPanel.tsx'),
  'utf8'
);

test('mobile response history panel uses shared copy, actions, and accessibility labels', () => {
  assert.match(source, /createAgentResponseHistoryMobilePropsParts,/);
  assert.match(source, /createAgentResponseHistoryMobileStyleSlots,/);
  assert.match(source, /getAgentResponseHistoryMobileRenderState,/);
  assert.match(source, /colors: Parameters<typeof getAgentResponseHistoryMobileRenderState>\[0\]\['colors'\];/);
  assert.match(source, /isCollapsed: boolean;/);
  assert.match(source, /shouldAnimateNewest: boolean;/);
  assert.match(source, /speakingIndex: number \| null;/);
  assert.match(source, /onToggleCollapsed: \(\) => void;/);
  assert.match(source, /onSpeakResponse: \(text: string, index: number\) => void;/);
  assert.match(source, /const responseHistoryRenderState = getAgentResponseHistoryMobileRenderState\(\{\s+responses,\s+colors,\s+isCollapsed,\s+animateNewest: shouldAnimateNewest,\s+speakingIndex,\s+\}\);/);
  assert.match(source, /const responseHistoryParts = createAgentResponseHistoryMobilePropsParts\(\{\s+renderState: responseHistoryRenderState,\s+styles,\s+onToggleCollapsed,\s+onSpeakResponse,\s+\}\);/);
  assert.match(source, /if \(!responseHistoryRenderState\.shouldRender\) \{[\s\S]*?return null;/);
  assert.match(source, /style=\{responseHistoryParts\.container\.style\}/);
  assert.match(source, /onPress=\{responseHistoryParts\.header\.touchable\.onPress\}/);
  assert.match(source, /activeOpacity=\{responseHistoryParts\.header\.touchable\.activeOpacity\}/);
  assert.match(source, /accessibilityRole=\{responseHistoryParts\.header\.touchable\.accessibilityRole\}/);
  assert.match(source, /accessibilityLabel=\{responseHistoryParts\.header\.touchable\.accessibilityLabel\}/);
  assert.match(source, /accessibilityState=\{responseHistoryParts\.header\.touchable\.accessibilityState\}/);
  assert.match(source, /name=\{responseHistoryParts\.header\.icon\.name\}/);
  assert.match(source, /name=\{responseHistoryParts\.header\.toggleIcon\.name\}/);
  assert.match(source, /\{responseHistoryParts\.header\.title\.text\}/);
  assert.match(source, /\{responseHistoryParts\.header\.badge\.text\.value\}/);
  assert.match(source, /onPress=\{item\.speakButton\.onPress\}/);
  assert.match(source, /activeOpacity=\{item\.speakButton\.activeOpacity\}/);
  assert.match(source, /accessibilityRole=\{item\.speakButton\.accessibilityRole\}/);
  assert.match(source, /accessibilityLabel=\{item\.speakButton\.accessibilityLabel\}/);
  assert.match(source, /name=\{item\.speakIcon\.name\}/);
  assert.match(source, /color=\{item\.speakIcon\.color\}/);
  assert.doesNotMatch(source, /from '@dotagents\/shared\/agent-user-response-store'/);
  assert.doesNotMatch(source, /AGENT_RESPONSE_HISTORY_PRESENTATION/);
  assert.doesNotMatch(source, /getAgentResponseHistoryToggleAccessibilityLabel\(isCollapsed\)/);
  assert.doesNotMatch(source, /getAgentResponseHistorySpeechAccessibilityLabel\(isSpeaking\)/);
  assert.doesNotMatch(source, /getAgentResponseHistorySpeechActionState\(/);
  assert.doesNotMatch(source, /getAgentResponseHistoryTitle\(\)/);
  assert.doesNotMatch(source, /getAgentResponseHistoryPanelState\(responses/);
  assert.doesNotMatch(source, /getAgentResponseHistoryMobileIconState\(\)/);
  assert.doesNotMatch(source, /if \(responses\.length === 0\) \{[\s\S]*?return null;/);
  assert.doesNotMatch(source, /accessibilityRole="button"/);
  assert.doesNotMatch(source, />Agent Responses<\/Text>/);
  assert.doesNotMatch(source, /'chevron-down'|'chevron-up'|'volume-medium'|'stop-circle'/);
  assert.doesNotMatch(source, /import \* as Speech from 'expo-speech';/);
  assert.doesNotMatch(source, /speakRemoteTts|stopRemoteTts|preprocessTextForTTS|DEFAULT_EDGE_TTS_VOICE/);
});

test('mobile response history panel reads compact sizing from shared surface tokens', () => {
  assert.match(source, /type AgentResponseHistoryMobileAnimationState,/);
  assert.match(source, /new Animated\.Value\([\s\S]*?animation\.newestInitialOpacity[\s\S]*?: animation\.visibleOpacity/);
  assert.match(source, /const animatedStyle = useMemo\(\(\) => \(\{ opacity: fadeAnim \}\), \[fadeAnim\]\);/);
  assert.match(source, /duration: animation\.newestFadeDurationMs/);
  assert.match(source, /toValue: animation\.visibleOpacity/);
  assert.match(source, /useNativeDriver: animation\.newestUseNativeDriver/);
  assert.doesNotMatch(source, /useNativeDriver: true/);
  assert.match(source, /<Animated\.View style=\{animatedStyle\}>/);
  assert.match(source, /import \{ spacing, radius \} from '\.\/theme';/);
  assert.match(source, /const responseHistoryStyleSlots = createAgentResponseHistoryMobileStyleSlots\(\{\s+renderState: responseHistoryRenderState,\s+spacing,\s+radius,\s+\}\);/);
  assert.match(source, /container:\s*\{[\s\S]*?\.\.\.responseHistoryStyleSlots\.container/);
  assert.match(source, /header:\s*\{[\s\S]*?\.\.\.responseHistoryStyleSlots\.header/);
  assert.match(source, /headerLeft:\s*\{[\s\S]*?\.\.\.responseHistoryStyleSlots\.headerLeft/);
  assert.match(source, /badge:\s*\{[\s\S]*?\.\.\.responseHistoryStyleSlots\.badge/);
  assert.match(source, /list:\s*\{[\s\S]*?\.\.\.responseHistoryStyleSlots\.list/);
  assert.match(source, /responseHeader:\s*\{[\s\S]*?\.\.\.responseHistoryStyleSlots\.responseHeader/);
  assert.match(source, /separator:\s*\{[\s\S]*?\.\.\.responseHistoryStyleSlots\.separator/);
  assert.match(source, /collapsedPreviewText:\s*\{[\s\S]*?\.\.\.responseHistoryStyleSlots\.collapsedPreviewText/);
  assert.match(source, /numberOfLines=\{responseHistoryParts\.collapsedPreview\.preview\.numberOfLines\}/);
  assert.match(source, /size=\{responseHistoryParts\.header\.icon\.size\}/);
  assert.match(source, /size=\{item\.speakIcon\.size\}/);
  assert.doesNotMatch(source, /responseHistorySurface/);
  assert.doesNotMatch(source, /responseHistorySurfaceColors/);
  assert.doesNotMatch(source, /responseHistoryPanelState/);
  assert.doesNotMatch(source, /hexToRgba\(/);
  assert.doesNotMatch(source, /overflow:\s*'hidden'/);
  assert.doesNotMatch(source, /duration:\s*300/);
  assert.doesNotMatch(source, /new Animated\.Value\(isNewest \? 0 : 1\)/);
  assert.doesNotMatch(source, /<Animated\.View style=\{\{ opacity: fadeAnim \}\}>/);
  assert.doesNotMatch(source, /\[\.\.\.responses\]\.reverse\(\)\.map/);
  assert.doesNotMatch(source, /Math\.max\(\.\.\.responses\.map/);
  assert.doesNotMatch(source, /getAgentResponseHistoryRenderItems/);
  assert.doesNotMatch(source, /maxHeight:\s*300/);
  assert.doesNotMatch(source, /size=\{18\}/);
  assert.doesNotMatch(source, /theme\.colors\.(background|foreground|card|border|muted|mutedForeground|primary|primaryForeground|destructive|success|warning|info)/);
  assert.doesNotMatch(source, /AGENT_RESPONSE_HISTORY_SURFACE_PRESENTATION/);
});

test('mobile response history renders list chrome from shared prop parts', () => {
  assert.match(source, /\{responseHistoryParts\.collapsedPreview && \(/);
  assert.match(source, /\{responseHistoryParts\.collapsedPreview\.timestamp\.text\}/);
  assert.match(source, /\{responseHistoryParts\.collapsedPreview\.preview\.text\}/);
  assert.match(source, /\{responseHistoryParts\.list && \(/);
  assert.match(source, /<ScrollView\s+style=\{responseHistoryParts\.list\.style\}\s+showsVerticalScrollIndicator=\{responseHistoryParts\.list\.showsVerticalScrollIndicator\}\s+>/);
  assert.match(source, /\{responseHistoryParts\.list\.items\.map\(\(item\) => \{/);
  assert.match(source, /<React\.Fragment key=\{item\.key\}>/);
  assert.match(source, /\{item\.separator && <View style=\{item\.separator\.style\} \/>/);
  assert.match(source, /<AnimatedResponseItem[\s\S]*?isNewest=\{item\.animated\.isNewest\}[\s\S]*?animation=\{item\.animated\.animation\}/);
  assert.match(source, /\{item\.timestamp\.text\}/);
  assert.match(source, /content=\{item\.entry\.text\}/);
  assert.doesNotMatch(source, /item\.shouldRenderSeparator &&/);
  assert.doesNotMatch(source, /const response = item\.entry;/);
  assert.doesNotMatch(source, /const speechActionState = item\.speechActionState;/);
  assert.doesNotMatch(source, /formatAgentResponseHistoryPreviewText/);
  assert.doesNotMatch(source, /formatAgentResponseHistoryTimestamp/);
  assert.doesNotMatch(source, /getLatestAgentResponseHistoryEntry/);
  assert.doesNotMatch(source, /const isSpeaking = speakingIndex === item\.originalIndex;/);
  assert.doesNotMatch(source, /item\.displayIndex > 0/);
  assert.doesNotMatch(source, /const \[isCollapsed, setIsCollapsed\] = useState\(true\);/);
  assert.doesNotMatch(source, /const \[speakingIndex, setSpeakingIndex\] = useState<number \| null>\(null\);/);
  assert.doesNotMatch(source, /handleSpeak/);
  assert.doesNotMatch(source, /!\s*isCollapsed && \(/);
  assert.doesNotMatch(source, /responseHistoryRenderState\.shouldRenderList/);
});
