const test = require('node:test');
const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');

const source = fs.readFileSync(
  path.join(__dirname, '..', 'src', 'ui', 'ResponseHistoryPanel.tsx'),
  'utf8'
);

test('mobile response history panel uses shared copy, actions, and accessibility labels', () => {
  assert.match(source, /createAgentResponseHistoryMobilePropsParts,/);
  assert.match(source, /createAgentResponseHistoryMobileStyleSlots,/);
  assert.match(source, /getAgentResponseHistoryMobileRenderState,/);
  assert.match(source, /type AgentResponseHistoryMobilePropsParts,/);
  assert.match(source, /type AgentResponseHistoryMobileStylesLike,/);
  assert.match(source, /type ResponseHistoryPanelParts =\s+AgentResponseHistoryMobilePropsParts<[\s\S]*?ResponseHistoryEntry,[\s\S]*?ResponseHistoryPanelStyles,[\s\S]*?ResponseHistoryToggleHandler/);
  assert.match(source, /colors: Parameters<typeof getAgentResponseHistoryMobileRenderState>\[0\]\['colors'\];/);
  assert.match(source, /isCollapsed: boolean;/);
  assert.match(source, /shouldAnimateNewest: boolean;/);
  assert.match(source, /speakingIndex: number \| null;/);
  assert.match(source, /onToggleCollapsed: ResponseHistoryToggleHandler;/);
  assert.match(source, /onSpeakResponse: ResponseHistorySpeakHandler;/);
  assert.match(source, /const responseHistoryRenderState = getAgentResponseHistoryMobileRenderState\(\{\s+responses,\s+colors,\s+isCollapsed,\s+animateNewest: shouldAnimateNewest,\s+speakingIndex,\s+\}\);/);
  assert.match(source, /const responseHistoryParts: ResponseHistoryPanelParts = createAgentResponseHistoryMobilePropsParts\(\{\s+renderState: responseHistoryRenderState,\s+styles,\s+onToggleCollapsed,\s+onSpeakResponse,\s+\}\);/);
  assert.match(source, /if \(!responseHistoryRenderState\.shouldRender\) \{[\s\S]*?return null;/);
  assert.match(source, /<View\s+\{\.\.\.responseHistoryParts\.container\.props\}>/);
  assert.match(source, /<TouchableOpacity\s+\{\.\.\.responseHistoryParts\.header\.touchable\.props\}/);
  assert.match(source, /<Ionicons\s+\{\.\.\.responseHistoryParts\.header\.icon\.props\}/);
  assert.match(source, /<Ionicons\s+\{\.\.\.responseHistoryParts\.header\.toggleIcon\.props\}/);
  assert.doesNotMatch(source, /responseHistoryParts\.header\.touchable\.(onPress|activeOpacity|accessibilityRole|accessibilityLabel|accessibilityState)/);
  assert.doesNotMatch(source, /responseHistoryParts\.header\.(icon|toggleIcon)\.(name|size|color)/);
  assert.match(source, /\{responseHistoryParts\.header\.title\.text\}/);
  assert.match(source, /\{responseHistoryParts\.header\.badge\.text\.value\}/);
  assert.match(source, /<TouchableOpacity\s+\{\.\.\.item\.speakButton\.props\}/);
  assert.match(source, /<Ionicons\s+\{\.\.\.item\.speakIcon\.props\}/);
  assert.doesNotMatch(source, /item\.speakButton\.(onPress|activeOpacity|accessibilityRole|accessibilityLabel)/);
  assert.doesNotMatch(source, /item\.speakIcon\.(name|size|color)/);
  assert.doesNotMatch(source, /from '@dotagents\/shared\/agent-user-response-store'/);
  assert.doesNotMatch(source, /AGENT_RESPONSE_HISTORY_PRESENTATION/);
  assert.doesNotMatch(source, /getAgentResponseHistoryToggleAccessibilityLabel\(isCollapsed\)/);
  assert.doesNotMatch(source, /getAgentResponseHistorySpeechAccessibilityLabel\(isSpeaking\)/);
  assert.doesNotMatch(source, /getAgentResponseHistorySpeechActionState\(/);
  assert.doesNotMatch(source, /getAgentResponseHistoryTitle\(\)/);
  assert.doesNotMatch(source, /getAgentResponseHistoryPanelState\(responses/);
  assert.doesNotMatch(source, /getAgentResponseHistoryMobileIconState\(\)/);
  assert.doesNotMatch(source, /if \(responses\.length === 0\) \{[\s\S]*?return null;/);
  assert.doesNotMatch(source, /accessibilityRole="button"/);
  assert.doesNotMatch(source, />Agent Responses<\/Text>/);
  assert.doesNotMatch(source, /'chevron-down'|'chevron-up'|'volume-medium'|'stop-circle'/);
  assert.doesNotMatch(source, /import \* as Speech from 'expo-speech';/);
  assert.doesNotMatch(source, /speakRemoteTts|stopRemoteTts|preprocessTextForTTS|DEFAULT_EDGE_TTS_VOICE/);
});

test('mobile response history panel reads compact sizing from shared surface tokens', () => {
  assert.match(source, /type AgentResponseHistoryMobileAnimationState,/);
  assert.match(source, /type ResponseHistoryPanelStyles =\s+AgentResponseHistoryMobileStylesLike<\s+StyleProp<ViewStyle>,[\s\S]*?StyleProp<TextStyle>\s+>;/);
  assert.doesNotMatch(source, /type ResponseHistoryPanelStyles = \{[\s\S]*?container: StyleProp<ViewStyle>;[\s\S]*?headerTitle: StyleProp<TextStyle>;[\s\S]*?collapsedPreviewText: StyleProp<TextStyle>;[\s\S]*?\};/);
  assert.match(source, /new Animated\.Value\([\s\S]*?animation\.newestInitialOpacity[\s\S]*?: animation\.visibleOpacity/);
  assert.match(source, /const animatedStyle = useMemo\(\(\) => \(\{ opacity: fadeAnim \}\), \[fadeAnim\]\);/);
  assert.match(source, /duration: animation\.newestFadeDurationMs/);
  assert.match(source, /toValue: animation\.visibleOpacity/);
  assert.match(source, /useNativeDriver: animation\.newestUseNativeDriver/);
  assert.doesNotMatch(source, /useNativeDriver: true/);
  assert.match(source, /<Animated\.View style=\{animatedStyle\}>/);
  assert.match(source, /import \{ spacing, radius \} from '\.\/theme';/);
  assert.match(source, /const responseHistoryStyleSlots = createAgentResponseHistoryMobileStyleSlots\(\{\s+renderState: responseHistoryRenderState,\s+spacing,\s+radius,\s+\}\);/);
  assert.match(source, /const styles: ResponseHistoryPanelStyles = StyleSheet\.create\(\{/);
  assert.match(source, /container:\s*\{[\s\S]*?\.\.\.responseHistoryStyleSlots\.container/);
  assert.match(source, /header:\s*\{[\s\S]*?\.\.\.responseHistoryStyleSlots\.header/);
  assert.match(source, /headerLeft:\s*\{[\s\S]*?\.\.\.responseHistoryStyleSlots\.headerLeft/);
  assert.match(source, /badge:\s*\{[\s\S]*?\.\.\.responseHistoryStyleSlots\.badge/);
  assert.match(source, /list:\s*\{[\s\S]*?\.\.\.responseHistoryStyleSlots\.list/);
  assert.match(source, /responseHeader:\s*\{[\s\S]*?\.\.\.responseHistoryStyleSlots\.responseHeader/);
  assert.match(source, /separator:\s*\{[\s\S]*?\.\.\.responseHistoryStyleSlots\.separator/);
  assert.match(source, /collapsedPreviewText:\s*\{[\s\S]*?\.\.\.responseHistoryStyleSlots\.collapsedPreviewText/);
  assert.match(source, /<Text\s+\{\.\.\.responseHistoryParts\.collapsedPreview\.preview\.props\}/);
  assert.match(source, /<Ionicons\s+\{\.\.\.responseHistoryParts\.header\.icon\.props\}/);
  assert.match(source, /<Ionicons\s+\{\.\.\.item\.speakIcon\.props\}/);
  assert.doesNotMatch(source, /numberOfLines=\{responseHistoryParts\.collapsedPreview\.preview\.numberOfLines\}/);
  assert.doesNotMatch(source, /size=\{responseHistoryParts\.header\.icon\.size\}/);
  assert.doesNotMatch(source, /size=\{item\.speakIcon\.size\}/);
  assert.doesNotMatch(source, /responseHistorySurface/);
  assert.doesNotMatch(source, /responseHistorySurfaceColors/);
  assert.doesNotMatch(source, /responseHistoryPanelState/);
  assert.doesNotMatch(source, /hexToRgba\(/);
  assert.doesNotMatch(source, /overflow:\s*'hidden'/);
  assert.doesNotMatch(source, /duration:\s*300/);
  assert.doesNotMatch(source, /new Animated\.Value\(isNewest \? 0 : 1\)/);
  assert.doesNotMatch(source, /<Animated\.View style=\{\{ opacity: fadeAnim \}\}>/);
  assert.doesNotMatch(source, /\[\.\.\.responses\]\.reverse\(\)\.map/);
  assert.doesNotMatch(source, /Math\.max\(\.\.\.responses\.map/);
  assert.doesNotMatch(source, /getAgentResponseHistoryRenderItems/);
  assert.doesNotMatch(source, /maxHeight:\s*300/);
  assert.doesNotMatch(source, /size=\{18\}/);
  assert.doesNotMatch(source, /theme\.colors\.(background|foreground|card|border|muted|mutedForeground|primary|primaryForeground|destructive|success|warning|info)/);
  assert.doesNotMatch(source, /AGENT_RESPONSE_HISTORY_SURFACE_PRESENTATION/);
});

test('mobile response history renders list chrome from shared prop parts', () => {
  assert.match(source, /\{responseHistoryParts\.collapsedPreview\.shouldRender \? \(/);
  assert.doesNotMatch(source, /responseHistoryParts\.collapsedPreview && \(/);
  assert.match(source, /\{responseHistoryParts\.collapsedPreview\.timestamp\.text\}/);
  assert.match(source, /\{responseHistoryParts\.collapsedPreview\.preview\.text\}/);
  assert.match(source, /\{responseHistoryParts\.list\.shouldRender \? \(/);
  assert.doesNotMatch(source, /responseHistoryParts\.list && \(/);
  assert.match(source, /<ScrollView\s+\{\.\.\.responseHistoryParts\.list\.props\}/);
  assert.doesNotMatch(source, /style=\{responseHistoryParts\.list\.style\}/);
  assert.doesNotMatch(source, /showsVerticalScrollIndicator=\{responseHistoryParts\.list\.showsVerticalScrollIndicator\}/);
  assert.match(source, /\{responseHistoryParts\.list\.items\.map\(\(item\) => \{/);
  assert.match(source, /<React\.Fragment key=\{item\.key\}>/);
  assert.match(source, /\{item\.separator\.shouldRender \? <View \{\.\.\.item\.separator\.props\} \/> : null\}/);
  assert.doesNotMatch(source, /item\.separator && <View style=\{item\.separator\.style\} \/>/);
  assert.match(source, /<AnimatedResponseItem[\s\S]*?isNewest=\{item\.animated\.isNewest\}[\s\S]*?animation=\{item\.animated\.animation\}/);
  assert.match(source, /\{item\.timestamp\.text\}/);
  assert.match(source, /content=\{item\.entry\.text\}/);
  assert.doesNotMatch(source, /item\.shouldRenderSeparator &&/);
  assert.doesNotMatch(source, /const response = item\.entry;/);
  assert.doesNotMatch(source, /const speechActionState = item\.speechActionState;/);
  assert.doesNotMatch(source, /formatAgentResponseHistoryPreviewText/);
  assert.doesNotMatch(source, /formatAgentResponseHistoryTimestamp/);
  assert.doesNotMatch(source, /getLatestAgentResponseHistoryEntry/);
  assert.doesNotMatch(source, /const isSpeaking = speakingIndex === item\.originalIndex;/);
  assert.doesNotMatch(source, /item\.displayIndex > 0/);
  assert.doesNotMatch(source, /const \[isCollapsed, setIsCollapsed\] = useState\(true\);/);
  assert.doesNotMatch(source, /const \[speakingIndex, setSpeakingIndex\] = useState<number \| null>\(null\);/);
  assert.doesNotMatch(source, /handleSpeak/);
  assert.doesNotMatch(source, /!\s*isCollapsed && \(/);
  assert.doesNotMatch(source, /responseHistoryRenderState\.shouldRenderList/);
});
